# De overgang in het jaar 2000

> Het lijkt wel alsof er iets monumentaals op til is: grafieken tonen de jaarlijkse groei van bevolkingsaantallen, de concentratie van koolstofdioxide in de atmosfeer, het aantal webadressen en de megabytes per dollar. Alle cijfers stijgen naar een asymptoot net na de eeuwwisseling: de singulariteit. Het einde van alles wat we kennen. Het begin van iets wat we wellicht nooit zullen doorgronden. -- Danny Hillis[^1]

## Voorgevoelens

Het jaar 2000 houdt de westerse verbeelding al eeuwenlang in zijn greep. Nadat men destijds verwachtte dat de wereld bij de millenniumwisseling van het eerste millennium na Christus zou instorten, keken theologen, evangelisten, dichters en zieners reikhalzend uit naar een decennium vol ingrijpende gebeurtenissen. Zelfs de beroemde Isaac Newton speculeerde ooit dat de wereld in het jaar 2000 ten onder zou gaan. Michel de Nostradamus, wiens profetieën al sinds 1568 door generaties zijn bekeken, voorspelde de komst van de derde antichrist in juli 1999.[^2] De Zwitserse psycholoog Carl Jung, expert op het gebied van het 'collectieve onbewuste', zag al in 1997 de geboorte van een nieuw tijdperk opdoemen. Men maakt zulke voorspellingen vaak belachelijk, net als de nuchtere prognoses van economen zoals Dr. Edward Yardeni van *Deutsche Bank Securities*, die verwachte dat computerstoringen op middernacht van het millennium de hele wereldeconomie compleet zouden ontwrichten.[^3] Of je het Y2K-probleem nu beschouwt als ongegronde hysterie, aangewakkerd door programmeurs en adviseurs op het gebied van informatietechnologie, of als een mysterieus fenomeen waarin technologie zich ontvouwt in samenhang met profetische ideeën, je kunt niet ontkennen dat de drempel van het millennium voor veel meer opwinding zorgt dan de gebruikelijke, morbide onzekerheid over de toekomst.

Het optimisme dat westerse samenlevingen de afgelopen 250 jaar kenmerkte, wordt nu overschaduwd door een gevoel van naderend onheil. Overal zie je het terug: in de gezichtsuitdrukkingen van mensen, in hun gesprekken, in peilingen en zelfs op de stembus. Net zoals dat een subtiele verandering in de ionen in de atmosfeer, nog voordat de wolken donker worden en de bliksem slaat, al verraadt dat er een onweersbui aan komt, zo hangt er in de schemering van het millennium een voorgevoel van verandering in de lucht. Men voelt op ieders eigen manier dat hun levenswijze ten dode opgeschreven is. Bij het aflopen van het decennium, komen zowel een moorddadige eeuw als een glorieus millenium vol menselijke verwezenlijkingen tot zijn eind. Alles vindt zijn einde in het jaar 2000.

> Want wat verborgen is zal ontdekt worden, en wat geheim is, zal bekend worden. -- Mattheüs 10:26

Wij zijn ervan overtuigd dat de moderne fase van de westerse beschaving ten einde loopt, en in dit boek leggen we uit waarom. Net als veel andere werken proberen we via een donkere spiegel te kijken en de vage contouren en verhoudingen van een naderende toekomst te schetsen. In zekere zin is het de bedoeling van dit werk om 'apocalyptisch' te zijn in de letterlijke betekenis van het woord. 'Apokalypsis' is Grieks voor 'onthulling'. Wij geloven dat een nieuw tijdperk, het informatietijdperk, op het punt staat zich te 'onthullen'.

> We observeren de eerste tekenen van een nieuwe logische ruimte, een ogenblikkelijke elektronische alomtegenwoordigheid waar iedereen toegang toe heeft, in kan gaan en kan ervaren. Kortom, we bevinden ons in de begindagen van een nieuwe gemeenschapsvorm. De virtuele gemeenschap wordt het model voor een seculier koninkrijk der hemelen; zoals Jezus zei dat er vele huizen waren in het koninkrijk van zijn Vader, zo zijn er ook talloze virtuele gemeenschappen, elk afgestemd op hun eigen wensen en behoeften. -- Michael Grasso[^4]

## De vierde fase van de menselijke maatschappij

Het thema van dit boek is de opkomst van een nieuwe machtsrevolutie die individuen bevrijdt en de traditionele natiestaat van de twintigste eeuw verdringt. Innovaties die de logica van geweld radicaal herschrijven, verschuiven de grenzen waarbinnen de toekomst vorm krijgt. Als onze conclusies kloppen, sta je op de drempel van de meest ingrijpende revolutie in de geschiedenis. Veel sneller dan de meesten zich voorstellen, zal de microprocessor de natiestaat ondermijnen en uiteindelijk vernietigen, waarna nieuwe vormen van sociale organisatie zullen ontstaan. Deze transformatie wordt allesbehalve eenvoudig.

De uitdaging die eraan verbonden is, wordt des te groter omdat deze zich in een ongekend tempo voltrekt, veel sneller dan we in het verleden hebben gezien. In de gehele menselijke geschiedenis, van de oertijd tot nu, kennen we slechts drie fundamentele ontwikkelingsstadia: (1) jager-verzamelaarsmaatschappijen, (2) agrarische samenlevingen en (3) industriële samenlevingen. Aan de horizon doemt nu iets compleet nieuws op: Informatiemaatschappijen, het vierde stadium van sociale organisatie.

Bij elk van de voorgaande samenlevingsstadia kende men een eigen, duidelijk afgebakende fase in de evolutie en beheersing van geweld. Zoals we uitvoerig toelichten, zullen Informatiemaatschappijen de voordelen van geweld drastisch verkleinen, mede omdat ze niet langer gebonden zijn aan één vaste locatie. De virtuele wereld van cyberspace, die romanschrijver William Gibson omschreef als een 'consensuele hallucinatie', zal voor pestkoppen zo onbereikbaar blijven als de verbeelding reikt. In dit nieuwe millennium zal de winst uit de grootschalige beheersing van geweld veel lager uitvallen dan op welk moment sinds vóór de Franse Revolutie ook. Dit heeft verstrekkende gevolgen. Eén daarvan is een toename van criminaliteit. Als de beloning voor grootschalig geweld instort, zal de prikkel voor kleinschalig geweld naar alle waarschijnlijkheid juist groeien. Geweld krijgt dan een meer willekeurige, lokale aard, terwijl georganiseerde criminaliteit in omvang toeneemt; wij lichten hierover verder toe.

Een andere logische consequentie van de afnemende voordelen van geweld is het vervagen van de politieke rol. Er is veel bewijs dat het vertrouwen in de burgerlijke mythen van de twintigste-eeuwse natiestaat snel afneemt. De ondergang van het communisme is slechts één opvallend voorbeeld. Zoals we in detail onderzoeken, bewijzen de afbrokkelende moraliteit en de groeiende corruptie onder leiders van westerse regeringen dat het potentieel van de natiestaat is uitgeput (het gaat hier niet om een willekeurige ontwikkeling). Zelfs vele leiders geloven de holle frasen die zij verkondigen niet meer, en ook het publiek schenkt die woorden geen vertrouwen meer.

### Geschiedenis herhaalt zich

Deze situatie vertoont opvallende overeenkomsten met het verleden. Telkens wanneer technologische veranderingen de oude structuren losmaken van de nieuwe economische drijfkrachten, veranderen ook de morele normen en gaan mensen degenen die de oude instituties leiden met groeiende minachting behandelen. Deze wijdverspreide afkeer komt vaak al duidelijk naar voren voordat er zelfs een nieuwe, samenhangende ideologie van verandering ontstaat. Zo was dat bijvoorbeeld in de late vijftiende eeuw, toen de middeleeuwse kerk nog het overheersende instituut van het feodalisme vormde. Ondanks het brede geloof in 'de heiligheid van het priesterlijke ambt', behandelden mensen zowel de hoge als de lage geestelijkheid met grote minachting. Dit is vergelijkbaar met de populaire houding ten opzichte van politici en bureaucraten in deze tijd.[^5]

We zijn ervan overtuigd dat we veel kunnen leren door het einde van de vijftiende eeuw, toen het leven doordrenkt was met georganiseerde religie, te vergelijken met de hedendaagse wereld, waarin politiek overal de boventoon voert. Destijds waren de kosten om de geïnstitutionaliseerde religie in stand te houden historisch extreem hoog, net zoals tegenwoordig de kosten voor het ondersteunen van de overheid absurd ver zijn opgelopen.

We hebben gezien hoe de georganiseerde religie veranderde na de buskruitrevolutie. Technologische innovaties stimuleerden het verkleinen van religieuze instellingen en dwongen tot drastische kostenbesparingen. Een vergelijkbare technologische revolutie dreigt aan het begin van dit millennium de natiestaat radicaal te verkleinen.

> Vandaag, na meer dan een eeuw aan elektronische technologie, hebben we ons centrale zenuwstelsel zelf uitgebreid in een mondiale omarming, waarbij we zowel ruimte als tijd, voor zover onze planeet betreft, hebben afgeschaft.[^6]

### De informatierevolutie

Naarmate grote systemen verder instorten, verliest systematische dwang zijn bepalende rol in het vormgeven van het economisch leven en de inkomensverdeling. Efficiëntie krijgt al snel voorrang boven de bevelen van de machthebbers bij het organiseren van sociale instituties. Dit houdt in dat provincies en zelfs steden die effectief eigendomsrechten bewaken en de rechtspraak draaiende houden, terwijl ze weinig middelen verbruiken, in het informatietijdperk als levensvatbare soevereiniteiten kunnen functioneren, iets wat de afgelopen vijf eeuwen zelden het geval was.

Binnen cyberspace ontstaat een geheel nieuw terrein voor economische activiteiten dat niet vatbaar is voor fysiek geweld. De grootste voordelen zullen vooral de 'cognitieve elite' treffen, die zich steeds minder laat beperken door politieke grenzen. Zij voelen zich net zo thuis in Frankfurt als in Londen, New York, Buenos Aires, Los Angeles, Tokio en Hong Kong. Binnen de rechtsgebieden zal de inkomensongelijkheid toenemen, terwijl tussen deze gebieden juist meer gelijkheid ontstaat.

*Het Soevereine Individu* onderzoekt de maatschappelijke en financiële gevolgen van deze revolutionaire ommekeer. Wij willen je helpen de kansen van dit nieuwe tijdperk te grijpen en ervoor zorgen dat de impact ervan je niet verwoest. Zelfs als slechts de helft van onze verwachtingen uitkomt, ondervind je een verandering van ongekende proporties, zonder werkelijk historisch precedent.

De transformatie in het jaar 2000 verandert radicaal het karakter van de wereldeconomie en gebeurt bovendien veel sneller dan elke voorgaande fasewisseling. In tegenstelling tot de agrarische revolutie kost het de informatierevolutie geen millennia om haar volledige impact te bereiken, en in tegenstelling tot de industriële revolutie spreidt haar effect zich niet uit over een periode van eeuwen, maar ervaar je de volledige reikwijdte ervan binnen één mensenleven.

Daarbij vindt deze transformatie vrijwel gelijktijdig over de hele wereld plaats. Technologische en economische innovaties beperken zich niet langer tot geïsoleerde uithoeken van de wereld. De ommekeer raakt vrijwel alle hoeken van de aarde en markeert een breuk met het verleden die zo ingrijpend is dat hij het bijna mythische rijk van de goden tot leven wekt, zoals de oude Grieken ooit voorstelden.

Veel meer dan men zich nu durft voor te stellen, zal blijken dat het in het nieuwe millennium buitengewoon lastig, zo niet onmogelijk, is om veel van onze hedendaagse instellingen te behouden. Zodra informatiesamenlevingen opkomen, onderscheiden ze zich van industriële samenlevingen op dezelfde manier als het Griekenland van Aeschylus verschilde van de wereld van de grotbewoners.

## *'Prometheus unbound'*: De opkomst van het Soevereine Individu

> Ik ken geen bemoedigender feit dan het onmiskenbare vermogen van de mens om zijn leven te verrijken door doelgerichte inzet -- Henry David Thoreau

De aanstaande transformatie brengt zowel goed als slecht nieuws met zich mee. Het positieve is dat de informatierevolutie mensen als nooit tevoren bevrijdt. Voor het eerst geniet degene die zichzelf kan bijscholen de volledige vrijheid om eigen ideeën te ontwikkelen en maximaal te profiteren van zijn productiviteit. Genialiteit komt tot bloei wanneer overheidsinmenging stopt en raciale en etnische vooroordelen hun invloed verliezen. Als je echt bekwaam bent, laat je je in de Informatiemaatschappij niet tegenhouden door bekrompen opvattingen. Het maakt niet uit wat de meeste mensen van je ras, uiterlijk, leeftijd, seksuele voorkeur of kapsel vinden. In de cybereconomie blijft je identiteit anoniem. Al ben je misschien minder fraai, mollig, ouder of heb je een beperking; dankzij de volledige kleurenblinde anonimiteit op de nieuwe frontlinies van de cyberspace, concurreert iedereen op gelijke voet met de jonge en knappe onder ons,.

### Ideeën worden rijkdom

Zodra competenties zich openbaren, worden ze beloond als nooit tevoren. In een wereld waarin ideeën de grootste bron van rijkdom vormen in plaats van louter fysiek kapitaal, heeft iedereen met een heldere geest de mogelijkheid om rijk te worden. Het informatietijdperk belooft een tijdperk van sociale mobiliteit te worden en opent talloze gelijke kansen voor de miljarden mensen in regio's die nooit ten volle hebben geprofiteerd van de welvaart van de industriële samenleving. De slimsten, succesvolste en meest ambitieuze treden op als ware zelfstandigen.

In eerste instantie bereikt slechts een enkeling volledige financiële soevereiniteit, maar dat doet niets af aan de voordelen van financiële onafhankelijkheid. Dat niet iedereen een gigantisch fortuin vergaart, betekent immers niet dat het streven naar rijkdom zinloos is. Er zijn 25.000 miljonairs voor elke miljardair. Als je wel miljonair bent maar geen miljardair, ben je zeker niet arm. In de toekomst zul je je financiële succes niet alleen koppelen aan het aantal nullen van je vermogen, maar ook aan de mate waarin je erin slaagt om volledige persoonlijke autonomie te bereiken. Hoe slimmer je bent, hoe minder energie je nodig hebt om de overgang naar financiële onafhankelijkheid te maken. Zelfs mensen met bescheiden middelen zullen vooruitkomen zodra de politieke druk op de wereldeconomie afneemt. Onovertroffen financiële onafhankelijkheid wordt dan een haalbaar doel voor jou en je kinderen.

Op het hoogste productiviteitsniveau concurreren en communiceren onafhankelijke individuen op een wijze die doet denken aan de relaties tussen de Griekse goden. De ongrijpbare berg Olympus van het komende millennium bevindt zich in cyberspace -- een wereld zonder fysieke vorm die desalniettemin tegen het tweede decennium van dit nieuwe millennium uit zal groeien tot 's werelds grootste economie. Tegen 2025 telt de cybereconomie miljoenen deelnemers. Sommigen zullen een vermogen ontwikkelen vergelijkbaar met dat van Bill Gates -- elk met een waarde van meer dan 10 miljard dollar -- terwijl de cyberarmen bestaan uit mensen die minder dan 200.000 dollar per jaar verdienen. Er komt geen cyberwelzijn, geen cybertaksen én geen cyberregering. De cybereconomie kan, in plaats van China, wel eens het grootste economische fenomeen van de komende dertig jaar worden.

Het goede nieuws is dat politici in dit nieuwe rijk de handel niet zullen beheersen, onderdrukken of reguleren, net zoals de wetgevers van de oude Griekse stadstaten zeker niet in staat waren om een stukje van Zeus' baard te knippen. Dat komt de rijken ten goede en is nog beter nieuws voor de minder vermogenden. De door de politiek opgelegde obstakels en lasten belemmeren immers meer het rijk worden dan het rijk blijven. De voordelen van afnemende opbrengsten uit geweld en het decentraliseren van rechtsgebieden zullen voor ieder energiek en ambitieus persoon ruimte creëren om te profiteren van de dood van de politiek. Ook de afnemers van overheidsdiensten zullen hier voordeel uit halen, omdat ondernemers de vruchten van de concurrentie verder uitbreiden. Veel van de vindingrijkheid werd vroeger juist gekanaliseerd naar militaire inspanningen omdat er nog weinig ruimte was voor economische concurrentie tussen jurisdicties. Maar de opkomst van de cybereconomie zal zorgen voor nieuwe vormen van concurrentie bij het leveren van diensten die traditioneel door de staat werden uitgevoerd. Met meer rechtsgebieden ontstaat er meer ruimte om te experimenteren met nieuwe methoden voor het afdwingen van contracten en het beschermen van mensen en hun eigendommen. Het vrijmaken van een groot deel van de wereldeconomie van politieke controle dwingt de resterende overheden om marktgerichtere methoden toe te passen. Op den duur hebben ze geen andere optie meer dan de inwoners van hun jurisdicties als klanten te behandelen, in plaats van hen te onderwerpen aan afpersing, net zoals de georganiseerde misdaad.

### Voorbij de politiek

Wat de mythologie ooit als het domein van de goden afschilderde, wordt voor het individu een haalbare keuze: een leven buiten de invloed van koningen en raden. Eerst zullen tientallen mensen, daarna honderden en uiteindelijk miljoenen zich bevrijden uit de greep van de politiek. Terwijl zij zich hiervan ontdoen, hervormen zij de werking van overheden, waardoor de sfeer van dwang afneemt en particuliere controle over middelen toeneemt.

De opkomst van het autonome individu zal opnieuw de bijzondere voorspellende kracht van mythen bevestigen. Vroege agrarische volkeren, die nauwelijks begrip hadden van de natuurwetten, verbeeldden zich dat 'bovennatuurlijke krachten' overal aanwezig waren. Deze krachten werden soms aangewend door mensen of door 'goden in menselijke gedaante', die op mensen leken en onder hen leefden, zoals Sir James George Frazer in *The Golden Bough* omschreef als 'een universele democratie'.[^7]

Toen de oude Grieken zich voorstelden dat de kinderen van Zeus onder hen leefden, lieten zij zich meevoeren door een diep geloof in magie. Zoals andere primitieve agrarische volkeren bewonderden zij de natuur en waren ze ervan overtuigd dat de kracht van de individuele wil, oftewel magie, de natuurlijke orde in beweging zette. Hun visie op de natuur en de goden straalde geen zelfbewuste, profetische inslag uit. Ze waren totaal onvoorbereid op de komst van microtechnologie. Het was voor hen onmogelijk om zich voor te stellen welke invloed deze technologie duizenden jaren later zou hebben op de marginale productiviteit van mensen, laat staan hoe het het evenwicht tussen macht en efficiëntie zou veranderen, en een revolutie zou ontketenen in de manier waarop bezit wordt gecreëerd en beschermd. Toch vertoont wat zij zich voorstelden in hun mythen een merkwaardige overeenkomst met de wereld die u waarschijnlijk zult meemaken.

### Alt.abracadabra

De 'abracadabra' die wordt uitgesproken bij het gebruik van magie vertoont bijvoorbeeld een merkwaardige gelijkenis met het invoeren van het wachtwoord dat nodig is om toegang te krijgen tot een computer. In zekere zin kunnen we met de snelle verwerking van computers de magie van de lampgeest al nabootsen. De eerste generaties van 'digitale dienaren' gehoorzamen nu al de bevelen van degenen die de computers beheersen waarin ze zijn opgesloten, net zoals dat geesten ooit opgesloten zaten in magische lampen. De virtuele realiteit van informatietechnologie breidt het rijk van menselijke verlangens uit, zodat bijna alles wat men zich maar kan voorstellen werkelijkheid lijkt te worden. 'Telepresentie' stelt mensen in staat om afstanden met een bijna bovennatuurlijke snelheid te overbruggen en op afstand gebeurtenissen te volgen, precies zoals de Grieken beweerden dat Hermes en Apollo dat konden. Na verloop van tijd genieten de Soevereine Individuen van het informatietijdperk, net als de goden uit oude mythen, van een soort 'diplomatieke immuniteit' tegen de politieke beproevingen die sterfelijke mensen door de eeuwen heen hebben gekend.

Het nieuwe, Soevereine Individu opereert in dezelfde fysieke omgeving als de gewone burger, maar politiek gezien leeft hij in een eigen sfeer. Met een veel groter arsenaal aan middelen tot zijn beschikking en zonder de beperkingen van talrijke vormen van dwang, gaat dit individu overheden hervormen en economieën herinrichten in het nieuwe millennium. De volledige impact van deze verschuiving is bijna onvoorstelbaar.

### Genialiteit en nemesis

Voor wie houdt van menselijke ambitie en succes, opent het informatietijdperk een schat aan kansen. Dit is zonder twijfel het beste nieuws in generaties, maar het gaat ook gepaard met minder positieve ontwikkelingen. De nieuwe maatschappelijke ordening, die voortvloeit uit de overwinning van de individuele autonomie en het realiseren van echte gelijke kansen op basis van verdienste, zal leiden tot ruime individuele vrijheid en grote beloningen voor wie uitblinkt. Dit betekent echter wel dat mensen veel meer verantwoordelijkheid voor hun eigen leven moeten nemen dan ze in het industriële tijdperk gewend waren. Tegelijk zal de onterecht verhoogde levensstandaard, waar de inwoners van geavanceerde industriële samenlevingen in de twintigste eeuw van profiteerden, sterk afnemen. Op dit moment verdient de top 15 procent van de wereldbevolking gemiddeld $21.000 per persoon per jaar, terwijl de overige 85 procent gemiddeld slechts $1.000 tot hun beschikking heeft. Dit enorme, in de loop der tijd opgepotte voordeel zal onvermijdelijk verdwijnen in de nieuwe realiteit van het informatietijdperk.

Naarmate dit gebeurt, implodeert het vermogen van natiestaten om op grote schaal inkomen te herverdelen. Informatietechnologie zorgt voor een scherpe toename van de concurrentie tussen rechtsgebieden. Wanneer technologie mobiel is en transacties plaatsvinden in de cyberspace, zoals steeds vaker het geval zal zijn, zullen overheden niet langer in staat zijn om meer te vragen voor hun diensten dan wat die diensten daadwerkelijk waard zijn voor de mensen die ervoor betalen. Iedereen met een laptop en een satellietverbinding kan elk informatiebedrijf vrijwel overal runnen, wat nagenoeg het totaal van de wereldwijde financiële handel van biljoenen dollars omvat.

Dit betekent dat om een hoog inkomen te realiseren, men zich niet langer gedwongen hoeft te voelen om in een rechtsgebied met hoge belastingen te wonen. In de toekomst, wanneer het merendeel van de welvaart wereldwijd verdiend en uitgegeven kan worden, zullen overheden die te hoge tarieven rekenen voor domicilie simpelweg hun beste klanten doen vertrekken. Als onze redenering klopt, en daar zijn wij van overtuigd, zal de natiestaat in de huidige vorm niet overleven.

## Het einde van naties

Veranderingen die de macht van gevestigde instellingen ondermijnen, zijn zowel verontrustend als riskant. Net zoals dat monarchen, edellieden, pausen en andere machthebbers in de vroege moderne tijd meedogenloos vochten om hun verworven privileges te behouden, zo zullen ook de huidige overheden geweld inzetten, vaak heimelijk en willekeurig, om de veranderende tijd tegen te houden. Verzwakt door de technologische uitdagingen gaat de staat steeds autonomer wordende individuen, voorheen haar gehoorzame burgers, benaderen met dezelfde meedogenloosheid en diplomatie als waarmee zij tot nu toe met andere regeringen omging.

De komst van deze nieuwe fase in de geschiedenis ging op 20 augustus 1998 met een knal van start, toen de Verenigde Staten voor ongeveer 200 miljoen dollar aan Tomahawk BGM-109 kruisraketten afvuurden op doelen die naar verluidt in verband stonden met de verbannen Saoedische miljonair Osama bin Laden. Bin Laden werd de eerste persoon in de geschiedenis op wiens satelliettelefoon raketaanvallen werden gericht. Tegelijkertijd verwoestten de Verenigde Staten een farmaceutische fabriek in Khartoem, Soedan, die met Bin Laden werd geassocieerd. Bin Ladens opkomst als de belangrijkste vijand van de Verenigde Staten illustreert een fundamentele verandering in de aard van oorlogsvoering. Één enkel individu, al bezit hij honderden miljoenen dollars, kan nu als een geloofwaardige bedreiging worden gezien voor de machtigste militaire macht van het industriële tijdperk. In uitspraken die doen denken aan de Koude Oorlogpropaganda over de Sovjet- Unie portretteerden de president van de Verenigde Staten en zijn nationale veiligheidsspecialisten Bin Laden, een privépersoon, als een transnationale terrorist en de voornaamste vijand van de Verenigde Staten.

Dezelfde militaire logica die ervoor zorgde dat Osama bin Laden als oppervijand van de Verenigde Staten werd gezien, zal zich ook aftekenen in de verhouding tussen overheden en hun burgers. Steeds zwaardere repressie zal een logisch gevolg zijn van het ontstaan van een nieuwe machtsverhouding tussen overheden en individuen. Door technologische vooruitgang worden individuen meer dan ooit soeverein, waardoor ze ook zo behandeld zullen worden, soms met geweld als vijanden, soms als gelijkwaardige onderhandelingspartners, soms als bondgenoten. Hoe meedogenloos overheden zich ook zullen opstellen tijdens deze overgangsperiode, een fusie van de belastingdienst met de inlichtingendienst zal hen weinig opleveren. Overheden zullen in toenemende mate moeten onderhandelen met autonome individuen, omdat de controle over hun middelen steeds verder zal verslappen.

De veranderingen die de Informatie-Revolutie teweegbrengt, veroorzaken niet alleen fiscale crises bij overheden, maar zorgen er ook voor dat alle grote structuren uiteenvallen. In de twintigste eeuw zijn al veertien rijken verdwenen. Het verval van rijken maakt deel uit van een proces dat uiteindelijk ook de natiestaat zal doen instorten. Overheden moeten zich aanpassen aan de groeiende zelfstandigheid van het individu. De capaciteit om belastingen te innen daalt met 50 tot 70 procent, wat kleinere rechtsgebieden bevoordeelt. Het vaststellen van concurrerende voorwaarden om bekwame individuen en hun kapitaal aan te trekken, slaagt in enclaves veel eenvoudiger dan op continentale schaal.

Wij zijn ervan overtuigd dat hedendaagse barbaren steeds vaker op de achtergrond de macht zullen grijpen, zodra de moderne natiestaat uiteenvalt. Groepen zoals de Russische *mafiya*, die de overblijfselen van de voormalige Sovjet-Unie uitbuitte, andere etnische misdaadbendes, *nomenklaturen*, drugsbaronnen en afvallige geheime diensten zullen hun eigen regels maken, en dat doen ze al.[^27] Veel meer dan men doorgaans denkt, hebben deze moderne barbaren de vorm van de natiestaat al binnengedrongen zonder haar uiterlijk wezenlijk te hebben veranderd. Ze fungeren als microparasieten die zich tegoed doen aan een systeem in verval. Net zo gewelddadig en meedogenloos als een staat in oorlog, passen deze groepen de technieken van de staat op een kleinere schaal toe. Hun toenemende invloed en macht draagt bij aan het krimpende belang van de politiek. Microprocessoren verkleinen de benodigde middelen die nodig zijn om effectief geweld in te zetten en te beheersen. Naarmate de technologische revolutie vordert, organiseert geweld zich steeds vaker buiten centrale controle en richt de aanpak om het in te dammen zich meer op efficiëntie dan op de omvang van macht.

### Geschiedenis in omgekeerde richting

De nieuwe logica van het informatietijdperk keert het proces waardoor de natiestaat zich in de afgelopen vijf eeuwen heeft ontwikkeld om. Lokale machtscentra zullen opnieuw aan invloed winnen, terwijl de staat uiteenvalt in gefragmenteerde, overlappende soevereine eenheden.[^8] De groeiende invloed van de georganiseerde misdaad is slechts één afspiegeling van deze trend. Multinationale ondernemingen moeten inmiddels al het niet-essentiële werk uitbesteden, en sommige conglomeraten, zoals AT\&T, Unisys en ITT, splitsten zich op in meerdere ondernemingen om winstgevender te kunnen opereren. De natiestaat zal uiteenvallen zoals een onhandelbaar conglomeraat, maar dat gebeurt waarschijnlijk pas nadat financiële crises haar hiertoe hebben gedwongen.

Niet alleen verandert de machtsbalans in de wereld, maar ook de aard van arbeid verandert radicaal. Dit betekent dat de manier waarop bedrijven opereren onvermijdelijk zal veranderen. De 'virtuele onderneming' illustreert een fundamentele transformatie in de bedrijfsvoering, mogelijk gemaakt door de dalende kosten voor informatie en transacties. We onderzoeken de gevolgen van de informatierevolutie en haar invloed op het uiteenvallen van bedrijven en het verdwijnen van de 'goede baan'. In het informatietijdperk betekent een 'baan' simpelweg een taak die je uitvoert, in plaats van een vaste positie. Microprocessors creëren geheel nieuwe mogelijkheden voor economische activiteiten die alle territoriale grenzen overschrijden. Deze grensoverschrijdende ontwikkeling is wellicht de meest revolutionaire sinds Adam en Eva werden verbannen uit het paradijs onder het vonnis van hun Schepper: 'In het zweet van uw gezicht zult gij uw brood verdienen.' Naarmate technologie onze hulpmiddelen radicaal vernieuwt, veroudert ons rechtssysteem, verandert onze moraal en verschuift onze perceptie. Dit boek legt uit hoe.

Dankzij microprocessoren en de razendsnelle vooruitgang in communicatie kan iedereen nu zelf bepalen waar hij of zij werkt. Transacties via internet worden steeds beter versleuteld en zullen voor belastingambtenaren binnenkort vrijwel onmogelijk te onderscheppen zijn. Belastingvrij kapitaal groeit 'offshore' aanzienlijk sneller dan binnenlands vermogen, dat nog steeds belast wordt volgens de hoge heffingen van de twintigste-eeuwse natiestaat. Na de millenniumwisseling zal een groot deel van de wereldhandel verhuizen naar het nieuwe domein van de cyberspace, een gebied waar regeringen even weinig invloed hebben als over de zeebodem of de verre planeten. In de cyberspace verdwijnen de dreigingen van fysiek geweld, de alfa en omega van de oude politiek. Hier ontmoeten de minderbedeelden en de machthebbers elkaar op gelijke voet. Cyberspace vormt de ultieme offshore jurisdictie: een economie zonder belastingen, een soort Bermuda in de lucht, vol diamanten.

Wanneer dit ultieme belastingparadijs volledig toegankelijk is voor het bedrijfsleven, zal vrijwel al het vermogen als offshorekapitaal fungeren, volledig onder beheer van hun eigenaar. Dit zal een kettingreactie in gang zetten. De staat is er inmiddels aan gewend geraakt om haar belastingbetalers te behandelen zoals een boer omgaat met zijn koeien, die hij op een weiland plaatst om gemolken te worden. Voor je het weet, zullen de koeien vleugels krijgen.

### De wraak van de natiestaat

Zoals een boze boer zal de staat in eerste instantie wanhopige pogingen ondernemen om haar ontsnapte kudde in toom te houden. Ze zal heimelijke, en zelfs gewelddadige middelen inzetten om de toegang tot bevrijdende technologieën te beperken. Dergelijke noodmaatregelen werken slechts tijdelijk, als ze überhaupt effect hebben. De natiestaat van de twintigste eeuw, met al haar arrogantie, zal uitgeput raken dankzij haar dalende belastinginkomsten.

Wanneer de staat haar uitgaven niet langer kan dekken door de belastingen te verhogen, zal ze nog wanhopigere maatregelen aanwenden. Daaronder valt ook het drukken van geld. Overheden zijn er inmiddels aan gewend dat ze een monopolie op de valuta hebben en deze naar eigen inzicht kunnen devalueren. Deze ogenschijnlijk willekeurige inflatie kenmerkt het monetaire beleid van vrijwel alle staten in de twintigste eeuw. Zelfs de sterkste munteenheid van de naoorlogse periode, de Duitse mark, verloor tussen 1 januari 1949 en het einde van juni 1995 maar liefst 71 procent van haar koopkracht, terwijl in dezelfde periode de koopkracht van de Amerikaanse dollar 84 procent daalde.[^9] Die inflatie werkt als een belasting op iedereen die de valuta aanhoudt. Zoals we later zullen zien, zal inflatie als inkomstenbron voor de overheid grotendeels verdwijnen door de opkomst van cybergeld. Men zal de nationale monopolies op de uitgifte en regulering van geld, waar de overheid gedurende de moderne tijd van heeft geprofiteerd, door nieuwe technologie kunnen omzeilen. De kredietcrisissen die Azië, Rusland en andere opkomende economieën in 1997 en 1998 teisterden, tonen immers aan dat nationale valuta en kredietbeoordelingen achterhaald zijn en de soepele werking van de wereldeconomie verstoren. Juist het feit dat de overheid eist dat alle transacties binnen haar jurisdictie in de nationale valuta worden uitgevoerd, maakt de economie kwetsbaar voor fouten van centrale bankiers en aanvallen van speculanten, die de ene deflatoire crisis na de andere veroorzaakten. In het informatietijdperk zullen individuen over cybervaluta kunnen beschikken en daarmee hun monetaire onafhankelijkheid terugwinnen. Wanneer zij hun eigen monetaire beleid via het internet kunnen voeren, zal het minder, of helemaal niet meer relevant zijn dat de staat controle blijft houden op de geldprinter van het industriële tijdperk. Hun invloed op de wereldwijde welvaart wordt dan ingehaald door wiskundige algoritmen die geen fysieke vorm kennen. In het nieuwe millennium zal cybergeld, beheerd door particuliere markten, het fiatgeld, uitgegeven door overheden, vervangen. Alleen de armen zullen het slachtoffer worden van inflatie en de daaropvolgende deflatoire spiralen, gevolgen van de kunstmatige hefboomwerking die fiatgeld in de economie brengt.

Zonder de gebruikelijke mogelijkheden om belastingen te heffen en geld in omloop te brengen, zullen regeringen, zelfs in doorgaans beschaafde landen, zich van hun nare kant laten zien. Naarmate de inkomstenbelasting steeds minder effectief blijkt te worden, zullen oude en arbitraire vormen van dwang weer onder het stof vandaan gehaald worden. De ultieme vorm van bronbelasting -- feitelijke of zelfs openlijke gijzelneming -- zal ingezet worden door overheden die wanhopig proberen te voorkomen dat rijkdom aan hun greep ontsnapt. Ongelukkige burgers zullen dan als gijzelaars voor losgeld worden vastgehouden; bijna zoals we zagen in de middeleeuwen. Ondernemingen die diensten verlenen ter bevordering van de individuele vrijheid raken verstrikt in infiltratie, sabotage en ontwrichting. Willekeurige onteigening van eigendom (alledaags in de Verenigde Staten, waar dit vijfduizend keer per week gebeurt) zal alleen maar toenemen. Regeringen zullen mensenrechten schenden, de vrije informatiestroom censureren, nuttige technologieën saboteren en soms nog veel erger handelen. Net zoals de inmiddels verdwenen Sovjet-Unie tevergeefs probeerde de toegang tot personal computers en Xerox-machines te beperken, zullen westerse regeringen met totalitaire middelen proberen de cybereconomie te onderdrukken.

## Terugkeer van de Luddieten

Dergelijke methoden kunnen echter bij bepaalde bevolkingsgroepen in de smaak vallen. De positieve ontwikkelingen van de individuele bevrijding en autonomie zullen voor velen die niet tot de cognitieve elite horen, juist als slecht nieuws overkomen. Het meeste verzet zal vermoedelijk komen van mensen met middelmatig talent in de huidige rijke landen. Zij zullen ervaren dat informatietechnologie een bedreiging vormt voor hun levensstijl. Degenen die profiteren van de georganiseerde dwang, waaronder miljoenen die een herverdeeld inkomen ontvangen van de overheid, kunnen de nieuwe vrijheid, zoals gerealiseerd door Soevereine Individuen, verafschuwen. Hun verontwaardiging onderstreept de waarheid dat 'waar je staat, wordt bepaald door waar je zit.'

> Soms vroeg ik me af hoe ik zo'n diepe meelevende pijn kon voelen voor het lot van een paar mannen die ik niet kende, terwijl zij in een honkbalstadion honderden mijlen verderop een wedstrijd speelden tegen een groep vreemden. Het antwoord is eenvoudig. Ik hield van mijn teams. Hoewel er risico aan verbonden was, was betrokkenheid de moeite waard. Sport deed mijn bloed sneller stromen, maakte me opgewonden en liet mijn hart bonzen. Ik vond het fijn om iets op het spel te hebben. Het leven kwam tot leven tijdens een wedstrijd. -- Craig Lambert

Het zou echter misleidend zijn om alle negatieve gevoelens die tijdens de aankomende transitiecrisis opkomen, louter toe te schrijven aan een kille hunkering om ten koste van anderen te leven. Er spelen echter nog meer factoren mee. De aard van de menselijke samenleving wijst erop dat er onvermijdelijk een misplaatste morele dimensie meespeelt in de naderende luddistische reactie. Die kille hunkering verschuilt zich in feite achter een morele façade. Wij belichten de morele en moralistische aspecten van de transitiecrisis. Niets zet mensen zo sterk in beweging als de overtuiging dat ze moreel in hun recht staan, meer nog dan puur eigenbelang. Hoewel de band met de burgerlijke mythes uit de twintigste eeuw snel verzwakt, bestaan er nog altijd echte gelovigen. Iedereen die in die eeuw volwassen werd, raakte doordrenkt met de plichten en verantwoordelijkheden van het burgerschap uit die tijd. De overgebleven morele principes uit de industriële samenleving zullen ten minste enkele neo-luddistische aanvallen op informatietechnologieën in gang zetten.

In dit opzicht blijkt het te verwachten geweld deels een uiting te zijn van wat wij 'moreel anachronisme' noemen: het toepassen van morele richtlijnen uit de ene economische periode op de omstandigheden van een andere. Iedere fase van de samenleving vraagt om eigen morele normen die mensen helpen de specifieke valkuilen te overwinnen die bij die manier van leven horen. Een agrarische samenleving functioneerde niet volgens de morele regels van een rondtrekkende Eskimostam, en zo kan ook de informatiesamenleving niet voldoen aan de principes die ooit het succes van een militante industriële staat in de twintigste eeuw mogelijk maakten. Dat lichten we graag toe.

De komende jaren zal moreel anachronisme zich ook in de kernlanden van het Westen duidelijk manifesteren, net zoals het de afgelopen vijf eeuwen in de landen daar ver vandaan te zien was. Westerse kolonisten en militaire expedities veroorzaakten dit soort crises zodra zij in aanraking kwamen met inheemse jagers- en verzamelaarsstammen, en volkeren wiens samenlevingen nog volgens agrarische modellen functioneerden. Het invoeren van nieuwe technologieën in omgevingen die achterbleven in de tijd leidde tot verwarring en morele crises. Het succes van christelijke missionarissen bij de bekering van miljoenen inheemse mensen is voor een groot deel te danken aan de lokale crises die ontstonden door de plotselinge invoering van nieuwe machtsstructuren van buitenaf. Dergelijke botsingen herhaalden zich keer op keer, van de zestiende eeuw tot de vroege decennia van de twintigste eeuw. Wij verwachten vergelijkbare conflicten in het begin van het nieuwe millennium, naarmate de informatiesamenleving het begint over te nemen van de gevestigde industriële systemen.

### De nostalgie naar dwang

De opkomst van het Soevereine Individu zal niet door iedereen als een veelbelovende, nieuwe fase in de geschiedenis worden omarmd, zelfs niet door degenen die er het meeste voordeel uit halen. Iedereen zal gemengde gevoelens hebben. Veel mensen zullen innovaties afkeuren die de territoriale natiestaat ondermijnen. Het is de menselijke natuur om iedere ingrijpende verandering vrijwel altijd als een dramatische achteruitgang te beschouwen. Vijfhonderd jaar geleden beweerden de hoflieden rondom de hertog van Bourgondië dat de opkomende innovaties, die het feodalisme ondermijnden, slecht waren. Zij meenden dat de wereld snel in verval zou raken, toevallig precies op het moment tijdens de Renaissance waarin historici later een explosie van menselijk potentieel constateerden. Zo zou deze periode in het volgende millennium als een nieuwe renaissance kunnen worden gezien, terwijl in de vermoeide ogen van de twintigste eeuw vooral angst is af te lezen.

Er is een grote kans dat degenen die aanstoot nemen aan deze nieuwe ontwikkelingen, en vele anderen die erdoor benadeeld raken, onaangenaam zullen reageren. Hun nostalgie naar dwang zal waarschijnlijk in geweld uitmonden. Ontmoetingen met deze nieuwe 'Luddieten' zorgen er in ieder geval voor dat de overstap naar radicaal nieuwe vormen van sociale organisatie voor iedereen voor wat ellende zal zorgen. Zet je schrap en bereid je voor op de duik. Nu de snelheid van verandering het morele en economische aanpassingsvermogen van velen in onze generatie te boven gaat, kun je rekenen op een felle, verontwaardigde weerstand tegen de Informatierevolutie, ondanks de grote belofte die zij brengt om de toekomst te bevrijden.

Je moet dit soort vervelende ontwikkelingen begrijpen en je er op voorbereiden. Er wacht een transitiecrisis op ons. Deflatoire crises, zoals de Aziatische financiële crisis van 1997 en 1998, zullen blijven opduiken zolang de verouderde instellingen uit het industriële tijdperk niet opgewassen zijn tegen de uitdagingen van de nieuwe, grensoverschrijdende economie. De nieuwe informatie- en communicatietechnologieën ondermijnen de moderne staat sterker dan welke andere politieke bedreiging dan ook sinds de tijd van Columbus. Dat is van belang, want machthebbers hebben zelden vreedzaam gereageerd op ontwikkelingen die hun gezag ondermijnen, en dat zal nu waarschijnlijk niet anders zijn.

De botsing tussen het nieuwe en het oude zal de eerste jaren van het nieuwe millennium bepalen. Wij voorzien een periode van groot gevaar en grote beloningen, waarin op sommige terreinen de beschaving sterk achteruitgaat en op andere terreinen ongekende kansen ontstaan. Steeds autonomere individuen en failliete, wanhopige regeringen zullen tegenover elkaar komen te staan aan beide zijden van een nieuwe kloof. Voor het einde van deze transitie voorzien we een ingrijpende verandering in het concept van soevereiniteit en de vrijwel volledige ondergang van de politiek. Waar de staat nu nog de middelen beheerst, zullen straks vrijwel alle overheidsdiensten geprivatiseerd zijn. Om onontkoombare redenen die we in dit boek uitvoerig bespreken, zal informatietechnologie de capaciteit van de staat zodanig ondermijnen dat zij niet meer in staat is om voor haar diensten meer te vragen dan deze daadwerkelijk waard zijn voor de burgers.

> Regeringen zullen zich moeten bezighouden met wat soevereiniteit betekent. -- Robert Martin

### Soevereiniteit door markten

In een mate die we tien jaar geleden nauwelijks konden voorstellen, verkrijgen individuen via marktmechanismen steeds meer vrijheid ten opzichte van territoriale natiestaten. Deze staten zien hun gezag snel verdwijnen en lopen het risico om failliet te gaan. Hoe machtig ze ook lijken, behouden zij enkel de mogelijkheid om te vernietigen, niet om bevelen uit te delen. Hun intercontinentale raketten en vliegdekschepen functioneren inmiddels als relikwieën, even imposant als zinloos, vergelijkbaar met het laatste oorlogspaard uit het feodale tijdperk.

Informatietechnologie breidt de markten drastisch uit doordat het de wijze verandert waarop activa worden gecreëerd en beschermd. Dit is werkelijk revolutionair. Het belooft zelfs een nog ingrijpendere impact te hebben op de industriële samenleving dan de introductie van buskruit ooit had op het feodale landbouwsysteem. De transformatie rond het jaar 2000 betekent de commercialisering van soevereiniteit en het einde van de traditionele politiek, precies zoals vuurwapens ooit de ondergang van het eedgebonden feodalisme inluidden. Burgerschap zal verdwijnen, net zoals de ridderlijkheid ooit verdween.

Wij zijn ervan overtuigd dat het tijdperk van de individuele economische soevereiniteit aanbreekt. Net zoals staalfabrieken, telefoonmaatschappijen, mijnen en spoorwegen die ooit genationaliseerd waren, wereldwijd in rap tempo werden geprivatiseerd, zul je spoedig de ultieme vorm van privatisering zien: de ingrijpende denationalisering van het individu. Het Soevereine Individu van het nieuwe millennium behoort niet langer tot de staatsbezittingen, een impliciet activum op de balans van de schatkist. Na de transitie van het jaar 2000 worden voormalige burgers geen burgers meer, maar klanten.

### Bandbreedte overwint grenzen

Het commercialiseren van soevereiniteit zal het traditionele burgerschap binnen de natiestaat gedateerd maken, vergelijkbaar met de ridderlijke eeden na de ineenstorting van het feodale systeem. In tegenstelling tot de burger, verplicht tot belastingbetalingen en gebonden aan een machtige staat, worden de Soevereine Individuen van de eenentwintigste eeuw klanten van overheden die opereren in een 'nieuwe logische ruimte'. Zij zullen onderhandelen over de beperkte diensten die zij van het overheidsapparaat wensen en zullen daarvoor betalen via contractuele overeenkomsten. De overheden van het informatietijdperk zullen zich volgens geheel andere principes moeten organiseren dan we de afgelopen eeuwen gewend waren. Sommige rechtsgebieden en diensten met betrekking tot soevereiniteit zullen ontstaan via 'assortive matching', een systeem waarbij overeenkomsten in voorkeuren, zoals commerciële belangen, de basis vormen waarop virtuele jurisdicties een klantenbestand opbouwen.

In zeldzame gevallen kunnen de nieuwe soevereiniteiten restanten zijn van middeleeuwse organisaties, zoals de 900 jaar oude Soevereine Militaire Hospitaalorde van St. Johannes van Jeruzalem, van Rhodos en van Malta. Deze orde, beter bekend als de Ridders van Malta, vormt een belangengroep van rijke katholieken met 10.000 leden en een jaarlijkse inkomstenstroom van enkele miljarden. Zij geven hun eigen paspoorten, postzegels en geld uit en onderhouden volledige diplomatieke betrekkingen met zeventig landen. Momenteel onderhandelt de orde met de Republiek Malta over de terugname van Fort St. Angelo. Door het fort in bezit te nemen, verkrijgen de Ridders het ontbrekende element van territorialiteit, zodat zij als soevereine entiteit erkend kunnen worden. De Ridders van Malta zouden zo opnieuw een soevereine microstaat kunnen vormen, gesteund door hun lange geschiedenis. Vanuit Fort St. Angelo keerden zij in 1565 tijdens de Grote Belegering de Turken de rug toe en regeerden zij Malta vele jaren, totdat Napoleon hen in 1798 verdreef. Als de Ridders van Malta in de komende jaren blijken terug te keren, zou dat het duidelijkste bewijs zijn dat het systeem van moderne natiestaten, dat na de Franse Revolutie zijn intrede deed, slechts een intermezzo was in de langere lijn van de geschiedenis, waarin het normaal was dat verschillende vormen van soevereiniteit naast elkaar bestonden.

Een ander, totaal verschillend model voor postmoderne soevereiniteit op basis van assortive matching zie je terug in het Iridium-satelliettelefoonnetwerk. In eerste instantie lijkt het vreemd om een mobiele telefoniedienst als een vorm van soevereiniteit te beschouwen, maar internationale autoriteiten hebben Iridium al erkend als een virtueel land. Zoals je wellicht weet, biedt Iridium een wereldwijde mobiele telefoniedienst waardoor abonnees via één nummer oproepen kunnen ontvangen, waar ze zich ook bevinden -- of je nu in Featherston, Nieuw-Zeeland bent of in de Boliviaanse Chaco. Om te garanderen dat de oproepen overal de juiste abonnees bereiken, stemden internationale telecomautoriteiten ermee in Iridium als een virtueel land te erkennen, compleet met een eigen landcode: 8816. Het vereist dan ook geen ingewikkelde logica om te beargumenteren dat als een virtueel land van satelliettelefoonabonnees soeverein kan zijn, meer samenhangende virtuele gemeenschappen op het grensoverschrijdende internet dit ook zullen kunnen zijn.

Bandbreedte (oftewel de draagcapaciteit van een communicatiemedium) is sinds de uitvinding van de transistor sneller gegroeid dan de rekenkracht. Als deze trend zich voortzet, zijn wij ervan overtuigd dat de bandbreedte binnen enkele jaren, kort na de millenniumwisseling, zodanig toeneemt dat men de 'metaverse' kan realiseren, de alternatieve cyberspacewereld zoals bedacht door sciencefictionauteur Neal Stephenson. Stephenson's 'metaverse' staat voor een hechte virtuele gemeenschap met haar eigen regels. Wij geloven dat, naarmate de cybereconomie groeit, de deelnemers uiteindelijk vrijgesteld worden van de verouderde wetten van traditionele natiestaten. De nieuwe cybergemeenschappen zullen minstens even welvarend zijn en hun belangen net zo effectief behartigen als de Soevereine Militaire Hospitaalorde van St. Johannes van Jeruzalem, van Rhodos en van Malta. Dankzij geavanceerde communicatietechnologieën en de mogelijkheden binnen informatieoorlogvoering zullen zij zich beter weten stand te houden. We onderzoeken daarnaast ook andere modellen van gefragmenteerde soevereiniteit, waarin kleine groepen feitelijk de soevereiniteit van zwakkere natiestaten kunnen leasen en hun eigen economische toevluchtsoorden kunnen exploiteren, vergelijkbaar met hoe vrije havens en vrijhandelszones dat nu doen.

We hebben een nieuwe morele woordenschat nodig om de relaties tussen Soevereine Individuen en wat er overblijft van de overheid te beschrijven. Naarmate de spelregels van deze nieuwe verhoudingen duidelijker worden, zullen ze waarschijnlijk stuiten op weerstand van mensen die zijn grootgebracht met het idee "burger" te zijn van een twintigste-eeuwse natiestaat. Het verdwijnen van naties en de 'denationalisering van het individu' doen enkele gekoesterde opvattingen vervagen, zoals het principe van 'gelijke bescherming onder de wet', dat uitgaat van machtsverhoudingen die spoedig tot het verleden behoren. Naarmate virtuele gemeenschappen sterkere samenhang ontwikkelen, zullen zij eisen dat hun leden volgens hun eigen regels ter verantwoording worden geroepen in plaats van volgens de wetten van de voormalige natiestaten waarin zij wonen. Binnen hetzelfde geografische gebied zullen opnieuw meerdere rechtsstelsels naast elkaar functioneren, zoals we in de oudheid en middeleeuwen zagen.

Net zoals dat de pogingen om de riddermacht te behouden, faalden door de opkomst van vuurwapens, zijn de moderne noties van nationalisme en burgerschap gedoemd om tot irrelevantie te vervallen door de ontwikkeling van microtechnologie. Ze zullen uiteindelijk belachelijk lijken, net zoals de heilige principes van het vijftiende-eeuwse feodalisme, waarmee al in de zestiende eeuw de spot werd gedreven. De gekoesterde burgerlijke waarden van de twintigste eeuw zullen lachwekkende anachronismen blijken te zijn voor komende generaties na de transformatie van het jaar 2000. De Don Quichot van de eenentwintigste eeuw wordt geen dwaalridder die de glorie van het feodalisme doet herleven, maar zal een bureaucraat in een bruin pak zijn: een belastingambtenaar die erop uit is om de burgers te controleren.

## Herleving van de wetten van de mark

We denken zelden aan overheden als concurrerende partijen, behalve in heel algemene zin. Daardoor is ons besef van wat soevereiniteit kan inhouden, verzwakt. Vroeger, toen de machtsverhoudingen het voor verschillende groepen bemoeilijkten om een stabiel monopolie op dwang te vestigen, was de macht vaak gefragmenteerd, overlapten rechtsgebieden elkaar gedeeltelijk en oefenden diverse entiteiten één of meer kenmerken van soevereiniteit uit. Vaak bleek de zogenaamde heerser in de praktijk nauwelijks enige macht te bezitten. Tegenwoordig concurreren overheden die minder sterk zijn dan natiestaten actief om op lokaal niveau een monopolie op dwang uit te oefenen. Deze concurrentie heeft geleid tot veranderingen in de wijze waarop geweld wordt beheerst en loyaliteit wordt gewonnen -- veranderingen die spoedig weer zichtbaar zullen worden.

Toen de macht van heren en vorsten nog beperkt was en de aanspraken van één of meer groepen elkaar overlapten bij grensgebieden, kon geen van beide partijen de overhand krijgen. In de Middeleeuwen kende men talrijke grensgebieden, de zogenaamde 'marken' (of *marches* in het Engels), waar soevereiniteiten in elkaar overliepen. Deze conflictrijke gebieden hielden decennialang, zo niet eeuwenlang stand binnen de grenzen van het Europese continent. Men vond marken tussen gebieden onder Keltische en Engelse invloed in Ierland; tussen Wales en Engeland; tussen Schotland en Engeland; tussen Italië en Frankrijk; tussen Frankrijk en Spanje; tussen Duitsland en de Slavische grensstreken van Centraal-Europa; en tussen de christelijke koninkrijken van Spanje en het islamitische koninkrijk Granada. Dergelijke grensgebieden ontwikkelden unieke institutionele en juridische structuren, en we verwachten dat we dit fenomeen in het komende millennium opnieuw zullen zien terugkeren. Doordat twee autoriteiten met elkaar concurreerden, betaalden de inwoners van deze streken zelden belasting. Bovendien konden zij doorgaans zelf bepalen wiens wetten zij zouden volgen, door middel van juridische instrumenten als de 'erkenning' en de 'beslaglegging' -- concepten die tegenwoordig vrijwel geheel zijn verdwenen. Wij voorzien dat zulke principes een prominente rol zullen spelen in het recht van informatiesamenlevingen.

### Het overstijgen van nationaliteit

Door de opkomst van de natiestaat was het lastig om precies vast te stellen hoeveel soevereine entiteiten de wereld telde, omdat zij op ingewikkelde wijze in elkaar overliepen en allerlei vormen van organisatie hanteerden. Dat zal in de toekomst opnieuw zo zijn. Binnen de natiestaat werden de grenzen tussen territoria scherp afgebakend, maar in het informatietijdperk zullen deze lijnen weer vervagen. In het nieuwe millennium raakt soevereiniteit opnieuw gefragmenteerd en duiken er nieuwe entiteiten op die slechts enkele, maar niet alle kenmerken bezitten die we met overheden associëren.

Sommige van deze nieuwe entiteiten, vergelijkbaar met de Tempeliers en andere religieuze militaire orden uit de middeleeuwen, kunnen met aanzienlijke rijkdom en militaire kracht opereren, ook al beschikken zij niet over een vast grondgebied. Ze organiseren zich op basis van principes die niets met nationaliteit te maken hebben. In de middeleeuwen ontleenden leden en leiders van religieuze organisaties, die in delen van Europa soevereine macht uitoefenden, hun gezag niet aan een nationale identiteit. Zij vertegenwoordigden diverse etnische achtergronden en verklaarden hun trouw aan God, niet aan een bepaalde band die een nationaliteit zou moeten scheppen.

### Koopliedenrepublieken van cyberspace

Je zult tevens zien dat samenwerkingsverbanden tussen kooplieden en vermogende individuen met semisouvereine bevoegdheden weer opbloeien, zoals de Hanze, een middeleeuwse confederatie van kooplieden. De Hanze, die actief was op de Franse en Vlaamse markten, groeide uit tot een organisatie die kooplieden uit zestig steden verenigde.[^10] De 'Hanseatic League' -- zoals men haar in het Engels op een overbodige wijze aanduidt (de letterlijke vertaling is immers: 'Liga liga') -- vormde een verbond van Germaanse koopmansgilden dat haar leden bescherming bood en handelsverdragen onderhandelde. Ze kreeg in diverse steden in Noord-Europa en de Baltische regio semisouvereine bevoegdheden. Vergelijkbare entiteiten zullen in het nieuwe millennium opkomen als vervanging van de stervende natiestaat, en zullen bescherming bieden en bijdragen aan het handhaven van contracten in een onveilige wereld.

Kortom, de toekomst zal waarschijnlijk niet voldoen aan de verwachtingen van degenen die de burgerlijke mythes van de industriële samenleving van de twintigste eeuw hebben geïnternaliseerd, waaronder ook de illusies van de sociale democratie, dat ooit de meest getalenteerde geesten opzweepte en motiveerde. Deze mensen gaan ervan uit dat samenlevingen zich ontwikkelen op de manier die voor de overheid het meest wenselijk is, het liefst als reactie op opiniepeilingen en nauwkeurig getelde stemmen. Dit bleek echter nooit zo evident als vijftig jaar geleden werd gedacht. Vandaag de dag is het een anachronisme, net zozeer een overblijfsel van het industrialisme als een roestige schoorsteen. Deze burgerlijke mythes laten niet alleen een denkwijze zien die maatschappelijke problemen als oplosbaar via technische ingrepen beschouwt, maar onthullen ook een vals vertrouwen dat hulpbronnen en individuen in de toekomst even kwetsbaar blijven voor politieke dwang als in de twintigste eeuw. Wij betwijfelen dat. Het zijn marktkrachten, niet politieke meerderheden, die samenlevingen zullen dwingen zich opnieuw in te richten op manieren die de publieke opinie noch zal begrijpen, noch zal verwelkomen. Als dat gebeurt, blijkt de naïeve opvatting dat geschiedenis is wat mensen willen dat zij is, buitengewoon misleidend.

Het zal daarom essentieel zijn om de wereld vanuit een nieuw perspectief te benaderen. Dat betekent dat u de zaken van buitenaf zult moeten observeren en veel vanzelfsprekend geachte aannames in vraag zult moeten stellen, zodat nieuwe inzichten kunnen ontstaan. Als u er niet in slaagt het conventionele denken te overstijgen in een tijd waarin dit denken de aansluiting met de werkelijkheid verliest, loopt u het risico ten prooi te vallen aan een epidemie van desoriëntatie. Die desoriëntatie leidt tot fouten die uw bedrijf, uw investeringen en uw levensstijl in gevaar kunnen brengen.

> Het universum beloont ons als we het doorgronden en straft ons als we dat niet doen. Als wij het universum doorgronden, slagen onze plannen en voelen wij ons op ons best. Maar als wij proberen te vliegen door van een klif te springen en simpelweg met onze armen te fladderen, dan zal het universum ons ten val brengen. -- JACK COHEN EN IAN STEWART[^11]

### De wereld vanuit een nieuw perspectief

Om u voor te bereiden op de toekomst, moet u begrijpen waarom de wereld die gaat komen anders zal zijn dan de voorspellingen van de meeste experts. Dit betekent dat u grondig moet kijken naar de verborgen oorzaken van verandering. Wij hebben geprobeerd dit inzichtelijk te maken met een onconventionele analyse, die wij de studie van 'megapolitiek' noemen. In de twee eerdere delen, *Blood in the Streets* en *The Great Reckoning*, betoogden we dat de voornaamste oorzaken van verandering niet te vinden zijn in politieke manifesten of in de uitspraken van overleden economen, maar in de verborgen factoren die de grenzen waarover macht wordt uitgeoefend, doen veranderen. Vaak zorgen subtiele wijzigingen in klimaat, topografie, micro-organismen en technologie ervoor dat de logica van geweld verschuift. Deze veranderingen transformeren ook de manier waarop mensen hun levensonderhoud organiseren en zich verdedigen.

We zijn ons ervan bewust dat onze benadering voor het doorgronden van wereldveranderingen sterk afwijkt van die van de meeste voorspellers. Wij beweren niet dat wij meer weten over bepaalde 'onderwerpen' dan degenen die hun hele carrière hebben gewijd aan diepgaande specialisatie. Integendeel, wij bekijken de zaken juist van buitenaf en beschikken over kennis van de onderwerpen waarop wij onze voorspellingen baseren. Voor ons draait het er vooral om te herkennen waar de grenzen van de noodzaak liggen. Als die grenzen veranderen, verandert de samenleving onvermijdelijk, ongeacht wat mensen graag zouden willen.

Vanuit ons perspectief schuilt de sleutel tot het begrijpen van de ontwikkeling van samenlevingen in het doorgronden van de factoren die de kosten en baten van geweld bepalen. Elke menselijke samenleving, van jagerstammen tot grote rijken, wordt gevormd door de wisselwerking van megapolitieke krachten die de dominante versie van de 'wetten van de natuur' vastleggen. Het leven is overal complex. Lammeren en leeuwen bewaken een fragiele balans, waarbij zij subtiel op elkaar inwerken. Als leeuwen ineens sneller zouden worden, zouden zij prooien kunnen vangen die voorheen ontsnapten. En stel dat lammeren plotseling vleugels zouden krijgen, dan zouden de leeuwen verhongeren. Het vermogen om geweld in te zetten en zich ertegen te verdedigen is de cruciale factor die het leven aan de marge beïnvloedt.

Wij hebben een goede reden om geweld centraal in onze theorie over megapolitiek te plaatsen. Het beheersen van geweld vormt het grootste dilemma voor iedere samenleving. Zoals we schreven in *The Great Reckoning*:

> De reden dat mensen tot geweld overgaan, is simpelweg dat het vaak loont. In zekere zin is dat het meest voor de hand liggende wat een mens kan doen als hij geld wil: het gewoon afpakken. Dit geldt evenzeer voor een leger dat een olieveld verovert als voor een enkele crimineel die zomaar een portemonnee pakt. Macht zoekt, zoals William Playfair schreef, 'altijd de gemakkelijkste weg naar rijkdom door degenen aan te vallen die erover beschikken.'
>
> De uitdaging voor voorspoed ligt juist in het feit dat roofzuchtig geweld onder bepaalde omstandigheden zeer winstgevend is. Oorlog herschrijft de spelregels, verandert de verdeling van eigendommen en inkomen, en bepaalt zelfs wie er leeft en wie sterft. Juist het feit dat geweld loont, maakt het zo moeilijk te beheersen.[^12]

Het denken in deze termen hielp ons ontwikkelingen te voorspellen waarover zelfs de meest doorgewinterde experts ervan overtuigd waren dat ze nooit zouden plaatsvinden. Zo was bijvoorbeeld *Blood in the Streets*, dat begin 1987 verscheen, onze poging om de eerste signalen in kaart te brengen van de grootschalige megapolitieke revolutie die zich nu ontvouwt. Destijds stelden wij dat technologische vernieuwing de mondiale machtsverhoudingen radicaal zou verstoren. Onze belangrijkste stellingen waren:

* Wij voorspelden dat het Amerikaanse overwicht zou afnemen, wat zou leiden tot economische onevenwichtigheden en tegenspoed, waaronder een beurscrash in de stijl van 1929. Hoewel de experts vrijwel unaniem weigerden te geloven dat zoiets kon gebeuren, werden de markten in oktober 1987, amper zes maanden na onze voorspelling, geschokt door de heftigste verkoopgolf van de eeuw.
* Wij waarschuwden de lezers voor de ineenstorting van het communisme. Wederom lachten de experts ons uit, maar in 1989 deden zich gebeurtenissen voor die "niemand had kunnen voorzien." De Berlijnse Muur viel en revoluties deden de communistische regimes, van de Baltische staten tot zelfs Boekarest, verdwijnen.
* Wij legden uit waarom het multi-etnische rijk, dat door de bolsjewistische elite werd overgenomen van de tsaren, onvermijdelijk uiteen zou vallen. Eind december 1991 hing de hamer- en sikkelvlag voor de laatste keer boven het Kremlin, waarna de Sovjetunie voorgoed ophield te bestaan.
* Midden in de intensieve wapenwedloop onder Reagan voorspelden wij dat de wereld op de drempel stond van een ingrijpende ontwapening. Ook dit werd als onwaarschijnlijk -- zo niet belachelijk -- afgedaan, maar in de daaropvolgende zeven jaar vond wel de meest ingrijpende ontwapening plaats sinds het einde van de Eerste Wereldoorlog.
* Terwijl experts in Noord-Amerika en Europa naar Japan wezen als bewijs dat overheden markten succesvol konden manipuleren, stelden wij het tegendeel vast. Wij voorspelden dat de bloeiperiode van de Japanse financiële bubbel zou eindigen in een ineenstorting. Niet lang na de val van de Berlijnse Muur stortte de Japanse aandelenmarkt in en verloor bijna de helft van haar waarde. Wij blijven ervan overtuigd dat het dieptepunt van deze neerwaartse beweging het verlies van 89 procent, zoals Wall Street na 1929 heeft geleden, kan evenaren of zelfs overtreffen.
* Terwijl bijna iedereen, van het middenklassegezin tot de grootste vastgoedinvesteerders ter wereld, ervan overtuigd leek dat vastgoedmarkten enkel zouden stijgen, waarschuwden wij voor een naderende vastgoedcrisis. Binnen vier jaar verloren vastgoedinvesteerders wereldwijd meer dan $1 biljoen ($1.000 miljard)  toen de vastgoedmarkt kelderde.
* Al ruim voordat experts de achteruitgang in de inkomens van arbeiders onderkenden, voorspelden wij in *Blood in the Streets* dat deze daling structureel zou blijven bestaan. Nu, bijna een decennium later, begint een slapende wereld eindelijk in te zien dat dit klopt. Het gemiddelde uurloon in de Verenigde Staten is gedaald tot een niveau lager dan tijdens de tweede Eisenhower-regering. In 1993 bedroeg het gemiddelde jaarinkomen, gecorrigeerd voor inflatie, $18.808. In 1957, toen Eisenhower werd ingezworen voor zijn tweede ambtstermijn, was het gemiddelde jaarlijkse uurloon in de VS $18.903.

Hoewel de centrale thema's uit *Blood in the Streets* achteraf gezien verrassend nauwkeurig bleken, noemden de hoeders van het conventionele denken deze inzichten nog enkele jaren geleden pure onzin. In 1987 bestempelde een recensent in *Newsweek* onze analyse als 'een ondoordachte aanval op de rede', waarmee hij de bekrompenheid van de laat-industriële mentaliteit treffend illustreerde.

Je zou denken dat *Newsweek* en vergelijkbare publicaties inmiddels inzagen dat onze analysemethode waardevolle inzichten bood in hoe de wereld veranderde. Maar niets is minder waar. De eerste uitgave van *The Great Reckoning* werd met dezelfde gniffelende vijandigheid ontvangen als *Blood in the Streets*. Zelfs het *Wall Street Journal* wees onze analyse resoluut af als het geklets van 'je suffe tante'.

Ondanks al het gegiechel, bleken de thema's van *The Great Reckoning* minder belachelijk dan de hoeders van de orthodoxie deden vermoeden.

Ook hebben we onze voorspelling over de ondergang van de Sovjet-Unie verder uitgewerkt door te onderzoeken waarom Rusland en de andere voormalige Sovjetrepublieken een toekomst tegemoet gingen vol toenemende burgerlijke onrust, hyperinflatie en dalende levensstandaarden.

* We legden uit waarom de jaren 1990 een decennium van krimp zouden worden, met voor het eerst een wereldwijde inkrimping van zowel overheden als bedrijven.
* We voorspelden tevens dat een ingrijpende herdefiniëring van de voorwaarden voor inkomensherverdeling stond te gebeuren, wat zou leiden tot flinke bezuinigingen op uitkeringen. Overal,van Canada tot Zweden, verschenen de eerste signalen van een fiscale crisis, en Amerikaanse politici begonnen te spreken over 'het beëindigen van de welvaartsstaat zoals wij die kennen.'
* Wij voorzagen en legden uit dat de 'nieuwe wereldorde' uiteindelijk als een 'nieuwe wereldwanorde' zou uitpakken. Lange tijd vóórdat de gruweldaden in Bosnië de krantenkoppen overspoelden, waarschuwden wij dat Joegoslavië in een burgeroorlog zou instorten.
* Nog vóórdat Somalië in volledige anarchie verviel, legden wij uit hoe de dreigende ineenstorting van regeringen in Afrika ervoor zou zorgen dat sommige landen daar feitelijk onder curatele zouden worden gesteld.
* Wij voorspelden en verduidelijkten waarom de militante islam het marxisme als leidende ideologie in de confrontatie met het Westen zou verdringen. Jaren voordat de bomaanslag in Oklahoma plaatsvond en men probeerde het World Trade Center op te blazen, lieten wij zien waarom de Verenigde Staten te maken zouden krijgen met een toename aan terrorisme.
* Nog vóórdat de krantenkoppen over rellen in Los Angeles, Toronto en andere steden verschenen, legden wij uit hoe de opkomst van criminele subculturen onder stedelijke minderheden de weg vrijmaakte voor wijdverspreid crimineel geweld.
* We voorspelden ook 'de laatste depressie van de twintigste eeuw', die in 1989 in Azië begon en zich vanaf de periferie naar het centrum van het mondiale systeem verspreidde. Wij stelden dat de Japanse aandelenmarkt het voorbeeld van Wall Street na 1929 zou volgen, wat uiteindelijk zou uitmonden in een kredietcrisis en depressie. Overheden in Japan en elders grepen fors in, waardoor de financiële markten tijdelijk niet volledig weerspiegelden hoe slecht de kredietsituatie daadwerkelijk was. Het verplaatste slechts de economische problemen en verergerde ze. Hierdoor kwamen overheden wereldwijd onder druk te staan om competitieve monetaire devaluaties door te voeren, en dreigde zelfs een systeemwijde kredietcrisis, zoals de crisis in de jaren 1930, die wereldwijd economieën deed instorten.

*The Great Reckoning* belichtte ook een reeks controversiële theses die nog niet bevestigd zijn, of het door ons voorspelde ontwikkelingsniveau nog niet hebben bereikt:

* We voorspelden dat de Japanse beurs dezelfde weg zou inslaan als Wall Street na 1929, wat zou uitmonden in een kredietcrisis en economische depressie. Ondanks dat de werkloosheid in landen als Spanje en Finland zelfs hoger uitviel dan in de jaren '30, en sommige landen -- zoals Japan -- met lokale depressies kampten, is er nog geen wereldwijde kredietcrash geweest zoals die destijds hele economieën onderuit haalde.
* We stelden dat het uiteenvallen van het centraal geleide systeem in de voormalige Sovjet-Unie zou leiden tot de verspreiding van kernwapens naar ministaten, terroristische groeperingen en criminele bendes. Tot grote opluchting van de wereld is dat niet gebeurd, althans niet in de mate die wij vreesden. Persberichten melden dat Iran diverse tactische kernwapens op de zwarte markt heeft aangeschaft en dat de Duitse autoriteiten meerdere pogingen tot de verkoop van nucleaire materialen hebben verijdeld. Er is overigens geen melding gemaakt van daadwerkelijke inzet of gebruik van kernwapens uit het arsenaal van de voormalige Sovjet-Unie.
* Ten slotte legden we uit waarom de zogenaamde 'War on Drugs' een recept was voor het ondermijnen van de politie- en rechtssystemen in landen met wijdverspreid drugsgebruik, vooral in de Verenigde Staten. Dankzij de tientallen miljarden dollars aan verborgen monopoliewinsten die drugshandelaren jaarlijks binnen harken, beschikken ze over zowel de middelen als de prikkel om zelfs schijnbaar stabiele landen te corrumperen. De internationale media hebben zo nu en dan gesuggereerd dat drugsgeld tot in de hoogste regionen van de Amerikaanse politiek is doorgedrongen, maar het volledige verhaal is nog niet verteld.

### Kijken waar anderen niet kijken

Hoewel sommige van onze voorspellingen achteraf fout bleken of met de huidige kennis als onjuist worden bestempeld, blijft het totaalplaatje standhouden tegen de kritiek. Veel van de ontwikkelingen die waarschijnlijk een rol zouden gaan spelen in de economische geschiedenis van de jaren 1990 werden al eerder voorspeld en toegelicht in *The Great Reckoning*. Wij voorspelden niet simpelweg een voortzetting van de bestaande trends, maar wezen op ingrijpende breuken met wat sinds de Tweede Wereldoorlog als normaal werd beschouwd. We waarschuwden dat de jaren negentig drastisch anders zouden zijn dan de voorgaande vijf decennia. Als je het nieuws van 1991 tot en met 1995 volgt, zie je dat de thema's uit *The Great Reckoning* bijna dagelijks werkelijkheid werden.

Wij interpreteren deze ontwikkelingen niet als losse tegenslagen, maar als schokgolven langs één doorlopende breuklijn. De oude orde wordt op zijn kop gezet door een megapolitieke aardbeving die een revolutie in de politieke instellingen zal veroorzaken, en de manier waarop kritische geesten de wereld beschouwen radicaal zal veranderen.

Ondanks de cruciale rol die geweld speelt in het functioneren van onze wereld, krijgt het opvallend weinig serieuze aandacht. De meeste politieke analisten en economen doen alsof geweld slechts een kleine ergernis is, vergelijkbaar met een vlieg die rond een taart zoemt, en niet als de bakker die de taart heeft gemaakt.

### Een andere grondlegger van de megapolitiek

Sterker nog, er is zo weinig helder nagedacht over de rol van geweld in de geschiedenis dat een bibliografie met alle megapolitieke analyses op één vel papier zou passen. In *The Great Reckoning* baseerden we onze redenering onder meer op een bijna volledig vergeten klassieker over megapolitieke analyse, namelijk *An Enquiry into the Permanent Causes of the Decline and Fall of Powerful and Wealthy Nations* van William Playfair, gepubliceerd in 1805. Eén van onze uitgangspunten is tevens het werk van Frederic C. Lane. Lane, een historicus die zich onder meer richtte op de middeleeuwen, publiceerde in de jaren '40 en '50 verschillende scherpe essays over de rol van geweld in de geschiedenis. Wellicht was zijn essay *Economic Consequences of Organized Violence*, dat in 1958 in het *Journal of Economic History* verscheen, het meest omvattende van deze werken. Buiten professionele economische en geschiedkundige kringen heeft slechts een enkeling het gelezen en lijken de meesten de ware betekenis ervan niet te hebben doorgrond. Net als Playfair richtte Lane zich tot een publiek dat op dat moment nog niet bestond.

### Inzichten voor het informatietijdperk

Lane publiceerde zijn werk over geweld en de economische betekenis van oorlog ruim voor de intrede van het informatietijdperk. Hij schreef zeker niet met de introductie van microprocessing of andere technologische revoluties die zich tegenwoordig ontvouwen in het vooruitzicht. Toch bieden zijn inzichten omtrent geweld een kader om te begrijpen hoe de informatierevolutie de samenleving zal herstructureren. Het toekomstbeeld dat Lane schetste, bleek in werkelijkheid een blik terug in de tijd.

Hij was een middeleeuwse historicus, met name gespecialiseerd in de handelsstad Venetië, waar het fortuin op en neer schommelde in een wereld vol geweld. Toen hij nadacht over de opkomst en ondergang van Venetië, viel hem op dat de manier waarop geweld wordt georganiseerd en gecontroleerd een cruciale rol speelt in hoe schaarse middelen worden ingezet.[^13]

Wij zijn ervan overtuigd dat Lanes analyses over de concurrerende toepassingen van geweld ons veel inzicht kunnen geven in hoe het leven in het informatietijdperk waarschijnlijk zal verlopen. Maar verwacht niet dat de meeste mensen zo'n extreem abstract betoog zullen opmerken, laat staan het daadwerkelijk volgen. Terwijl de wereld haar aandacht richt op partijdige debatten en excentrieke persoonlijkheden, glipt de dynamiek van de megapolitiek bijna onopgemerkt voorbij. De gemiddelde Noord-Amerikaan besteedt waarschijnlijk honderd keer meer aandacht aan O.J. Simpson dan aan de nieuwste microtechnologieën, die zijn baan overbodig lijken te maken en het politieke systeem, waar hij op vertrouwt voor zijn werkloosheidsuitkeringen, ondermijnen.

## De ijdelheid van wensen

De neiging om over het hoofd te zien wat van fundamenteel belang is, is niet alleen voorbehouden voor de bankzitter die tv kijkt. Volgens klassieke denkers verandert de wereld omdat de overtuigingen van mensen veranderen -- een van de hardnekkige illusies die de natiestaat in stand houdt. Zelfs ogenschijnlijk scherpe analisten komen vaak met verklaringen en voorspellingen waarbij grote historische gebeurtenissen worden voorgesteld alsof ze voort zijn gekomen uit wensdenken. Een opvallend voorbeeld van dit type redenering verscheen op de opiniepagina van de *New York Times* in een artikel van Nicholas Colchester, precies op het moment dat wij *Goodbye, Nation State, Hello... What?* schreven.[^14] Niet alleen behandelde hij het onderwerp, de ondergang van de natiestaat, precies het thema dat wij bespreken, maar plaatste hij zichzelf ook als een treffend voorbeeld van hoe ver ons denken van de norm afwijkt. Colchester is geen eenvoudige denker. Hij was redactioneel directeur van de *Economist Intelligence Unit*. Als iemand een realistisch wereldbeeld belichaamt, dan is dat ongetwijfeld hij. Toch betoogt hij in zijn artikel op meerdere punten dat 'de komst van een internationale overheid' nu onvermijdelijk is.

Waarom? Omdat de natiestaat wankelt en niet langer in staat is de economische krachten in toom te houden.

Wat ons betreft is deze veronderstelling zo goed als absurd. Het is een misvatting om te denken dat een nieuwe bestuursvorm automatisch opkomt zodra een bestaande faalt. Volgens die logica hadden Haïti en Zaïre al lang beter bestuur moeten kennen, simpelweg omdat wat zij hadden zo overduidelijk ontoereikend was.

Het standpunt van Colchester, breed gedeeld door de weinigen in Noord-Amerika en Europa die over zulke zaken nadenken, houdt totaal geen rekening met de grotere megapolitieke krachten die bepalen welke politieke systemen werkelijk levensvatbaar zijn. Dat vormt de kern van dit boek. Wanneer we rekening houden met de technologieën die het nieuwe millennium vormgeven, zullen we waarschijnlijk niet één wereldregering krijgen, maar eerder microregeringen of zelfs anarchistische toestanden.

Voor elke serieuze analyse van de rol van geweld in het bepalen van de regels waar iedereen zich aan moet houden, zijn er tientallen boeken geschreven over de miniscule details van graansubsidies en honderden over obscure aspecten van monetair beleid. Het gebrek aan een doordachte benadering van de cruciale kwesties die echt het verloop van de geschiedenis bepalen, weerspiegelt waarschijnlijk de relatieve stabiliteit van de machtsstructuur van de afgelopen eeuwen. De vogel die op de rug van een nijlpaard in slaap valt, maakt zich geen zorgen over zijn zitplek totdat het dier in beweging komt. Dromen, mythen en fantasieën spelen een veel grotere rol in het vormgeven van wat men de 'sociale wetenschappen' noemt dan men doorgaans vermoedt.

Nergens is dit duidelijker dan in de talloze teksten over economische rechtvaardigheid. Terwijl men eindeloos praat en schrijft over wat eerlijk is of niet, wordt zelden diepgaand onderzocht hoe geweld de samenleving vormgeeft, en dus de grenzen bepaalt waarbinnen de economie opereert. Moderne ideeën over economische rechtvaardigheid veronderstellen echter vaak dat de samenleving dient aangestuurd te worden door een uiterst krachtig dwangapparaat (één dat in staat is om welvaart af te nemen en te herverdelen). Deze vorm van macht is slechts een paar generaties geleden ontstaan, en nu is ze aan het afbrokkelen.

### Big Brother over de sociale zekerheid

Door industriële technologie beschikten overheden in de twintigste eeuw over meer controle-instrumenten dan ooit tevoren. Voor een tijd leek het onvermijdelijk dat overheden het geweld zo effectief zouden monopoliseerden dat er nauwelijks nog ruimte zou blijven voor individuele autonomie. Halverwege de eeuw durfde niemand te verlangen naar een triomf van het Soevereine Individu.

Enkele van de scherpste waarnemers uit het midden van de twintigste eeuw waren ervan overtuigd dat de drang van natiestaten om de macht te centraliseren uiteindelijk zou leiden tot een totalitaire overheersing van alle levensdomeinen. In George Orwells *1984*, uitgegeven in 1949, hield 'Big Brother' elk individu nauwlettend in de gaten, terwijl hij vergeefs probeerde ook maar een spoor van autonomie en eigenwaarde te behouden. Het leek een verloren strijd. Friedrich von Hayeks *The Road to Serfdom*, uit 1944, benaderde het onderwerp op een wetenschappelijke manier en betoogde dat vrijheid ten onder zou gaan aan een nieuwe vorm van economische controle, waardoor de staat uiteindelijk de absolute macht zou krijgen. Deze werken schreef men vóór de opkomst van microprocessoren, die later een scala aan technologieën zouden introduceren waarmee zelfs kleine groepen en individuen onafhankelijk van de centrale autoriteit kunnen opereren.

Hoe scherp Hayek en Orwell ook waren, ze bleken uiteindelijk te pessimistisch. De geschiedenis heeft enkele verrassingen voortgebracht. Het totalitaire communisme hield nauwelijks stand tot 1984. Een nieuwe variant van lijfeigenschap zou in het volgende millennium nog kunnen ontstaan als overheden erin slagen de bevrijdende kracht van microtechnologie te onderdrukken. Het is echter veel waarschijnlijker dat we ongekende kansen en meer individuele autonomie zullen ervaren. Waar onze ouders zich zorgen over maakten, blijkt mogelijk helemaal geen probleem te vormen. Wat zij als vaste en blijvende kenmerken van het sociale leven beschouwden, lijkt nu gedoemd te verdwijnen. Zodra de nood het eist, passen we ons aan en organiseren we ons leven naar de nieuwe werkelijkheid.

### De risico's van voorspellen

We wagen ongetwijfeld een stukje van onze waardigheid als we proberen om ingrijpende veranderingen in de organisatie van ons leven en in de cultuur die ons verbindt te voorspellen en te verklaren. De meeste voorspellingen blijken uiteindelijk belachelijk, en hoe dramatischer de voorspelde verandering, hoe beschamender zij doorgaans uitpakken. De wereld gaat niet ten onder, de ozonlaag verdwijnt niet en de voorspelde ijstijd maakt plaats voor wereldwijde opwarming. Ondanks alle signalen die wijzen op het tegenovergestelde, zit er nog steeds olie in de tank. Meneer Antrobus, de doorsnee-man uit *The Skin of Our Teeth*, weet te voorkomen dat hij bevriest, overleeft oorlogen en dreigende economische rampen, en wordt oud, terwijl hij de weldoordachte waarschuwingen van experts links laat liggen.

De meeste pogingen om de toekomst te 'onthullen' komen al snel komisch over. Zelfs als eigenbelang onze blik op scherp zet, blijft onze visie op de toekomst vaak kortzichtig. In 1903 stelde Mercedes: 'Er zullen nooit 1 miljoen auto's wereldwijd rondrijden, omdat het onwaarschijnlijk is dat 1 miljoen ambachtslieden tot chauffeurs zullen kunnen worden opgeleid.'[^15]

Dit besef zou ons tot zwijgen moeten brengen, maar dat gebeurt niet. We schuwen het niet om onze welverdiende portie spot te incasseren. Als we er ver naast zitten, mogen toekomstige generaties naar hartenlust lachen, als ze zich überhaupt herinneren wat we hebben gezegd. Het durven uiten van een gedachte houdt altijd het risico in dat je het mis hebt. We zijn heus niet zo star of voorzichtig dat we geen fouten durven maken. Liever delen we ideeën die u mogelijk iets opleveren, dan dat we ze inslikken uit angst dat ze achteraf overdreven of pijnlijk blijken.

Arthur C. Clarke merkte scherp op dat er twee essentiële redenen zijn waarom voorspellingen over de toekomst doorgaans mislukken: 'gebrek aan moed en gebrek aan verbeeldingskracht'.[^16] Hij schreef dat 'een gebrek aan moed het vaakst voorkomt. Het treedt op wanneer, ondanks dat alle relevante feiten bekend zijn, de voorspeller niet inziet dat ze onvermijdelijk tot één conclusie leiden. Sommige van deze voorspellingen zijn zo belachelijk dat ze bijna ongelooflijk lijken.'[^17]

Als onze benadering van de informatierevolutie tekortschiet -- en dat zal onvermijdelijk gebeuren -- komt dat eerder door een gebrek aan verbeeldingskracht dan door een gebrek aan moed. Het voorspellen van de toekomst is immers altijd een gedurfde onderneming die terecht scepsis oproept. Wellicht zal de tijd aantonen dat onze conclusies de bal compleet mis slaan. In tegenstelling tot Nostradamus gedragen wij ons niet als profeten. We doen geen vage voorspellingen door met een toverstok in een kom water te roeren of door horoscopen te raadplegen, en we gebruiken ook geen cryptisch taalgebruik. We willen u een scherpe en onbevooroordeelde kijk geven op zaken die wel eens van groot persoonlijk belang zouden kunnen blijken.

Wij vinden het onze plicht om onze ideeën uiteen te zetten, ook al zullen sommigen ze ervaren als heiligschennis, omdat ze anders wellicht onopgemerkt blijven. In de gesloten denkwijze van de late geïndustrialiseerde samenleving gaan ideeën niet zo vrij rond als via de gevestigde media zou moeten.

Dit boek is tot stand gekomen vanuit een constructieve instelling. Het is het derde boek dat we gezamenlijk schrijven, waarin we de verschillende fasen van de ingrijpende verandering die momenteel gaande is analyseren. Net als *Blood in the Streets* en *The Great Reckoning* vormt dit een gedachte-experiment. Het onderzoekt hoe de industriële samenleving ten onder zal gaan en vervolgens opnieuw vorm zal krijgen. Wij voorzien dat de komende jaren verbluffende paradoxen aan het licht zullen komen. Enerzijds zul je de opkomst van een nieuwe vrijheid ervaren, waarin het Soevereine Individu centraal staat, en mag je verwachten dat de productiviteit vrijwel volledig bevrijd zal worden. Tegelijkertijd zien wij het verval van de moderne natiestaat voor ons. Veel garanties omtrent gelijkheid, die in de twintigste eeuw als vanzelfsprekend werden beschouwd, zullen met die staat verdwijnen. Wij zijn ervan overtuigd dat de representatieve democratie, zoals we die nu kennen, zal vervagen en plaats zal maken voor een keuzedemocratie in de digitale marktplaats. Indien onze inzichten kloppen, wordt de politiek van de volgende eeuw veel diverser en minder belangrijk dan we nu gewend zijn.

We zijn ervan overtuigd dat onze redenering goed te volgen is, ook al brengt ze u langs intellectueel ruig terrein en minder vertrouwde uithoeken. Mocht onze intentie op bepaalde punten niet glashelder overkomen, dan is dat niet omdat we geheimzinnig willen doen of de klassieke dubbelzinnigheid toepassen, zoals in de vage cryptische uitspraken van sommige anderen. Wij gebruiken geen dubbelzinnigheid. Indien onze argumenten onduidelijk lijken, komt dat vooral doordat we er niet in geslaagd zijn onze overtuigende ideeën simpel en toegankelijk te verwoorden. In tegenstelling tot veel voorspellers willen wij dat je onze gedachtegang doorgrondt en zelfs eigen maakt. Onze visie steunt niet op spirituele zweverigheid of kosmische bewegingen, maar op ouderwetse, ongepolijste logica. Om zeer logische redenen zijn we ervan overtuigd dat microprocessing de natiestaat onvermijdelijk zal ondermijnen en vernietigen, terwijl het tegelijkertijd nieuwe vormen van sociale organisatie zal voortbrengen. Het is niet alleen mogelijk, maar ook noodzakelijk dat u zich een beeld vormt van bepaalde aspecten van de nieuwe manier van leven die misschien eerder werkelijkheid wordt dan u verwacht.

### Ironieën van een voorspelde toekomst

Al eeuwenlang wordt het einde van dit millennium beschouwd als een beladen moment in de geschiedenis. Meer dan 850 jaar geleden stelde St. Malachy vast dat het jaar 2000 de datum van het Laatste Oordeel zou zijn. In 1934 voorspelde de Amerikaanse helderziende Edgar Cayce dat de aarde in 2000 op haar as zou draaien, waardoor Californië in tweeën zou splijten en New York City en Japan overstromingen zouden ondervinden. In 1980 verklaarde de Japanse raketwetenschapper Hideo Itokawa dat de uitlijning van de planeten in een 'Grand Cross' op 18 augustus 1999 grootschalige milieucatastrofes zou veroorzaken, met als uiteindelijke gevolg het einde van het menselijk leven op aarde.[^18]

Zulke apocalyptische visioenen worden al snel het onderwerp van spot. Hoewel het jaar 2000 een symbolisch en opvallend rond getal is, is het in feite niet meer dan een toevallig product van de westerse, christelijke kalender. In andere kalenders en jaartellingen beginnen de eeuwen en millennia op totaal andere tijdstippen in de geschiedenis. Volgens de islamitische kalender komt 2000 n.Chr. overeen met het jaar 1378, wat op het eerste gezicht een gewoon jaartal lijkt. In de Chinese kalender, die zich elke zestig jaar herhaalt, valt 2000 in een drakenjaar, onderdeel van een voortdurende cyclus die al millennia doorgaat. Er schuilt echter meer achter het jaar 2000 dan louter religieuze betekenis. Het belang ervan wordt niet alleen gedragen door de christelijke traditie, maar ook door de beperkingen van de informatietechnologie in de twintigste eeuw.

Het zogenaamd Y2K-probleem, een potentieel verwoestende logische fout in miljarden regels computercode, dreigt op middernacht van het millennium de vitale onderdelen van de industriële samenleving plat te leggen. Veel computers en microprocessors maken nog steeds gebruik van software uit de begintijd van de computer, toen geheugenruimte met $600.000 per megabyte kostbaarder was dan goud. Om dure opslagruimte te besparen gebruikten de eerste programmeurs slechts de laatste twee cijfers van het jaartal. Deze gewoonte om tweecijferige datumvelden te gebruiken werd overgenomen in de meeste software voor mainframecomputers, en vond later ook brede toepassing in pc's en zogenoemde embedded chips --- microprocessors die bijna alles aansturen: van videorecorders tot het ontstekingssysteem van auto's, van beveiligingssystemen tot telefoons, van schakeltechniek in het telefoonnetwerk tot proces- en controlesystemen in fabrieken, energiecentrales, olieraffinaderijen, chemische installaties, pijpleidingen en meer. In zo'n verkort veld wordt het jaar 1999 bijvoorbeeld weergegeven als '99'. De vraag is echter: wat gebeurt er in het jaar 2000? Een groot deel van de computers zouden de '00' mogelijk interpreteren als het jaar 1900. Hierdoor zouden tal van niet-geüpdatete computers en andere digitale apparaten het jaar 2000 onjuist kunnen registreren.

Dit zou tot ernstige datacorruptie kunnen leiden, wat onbedoeld ook nieuwe mogelijkheden voor informatieoorlogvoering introduceert. In de informatiesamenleving zullen potentiële vijanden complete systemen kunnen ontregelen met 'logische bommen': stukjes code die cruciale data saboteren en zo alles ontwrichten.

Tijdens een militaire operatie hoef je bijvoorbeeld niet per se een vliegtuig neer te schieten als je de gegevens, die essentieel zijn voor de veilige werking ervan, kunt verstoren. Datacorruptie kan bijna net zo verwoestend zijn als fysieke wapens wanneer het gaat om het ontregelen van een moderne samenleving. De mogelijke verstrekkende gevolgen hiervan zouden bij nader inzien voor de hand moeten liggen. Zo meldde de *Mail of London* op 14 december 1997 dat luchtvaartmaatschappijen wereldwijd van plan waren om op 1 januari 2000 honderden vluchten te annuleren, uit angst dat de luchtverkeersleidingssystemen zouden falen.[^19] Niet alleen deze systemen, maar ook de datumgevoelige functies in de vliegtuigen zelf zouden risico lopen. Volgens Boeing hebben veel vliegtuigen Y2K-aanpassingen nodig. Een groot deel van de apparatuur zou storingen kunnen vertonen wanneer ze een gebeurtenis op een ongeldige datum registreren. De computergestuurde fly-by-wire-systemen die vliegtuigen aansturen, zouden defect kunnen raken als hun programmering zou concluderen dat cruciaal onderhoud voor het laatst in 1900 heeft plaatsgevonden. Ze kunnen zelfs in een foutlus vastlopen en daardoor uitschakelen.

De potentieel dodelijke kettingreacties van een logische tijdbom die cruciale besturingssystemen platlegt, zouden de eeuwwisseling op een onvergetelijk onaangename wijze kunnen markeren. Zelfs als je op oudejaarsnacht niet in een vliegtuig zit, kunnen talloze apparaten om je heen crashen door foutlussen en je dagelijkse leven flink verstoren. Zorg ervoor dat je ongelukken voorkomt, of ze nu ontstaan door pacemakers die niet Y2K-conform zijn of door dronken millenniumvierders. Als zulke pacemakers kunnen falen, kan ook het telefoonsysteem het begeven, waardoor je mogelijk niet eens de hulpdiensten kunt bereiken.

Tenzij je je in een regio met slecht functionerende infrastructuur bevindt, ben je eraan gewend dat je gewoon je telefoon oppakt en direct kunt bellen. Gelukkig hoeven we ons zelden druk te maken over de technische details van telefoonnetwerken. De schakelapparatuur en routers van de telecominfrastructuur blijken echter erg afhankelijk van datumvelden. Alle verbindingen worden opgeslagen met datum en tijd, wat essentieel is voor het berekenen van de gespreksduur en de daarop gebaseerde facturering. Als je op 31 december 1999 om 23:59:30 een gesprek van precies één minuut voert en het systeem om 00:00:30 dit gesprek registreert met een negatieve duur van meer dan 99 jaar, kunnen foutlussen ontstaan en schakelt het systeem zich mogelijk uit. Hoewel langeafstands firma's, en lokale dienstverleners waarschijnlijk ook, enorme bedragen investeren in het updaten van hun schakelsystemen zodat deze Y2K-conform worden, kan het hele netwerk in de problemen komen als zelfs een paar kleinere bedrijven niet voldoen en uitvallen. In dat scenario mag je van geluk spreken als je op 1 januari 2000 überhaupt nog een verbinding krijgt.

Zoals Y2K-expert Peter de Jager het verwoordde: "Als we het vermogen verliezen om te bellen, verliezen we alles. We verliezen elektronische betalingen, we verliezen de handel, we verliezen het bankkantoor." En de gevolgen van Y2K-fouten zouden zelfs nog verder kunnen reiken.

Niemand weet precies in hoeverre cruciale systemen door het millenniumprobleem ten onder zullen gaan. Embedded systemen, die niet herprogrammeerd kunnen worden en dus vervangen moeten worden zodra zij datumgevoelige fouten vertonen, vind je onder andere in auto's, vrachtwagens en bussen die na 1976 gebouwd zijn. De kans om betrokken te raken bij een ongeluk met voertuigen, bestuurd door mensen met niet-conforme pacemakers, zal uiteindelijk dus misschien niet heel groot zijn omdat die voertuigen mogelijk niet eens zullen starten. Ook in energiecentrales, water- en rioleringssystemen, medische apparatuur, militaire uitrusting, vliegtuigen, offshore olieplatforms, olietankers, alarmsystemen en liften komen embedded systemen veel voor. Hoewel veel installaties met microprocessors zelf geen datumgevoelige functies uitvoeren, zijn ze voor hun interne werking vaak wel afhankelijk van een klok, die mogelijk Y2K-gevoelig is.

## Mainframes en de Y2K-tijdbom

De grootschalige bestuurs- en controlesystemen van de overheid en grote bedrijven, waarin enorme transacties via mainframecomputers worden verwerkt, stonden aanvankelijk centraal in de Y2K-bezorgdheid. Deze systemen draaien op grote machines met software die vaak decennia oud en grotendeels niet Y2K-conform is. Daarom richtten de eerste Y2K-waarschuwingen, voor het eerst geuit door Peter de Jager begin jaren 1990, zich voornamelijk op de noodzaak om de besturingssystemen van grote, multiprocessor-mainframes te moderniseren. De heer de Jager uitte de zorg dat er mogelijk niet genoeg programmeurs beschikbaar zullen zijn die kennis hebben van COBOL (de oude computertaal waarin de noodzakelijke patches en reparaties aan datumgevoelige code uitgevoerd moeten worden) zelfs als ieder bedrijf en overheidsinstantie met een kwetsbaar systeem enkele jaren daarvoor een noodprogramma zou hebben opgestart. Aangezien dit niet is gebeurd en veel beheerders van datumgevoelige informatiesystemen pas recent begonnen zijn met het onderzoeken van hun kwetsbaarheden, mag je er met grote zekerheid van uitgaan dat veel mainframesystemen niet goed voorbereid zullen zijn.

Dit vormt uiteraard een groot probleem, omdat er in de huidige economie echt geen alternatief bestaat voor computerverwerking. De meeste bedrijven die groot genoeg zijn om een mainframe te gebruiken voor het verwerken van hun transacties, zijn namelijk afhankelijk van een dusdanig groot transactievolume dat ze niet meer met de ouderwetse papieren systemen uit de negentiende eeuw kunnen functioneren. Als die ondernemingen noodgedwongen weer op papieren documenten zouden moeten vertrouwen, zouden zij slechts een fractie van hun gebruikelijke transacties kunnen afhandelen. Het plotselinge inkomensverlies, als gevolg van zo'n dramatische daling in bedrijfsactiviteit, zou het voortbestaan van bijna alle bedrijven, op enkele van de best gekapitaliseerde na, ernstig in gevaar brengen.

Bijna alle financiële processen (zoals facturering, inkoop- en loonadministratie, voorraadbeheer en naleving van regelgeving) zullen compleet worden verstoord. Enorme hoeveelheden data gaan verloren als computers crashen of foutieve informatie uitspuwen door het Y2K-probleem. In sommige gevallen blijkt het zelfs een zegen als systemen direct crashen, in plaats van dat hun data geleidelijk wordt gecorrumpeerd tot een massale storing het probleem aan de kaak stelt. Wat zal er gebeuren wanneer een backup-programma bestanden die oorspronkelijk op 07/04/99 zijn aangemaakt, kopieert naar een update op 01/04/00? Wie zal het zeggen? Zal de computer een betaling voor een verzekeringspolis die op 4 januari '1900' uitgevoerd is, interpreteren als een signaal dat de polis al een eeuw in gebreke is, met als gevolg dat de polis wordt geannuleerd en uit de administratie verdwijnt? Zullen computers van banken en financiële instellingen proberen om honderd jaar rente in rekening te brengen voor leningen die de overgang naar het nieuwe millennium overspannen? Zullen banken en effectenmaatschappijen nauwkeurig rekeningstanden bijhouden en tijdig toegang geven tot tegoeden? Dit zijn slechts enkele van de intrigerende vraagstukken waarmee je te maken krijgt als gevolg van het Y2K-probleem.

> Dit is mogelijk het meest destructieve onderdeel van het jaar 2000-probleem. Dit betreft niet het ongemak wanneer uw salaris enkele dagen te laat komt. Dit gaat over echte chaos op straat. -- Dr. Leon Kappelman, medevoorzitter van de Year 2000-werkgroep van de Society For Information Management.

Ook moet je je afvragen wat er gebeurt als de elektriciteit uitvalt door Y2K-gerelateerde storingen. Zonder stroom functioneren de meeste systemen niet, ook degene die niet direct door Y2K-problemen getroffen zijn, zoals je koelkast, vriezer en mogelijk zelfs je verwarming. Y2K-problemen kunnen de veiligheidsgerelateerde toegangs- en beheerssystemen in kerncentrales verstoren. Zo dragen medewerkers in kerninstallaties dosimetrie-apparaten die de hoeveelheid stralingsblootstelling bijhouden die zij in de faciliteit ontvangen. Deze apparaten worden regelmatig gecontroleerd en de gegevens over de blootstellingsniveaus worden opgeslagen in een computersysteem dat de toegang van medewerkers tot de faciliteit beheert. Uiteraard, als deze bestuurlijke computers uitvallen, raken al die uitgebreide controles, die bedoeld zijn om een veilige werking en goed onderhoud te garanderen, volledig in de war. Belangrijker nog: een memo van de Nuclear Regulatory Commission merkt op dat veel 'niet-veiligheidsgerelateerde, maar belangrijke computergebaseerde systemen, hoofdzakelijk databases en de dataverzameling die onmisbaar is voor de werking van de centrale,' datumgevoelig zijn.

Ook reguliere elektriciteitscentrales lopen net zo goed risico op Y2K-verstoringen. Kolencentrales zijn immers gevoelig voor onderbrekingen in het transportsysteem dat de kolen naar de ketels vervoert. In het winterseizoen van 1997/1998 moesten exploitanten van kolencentrales in sommige gevallen hun productie verminderen door vertragingen in de leveringsketen van Western Coal, veroorzaakt door de fusie van de spoorwegsystemen van Southern Pacific en Union Pacific. Het probleem ontstond door incompatibiliteiten tussen de computerbestuurde controle- en dispatchsystemen die beide spoorwegmaatschappijen hanteerden. Een woordvoerder van Union Pacific noemde de integratie van de twee systemen een 'nachtmerrie', ondanks dat Union Pacific Technologies als koploper wordt gezien in de ontwikkeling van geautomatiseerde transportsystemen. Door de programmeerproblemen kon de spoorwegmaatschappij de bewegingen van haar goederenwagons niet nauwkeurig volgen. Het onvermogen van Union Pacific om de systemen van Southern Pacific succesvol te integreren, is een slecht voorteken voor wat er kan gebeuren wanneer de logische tijdbommen van Y2K het transport, de elektriciteitsopwekking en andere economische sectoren verstoren.

De grootste zorg rond het elektriciteitsnet komt voort uit het feit dat computers voortdurend toezicht houden op het hele systeem en het actief aansturen, waardoor elektriciteit efficiënt wordt verplaatst van overschotgebieden naar regio's met een tekort. Computers monitoren dit proces nauwgezet om spanningspieken en storingen te voorkomen. Elke overdracht wordt geregistreerd met vermelding van tijd en datum, vergelijkbaar met de registratie bij een telefoongesprek. Robuuste mechanische relais maken de verbindingen weliswaar mogelijk, maar computersystemen sturen ze aan. Die computercontroles, die essentieel zijn voor de vermogensbalancering, kunnen echter om dezelfde redenen falen als telefonienetwerken. In Noord-Amerika zijn de systemen die de stroomverdeling regelen sterk afhankelijk van telefoonverbindingen zoals T-1-lijnen en draadloze netwerken. Als het telefonienetwerk uitvalt, kun je er dus ook op rekenen dat de elektriciteitsvoorziening instort. En de ervaring in Canada in januari 1998 toont aan hoe lastig het is om het systeem weer aan de praat te krijgen zodra de elektriciteit over een groot gebied wegvalt. Stroomuitvallen zouden oncomfortabel lang kunnen aanhouden.

## Y2K en het nucleaire arsenaal

Als de stroom in het hart van de winter zou uitvallen, betekent dat in de moderne economie een enorme verstoring en zelfs een potentiële bedreiging voor de volksgezondheid, vooral voor mensen die afhankelijk zijn van elektrische verwarming en medische apparatuur. Het ergste scenario is echter nog grimmiger. John Koskinen, hoofd van het Y2K Conversion Council van president Clinton, waarschuwt dat de Amerikaanse militaire arsenalen mogelijk niet meer functioneren zodra de klok op 31 december 1999 middernacht slaat. Hoewel hij geen onnodige paniek wil zaaien, voegt Koskinen eraan toe: 'Er moet zich zorgen over worden gemaakt.' Een van de zorgen over de nucleaire raketten was dat 'als de data niet naar behoren functioneert, ze vanzelf zouden kunnen lanceren.' Natuurlijk geldt dezelfde zorg, zo niet meer, voor de Russische nucleaire raketten. Ruslands faillissement heeft de noodzakelijke upgrades voor Y2K-compatibiliteit nog problematischer gemaakt dan in de Verenigde Staten, en er is bewijs dat Rusland de Y2K-conversie nog niet serieus neemt. Hoewel iedereen hoopt dat er geen toevallige lanceringen plaatsvinden, bestaat er weinig twijfel dat de jaarwisseling naar 2000 de wereldwijde veiligheid in gevaar zal kunnen brengen, simpelweg doordat militaire communicatiesystemen in veel landen mogelijk niet naar behoren zullen functioneren. Zoals Koskinen het verwoordt: 'Als je in een land zit en plotseling niet precies kunt achterhalen wat er gaande is, omdat je communicatiesystemen niet optimaal werken, raak je nog nerveuzer.' Neem dat dus zeker mee in je lijst met Y2K-zorgen. Deze logische tijdbom kan de lancering van echte explosieve wapens bewerkstelligen, wat het gevaar aantoont dat voortkomt uit informatieoorlogvoering tegen gecentraliseerde beheers- en controlesystemen.

Terroristen die een gecentraliseerd systeem willen treffen, zouden juist 31 december 1999 kunnen kiezen als moment om toe te slaan, omdat op dat moment veel systemen op hun meest kwetsbaar zijn. Niet alleen raken de communicatiesystemen zwaar overbelast, met als gevolg dat de stroom uitvalt, voertuigen niet starten en de 112-diensten van de politie, brandweer en ambulance niet bereikbaar zijn, maar ook tal van andere voorzieningen, zoals de luchtverkeersleiding, kunnen het begeven. Zonder stroom is er geen kraanwater, vallen rioolinstallaties uit en zullen verkeerslichten ermee ophouden. Binnen enkele uren nadat het transportsysteem instort, zal het voedsel in supermarkten uitverkocht zijn, of zelfs geplunderd. Recente ervaringen in Amerikaanse steden laten zien dat een gebrek aan stroom, water, verwarming, licht en communicatie met hulpdiensten, waaronder politie en brandweer, samen het verval van de beschaving kunnen inluiden. Hoewel niemand met zekerheid kan vaststellen wat de impact van het Y2K-probleem zal zijn, zou dit kunnen uitmonden in plunderingen en rellen op straat, zeker als het duidelijk wordt dat er problemen zullen ontstaan bij het uitgeven van loon-, bijstands- en pensioenbetalingen.

> Wij zullen niet zijn wat wij geweest zijn, maar we zullen beginnen anders te zijn. -- Joachim de Fiore[^20]

Doemvoorspellingen rondom het nieuwe millennium berusten niet per se op de christelijke theologie, maar sluiten naadloos aan bij de millennialtraditie van Joachim de Fiore. Zijn meditaties deden hem immers geloven dat Christus slechts 'het tweede scharnier in de geschiedenis' vormde en dat er onvermijdelijk een volgend scharnier zou volgen.[^21] Zo stelt filosoof Michael Grasso dat de informatierevolutie de menselijke geschiedenis stuurt naar de verwezenlijking van de profetische visie van de Westerse wereld. Hij noemt dit 'technocalypse.' Of technologische ontwikkelingen nu wel of niet door millenniale visies worden beïnvloed, het Y2K-fenomeen blijft een product van de overheersende westerse blik op de tijd. Op een merkwaardige manier sluit het aan bij dromen, visioenen of hun numerieke interpretaties, zoals Newtons duiding van de profetieën van Daniël. Deze intuïtieve gedachten ontstaan vanuit een perspectief dat de geboorte van Christus als middelpunt van de geschiedenis beschouwt. Bovendien versterken grote, ronde getallen dit perspectief, want elke handelaar herkent de bijzondere aantrekkingskracht die zij uitoefenen.

Het tweeduizendste jaar van onze jaartelling kan niet anders dan een brandpunt worden voor de verbeelding van intuïtieve denkers.

Critici zouden deze voorspellingen zonder moeite belachelijk kunnen maken, zelfs zonder in te gaan op de dubbelzinnige en omstreden theologische begrippen van de Apocalyps en het Laatste Oordeel, die juist zoveel kracht aan deze vooruitzichten geven. Opmerkelijk genoeg weegt de Y2K-bug zwaarder dan de historische onnauwkeurigheden in onze tijdrekening, die het symbolische gewicht van het jaar 2000 binnen de Christelijke jaartelling juist hadden kunnen afzwakken. Het jaar 2000 kan een keerpunt in de geschiedenis betekenen, simpelweg omdat het de overgang naar een nieuw millennium markeert. In principe begint het volgende millennium pas in 2001, aangezien het jaar 2000 slechts het tweeduizendste jaar sinds de geboorte van Christus aanduidt. Tenminste, dat zou zo zijn als Christus daadwerkelijk in het eerste jaar van ons huidige tijdperk was geboren, maar dat is niet zo. In 533, toen men bepaalde om de geboorte van Christus als uitgangspunt te nemen voor de westerse jaartelling in plaats van de oprichtingsdatum van Rome, maakten de monniken die deze nieuwe conventie invoerden een rekenfout. Tegenwoordig gaan we ervan uit dat hij in 4 v.Chr. werd geboren. Volgens deze berekening eindigt de volledige periode van tweeduizend jaar sinds zijn geboorte al rond 1997. Dit is ook de reden waarom Carl Jung dit ogenschijnlijk vreemde jaartal als startdatum voor een Nieuwe Tijd voorstelde.

Lach erom als je wilt, maar wij wijzen intuïtieve inzichten in de geschiedenis beslist niet af. Hoewel ons betoog op logica rust en niet op vooringenomen veronderstellingen, raken we diep onder de indruk van de profetische kracht van het menselijk bewustzijn. Keer op keer bevestigt het de visioenen van krankzinnigen, helderzienden en heiligen. Hetzelfde geldt voor de transformatie die rond het jaar 2000 lijkt aan te breken. De datum, die al lang verankerd is in de westerse verbeelding, lijkt het keerpunt te markeren dat bewijst dat de geschiedenis een bestemming heeft. We kunnen niet precies verklaren waarom dat zo is, maar we hebben er desondanks alle vertrouwen in.

Onze intuïtie vertelt ons dat de geschiedenis een bestemming kent en dat vrije wil en determinisme twee zijden van dezelfde medaille vormen. De menselijke interacties die de geschiedenis vormgeven, lijken erop te wijzen dat een bepaald lot hen stuurt. Net zoals een elektronenplasma (een dicht samengepakt gas van elektronen) zich als een complex systeem gedraagt, handelen mensen op een vergelijkbare manier. De individuele bewegingsvrijheid van elektronen blijkt immers verenigbaar te zijn met een sterk geordend collectief gedrag. Zoals David Ohm over een elektronenplasma opmerkte, is de menselijke geschiedenis 'een hoogst georganiseerd systeem dat zich als een geheel gedraagt.'

Het doorgronden van de werking van de wereld betekent dat je leert aanvoelen hoe de menselijke samenleving handelt volgens de wiskundige wetten van de natuur. De werkelijkheid verloopt niet lineair, terwijl de meeste mensen juist een lineair patroon verwachten. Om de dynamiek van verandering echt te begrijpen, moet je inzien dat onze samenleving (net als andere complexe systemen in de natuur) cyclische patronen en abrupte breuken vertoont. Dit houdt in dat bepaalde aspecten van de geschiedenis de neiging hebben zich te herhalen en dat ingrijpende veranderingen vaak plotseling plaatsvinden in plaats van geleidelijk.

Te midden van de vele ritmes in het menselijk bestaan duikt er een raadselachtige vijfhonderdjarige cyclus op, die telkens samenvalt met grote omslagen in de westerse geschiedenis. Nu het jaar 2000 nadert, valt het op dat het laatste decennium van elke eeuw die deelbaar is door vijf, altijd gepaard gaat met een diepgaande transitie binnen de Westerse wereld. Dit patroon markeert nieuwe fasen van sociale organisatie, vergelijkbaar met de manier waarop geboorte en dood de cyclus van menselijke generaties bepalen. Dit is al zo sinds ten minste 500 v.Chr., toen de Griekse democratie opkwam door de constitutionele hervormingen van Kleisthenes in 508 v.Chr. De volgende vijfhonderd jaar kenden een periode van groei en versterking van de Oude economie, die culmineerde in de geboorte van Christus in 4 v.Chr. Deze periode bleek voor dat economische systeem tevens de tijd met de grootste welvaart te zijn, waarin de rentevoeten hun laagste niveau bereikten. Een niveau dat niet meer bereikt is tot in de moderne tijd.

In de daaropvolgende vijfhonderd jaar nam de welvaart geleidelijk af, wat uiteindelijk leidde tot de ineenstorting van het Romeinse Rijk tegen het einde van de vijfde eeuw na Christus. Het is de moeite waard om de samenvatting van William Playfair hier te herhalen: "Het hoogtepunt van de Romeinse macht viel samen met de geboorte van Christus, in de tijd van keizer Augustus. Vanaf dat moment ging het rijk langzaam achteruit, tot in 490 n. Chr. haar laatste legioenen uiteenvielen en de westerse wereld afgleed in wat we nu kennen als de Donkere middeleeuwen."[^22]

De daaropvolgende vijfhonderd jaar werden gekenmerkt door een krimpende economie; de langafstandshandel kwam tot stilstand, steden raakten verlaten, geld kwam in onbruik en kunst en geletterdheid verdwenen bijna volledig. De ineenstorting van het West-Romeinse Rijk leidde tot het verval van een effectief rechtsstelsel, waardoor er primitieve regelingen ontstonden voor het oplossen van geschillen. Tegen het einde van de vijfde eeuw werd bloedwraak steeds meer de norm, en in het jaar 500 vond het eerste geregistreerde geval van een godsoordeel plaats.

Nogmaals, duizend jaar geleden markeerde het laatste decennium van de tiende eeuw een andere enorme omwenteling in sociale en economische systemen. Wellicht is de minst bekende van deze transities de feodale revolutie, die begon in een periode van totale economische en politieke onrust. In *Transformation of the Year One Thousand* stelt Guy Bois, professor middeleeuwse geschiedenis aan de Universiteit van Parijs, dat deze breuk aan het einde van de tiende eeuw zorgde voor de volledige ineenstorting van de overblijfselen van oude instituties en de opkomst van iets nieuws uit de anarchie van het feodalisme.[^23] Zoals Raoul Glaber het verwoordde: 'Er werd gezegd dat de hele wereld in één klap de lompen van de oudheid van zich afschudde.'[^24] Het nieuwe systeem dat plotseling opkwam, stimuleerde de geleidelijke heropleving van de economische groei en zorgde ervoor dat de daaropvolgende vijfhonderd jaar, die we nu de middeleeuwen noemen, gepaard gingen met een heropleving van het gebruik van geld en internationale handel, naast de herontdekking van rekenkunde, geletterdheid en tijdsbesef.

In het laatste decennium van de vijftiende eeuw vond een nieuw keerpunt plaats. Europa herstelde zich uit het door de Zwarte Dood veroorzaakte demografische tekort en begon vrijwel onmiddellijk haar macht over de wereld uit te breiden. De 'buskruitrevolutie', de 'renaissance' en de 'reformatie' benoemden elk een aspect van deze overgangsperiode die de moderne tijd inluidde. Het begon spectaculair toen Karel VIII Italië binnenviel met nieuwe bronzen kanonnen. Dit opende de weg naar nieuwe werelddelen, zoals bleek uit Columbus' reis naar Amerika in 1492. Die ontdekking stimuleerde de meest dramatische economische groei die de mensheid ooit heeft gekend en ging gepaard met een revolutie in de natuurkunde en astronomie, wat de moderne wetenschap deed ontstaan. Bovendien verspreidde de boekdruktechnologie de ideeën op grote schaal.

Wij bevinden ons nu op de drempel van een nieuwe millenniale transformatie. De uitgebreide systemen voor beheer en controle die we uit het industriële tijdperk hebben geërfd, kunnen bij de overgang naar het nieuwe millennium uit elkaar vallen zoals de paardenkar. Of de Y2K-logicabom nu wel of niet zal leiden tot een onmiddellijke ineenstorting van de industriële samenleving maakt niet uit, het einde ervan is hoe dan ook nabij. Wij verwachten dat de opkomst van de informatiesamenleving de wereld ingrijpend zal veranderen, op manieren die in dit boek worden toegelicht. Het is begrijpelijk dat je twijfels hebt omdat een cyclus die zich slechts tweemaal per millennium herhaalt niet genoeg herhalingen kent voor statistische significantie. Economen benaderen zelfs kortere cycli met scepsis, omdat ze meer overtuigend statistisch bewijs verlangen. Professor Dennis Robertson schreef ooit dat we enkele eeuwen moeten afwachten alvorens met zekerheid te kunnen spreken over het bestaan van de vier en acht tot tien jaar durende handelscycli.[^25] Volgens dat criterium zou hij ongeveer dertigduizend jaar moeten wachten om zeker te weten dat de vijfhonderdjarige cyclus geen toevalligheid betreft. Wij zijn minder dogmatisch en erkennen liever dat de patronen van de werkelijkheid complexer zijn dan de statische en lineaire evenwichtsmodellen die de meeste economen hanteren.

Wij menen dat de komst van het jaar 2000 meer betekent dan slechts een praktische onderverdeling van een eindeloos tijdscontinuüm. Wij geloven dat het een keerpunt vormt tussen de Oude Wereld en een opkomende Nieuwe Wereld. Het industriële tijdperk verdwijnt in hoog tempo, en ironisch genoeg kan de ondergang ervan worden versneld doordat men in vroege computers, door het dure geheugen, tweecijferige datumvelden ging gebruiken. Toen Hollerithponskaarten slechts tachtig tekens konden bevatten, leek het verstandig om om datums af te korten. In tegenstelling tot de verwachtingen van de vroege programmeurs hield deze afkorting echter vier decennia stand tot het einde van het millennium, met een onbedoelde logicabom, die een groot deel van de industriële samenleving zou kunnen verwoesten, tot gevolg. Het Office of Management and Budget van de Amerikaanse overheid omschreef het computerprobleem in *Getting Federal Computers Ready for 2000*, een rapport van 7 februari 1997: 'Tenzij ze gerepareerd of vervangen worden, zullen ze bij de overgang van de eeuw op één van de volgende drie manieren falen: ofwel wijzen ze legitieme invoer af, ofwel berekenen ze foutieve resultaten, ofwel functioneren ze simpelweg niet.' Deze drie gevolgen zouden samen de industriële samenleving compleet kunnen lamleggen. In elk geval staat massaproductietechnologie op het punt te worden overschaduwd door een nieuwe miniaturisatietechnologie, en een crisis op korte termijn zal dat proces alleen maar versnellen. Dankzij de nieuwe informatietechnologie is een wetenschap op het gebied van niet-lineaire dynamica ontstaan, waarvan de verrassende conclusies nog slechts afzonderlijke elementen zijn die samen moeten worden geweven tot een coherent wereldbeeld. We leven in het tijdperk van de computer, maar onze dromen worden nog steeds op het weefgetouw gesponnen. We houden vast aan de metaforen en denkbeelden van het industrialisme. Denkers die stierven lang voordat bijna iedereen die nu leeft geboren werd, zoals Adam Smith en Karl Marx, hebben aangetoond dat onze politieke arena nog steeds langs de industriële scheidslijn tussen rechts en links balanceert.[^28] Wij stellen echter dat het 'gezonde verstand' van het industriële tijdperk op vele terreinen niet meer van toepassing is in de radicaal veranderende wereld.

Meer dan vijfentachtig jaar na de dag in 1911 waarop Oswald Spengler werd getroffen door een voorgevoel van een naderende wereldoorlog en 'de ondergang van het Westen', zien wij eveneens '*een historische fasewisseling* plaatsvinden ... precies op het moment dat al honderden jaren voorbestemd lijkt te zijn.'[^26] Net als Spengler voorzien wij de naderende ondergang van de westerse beschaving en daarmee de ineenstorting van de wereldorde die de afgelopen vijf eeuwen heeft gedomineerd, sinds Columbus naar het westen zeilde om contact te leggen met de Nieuwe Wereld. Maar in tegenstelling tot Spengler zien wij in het komende millennium juist de geboorte van een nieuwe fase binnen de westerse beschaving.

[^1]: Danny Hillis, 'The Millennium Clock', *Wired*, special edition, Herfst 1995, p. 48.
[^2]: Ericka Cheetham, *The Final Prophecies of Nostradamus* (New York: Putnam, 1989), p. 424.
[^3]: Dr. Edward Yardeni, *Year 2000 Recession*: 'Prepare for the worst. Hope for the best', Versie 5.0, 13 mei 1998, B1.2.
[^4]: Michael Grasso, *The Millenium Myth: Love and Death at the End of Time*, Wheaton, Illinois: Quest Books, 1995.
[^5]: Johan Huizinga, *The Waning of the Middle Ages*, vert. E Hopman (Londen: Penguin Books, 1990), p. 172.
[^6]: Marshall McLuhan, *Understanding Media*, New York: Signet, 196, p. 19.
[^7]: James George Frazer, *The Golden Bough: A Study in Magic and Religion* (New York: Macmillan, 1951), p. 105.
[^8]: Voor meer details over gefragmenteerde soevereiniteiten als voorloper en alternatief voor de natiestaat, zie Charles Tilly, *Coercion, Capital and European States AD 990-1992* (Oxford: Blackwell, 1993).
[^9]: De Duitse GPI-index stond op 33,20 op 31 december 1948, en 112,90 op 30 juni 1995, wat neerkomt op een samengestelde jaarlijkse depreciatie van 2,7 procent. De Amerikaanse CPI stond op 24 op 31 december 1948, en 152,50 op 30 juni 1995. De cumulatieve Amerikaanse inflatie was 635 procent voor de periode.
[^10]: Janet L. Abu-Lughod, *Before European hegemony: the world system A.D. 1250-1350* (Oxford: Oxford University Press, 1991), p. 62.
[^11]: Jack Cohen en Ian Stewart, *The Collapse of Chaos* (New York: Viking, 1994).
[^12]: Zie James Dale Davidson en Lord William Rees-Mogg, *The Great Reckoning*, 2e ed. (New York: Simon & Schuster, 1993), p. 53.
[^13]: Frederic C. Lane, 'Economic consequences of organized violence', *The Journal of Economic History* vol.18, nr.4 (december 1958), p. 402.
[^14]: Nicholas Colehester, 'Goodbye nationstate, hello ... what?', *New York Times*, 17 juli 1994, p. E17.
[^15]: Norman Macrae, 'Governments in Decline', Cato Policy Report, juli/augustus 1992, p. 10.
[^16]: Arthur C. Clarke, *Profiles of the Future: An Enquiry into the Limits of the Possible* (Londen: Victor Gollancz Ltd., 1962), p. 13.
[^17]: Ibid.
[^18]: A. T. Mann, *Millennium Prophecies: Predictions for the Year 2000* (Shafiesbury, Engeland: Element Books, 1992), pp. 88, 112, 117.
[^19]: Yardeni, op. cit., p. 45.
[^20]: Geciteerd in Frooso, op. cit., p. 40.
[^21]: Ibid
[^22]: William Playfair, *An Inquiry into the Permanent Causes of the Decline and Fall of Powerful and Wealthy Nations: Designed to Show How the Prosperity of the British Empire May be Prolonged* (Londen: Greenland and Norris, 1805), p. 79.
[^23]: Guy Bois, *The Transformation of the Year One Thousand: The Village of Lournard from Antiquity to Feudalism* (Manchester, Engeland: Manchester University Press, 1992).
[^24]: Ibid., p. 150.
[^25]: Geciteerd in S. B. Saul, *The Myth of the Great Depression* (Londen: Macmillan, 1985), p. 10.
[^26]: Oswald Spengler, *The Decline of the West*, vert. Charles Francis Atkinson, geciteerd in I. F. Clark, *The Pattern of Expectation, 1644-2001* (Londen: Jonathan Cape, 1979), p. 220.
[^27]: Nomenklaturen zijn de gevestigde elites die de voormalige Sovjet-Unie en andere door de staat bestuurde economieën regeerden.
[^28]: Adam Smith stierf in 1790, Karl Marx in 1883.
