# Megapolitieke transformaties in historisch perspectief

> "In de geschiedenis, net als in de natuur, zijn geboorte en dood voortdurend in balans" -- Johan huizinga[^29]

## Het verval van de moderne wereld

Naar onze mening ben je getuige van niets minder dan het verval van de Moderne Tijd. Het is een ontwikkeling gedreven door een meedogenloze maar verborgen logica. Meer dan we doorgaans beseffen, en meer dan CNN en de kranten ons vertellen, zal het volgende millennium niet langer "modern" zijn. We zeggen dit niet om te suggereren dat je een wilde of primitieve toekomst te wachten staat, hoewel dat mogelijk is, maar om te benadrukken dat het tijdperk in de geschiedenis dat nu aanbreekt kwalitatief zal verschillen van hetgene waarin je geboren bent.

Er komt iets nieuws aan. Net zoals dat agrarische samenlevingen verschilden van jagers-verzamelaarsbenden, en industriële samenlevingen radicaal verschilden van feodale of yeomanboerensystemen, zo zal de komende Nieuwe Wereld een radicale breuk betekenen met al het voorgaande.

In het nieuwe millennium zullen het economische en politieke leven niet langer georganiseerd worden op gigantische schaal onder de heerschappij van de natiestaat, zoals dat tijdens de moderne eeuwen het geval was. De beschaving die ons wereldoorlogen, de lopende band, sociale zekerheid, inkomstenbelasting, deodorant en de broodrooster bracht, is stervende. Deodorant en de broodrooster zullen misschien overleven. De andere niet. Als een oude, ooit machtige man heeft de natiestaat een toekomst die in jaren en dagen te tellen is, en niet langer in eeuwen en decennia.

Overheden hebben al veel van hun regulerende en dwingende macht verloren. De ineenstorting van het communisme markeerde het einde van een lange cyclus van vijf eeuwen, waarin de omvang van macht de efficiëntie van de overheid overschaduwde. Het was een tijd waarin geweld in toenemende mate loonde, maar die tijd is voorbij. De wereld is al begonnen aan een historische omwenteling van formaat. Misschien zegt een toekomstige Gibbon, die de ondergang van het Moderne Tijdperk beschreef, wel dat dat tijdperk al voorbij was toen jij dit boek in handen kreeg. Terugkijkend kan hij zeggen, net als wij, dat het eindigde met de val van de Berlijnse Muur in 1989, of met het uiteenvallen van de Sovjet-Unie in 1991. Beide data kunnen een bepalende gebeurtenis blijken in de evolutie van de beschaving, als het einde van wat we nu kennen als de Moderne Tijd.

Het vierde stadium van de menselijke ontwikkeling komt eraan, en misschien is het minst voorspelbare kenmerk ervan de nieuwe naam waaronder het bekend zal worden. Noem het "Post-Modern." Noem het de "Cybersamenleving" of het "Informatietijdperk." Of verzin zelf een naam. Niemand weet welke bijnaam aan de volgende fase van de geschiedenis zal blijven plakken.

We weten niet eens of de vijfhonderd jaar durende periode van de geschiedenis die net eindigt, zal blijven worden beschouwd als "modern." Als toekomstige historici kennis van etymologie hebben, zal dat niet zo zijn. Een passendere titel zou kunnen zijn "Het Tijdperk van de Staat" of "Het Tijdperk van Geweld." Zo'n naam zou echter buiten de tijdsgeest vallen die momenteel de tijdperken van de geschiedenis benoemt. "Modern," volgens het Oxford English Dictionary, betekent "behorend tot de tegenwoordige en recente tijden, onderscheiden van het verre verleden... In historisch gebruik gewoonlijk toegepast (in tegenstelling tot antiek en middeleeuws) op de tijd volgend op de MIDDELEEUWEN."[^30]

Westerse mensen beschouwden zichzelf pas “modern” toen ze inzagen dat de middeleeuwse periode voorbij was. Voor 1500 had niemand ooit aan de feodale eeuwen gedacht als een "midden"-periode in de Westerse beschaving. De reden is duidelijk bij reflectie: voordat een tijdperk redelijkerwijs kan worden gezien als ingeklemd in het "midden" van twee andere historische tijdperken, moet het al tot een einde zijn gekomen. Degenen die tijdens de feodale eeuwen leefden, hadden zich niet kunnen voorstellen dat ze in een tussenhuis woonden tussen de oudheid en de moderne beschaving, totdat het hen daagde niet alleen dat de middeleeuwse periode voorbij was, maar ook dat de middeleeuwse beschaving dramatisch verschilde van die van de Oudheid.[^31]

Menselijke culturen hebben blinde vlekken. We hebben geen vocabulaire om paradigmaveranderingen in de grootste kaders van het leven te beschrijven, vooral als die om ons heen gebeuren. Ondanks de vele dramatische veranderingen die zich hebben ontvouwd sinds de tijd van Mozes, hebben slechts enkele ketters de moeite genomen om na te denken over hoe de overgangen van de ene fase van beschaving naar de andere werkelijk plaatsvinden.

Hoe worden ze veroorzaakt? Wat hebben ze met elkaar gemeen? Aan welke patronen kunnen we zien wanneer ze beginnen en hoe weten we wanneer ze voorbij zijn? Wanneer zullen Groot-Brittannië of de Verenigde Staten ten einde komen? Voor deze vragen zal het lastig zijn om conventionele antwoorden te vinden.

### Het taboe op vooruitziendheid

"Buiten" een bestaand systeem zien is als een toneelknecht die een dialoog probeert te forceren met een personage in een toneelstuk. Het schendt een conventie die helpt het systeem te laten functioneren. In elke maatschappij geldt een stilzwijgend verbod: denk vooral niet na over hoe het systeem ooit kan ophouden te bestaan, of wat ervoor in de plaats zou kunnen komen. Impliciet is ieder systeem het laatste of het enige systeem dat ooit zal bestaan, ook al wordt dit niet openlijk uitgesproken. Van de mensen die ooit een geschiedenisboek hebben gelezen, zal slechts een minderheid zo'n aanname realistisch vinden als ze ermee geconfronteerd zouden worden. Desondanks is dat de conventie die de wereld regeert. Ieder sociaal systeem doet alsof haar regels nooit zullen worden vervangen, hoe sterk of zwak zij ook aan de macht probeert vast te houden. Ze zijn het laatste woord. Of misschien het enige woord. Primitievelingen geloven dat hun ideeën de enige mogelijke manier beschrijven om het leven te organiseren. Economisch meer gecompliceerde systemen die een gevoel van geschiedenis incorporeren spannen hiervan gewoonlijk de kroon. Of het nu gaat om Chinese mandarijnen aan het hof van de keizer, de marxistische nomenklatura in Stalins Kremlin, of leden van het Amerikaanse Huis van Afgevaardigden: de machthebbers verbeelden zich óf dat er geen geschiedenis bestaat, óf dat zij het hoogtepunt ervan vormen --- verheven boven iedereen die hen voorging, en als voorhoede van alles wat nog komen zal.

Om bijna onvermijdelijke redenen is dit de waarheid. Hoe duidelijker het is dat een systeem zijn einde nadert, hoe minder bereid mensen zullen zijn om zich aan haar wetten te houden. Elke sociale organisatie zal daarom de neiging hebben om analyses die zijn ondergang voorzien te ontmoedigen of te bagatelliseren. Alleen al door dit feit worden grote keerpunten in de geschiedenis zelden opgemerkt terwijl ze gebeuren. Eén ding kun je in elk geval zeker weten over de toekomst: conventionele denkers zullen grote veranderingen niet verwelkomen of aankondigen.

Conventionele informatiebronnen zullen je geen objectieve en tijdige waarschuwing geven over hoe de wereld verandert en waarom. Als je de grote overgang die nu gaande is wilt begrijpen, heb je geen andere keuze dan het zelf uit te zoeken.

## Voorbij het voor de hand liggende

Dit betekent verder kijken dan onze neus lang is. De geschiedenis toont dat overgangen mogelijk decennia of zelfs eeuwen nadat ze gebeuren niet worden erkend, zelfs wanneer die achteraf gezien onmiskenbaar reëel bleken te zijn. Neem de val van Rome. Het was waarschijnlijk de belangrijkste historische ontwikkeling in het eerste millennium van het Christelijke Tijdperk. Zelfs lang nadat Rome gevallen was, hield men de illusie van haar voortbestaan in stand, vergelijkbaar met het gebalsemde lichaam van Lenin. Wie alleen naar het officiële nieuws luisterde, had pas door dat Rome was gevallen toen dat allang geen verschil meer maakte.

Dit kwam niet alleen door de beperkte communicatiemogelijkheden van de antieke wereld. De uitkomst zou grotendeels hetzelfde zijn geweest als CNN al zou hebben bestaan en haar videoband draaide in september 476. Toen werd de laatste Romeinse keizer in het Westen, Romulus Augustulus, gevangengenomen in Ravenna, en werd gedwongen om in een villa in Campanië te pensioneren. Zelfs als Wolfe Blitzer daar zou zijn geweest om met minicamera's het nieuws in het jaar 476 op te nemen, is het onwaarschijnlijk dat hij of iemand anders zou hebben gedurfd die gebeurtenissen te karakteriseren als het einde van het Romeinse Rijk. Dat is natuurlijk precies wat latere historici uiteindelijk wel concludeerden.

De redacteuren van CNN zouden waarschijnlijk geen goedkeuring hebben gegeven voor een voorpagina-artikel met de titel "Rome is gevallen." De machthebbers ontkenden dit. "Nieuws"-kanalen omarmen zelden controverse omdat dit hun inkomsten zou kunnen ondermijnen. Ze zijn vaak partijdig, soms zelfs in grote mate. Maar ze rapporteren zelden conclusies die abonnees zouden kunnen overtuigen om hun abonnementen op te zeggen en ervan door te gaan. Daarom zou slechts een enkeling de val van Rome hebben gerapporteerd, zelfs als het technologisch mogelijk zou zijn geweest. Experts zouden meteen geroepen hebben dat het onzin was om te beweren dat Rome gevallen was. Zoiets zeggen was niet goed voor de handel --- en mogelijk zelfs gevaarlijk voor je gezondheid. De macht lag toen bij barbaren, en die hielden vol dat Rome zoals men dat kende, nog altijd bestond.

Het probleem was echter niet alleen dat de autoriteiten zeiden: "Rapporteer dit niet of we zullen je doden." Wat nog meer meespeelde, was dat Rome tegen het einde van de vijfde eeuw al zo ver was afgetakeld, dat de "val" voor de meeste mensen die het meemaakten nauwelijks als zodanig werd opgemerkt. Pas een generatie later suggereerde Graaf Marcellinus in feite voor het eerst dat "Het West-Romeinse Rijk ten onder ging met Augustulus."[^32] Het duurde nog decennia, misschien zelfs eeuwen, voordat het algemeen erkend werd dat het Romeinse Rijk in het Westen niet langer bestond. Karel de Grote geloofde in het jaar 800 zonder twijfel dat hij een legitieme Romeinse keizer was.

Het punt is niet dat Karel de Grote en allen die in conventionele termen dachten over het Romeinse Rijk na 476 idioten waren, integendeel. Maatschappelijke veranderingen worden vaak vaag of dubbelzinnig voorgesteld. Als invloedrijke instellingen die vaagheid gebruiken om een voor hen gunstige conclusie te versterken, zelfs als die grotendeels op schijn berust, zal alleen iemand met een sterk karakter en uitgesproken overtuigingen het aandurven die tegen te spreken. Wie zich inleeft in het leven van een Romein in de vijfde eeuw begrijpt hoe makkelijk het was om te geloven dat alles nog steeds hetzelfde was gebleven. Die zekerheid was de optimistische conclusie. Iets anders denken had beangstigend kunnen zijn, en waarom tot een beangstigende conclusie komen, als er ook een geruststellende voorhanden was?

Er waren uiteindelijk ook goede redenen om te denken dat het leven gewoon door zou gaan zoals altijd. Dat deed het in het verleden ook. De Romeinse legers, vooral aan de grenzen van het rijk, werden al eeuwenlang geïnfiltreerd door barbaren.[^33] Tegen de derde eeuw was het voor het leger bijna een gewoonte geworden om regelmatig een nieuwe keizer uit te roepen. Tegen de vierde eeuw waren zelfs officieren gegermaniseerd en vaak analfabeet.[^34] Voor de val van Romulus Augustulus werden al talrijke keizers op brute wijze van de troon gestoten. Zijn vertrek zou voor zijn tijdgenoten niet anders hebben geleken dan de vele andere omwentelingen in deze chaotische periode. Hij werd zelfs weggestuurd met een pensioen, al was het slechts een korte periode voordat hij werd vermoord. Dit bewees dat het systeem nog overeind stond. De optimist vond juist dat Odoacer, die Romulus Augustulus afzette, het rijk herenigde, en niet vernietigde. Odoacer, een zoon van Attila's rechterhand Edecon, was een intelligente man. Hij riep zichzelf niet uit tot keizer. In plaats daarvan riep hij de Senaat bijeen en haalde zijn al te beïnvloedbare leden over dat zij het keizerschap en dus de soevereiniteit over het hele rijk aan Zeno, de keizer in het verre Byzantium, zouden aanbieden. Odoacer was slechts Zeno's patricius, aangesteld om Italië te leiden.

Zoals Will Durant schreef in *The Story of Civilization*, leken deze veranderingen niet op de "val van Rome" maar slechts "verwaarloosbare verschuivingen op het nationale toneel."[^35] Toen Rome viel, zei Odoacer dat Rome bleef bestaan. Net als bijna iedereen deed hij maar al te graag alsof alles hetzelfde bleef. Ze wisten dat "de oude glorie van Rome" veel beter was dan de barbarij die haar verving. Zelfs de barbaren dachten dat. Zoals C. W. Previte-Orton schreef in *The Shorter Cambridge Medieval History*, was het eind van de vijfde eeuw, toen "de keizers waren vervangen door barbaarse Germaanse koningen", een "aanhoudende schijnvertoning".[^36]

### "Hardnekkige schijnvertoning"

Deze "schijnvertoning" hield de façade van het oude systeem overeind, ook al was de kern ervan al "aangetast door barbarij".[^37] De oude regeringsvormen bleven hetzelfde toen de laatste keizer werd vervangen door een barbaarse "luitenant". De Senaat kwam nog steeds bijeen. "De pretoriaanse prefectuur en andere hoge ambten gingen door, en werden gehouden door vooraanstaande Romeinen."[^38] Consuls werden nog steeds voor een jaar aangesteld. "De Romeinse burgerlijke administratie bleef onaangetast."[^39] Sterker nog, op sommige vlakken bleef het intact tot de opkomst van het feodalisme aan het einde van de tiende eeuw. Bij openbare gelegenheden werd nog steeds gebruik gemaakt van de oude keizerlijke insignes. Het christendom was nog steeds de staatsgodsdienst. De barbaren deden nog steeds alsof ze trouw verschuldigd waren aan de Oostelijke keizer in Constantinopel, en aan de tradities van het Romeinse recht. Maar, in Durant's woorden, "in het Westen was het grote Rijk er niet meer."[^40]

### Nou en?

De val van Rome lijkt misschien iets van lang geleden, maar is verrassend relevant als je kijkt naar hoe de wereld er nu voorstaat. De meeste boeken over de toekomst zijn eigenlijk boeken over het heden. We hebben geprobeerd dat gebrek te verhelpen door van dit boek over de toekomst allereerst een boek over het verleden te maken. Wij denken dat je een beter perspectief zult krijgen op wat de toekomst brengt als we belangrijke megapolitieke punten over de logica van geweld illustreren met echte voorbeelden uit het verleden. De geschiedenis is een geweldige leermeester. De verhalen die het te vertellen heeft zijn interessanter dan wat wij kunnen verzinnen, en veel van de meest interessante verhalen gaan over de val van Rome. Ze bevatten belangrijke lessen die relevant kunnen zijn voor jouw toekomst in het Informatietijdperk.

Een van de best beschreven voorbeelden van een grote overgang in de geschiedenis, waarbij de overheid implodeerde, is de val van Rome. De overgang rond het jaar 1000 ging ook gepaard met de ineenstorting van centrale autoriteit, en leidde tot een toename in de complexiteit en omvang van economische activiteiten. De Buskruitrevolutie aan het eind van de vijftiende eeuw bracht grote institutionele veranderingen met zich mee, die juist de schaal van bestuur vergrootten in plaats van verkleinden. Vandaag de dag, voor het eerst in duizend jaar, ondermijnen en vernietigen de megapolitieke omstandigheden in het Westen overheden en vele andere grootschalige instituties.

Uiteraard verschilden de oorzaken van de bestuurlijke implosie aan het einde van het Romeinse Rijk aanzienlijk van de factoren die een rol spelen bij de opkomst van het Informatietijdperk. Een van de redenen is dat het Romeinse imperium simpelweg te grootschalig was. Het werd onmogelijk om de economie van geweld te handhaven. De kosten om de ver uitgespreide grenzen van het rijk te verdedigen, overtroffen de economische voordelen die een oude agrarische economie kon opbrengen. De last van belasting en regulering die nodig waren om de militaire inspanning te financieren, steeg tot boven de draagkracht van de economie. Corruptie werd endemisch. Militaire commandanten, zoals historicus Ramsay MacMullen heeft gedocumenteerd, spendeerden een groot deel van hun tijd aan het misbruiken van hun positie, voor "illegale winsten".[^41] Dit deden ze door de bevolking af te persen, wat de vierde-eeuwse waarnemer Synesius beschreef als "de vredesoorlog, bijna erger dan de barbarenoorlog, en voortkomend uit het gebrek aan discipline van het leger en de hebzucht van de officieren."[^42]

Een andere belangrijke factor die bijdroeg aan de val van Rome was een demografisch tekort veroorzaakt door de Antonijnse pest. De sterke krimp van de Romeinse bevolking droeg op veel vlakken duidelijk bij aan economische en militaire zwakte. Vandaag de dag is daar nog geen sprake van, althans nog niet. Op langere termijn, misschien, zal de gesel van nieuwe "plagen" de uitdagingen van technologische devolutie in het nieuwe millennium verergeren. De ongekende toename van de menselijke bevolking in de twintigste eeuw creëert een verleidelijk doelwit voor snel muterende microparasieten. Angsten over het Ebola-virus, of iets dergelijks, dat metropolitane bevolkingen binnenvalt, kunnen gegrond zijn. Maar dit is niet de plaats om de co-evolutie van mensen en ziekten te overwegen. Hoe interessant dat onderwerp ook is, ons argument op dit punt gaat niet over waarom Rome viel, of over de vraag of de wereld op dit moment kwetsbaar is voor sommige van dezelfde invloeden die bijdroegen aan de Romeinse achteruitgang. Het gaat over iets anders - namelijk de manier waarop de grote transformaties van de geschiedenis worden waargenomen, of liever, verkeerd waargenomen terwijl ze gebeuren.

Mensen zijn altijd en overal tot op zekere hoogte conservatief, met een kleine "c". Men is terughoudend wanneer het gaat over het loslaten van traditionele sociale conventies, het ondermijnen van erkende instituties en het ter discussie stellen van de wetten en waarden waarop zij gefundeerd waren. Maar weinig mensen kunnen zich voorstellen dat schijnbaar kleine veranderingen in klimaat, technologie of een andere variabele op de een of andere manier verantwoordelijk zouden kunnen zijn voor het doorbreken van verbindingen met de wereld waarin hun ouders zijn opgegroeid. De Romeinen waren terughoudend om de veranderingen die zich om hen heen ontvouwden te erkennen. En dat zijn wij ook.

Toch, of je het nu erkent of niet, we gaan door een verandering van historisch seizoen, een transformatie in de manier waarop mensen hun levensonderhoud organiseren en zichzelf verdedigen, die zo diepgaand is dat het onvermijdelijk de hele samenleving zal transformeren. Het zal zelfs zo diepgaand zijn dat het, om het goed te begrijpen, noodzakelijk is om bijna niets als vanzelfsprekend te beschouwen. Steeds opnieuw zul je de neiging hebben om te geloven dat de komende Informatie Samenlevingen grote gelijkenissen zullen hebben met de industriële samenlevingen waar je in opgroeide. Wij betwijfelen dat. Microprocessing zal de mortel in de bakstenen oplossen. Het zal de logica van geweld zo diepgaand veranderen dat het dramatisch de manier zal veranderen waarop mensen hun levensonderhoud organiseren en zichzelf verdedigen. Toch zal men geneigd zijn om de onvermijdelijkheid van deze veranderingen te bagatelliseren, of om te discussiëren over hun wenselijkheid alsof industriële instellingen per decreet zouden kunnen bepalen hoe de geschiedenis evolueert.

### De grote illusie

Auteurs die op vele manieren beter geïnformeerd zijn dan wij, zullen je desondanks op het verkeerde been zetten als het gaat over de toekomst, omdat zij de werking van samenlevingen slechts oppervlakkig analyseren. David Kline en Daniel Burstein hebben bijvoorbeeld een goed onderzocht boek geschreven, getiteld *Road Warriors: Dreams and Nightmares Along the Information Highway*. Het zit vol bewonderenswaardige details, maar veel van deze details worden aangedragen om een illusie te beargumenteren, namelijk het idee 'dat burgers gezamenlijk en bewust kunnen ingrijpen om de spontane economische en natuurlijke processen om hen heen vorm te geven.'[^43] Hoewel het misschien niet voor de hand liggend is, is dit met de stelling dat het feodalisme zou hebben overleefd als iedereen zich opnieuw had toegewijd aan de ridderlijkheid. Niemand in een hof van de late vijftiende eeuw zou bezwaar hebben gemaakt tegen zo'n sentiment. Sterker nog, het zou ketterij zijn geweest om dat te doen. Maar het zou ook volledig misleidend zijn geweest, een voorbeeld van de slang die de toekomst in zijn oude huid probeert te wringen.

De fundamentele oorzaken van verandering zijn juist niet onderworpen aan bewuste controle. Het zijn de factoren die de omstandigheden veranderen waaronder geweld loont. Ze staan zelfs zo ver af van elke vorm van bewuste manipulatie, dat ze in een wereld die doordrenkt is van politiek, geen onderwerp van politiek gemanoeuvreer vormen. Niemand heeft ooit in een demonstratie geroepen: "Verhoog schaalvoordelen in het productieproces." Geen spandoek heeft ooit geëist: "Vind een wapensysteem uit dat het belang van de infanterie verhoogt." Geen kandidaat heeft ooit beloofd om "de balans tussen efficiëntie en schaalgrootte van de bescherming tegen geweld te veranderen." Zulke slogans zouden belachelijk zijn, juist omdat deze doelen buiten ieders vermogen liggen om ze bewust te beïnvloeden. Toch, zoals we zullen zien, bepalen deze variabelen in veel grotere mate hoe de wereld werkt dan welk politiek platform dan ook.

Als je er goed over nadenkt, wordt al snel duidelijk dat belangrijke historische keerpunten zelden primair worden gedreven door menselijke verlangens. Ze gebeuren niet omdat mensen het zat worden van één manier van leven en plotseling een andere prefereren. Als je er even bij stilstaat, zul je begrijpen waarom. Als wat mensen denken en verlangen als enige zouden bepalen wat er gebeurt, dan zouden alle abrupte veranderingen in de geschiedenis worden verklaard door wilde stemmingswisselingen, los van enige verandering in de feitelijke levensomstandigheden. In feite gebeurt dit nooit. Alleen in gevallen van medische problemen, die een paar mensen treffen, zien we willekeurige fluctuaties in stemming die volledig los lijken te staan van een objectieve oorzaak.

Over het algemeen besluiten grote aantallen mensen niet plotseling en allemaal tegelijk hun manier van leven op te geven, simpelweg omdat ze dat grappig vinden. Geen enkele jager-verzamelaar heeft ooit gezegd: "Ik ben het zat om in prehistorische tijden te leven; ik leef liever als een boer in een boerendorp." Elke beslissende omslag in gedragspatronen en waarden is zonder uitzondering een reactie op een werkelijke verandering in de omstandigheden van het leven. In die zin, althans, zijn mensen altijd realistisch. Als hun opvattingen abrupt veranderen, wijst dat waarschijnlijk erop dat ze zijn geconfronteerd met een afwijking van de vertrouwde omstandigheden: een invasie, een plaag, een plotselinge klimatologische verschuiving, of een technologische revolutie die hun levensonderhoud of hun vermogen om zichzelf te verdedigen verandert.

Grote veranderingen in de geschiedenis zijn meestal niet wat mensen willen. Ze verstoren juist de rust en stabiliteit waar de meeste mensen naar verlangen. Wanneer verandering optreedt, veroorzaakt het typisch wijdverspreide desoriëntatie, vooral onder degenen die hun inkomen of sociale status verliezen. Je zult tevergeefs kijken naar opiniepeilingen of stemmingsbarometers om een begrip te krijgen van hoe de komende megapolitieke overgang zich waarschijnlijk zal ontvouwen.

## Leven zonder vooruitziende blik

Als we er niet in slagen om de grote overgang, die om ons heen gaande is, waar te nemen, komt dat deels doordat we die niet willen zien. Onze jagende voorouders waren misschien net zo koppig, maar zij hadden een beter excuus. Niemand had tienduizend jaar geleden de gevolgen van de Agrarische Revolutie kunnen voorzien. Sterker nog, men voorzag toen überhaupt niet veel meer dan waar ze de volgende maaltijd zouden kunnen vinden. Toen men aan landbouw begon, bestond er geen verslaglegging van gebeurtenissen uit het verleden, om daaruit lessen te trekken voor de toekomst. De Westerse tijdsindeling, zoals seconden, minuten, uren, dagen, enzovoort, om de jaren af te meten, bestond nog niet eens. Jager-verzamelaars leefden in het "eeuwige heden," zonder kalenders, en inderdaad, zonder enige geschreven verslagen. Ze kenden geen wetenschap, en beschikten over geen enkel ander intellectueel instrument om oorzaak en gevolg te begrijpen dan hun eigen intuïtie. Wat betreft vooruitkijken, waren onze primitieve voorouders blind. Om de bijbelse metafoor te citeren, ze hadden nog niet van de vrucht der kennis gegeten.

### Leren van het verleden

Gelukkig staan wij er beter voor. De afgelopen vijfhonderd generaties hebben ons een analytisch vermogen geschonken dat onze voorouders misten. Wetenschap en wiskunde hebben geholpen vele geheimen van de natuur te openbaren, waardoor we een begrip van oorzaak en gevolg hebben dat grenst aan het magische vergeleken met dat van de vroege jager-verzamelaars. Computationele algoritmen, ontstaan dankzij de komst van snelle computers, hebben nieuwe inzichten opgeleverd in de werking van complexe, dynamische systemen zoals de menselijke economie. De zorgvuldige ontwikkeling van politieke economie zelf, hoewel het verre van perfect is, heeft ons begrip van de factoren die menselijk handelen beïnvloeden, vergroot. Een belangrijk inzicht daaruit is dat mensen altijd en overal geneigd zijn op prikkels te reageren, niet altijd zo mechanisch als economen zich voorstellen, maar ze reageren wel. Kosten en baten doen ertoe. Veranderingen in externe omstandigheden die de baten verhogen van bepaald gedrag of de kosten ervan verlagen, zullen leiden tot meer van dat gedrag, als de rest onveranderd blijft.

### Prikkels doen ertoe

Het feit dat mensen de neiging hebben om te reageren op kosten en baten is een essentieel element bij het doen van voorspellingen. Je kunt met grote zekerheid zeggen dat als je een biljet van honderd dollar op straat laat vallen, iemand het snel zal oprapen, of je nu in New York, Mexico-Stad of Moskou bent. Dit is niet zo triviaal als het lijkt. Het toont aan waarom de slimme mensen die zeggen dat voorspellen onmogelijk is, ongelijk hebben. Elke voorspelling die accuraat de impact van prikkels op gedrag anticipeert zal het waarschijnlijk grotendeels bij het juiste eind hebben. Hoe groter de geanticipeerde verandering in kosten en baten, hoe minder voor de hand liggend de voorspelling waarschijnlijk zal zijn.

De meest verstrekkende voorspellingen van allemaal zullen waarschijnlijk voortkomen uit het herkennen van de implicaties van verschuivende megapolitieke variabelen. Geweld is de ultieme grens die gedrag bepaalt; dus, als je kunt begrijpen hoe de logica van geweld zal veranderen, kun je met grote nauwkeurigheid voorspellen waar mensen het equivalent van honderd-dollarbiljetten in de toekomst zullen laten vallen of oprapen.

We bedoelen hiermee niet dat je het onkenbare kunt weten. Wij kunnen je niet vertellen hoe je winnende loterijnummers kunt voorspellen, of welke willekeurige gebeurtenis dan ook. We hebben geen manier om te weten of wanneer een terrorist een atoomexplosie in Manhattan zal doen ontploffen, of als een asteroïde Saoedi-Arabië zal treffen. We kunnen de komst van een nieuwe ijstijd, een plotselinge vulkaanuitbarsting, of de opkomst van een nieuwe ziekte niet voorspellen. Het aantal onkenbare gebeurtenissen die de koers van de geschiedenis zouden kunnen veranderen is groot. Maar het onkenbare weten is heel anders dan de gevolgen overzien van wat al bekend is. Als u een bliksemflits ver weg ziet, kunt u met een grote zekerheid voorspellen dat een donderslag zal volgen. Het voorspellen van de gevolgen van megapolitieke transities omvat veel langere tijdsbestekken, en minder zekere verbanden, maar het idee is hetzelfde.

Megapolitieke katalysatoren voor verandering verschijnen gewoonlijk ruim voordat hun gevolgen zich manifesteren. Het duurde vijfduizend jaar voordat de volledige implicaties van de Agrarische Revolutie aan het licht kwamen. De overgang van een agrarische samenleving naar een industriële samenleving gebaseerd op fabricage en chemische kracht ontvouwde zich sneller. Het duurde eeuwen. De overgang naar de Informatiemaatschappij zal nog sneller gebeuren, waarschijnlijk binnen een leven. Toch, zelfs rekening houdend met de versnelling van de geschiedenis, kunt je verwachten dat decennia zullen verstrijken voordat de volledige megapolitieke impact van de huidige informatietechnologie wordt gerealiseerd.

### Grote en kleine megapolitieke overgangen

Dit hoofdstuk analyseert enkele gemeenschappelijke kenmerken van megapolitieke overgangen. In volgende hoofdstukken kijken we meer nauwkeurig naar de Agrarische Revolutie, en de overgang van boerderij naar fabriek, de tweede van de grote faseveranderingen. Binnen het agrarische stadium van de beschaving waren er vele kleine megapolitieke overgangen zoals de val van Rome en de Feodale Revolutie van het jaar 1000. Deze markeerden de verschuivingen in de machtsbalans: overheden kwamen en gingen, en de opbrengsten van de landbouw gingen van de ene groep over naar de andere. De eigenaren van uitgestrekte landgoederen ten tijden van het Romeinse Rijk, vrije boeren in de Europese vroege Middeleeuwen, en de heren en lijfeigenen van de feodale periode aten allemaal graan van dezelfde akkers. Ze leefden onder zeer verschillende overheden dankzij de cumulatieve impact van verschillende technologieën, fluctuaties in het klimaat, en de ontwrichtende invloed van ziektes.

We beweren niet al deze veranderingen grondig te verklaren, hoewel we een beeld hebben geschetst van de manier waarop veranderende megapolitieke variabelen de machtsuitoefening in het verleden hebben beïnvloed. Overheden zijn gegroeid en gekrompen naarmate megapolitieke schommelingen de kosten van machtsprojectie verlaagden en verhoogden.

Hier zijn enkele samenvattende punten die je in gedachten zou moeten houden wanneer je probeert de Informatierevolutie te begrijpen:

1. Een verschuiving in de megapolitieke machtsfundamenten voltrekt zich doorgaans ver ver vóór de daadwerkelijke revoluties in de machtsuitoefening.
2. Inkomens dalen meestal wanneer een grote overgang begint, vaak omdat een samenleving door bevolkingsdruk kwetsbaar is geworden en hulpbronnen heeft gemarginaliseerd.
3. "Buiten" een systeem zien is gewoonlijk taboe. Mensen zijn vaak blind voor de logica van geweld in de bestaande samenleving en daardoor vrijwel altijd ook voor veranderingen in die logica, of die nu verborgen of openlijk zijn. Megapolitieke transities worden zelden herkend voordat ze zich voordoen.
4. Grote overgangen gaan altijd gepaard met een culturele revolutie, en leiden gewoonlijk tot botsingen tussen aanhangers van de oude en de nieuwe waarden.
5. Megapolitieke overgangen zijn nooit populair, omdat ze moeizaam verworven intellectueel kapitaal achterhaald maken en gevestigde morele voorschriften ondermijnen. Ze worden niet op algemeen verzoek uitgevoerd, maar als reactie op veranderende externe omstandigheden die de logica van geweld in de lokale context veranderen.
6. Transities naar nieuwe manieren om het levensonderhoud te organiseren of naar nieuwe typen overheden, beperken zich aanvankelijk tot de gebieden waar de megapolitieke katalysatoren werkzaam zijn.
7. Met de mogelijke uitzondering van de vroege stadia van landbouw, hebben eerdere overgangen altijd perioden van sociale chaos en verhoogd geweld betrokken vanwege desoriëntatie en de ineenstorting van het oude systeem.
8. Corruptie, moreel verval, en inefficiëntie lijken signaalkenmerken te zijn van de laatste stadia van een systeem.
9. Het groeiende belang van technologie bij het vormgeven van de logica van geweld heeft geleid tot een versnelling van de geschiedenis, waardoor er voor elke opeenvolgende transitie minder tijd voor aanpassing overblijft dan ooit tevoren.

### De geschiedenis versnelt

Nu gebeurtenissen zich vele malen sneller ontvouwen dan tijdens voorgaande transformaties, zou een vroegtijdig inzicht in hoe de wereld zal veranderen veel meer voor je kunnen betekenen dan voor je voorouders op een vergelijkbaar keerpunt in het verleden. Zelfs als de eerste boeren op miraculeuze wijze de volledige megapolitieke implicaties van het bewerken van de aarde hadden begrepen, zou deze informatie praktisch nutteloos zijn geweest omdat duizenden jaren zouden verstrijken voordat de overgang naar de nieuwe fase van de samenleving voltooid was.

Vandaag de dag is dat anders. De geschiedenis is in een stroomversnelling geraakt. Voorspellingen die de megapolitieke gevolgen van nieuwe technologie correct inschatten, zijn vandaag de dag waarschijnlijk veel nuttiger. Het kunnen doorgronden van de implicaties van de huidige overgang naar de Informatiemaatschappij is vele malen waardevoller dan dat het volledige begrip van de gevolgen van de transitie van landbouw naar industrie toen was. Simpel gezegd, de actie-horizon voor megapolitieke voorspellingen is ingekort tot de nuttigste tijdsduur: de duur van een mensenleven.

> "Terugkijkend over de eeuwen, of zelfs alleen kijkend naar het heden, kunnen we duidelijk waarnemen dat velen hun inkomen hebben gekregen, vaak een zeer goed inkomen, door middel van hun speciale vaardigheid in het toepassen van wapens van geweld, en dat hun handelingen in grote mate bepaalden hoe schaarse middelen werden ingezet." -- Frederic C. Lane[^44]

Onze studie van de megapolitiek is een poging om precies dat te doen: het in kaart brengen van de gevolgen van de factoren die de grenzen verschuiven waarbinnen geweld wordt uitgeoefend.

Deze megapolitieke factoren bepalen grotendeels wanneer en waar geweld loont. Ze beïnvloeden ook de verdeling van het inkomen. Zoals economisch historicus Frederic Lane zo duidelijk verwoordde, speelt de manier waarop geweld wordt georganiseerd en beheerst een grote rol bij het bepalen van "*hoe schaarse middelen worden ingezet.*"[^45]

## Een spoedcursus megapolitiek

Het concept megapolitiek is een krachtig idee. Het helpt enkele van de grote mysteries van de geschiedenis te verklaren, zoals hoe regeringen opkomen en vallen, wat voor soorten instellingen ze worden, de timing en uitkomst van oorlogen, en patronen van economische welvaart en achteruitgang. Door de kosten en baten van het projecteren van macht te verhogen of te verlagen, regeert megapolitiek het vermogen van mensen om hun wil aan anderen op te leggen. Sinds de vroegste menselijke samenlevingen is dit het geval geweest, en dat is het nog steeds. In *Blood in the Streets* en *The Great Reckoning* onderzochten we vele van de belangrijke verborgen megapolitieke factoren die de evolutie van de geschiedenis bepalen. Om de gevolgen van megapolitieke verandering te begrijpen, moet je inzicht krijgen in de factoren die revoluties in het gebruik van geweld realiseren. Deze variabelen kunnen enigszins willekeurig worden gegroepeerd in vier categorieën: topografie, klimaat, microben, en technologie.

1\. **Topografie** is een cruciale factor, zoals bewezen door het feit dat, in tegenstelling tot op land, de controle van geweld op open zee nooit is gemonopoliseerd. Geen enkele overheid is er ooit in geslaagd om er enkel haar wetten te laten gelden. Om te begrijpen hoe de organisatie van geweld en bescherming zal evolueren naarmate de economie migreert naar cyberspace, is dit van belang.

Topografie, in combinatie met klimaat, speelde een grote rol in de vroege geschiedenis. De eerste staten kwamen op in overstromingsvlaktes, omringd door woestijn, zoals in Mesopotamië en Egypte, waar water voor irrigatie overvloedig was maar omliggende regio's te droog waren om kleinschalige landbouw mogelijk te maken. In deze context betaalden individuele landbouwers een hoge prijs als zij weigerden samen te werken aan het behoud van het politieke systeem. Zonder irrigatie, die alleen op grote schaal kon worden verschaft, zouden gewassen niet groeien. Geen gewassen betekende verhongering. Wie het water in de woestijn beheerste, bezat de macht --- en dat leidde tot een despotische en steenrijke overheid.

Zoals we analyseerden in The Great Reckoning, speelden topografische omstandigheden ook een grote rol in de welvaart van vrije boeren in het oude Griekenland, waardoor het zich kon ontwikkelen tot de wieg van de Westerse democratie. Gegeven de primitieve transportmogelijkheden die drieduizend jaar geleden in de Middellandse Zee-regio gebruikelijk waren, was het vrijwel onmogelijk voor personen, die meer dan een paar kilometer van de zee woonden, om te concurreren in de productie van waardevolle gewassen: olijven en druiven. Wanneer olie en wijn over land moesten vervoerd worden, waren de transportkosten zo hoog dat verkoop met winst onmogelijk was. Door de grillige kustlijn van Griekenland lag het grootste deel van het land op niet meer dan twintig mijl van de zee. Dit gaf Griekse boeren een beslissend voordeel ten opzichte van hun potentiële concurrenten in landinwaarts gelegen gebieden.

Door dit handelsvoordeel verdienden Griekse boeren hoge inkomens met de controle van slechts kleine stukken grond. Deze hoge inkomens stelden hen in staat om kostbare wapenuitrusting te kopen. De beroemde hoplieten van het oude Griekenland waren boeren of landheren die zichzelf op eigen kosten bewapenden. De Griekse hoplieten waren zowel goed bewapend als sterk gemotiveerd, en vormden een militaire macht die men niet kon negeren. De Griekse democratie ontstond uit de topografische omstandigheden, net zoals andere soort topografieën de despotische systemen van Egypte en elders mogelijk maakten.

2\. **Klimaat** bepaalt ook mede de grenzen waarbinnen brute kracht kan worden uitgeoefend. Een verandering van klimaat was de katalysator voor de eerste grote overgang van foerageren naar landbouw.

Het einde van de laatste ijstijd, ongeveer dertienduizend jaar geleden, leidde tot een radicale verandering van de vegetatie. In het Nabije Oosten, waar de ijstijd als eerste tot een einde kwam, begonnen bossen zich door een geleidelijke stijging in temperatuur en regenval te verspreiden naar gebieden die voorheen bestonden uit grasland. De snelle verspreiding van beukenbossen in het bijzonder beperkte het menselijke dieet ernstig. Zoals Susan Alling Gregg het verwoordde in *Foragers and Farmers*:

"De ontwikkeling van beukenbossen moet ernstige gevolgen hebben gehad voor lokale mensen-, planten- en dierenpopulaties. De kroonlaag van een eikenbos is relatief open en laat grote hoeveelheden zonlicht de bosbodem bereiken. Daardoor ontstaat een wilde onderbegroeiing van gemengde struiken, kruiden en grassen, en deze diversiteit aan planten ondersteunt op zijn beurt een verscheidenheid aan wild. Daarentegen is de kroonlaag van een beukenbos gesloten en is de bosbodem zwaar beschaduwd. Buiten een korte bloeiperiode van lentebloemen voorafgaand aan het uitlopen van de bladeren, groeien er alleen soorten die goed tegen schaduw kunnen, zoals zeggen, varens en enkele grassoorten."[^46]

Na verloop van tijd drongen dichte bossen de open vlaktes binnen en verspreidden zich door Europa richting de oostelijke steppen.[^47] De bossen verdrongen de graslanden die grote dieren onderhielden, waardoor het voor de menselijke jagers steeds moeilijker werd om zichzelf te onderhouden.

De populatie van jager-verzamelaars was te sterk gegroeid tijdens de welvarende periode gedurende de ijstijd, waardoor ze zichzelf niet meer kon ondersteunen met de krimpende kuddes grote zoogdieren, waarvan vele soorten tot uitsterven werden gejaagd. De overgang naar landbouw was niet hun voorkeur, maar eerder een gedwongen improvisatie om tekorten in het dieet aan te vullen. Jagen bleef dominant in de meer noordelijke gebieden, waar de verwarmingstrend de habitats van grote zoogdieren niet nadelig had beïnvloed, en in tropische regenwouden, waar de wereldwijde opwarming niet leidde tot het verminderen van de voedselvoorzieningen. Sinds de opkomst van landbouw zijn veranderingen veel vaker veroorzaakt door afkoeling dan door opwarming van het klimaat.

Als het klimaat zal blijven fluctueren in de toekomst, zal het nuttig zijn om een bescheiden begrip te hebben van de rol die klimaatverandering speelde in vroegere maatschappijen. Het is bijvoorbeeld zo dat een daling van één graad Celsius gemiddeld het groeiseizoen met drie tot vier weken vermindert en honderdvijftig meter afhaalt van de maximale hoogte waarop gewassen kunnen worden verbouwd. Dit zegt iets over de grenzen waarbinnen mensen in de toekomst zullen moeten handelen.[^48] Je kunt deze kennis gebruiken om veranderingen in alles, van graanprijzen tot de prijzen van landbouwgrond, te voorspellen. Je zou zelfs de waarschijnlijke impact van vallende temperaturen op reële inkomens en politieke stabiliteit kunnen inschatten. In het verleden zijn overheden omvergeworpen toen, door meerdere opeenvolgende mislukte oogsten, de voedselprijzen verhoogden en de koopkracht opdroogde.

Het is bijvoorbeeld geen toeval dat de zeventiende eeuw, de koudste in de moderne periode, ook een periode van revolutie wereldwijd was. Een verborgen megapolitieke oorzaak van dit ongenoegen was scherp kouder weer. Het was zelfs zo koud dat wijn op de tafel van de "Zonnekoning" in Versailles bevroor. Verkorte groeiseizoenen veroorzaakten mislukte oogsten en ondermijnden reële inkomens. Door het koudere weer begon de welvaart af te nemen en gleed de wereld rond 1620 een lange wereldwijde depressie in. Die bleek buitengewoon ontwrichtend. De economische crisis van de zeventiende eeuw leidde tot een golf van opstanden wereldwijd, met een piek in het jaar 1648 --- precies tweehonderd jaar vóór een andere, bekendere cyclus van revoluties. Tussen 1640 en 1650 waren er opstanden in Ierland, Schotland, Engeland, Portugal, Catalonië, Frankrijk, Moskou, Napels, Sicilië, Brazilië, Bohemen, Oekraïne, Oostenrijk, Polen, Zweden, Nederland, en Turkije. Zelfs China en Japan werden overspoeld met onrust.

Het is wellicht ook geen toeval dat het mercantilisme overheerste in de zeventiende eeuw, tijdens een periode van krimpende handel. Economisch isolationisme was misschien het meest uitgesproken aan het einde van de eeuw, "toen een verschrikkelijke hongersnood plaatsvond."[^49] In de achttiende eeuw, vooral na 1750, hadden warmere temperaturen en betere oogsten de inkomens in West-Europa voldoende verhoogd, waardoor de vraag naar productiegoederen op gang kwam. Naarmate het vrijemarktbeleid breder werd ingevoerd, ontstond een zichzelf versterkende impuls van economische groei. De industrie breidde zich uit tot een ongekende schaal --- het begin van wat we de Industriële Revolutie zijn gaan noemen. Technologie en productie werden steeds belangrijker en verminderden de invloed van het weer op de economische cycli.

Je moet de impact van een plotse verlaging van de temperatuur echter niet onderschatten. Zelfs vandaag de dag kan het de koopkracht flink onder druk zetten, ook in welvarende gebieden zoals Noord-Amerika. Maatschappijen hebben een sterke tendens om zichzelf crisis-gevoelig te maken wanneer de bestaande instellingen hun beste tijd hebben gehad. In het verleden manifesteerde deze tendens zich vaak in een bevolkingsgroei die de grenzen van wat het land kon dragen, opzocht. Dit gebeurde zowel voor de overgang van het jaar 1000 als aan het einde van de vijftiende eeuw. De flinke daling van de koopkracht, veroorzaakt door mislukte oogsten en lagere opbrengsten, speelde in beide gevallen een significante rol in het vernietigen van de overheersende instellingen. Op dit moment zijn die problemen vooral zichtbaar in de consumentenkredietmarkten. Toen plotselinge temperatuurdalingen de opbrengsten van oogsten verminderden en het beschikbaar inkomen afnam, leidde dat tot wanbetalingen van schulden en opstanden tegen de belastingheffing. Het verleden leert ons dat deze omstandigheden ook in de toekomst zouden kunnen resulteren in zowel economische afsluiting als politieke onrust.

3\. **Microben** hebben door hun invloed op ziekten en immuniteit vaak bepaald hoe macht kon worden ingezet. Dit was zeker het geval in de Europese verovering van de Nieuwe Wereld, zoals we onderzochten in *The Great Reckoning*. Europese kolonisten, doordrenkt met ziektes uit ontwikkelde agrarische samenlevingen, hadden al relatieve immuniteit tegen kinderinfecties zoals de mazelen. De Indianen die ze ontmoetten leefden grotendeels in dun bevolkte jager-verzamelaarsstammen, en hadden nog geen immuniteit tegen Westerse ziekten ontwikkeld. Ze werden daardoor gedecimeerd. Vaak stierven de meesten zelfs al voordat ze met blanke mensen in aanraking kwamen, doordat geïnfecteerde Indianen die aan de kust voor het eerst Europeanen ontmoetten naar het binnenland reisden, en zo de ziektes verspreidden.

Er zijn ook microbiologische grenzen voor de uitoefening van macht. In *Blood in the Streets* bespraken we hoe malaria het voor blanken eeuwenlang onmogelijk maakte om een invasie in tropisch Afrika te realiseren. Vóór de ontdekking van kinine in het midden van de negentiende eeuw konden blanke legers niet overleven in regio's met malaria, hoe superieur hun wapens ook waren.

De interactie tussen mensen en microben heeft ook belangrijke demografische effecten voortgebracht die de kosten en baten van geweld hebben veranderd. Wanneer het aantal sterfgevallen sterk fluctueert vanwege epidemische ziekten, hongersnood, of andere oorzaken, neemt de kans om te sterven door oorlogsvoering af. Vanaf de zestiende eeuw werden uitschieters van het sterftecijfer steeds minder frequent, wat helpt verklaren waarom gezinnen kleiner werden en waarom er vandaag de dag, vergeleken met vroeger, veel minder tolerantie is voor plotselinge sterfgevallen in oorlog. Hierdoor is ook de tolerantie voor imperialisme afgenomen en zijn de kosten om aan machtsprojectie te doen verhoogd in gemeenschappen met een laag geboortecijfer.

Hedendaagse samenlevingen, bestaande uit kleine families, vinden zelfs een klein aantal oorlogsdoden vaak onacceptabel. Vroege moderne samenlevingen waren daarentegen veel toleranter wat betreft de menselijke kosten die horen bij het imperialisme. Vóór de aanvang van deze eeuw kregen de meeste ouders vele kinderen, waarvan al werd verwacht dat enkelen plotseling zouden sterven door ziekte. In deze periode, waarin jong overlijden doodnormaal was, waren aspirant-soldaten en hun families veel meer bereid om de gevaren van het slagveld te trotseren.

> "Machines zijn agressief. De wever wordt een web, de machinist een machine. Als je gereedschappen niet gebruikt, gebruiken zij jou." -- Emerson

4\. **Technologie** heeft tijdens de moderne eeuwen verreweg de grootste rol gespeeld in het bepalen van de kosten en baten van het projecteren van macht. Dit boek beargumenteert dat het dat zal blijven doen. Technologie heeft verschillende cruciale dimensies:

**A. Balans tussen offensief en defensief.** De balans tussen aanval en verdediging, bepaald door de toegang tot wapentechnologie, bepaalt de schaal van de politieke organisatie. Wanneer offensieve capaciteiten stijgen, overheerst het vermogen om macht op afstand te projecteren, jurisdicties hebben dan de neiging om te consolideren, en overheden vormen zich op grotere schaal. In tijden zoals nu, nemen defensieve mogelijkheden toe. Hierdoor wordt het duurder om macht buiten de kerngebieden te projecteren. Rechtsgebieden hebben de neiging te versnipperen en grote overheden vallen uiteen in kleinere.

**B. Gelijkheid en de overheersing van de infanterie.** Een belangrijk kenmerk dat de mate van gelijkheid onder burgers bepaalt, is de aard van wapentechnologie. Wapens die relatief goedkoop zijn, zorgen dat de macht gelijker verdeeld wordt, omdat ze kunnen worden ingezet door niet-professionals. Dit versterkt het militaire belang van infanterie. Toen Thomas Jefferson zei dat "alle mensen als gelijken zijn geschapen", klonk dat veel geloofwaardiger dan het eeuwen daarvoor zou hebben gedaan. Een boer met zijn jachtgeweer was niet alleen even goed bewapend als de typische Britse soldaat met zijn Brown Bess, hij was zelfs beter bewapend. De boer met het geweer kon op de soldaat schieten vanaf een grotere afstand, en met grotere nauwkeurigheid. Dit was een duidelijk verschil met de Middeleeuwen, toen een boer met een hooivork - meer kon hij zich niet veroorloven - nauwelijks had kunnen hopen stand te houden tegen een zwaar bewapende ridder te paard. Niemand schreef in 1276 dat "alle mensen als gelijken zijn geschapen." Op dat moment, in de meest fundamentele zin, waren mensen niet gelijk. Één enkele ridder kon veel meer brute kracht uitoefenen dan tientallen boeren bij elkaar.

**C. Voor- en nadelen van schaal op vlak van geweld.** Een andere variabele die helpt bepalen of er een paar grote overheden of vele kleine zullen zijn, is de organisatorische schaal die vereist is om de heersende wapens in te zetten. Als geweld in toenemende mate loont, hebben overheden voordeel wanneer ze op grote schaal opereren, en hebben ze de neiging groter te worden. Wanneer een kleine groep echter erin slaagt hun middelen effectief genoeg in te zetten om de grotere macht te kunnen weerstaan, heeft soevereiniteit de neiging om te fragmenteren, wat het geval was tijdens de Middeleeuwen. Kleine, onafhankelijke autoriteiten voerden veel van de functies van de overheid uit. Zoals we in een later hoofdstuk zullen bespreken, geloven we dat het Informatietijdperk de opkomst van cybersoldaten zal brengen, die de voorbodes zullen zijn van de ontbinding van centrale macht. Cybersoldaten zouden niet alleen door natiestaten kunnen worden ingezet, maar ook door hele kleine organisaties, en zelfs door individuen. Oorlogen van het volgende millennium zullen enkele "veldslagen" kennen die volledig zonder bloedvergieten zullen verlopen, met computers.

**D. Schaalvoordelen van productie.** Een andere cruciale factor bij het bepalen of de uiteindelijke machtsuitoefening lokaal of op afstand plaatsvindt, is de schaal van de bedrijven waarin mensen hun geld verdienen. Als belangrijke bedrijven alleen goed kunnen functioneren op grote schaal, binnen een groot handelsgebied, dan kunnen overheden die dat mogelijk maken voldoende bijkomende inkomsten afromen om een grote overheid te onderhouden. Onder zulke omstandigheden functioneert de hele wereldeconomie gewoonlijk effectiever als één sterke wereldmacht alle anderen domineert, zoals het Britse Rijk dat deed in de negentiende eeuw. Soms leiden de megapolitieke variabelen er echter toe dat de schaal van economische handel in elkaar stort. Als het onderhouden van een groot handelsgebied steeds minder economisch voordeel oplevert, kunnen grotere overheden, die voorheen profiteerden van de voordelen van grotere handelsgebieden, beginnen uiteen te vallen - zelfs in situaties waarin het strategische evenwicht tussen offensieve en defensieve middelen grotendeels constant blijft.

**E. Verspreiding van technologie.** Nog een factor die invloed heeft op macht, is hoe wijdverspreid belangrijke technologieën zijn. Wanneer het mensen lukt om wapens of productiemiddelen te accumuleren of te monopoliseren, hebben ze de neiging om macht te centraliseren. Zelfs technologieën met een overwegend defensief karakter, zoals het machinegeweer, bleken tijdens de periode waarin ze niet wijd verspreid waren, krachtige offensieve wapens te zijn die bijdroegen aan een groeiende schaal van de overheid. Toen de Europese machten laat in de negentiende eeuw een monopolie op machinegeweren hadden, waren ze in staat om die wapens tegen volkeren aan de grenzen van hun territoria in te zetten, en zo hun koloniale rijken enorm uit te breiden. Later, in de twintigste eeuw, toen machinegeweren wijd beschikbaar werden, vooral in de nasleep van Wereldoorlog II, werden ze juist ingezet om rijken te vernietigen. Als alle andere omstandigheden gelijk blijven, geldt: hoe breder sleuteltechnologieën verspreid zijn, des te breder de macht verspreid zal zijn en des te kleiner de optimale schaal van de overheid.

## De snelheid van megapolitieke verandering

Hoewel technologie vandaag verreweg de belangrijkste factor is, en schijnbaar in toenemende mate, hebben de vier grote megapolitieke factoren in het verleden elk een rol gespeeld in het bepalen van de schaal waarop macht kon worden uitgeoefend.

Samen bepalen deze factoren of het loont om geweld op grotere schaal toe te passen. Dit bepaalt hoe belangrijk vuurkracht is in verhouding tot efficiënt gebruik van middelen. Het heeft ook een sterke invloed op de verdeling van inkomen in de markt. De vraag is: welke rol zullen deze factoren in de toekomst spelen? Om hier een antwoord op te geven is het cruciaal om te weten dat deze megapolitieke variabelen zich met enorm uiteenlopende snelheden ontwikkelen.

Topografie is vrijwel onveranderlijk geweest doorheen de hele geschiedenis. Buiten kleine lokale effecten, zoals het dichtslibben van havens, het opspuiten van land of erosie, is de topografie van de aarde bijna hetzelfde vandaag als toen Adam en Eva uit Eden stapten. En het zal waarschijnlijk zo blijven totdat een nieuwe ijstijd de landschappen van de continenten opnieuw vormgeeft, of totdat een andere ingrijpende gebeurtenis het aardoppervlak verstoort. Op een fundamenteler niveau lijken geologische tijdperken te veranderen over periodes van 10 tot 40 miljoen jaar, wellicht als gevolg van grote meteorietinslagen. Ooit kunnen er opnieuw geologische omwentelingen zijn die de topografie van onze planeet aanzienlijk zullen veranderen. Als dat gebeurt, mag je er wel van uit gaan dat zowel het honkbal- als het cricketseizoen zullen worden geannuleerd.

Het klimaat verandert veel frequenter dan topografie. In het laatste miljoen jaar heeft klimaatverandering voor het merendeel van de bekende veranderingen in het aardoppervlak gezorgd. Tijdens ijstijden groeven gletsjers nieuwe valleien, veranderden de loop van rivieren, scheidden eilanden van continenten of voegden ze samen door het zeeniveau te verlagen.

Fluctuaties in het klimaat hebben een significante rol gespeeld in de geschiedenis. Eerst in het bewerkstelligen van de Agrarische Revolutie na het einde van de laatste ijstijd, en later in het destabiliseren van regimes tijdens perioden van koudere temperaturen en droogte. Recentelijk zijn er zorgen geweest over de mogelijke impact van "wereldwijde opwarming." Deze zorgen kunnen niet zonder meer worden weggewuifd. Toch, vanuit een langer perspectief genomen, lijkt juist een verschuiving naar een kouder, en niet een warmer klimaat, een groter risico te zijn. Studies van temperatuurfluctuaties, gebaseerd op de analyse van zuurstofisotopen in kernmonsters van de oceaanbodem, tonen dat de huidige periode de tweede warmste is in meer dan 2 miljoen jaar.[^50] Als het kouder zou worden, zoals dat in de zeventiende eeuw gebeurde, zou dat een destabiliserende werking kunnen hebben op de megapolitiek. In die zin is het huidige alarmisme over de opwarming van de aarde wellicht geruststellend. Als deze waarschuwingen kloppen, betekent dat dat de temperaturen binnen het abnormaal warme en relatief milde bereik dat we de afgelopen drie eeuwen hebben meegemaakt, blijven fluctueren.

Het tempo van verandering door microben is echter een puzzel. Microben kunnen zeer snel muteren. Dit is vooral waar voor virussen. De gewone verkoudheid, bijvoorbeeld, muteert op een bijna kaleidoscopische manier. Hoewel deze mutaties in hoog tempo plaatsvinden, is hun effect op het verleggen van de grenzen waarbinnen macht wordt uitgeoefend aanzienlijk minder abrupt dan dat van technologische veranderingen. Waarom? Een deel van de reden is dat microben er meer baat bij hebben om hun gastheer enkel te infecteren dan om hem te doden. Virulente infecties die hun gastheren te gemakkelijk doden, hebben de neiging om zichzelf in het proces uit te roeien. Microparasieten kunnen alleen overleven als ze hun gastheren niet te snel of allemaal tegelijk doden.

Dat wil natuurlijk niet zeggen dat er geen uitbarstingen van dodelijke ziektes kunnen voorkomen die de machtsbalans veranderen. Zulke episodes kwamen prominent in de geschiedenis voor. De Zwarte Dood decimeerde aanzienlijke delen van de Euraziatische bevolking en bracht ernstige schade toe aan de internationale economie van de veertiende eeuw.

### Wat had kunnen zijn

Je kunt geschiedenis bekijken als wat er daadwerkelijk is gebeurd, maar ook als wat er had kunnen gebeuren. Het was niet onmogelijk voor microparasieten om in de moderne tijd nog grotere schade te hebben aangericht. Stel je voor dat er, net als malaria maar dan erger, een ziekte was geweest die de macht van het Westen aan haar grenzen had kunnen tegenhouden. De eerste Portugese zeevaarders die richting Afrika gingen, hadden zomaar een dodelijk retrovirus kunnen oplopen -- een nog besmettelijkere vorm van aids -- waardoor die hele nieuwe handelsroute naar Azië er nooit was gekomen. Ook Columbus en de eerste kolonisten in de Nieuwe Wereld hadden ziekten kunnen tegenkomen die hen op dezelfde manier zouden teisteren als de inheemse lokale bevolkingen, die door mazelen en andere Westerse kinderziekten werden getroffen. Toch gebeurde dit niet, waardoor je bijna het gevoel krijgt alsof de geschiedenis een soort lotsbestemming kent.

Microben droegen in de moderne periode minder bij aan het afremmen van de consolidatie van macht, maar faciliteerden het eerder. Westerse troepen en kolonisten ervaarden dat de technologische voordelen, die hen toelieten om macht uit te oefenen, werden versterkt door de microbiologische. Westerlingen waren gewapend met ongeziene biologische wapens, namelijk hun relatieve immuniteit voor kinderziekten die inheemse volkeren vaak juist verwoestten. Dit gaf Westerse reizigers een duidelijk voordeel op hun minder dicht bevolkte tegenstanders. De overdracht van ziekten ontwikkelde zich bijna geheel in één richting, van Europa naar buiten. Er was geen gelijkaardige overdracht in de andere richting, van de periferie naar de kern.

Als een mogelijk tegenvoorbeeld hebben sommigen beweerd dat Westerse ontdekkingsreizigers syfilis van de Nieuwe Wereld naar Europa importeerden. Dit is discutabel. Als het echter waar is, bleek het geen significante barrière voor de uitoefening van macht te zijn. Syfilis had vooral als gevolg dat de seksuele normen en gewoonten in het Westen veranderden. Vanaf het einde van de vijftiende eeuw tot het laatste kwart van de twintigste eeuw was de impact van microben op industriële samenleving steeds minder desastreus. Ondanks de persoonlijke tragedies en het ongeluk, veroorzaakt door uitbraken van tuberculose, polio, en griep, kwamen er in de moderne periode geen nieuwe ziekten op die de megapolitieke impact van de Antonijnse plagen of de Zwarte Dood zelfs benaderden. Tijdens de moderne periode verbeterde de volksgezondheid, en werden vaccinaties en tegengif wijdverbreid. In grote lijnen verminderde dit de invloed van infectieuze microben op de machtsprojectie, waardoor het relatieve belang van technologie sterk toenam.

De recente opkomst van AIDS en waarschuwingen over de potentiële verspreiding van exotische virussen zijn hints dat er geen garantie is dat de rol van microben in de toekomst even goedaardig zal zijn als dat het over de afgelopen vijfhonderd jaar is geweest. Maar het is onmogelijk om te weten of, of wanneer, een nieuwe plaag de wereld zal infecteren. De kans dat een uitbarsting van microparasieten, zoals een virale pandemie, de megapolitieke dominantie van technologie zou kunnen verstoren, is vele malen groter dan een verandering van klimaat of topografie.

We hebben geen manier om grote veranderingen in het leven op aarde zoals we dat kennen te monitoren of te voorspellen. Dus houden we onze vingers gekruist en hopen we dat de belangrijkste megapolitieke krachten in het komende millennium technologisch zullen zijn, en niet biologisch van aard. Als geluk aan de zijde van de mensheid blijft, zal technologie als de leidende megapolitieke variabele aan belang blijven toenemen.

Dit was echter niet altijd zo, zoals een overzicht van de eerste grote megapoliteike transformatie, de Agrarische Revolutie, duidelijkt toont.

[^29]: Huizinga, op. cit., p.7.
[^30]: *The Compact Edition of the Oxford English Dictionary*, vol. 1 (Oxford: Oxford University Press, 1971), p. 1828.
[^31]: Michael Hicks, *Bastard Feudalism* (Londen: Longmans, 1995), p.1.
[^32]: Ibid., p.102.
[^33]: Zie S. A. Cook et al., red., *The Cambridge Ancient History*, vol.12 (Cambridge: Cambridge University Press, 1971), pp. 208-22.
[^34]: Ibid., pp. 209-20.
[^35]: Will Durant, *The Story of Civilization*, vol.4, *The Age of Faith* (New York: Simon & Schuster, 1950), p.43.
[^36]: C. W. Previte-Orton, *The Shorter Cambridge Medieval History*, vol.1 (Cambridge: Cambridge University Press, 1971), p.102.
[^37]: Ibid., p. 131.
[^38]: Ibid., p.137.
[^39]: Ibid.
[^40]: Durant, op. cit., p.43.
[^41]: Ramsay MacMullen, *Corruption and the Decline of Rome* (New Haven: Yale University Press, 1988), p. 192.
[^42]: Geciteerd in ibid., p.193.
[^43]: Geciteerd in David Kline en Daniel Burstein, *Is Government Obsolete?* *Wired*, januari 1996, p.105.
[^44]: Lane, *Economic Consequences of Organized Violence*, op. cit.
[^45]: Ibid.
[^46]: Susan AIling Gregg, *Foragers and Farmers: Population Interaction and Agricultural Expansion in Prehistoric Europe* (Chicago: University of Chicago Press, 1988), p.9.
[^47]: Stephen Boyden, *Western Civilization in Biological Perspective* (Oxford: Clarendon Press, 1987), p. 89. Zie ook Marvin Harris, *Cannibals and Kings* (New York: Vintage, 1978), p. 29-32.
[^48]: Geoffrey Parker en Lesley Ni. Smith, red., *The General Crisis of the Seventeenth Century* (Londen: Routledge & Kegan Paul, 1985), p. 8.
[^49]: Zie Charles Woolsey Cole, *French Mercantilism: 1683-1700* (New York: Octagon Books, 197.1), p. 6.
[^50]: Chris Scarre, red., *Past Worlds: The Times Atlas of Archaeology 314* (New York: Random House, 1995), p. 58.
