# Ten oosten van Eden

::: {.content-hidden when-format="latex"}
*De landbouwrevolutie en de verfijning van geweld*
:::

> 'Toen vroeg de HEER: 'Waar is je broer Abel?' Kaïn antwoordde: 'Dat weet ik niet. Moet ik soms waken over mijn broer?' 'Wat heb je gedaan?' zei de HEER. 'Hoor toch hoe het bloed van je broer uit de aarde tot mij roept!' - Genesis 4:9-10

Vijfhonderd generaties geleden begon de eerste faseverandering in de organisatie van de menselijke samenleving.[^51] Onze voorouders in verscheidene regio's pakten met tegenzin primitieve werktuigen op, zoals scherp gemaakte stokken en provisorische schoffels, en gingen aan het werk. Toen ze de eerste gewassen zaaiden, legden ze ook een nieuwe basis voor de macht in de wereld. De landbouwrevolutie was de eerste grote economische en sociale revolutie. Deze revolutie begon met de verdrijving uit Eden en ontwikkelde zich zo langzaam dat het het jagen en verzamelen, toen de twintigste eeuw aanbrak, nog niet volledig had verdrongen in alle geschikte gebieden op aarde. Deskundigen geloven dat de landbouw, zelfs in het Nabije Oosten waar het voor het eerst ontstond, werd ingevoerd via 'een lang, stapsgewijs proces' dat 'wellicht vijfduizend jaar of meer in beslag nam'.[^52]

Het lijkt wellicht overdreven om een proces dat zich over millennia uitstrekte als een 'revolutie' te omschrijven. Toch was de komst van de landbouw precies dat: een vertraagde revolutie die het menselijk leven, door de logica van geweld te veranderen, transformeerde. Waar landbouw vaste grond kreeg, werd geweld een steeds zichtbaarder aspect van het dagelijkse leven. Zij die in staat waren om geweld te organiseren of beheersen, gingen de samenleving domineren.

Wie de agrarische revolutie begrijpt, heeft een eerste stap gezet in het doorgronden van de Informatierevolutie. De introductie van het ploegen en oogsten is een schoolvoorbeeld van hoe de maatschappelijke organisatie ingrijpend kan veranderen door een ogenschijnlijk simpele verandering in de aard van arbeid. Als je deze revolutie uit het verleden in het juiste perspectief kunt plaatsen, zul je beter kunnen inschatten hoe de geschiedenis zich zal ontvouwen als reactie op de nieuwe logica van geweld, die met microprocessoren haar intrede deed.

Om het revolutionaire karakter van de landbouw op waarde te schatten, moet je eerst een beeld hebben van hoe de oermaatschappij functioneerde. We hebben dit thema uitgebreid verkend in *The Great Reckoning*, maar zullen het hieronder kort schetsen. Gedurende een lange prehistorische periode van relatieve stilstand, waarin het menselijk bestaan nauwelijks evolueerde van generatie op generatie, waren jager-verzamelaarsamenlevingen de enige sociale organisatiestructuren. Antropologen stellen dat de mens gedurende 99 procent van zijn bestaan op aarde een jager en verzamelaar is geweest. Cruciaal voor het langdurige succes, maar ook het uiteindelijke falen van jager-verzamelaarsgroepen, is het feit dat ze op zeer kleine schaal in een uitgestrekt gebied moesten opereren.

Ze konden alleen overleven waar de bevolkingsdichtheid gering was. Denk, om te begrijpen waarom, aan de problemen die grotere groepen met zich mee zouden hebben gebracht. Ten eerste zou een groep van duizend jagers, die tegelijk door het landschap trok, zoveel tumult hebben veroorzaakt dat het wild op de vlucht zou zijn gejaagd. Erger nog, zelfs als een klein leger jagers er nu en dan in zou zijn geslaagd om een enorme kudde wild in het nauw te drijven, zou het voedsel dat ze verzamelden -- inclusief vruchten en eetbare planten uit de natuur -- niet lang in overvloed zijn gebleven. Een grote groep foerageerders zou het landschap hebben uitgeput door roofbouw, vergelijkbaar met een uitgehongerd leger tijdens de Dertigjarige Oorlog. Om deze uitputting te beperken, moesten de groepen dus klein blijven. Zoals Stephen Boyden schrijft in *Western Civilization in Biological Perspective*: 'Jager-verzamelaarsgroepen tellen doorgaans tussen de vijfentwintig en vijftig individuen'.[^53]

Vandaag de dag is leven op tienduizend hectare in een gematigd klimaat een luxe die slechts voor de allerrijksten is weggelegd. Een familie van jager-verzamelaars had aan minder nauwelijks genoeg gehad. Ze hadden doorgaans duizenden hectare per persoon nodig, zelfs in de meest vruchtbare gebieden. Dit verklaart waarom periodes van snelle bevolkingsgroei, juist in periodes met goede omstandigheden voor landbouw, konden uitmonden in crisissen. Jager-verzamelaars hadden zoveel ruimte nodig dat hun gemeenschappen nauwelijks dichter bevolkt waren dan het leefgebied van beren, lang voor de eerste akkers ontstonden.

Op kleine verschillen na leek het menselijke dieet op dat van een beer. Deze foeragerende samenlevingen waren voor hun voedsel afhankelijk van wat het open landschap en nabijgelegen wateren te bieden hadden. Hoewel sommigen visten, waren de meeste jagers voor een derde tot een vijfde van hun voedselinname afhankelijk van de eiwitten van grote zoogdieren. Naast enkele eenvoudige werktuigen en voorwerpen die ze met zich meedroegen, hadden jager-verzamelaars vrijwel geen technologie tot hun beschikking. Ze misten doorgaans effectieve methoden om vlees of ander voedsel langdurig te bewaren. Het meeste voedsel moest kort na het verzamelen worden geconsumeerd, anders bedierf het. Dit betekent natuurlijk niet dat sommige jager-verzamelaars geen bedorven voedsel aten. Eskimo's, zo meldt Boyden, 'zouden een bijzondere voorliefde hebben voor voedsel in staat van ontbinding'.[^54] Hij citeert de waarnemingen van deskundigen die stellen dat Eskimo's 'viskoppen begraven en ze laten wegrotten tot de graten dezelfde consistentie hebben als het vlees. Vervolgens kneden ze de stinkende massa tot een pasta en eten die op'; ze zijn ook dol op de 'vette, madenrijke larven van de kariboevlieg, rauw geserveerd... hertenkeutels, die ze als bessen eten... en merg van meer dan een jaar oud, wemelend van de maden'.[^55]

Op enkele delicatessen na legden jager-verzamelaars nauwelijks voedseloverschotten aan. Zoals antropoloog Gregg opmerkt, 'slaan rondtrekkende bevolkingsgroepen over het algemeen geen voedselvoorraden aan als buffer tegen seizoensgebonden of onverwachte schaarste.' Er viel bij de jager-verzamelaars bijgevolg weinig te stelen. Het was onhoudbaar in omstandigheden waarin geen voedseloverschot kon worden bewaard, om een arbeidsverdeling op te bouwen waarin mensen gespecialiseerd waren in het toepassen van geweld. De logica van de jacht bracht ook met zich mee dat geweld tussen jager-verzamelaarsgroepen nooit grootschalig kon zijn, omdat de groepen zelf klein moesten blijven.

De kleine omvang van de jager-verzamelaarsgroepen was ook op een andere manier voordelig. De leden van zulke kleine groepen kenden elkaar door en door, waardoor ze effectiever konden samenwerken. Besluitvorming wordt lastiger naarmate een groep groter wordt, omdat er steeds meer tegenstrijdige belangen ontstaan. Denk maar eens aan hoe moeilijk het is om met twaalf man een etentje te organiseren. Stel je voor hoe hopeloos de taak zou zijn geweest om honderden of duizenden mensen te organiseren tijdens een voortdurend verplaatsend feestmaal. Omdat zij geen blijvende, afzonderlijke politieke organisatie of bureaucratie hadden, zoals vereist voor oorlogsspecialisatie, moesten jager-verzamelaarsgroepen vertrouwen op overtuiging en consensus -- principes die het best werken bij kleine groepen met een relatief gemoedelijke stemming.

Of het er daadwerkelijk gemoedelijk aan toe ging in groepen jager-verzamelaars staat echter ter discussie. Sir Henry Maine verwijst naar 'de universele oorlogszuchtigheid van de primitieve mens'. In zijn woorden: 'Het is niet vrede dat natuurlijk en primitief is, maar oorlog.'[^56] Zijn visie wordt ondersteund door het werk van evolutionair biologen. R. Paul Shaw en Yuwa Wong merken op: 'Er zijn sterke aanwijzingen dat veel van de zichtbare verwondingen op overblijfselen van de *Australopithecus*, *Homo erectus* en *Homo sapiens* uit de vierde Europese ijstijd en de daaraan voorafgaande periodes het gevolg waren van gevechten.'[^57] Anderen trekken dit echter in twijfel. Deskundigen als Stephen Boyden beweren dat primitieve groepen doorgaans niet oorlogszuchtig of gewelddadig waren. Er ontstonden sociale conventies om interne spanningen te verminderen en het makkelijker te maken om de jachtbuit te verdelen. Vooral in gebieden waar men op groter wild joeg, dat voor een enkele jager moeilijk te vellen was, ontstonden religieuze en sociale regels die de herverdeling van al het gevangen wild onder de hele groep faciliteerden. Wanneer een calorierijke buit moest worden verdeeld, kregen andere jagers de eerste prioriteit. Noodzaak, en niet sentiment, was hierbij de drijfveer. De eersten die aanspraak maakten op de buit waren de economisch meest bekwame en militair sterkste leden, niet de zieken en de zwakken. Een belangrijke reden voor deze voorrangsregel was ongetwijfeld het feit dat jagers in de fleur van hun leven ook de militair sterkste leden van de kleine groep waren. Door hen het eerste recht op de buit te geven, werden mogelijk dodelijke interne conflicten in de groep tot een minimum beperkt.

Zolang de bevolkingsdichtheid van de jager-verzamelaars laag bleef, waren hun goden niet militant, maar ze belichaamden natuurkrachten of de dieren waarop ze jaagden. De beperkte hoeveelheid bezittingen en de uitgestrekte, open gebieden maakten oorlogsvoering in de meeste gevallen overbodig. Buiten de eigen kleine familie of clan waren er weinig buren die een bedreiging konden vormen. Doordat jager-verzamelaars rondtrokken op zoek naar voedsel, werden bezittingen die het strikte minimum overschreden een last. Wie weinig bezat, had vanzelfsprekend ook weinig last van schendingen van het eigendomsrecht. Omdat men weinig investeerde in een specifieke plek, koos men er bij conflicten vaak voor om de wegen te scheiden. Vluchten was een eenvoudige oplossing voor persoonlijke vetes of andere buitensporige eisen. Dit betekent niet dat de vroege mens vreedzaam was. Mogelijk waren ze gewelddadig en onaangenaam in een mate die we ons nauwelijks kunnen voorstellen. Maar als ze geweld gebruikten, was dat meestal om persoonlijke redenen of, wat misschien nog erger is, voor de sport.

Jagers-verzamelaars leefden in kleine groepen waarin, afgezien van het onderscheid tussen de geslachten, nauwelijks sprake was van een arbeidsverdeling. Ze hadden geen georganiseerde overheid, doorgaans geen permanente nederzettingen en geen mogelijkheid om rijkdom te vergaren. Zelfs elementaire bouwstenen van de beschaving, zoals een geschreven taal, waren onbekend in de oereconomie. Zonder geschreven taal konden er geen officiële archieven worden bijgehouden en dus geen geschiedenis.

### Overbejaging

Het bestaan als jager-verzamelaar kende heel andere prikkels dan die waaraan we sinds de opkomst van de landbouw gewend zijn geraakt. Voor het leven als jager-verzamelaar was maar weinig kapitaal nodig. Een paar primitieve gereedschappen en wapens volstonden. Er waren geen mogelijkheden om te investeren en er was zelfs geen particulier grondbezit, met uitzondering van steengroeven waar vuursteen of speksteen werd gewonnen.[^58] Zoals antropologe Susan Alling Gregg in *Foragers and Farmers* schreef, 'was het bezit van en de toegang tot hulpbronnen gemeenschappelijk eigendom van de groep.'[^59] Op zeldzame uitzonderingen na, zoals vissers die aan de oevers van meren leefden, hadden jagers-verzamelaars doorgaans geen vaste verblijfplaats. Omdat ze geen permanent onderkomen hadden, was er voor hen weinig reden om hard te werken voor bezittingen of het onderhoud ervan. Ze hoefden geen hypotheek of belastingen te betalen en geen meubels te kopen. Het kleine aantal consumptiegoederen dat ze bezaten, bestonden uit dierenhuiden en persoonlijke versieringen die de groepsleden zelf maakten. Er waren amper prikkels om iets te verzamelen dat als geld had kunnen dienen, want er was nauwelijks iets te koop. In zulke omstandigheden stelde het begrip 'sparen' voor jagers-verzamelaars weinig voor.

Omdat er geen reden was om te verdienen en er nauwelijks sprake was van een arbeidsverdeling, moet het idee van hard werken als deugd vreemd voor ze zijn geweest. Behalve in tijden van uitzonderlijke tegenspoed, wanneer een langdurige inspanning vereist was om iets eetbaars te vinden, verrichtte men weinig arbeid omdat er simpelweg weinig nodig was. Er viel letterlijk niets te winnen door meer te presteren dan het strikte minimum dat nodig was om te overleven. Voor de leden van een doorsnee jagers-verzamelaarsgroep betekende dat een werkweek van slechts acht tot vijftien uur.[^60] Omdat de arbeid van een jager de voedselvoorraad niet deed toenemen maar enkel kon uitputten, droeg iemand die zich heldhaftig uitsloofde om meer dieren te doden of meer vruchten te plukken dan men kon opeten voor het bedierf, niets bij aan de welvaart. Integendeel, overbejaging verminderde de kans om in de toekomst voedsel te vinden en had dus een schadelijke invloed op het welzijn van de groep. Daarom bestraften of verstootten sommige jagers-verzamelaars, zoals de Eskimo's, groepsleden die zich aan overbejaging schuldig maakten.

Het voorbeeld van de Eskimo's die overbejaging bestraffen, is bijzonder veelzeggend, omdat ze, veel meer dan anderen, vlees hadden kunnen bewaren door het te bevriezen. Bovendien was het voor hen mogelijk om ten minste een deel van de oliën, die uit grote zeedieren werden gewonnen, op te slaan. Dat jagers-verzamelaars er over het algemeen voor kozen om dit niet te doen, weerspiegelt hun veel passievere omgang met de natuur. Het zou ook wat kunnen zeggen over de mate waarin cognitie en mentale processen door cultuur worden beïnvloed. Het leerproces en gedrag worden begrensd door de complexe omgeving, waardoor de toepassing van sommige strategieën veel moeilijker kan zijn dan op het eerste gezicht lijkt. Zoals R. Paul Shaw en Yuwa Wong schreven: 'Omdat niches in veel opzichten verschillen, verschillen ook de leerpatronen.'[^61]

Vanuit dit perspectief bracht de opkomst van de landbouw meer met zich mee dan enkel een verandering in het voedingspatroon; het ontketende ook een grote revolutie in de organisatie van het economische leven en de cultuur, en een transformatie van de logica van geweld. Landbouw bracht grootschalige kapitaalgoederen in de vorm van grond en soms irrigatiesystemen voort. De gewassen en gedomesticeerde dieren die de boeren verbouwden en verzorgden, waren waardevolle bezittingen. Ze konden worden opgeslagen, gehamsterd en gestolen. Omdat de gewassen gedurende het hele groeiseizoen verzorgd moesten worden, van het zaaien tot de oogst, werd wegtrekken bij dreigingen minder aantrekkelijk, vooral in droge streken waar de mogelijkheden om gewassen te verbouwen beperkt waren tot de kleine gebieden met een betrouwbare watertoevoer. Naarmate ontsnappen moeilijker werd, namen de kansen op georganiseerde afpersing en plunderingen toe. Boeren waren tijdens de oogsttijd vaak het slachtoffer van overvallen. Geleidelijk nam de schaal van oorlogvoering dus toe.

Hierdoor neigde de omvang van samenlevingen te vergroten, omdat gewelddadige conflicten meestal werden gewonnen door de grotere groep. Naarmate de concurrentie om grond en de controle over de opbrengst ervan toenam, werden maatschappijen steeds minder mobiel. Er ontstond een duidelijke arbeidsverdeling. Voor het eerst deden loonarbeid en slavernij hun intrede. Boeren en veehouders specialiseerden zich in voedselproductie. Pottenbakkers maakten opslagpotten voor voedsel. Priesters baden tot hun god(en) voor regen en rijke oogsten. Specialisten in geweld -- de voorvaderen van de overheid -- richtten zich steeds meer op plundering en bescherming tegen plundering. Samen met de priesters werden zij de eerste rijken in de geschiedenis.

In de vroege stadia van agrarische samenlevingen eisten deze krijgers een deel van de jaarlijkse oogst op in ruil voor bescherming. Op plekken waar de dreiging minimaal was, wisten zelfstandige boeren soms een relatief grote mate van autonomie te behouden. Naarmate de bevolkingsdichtheid echter toenam en de strijd om voedsel verhevigde, vooral in woestijnachtige gebieden waar productieve grond schaars was, kon de krijgersgroep een groot deel van de totale opbrengst voor zich opeisen. Met de inkomsten uit deze afgedwongen heffingen, die opliepen tot wel 25 procent van de graanoogst en de helft van de groei van de veestapel, stichtten deze krijgers de eerste staten. Door landbouw nam het belang van dwang aanzienlijk toe. De sterke toename van middelen die buitgemaakt konden worden, leidde tot een forse stijging van het aantal plunderingen.

Het duurde millennia voordat de logica van de agrarische revolutie zich volledig manifesteerde. Lange tijd leefden dunbevolkte gemeenschappen van boeren in gematigde streken mogelijk grotendeels op dezelfde wijze als hun jagende en verzamelende voorouders. Waar grond en regenval overvloedig waren, verbouwden boeren hun gewassen op kleine schaal zonder veel gewelddadige inmenging. Maar toen de bevolking over een periode van enkele duizenden jaren groeide, kregen zelfs boeren in dunbevolkte gebieden te maken met onvoorspelbare plunderingen, waardoor ze soms niet genoeg zaaigoed overhielden voor de oogst van het volgende jaar. Wederzijdse plunderingen, oftewel anarchie, was een van de uitersten, net als onbeschermde gemeenschappen die leefden zonder een gespecialiseerde organisatie die het monopolie op geweld had.

Na verloop van tijd verspreidde de aan landbouw inherente logica van geweld zich over een steeds groter gebied. De regio's waar landbouw en veeteelt konden voortbestaan zonder de strooptochten van overheden, werden teruggedrongen tot enkele zeer afgelegen gebieden. De Kafir-regio's van Afghanistan, om een extreem voorbeeld te noemen, boden weerstand tegen de invoering van een centrale overheid tot in het laatste decennium van de negentiende eeuw. In dat proces waren ze echter al eeuwen eerder veranderd in een vrij militante samenleving, georganiseerd op basis van verwantschapslijnen. Dergelijke structuren waren niet in staat om op grote schaal militaire macht te mobiliseren. Tot de Britten moderne wapens naar de regio brachten, bleven de Kafirs onafhankelijk in hun afgelegen Bashgal- en Waigal-valleien, omdat hun bolwerken werden beschermd door de topografie, met hoge bergen en woestijnen die hen scheidden van veroveraars van buitenaf.[^62]

Na verloop van tijd drukte de fundamentele logica van de agrarische revolutie haar stempel op de samenlevingen waar landbouw werd toegepast. Door de landbouw konden menselijke gemeenschappen op een veel grotere schaal functioneren. Ongeveer tienduizend jaar geleden begonnen steden op te komen. Hoewel klein naar de huidige maatstaven, waren ze de centra van de eerste 'beschavingen', een woord afgeleid van *civitas*, wat in het Latijn 'burgerschap' of 'inwoner van een stad' betekent. Omdat de landbouw bezittingen voortbracht die geplunderd en beschermd moesten worden, ontstond ook de noodzaak voor een voorraadadministratie. Belasting heffen is onmogelijk als men geen administratie kan voeren en ontvangstbewijzen kan uitschrijven. De symbolen die in de boekhouding werden gebruikt, vormden de beginselen van het schrift, een vernieuwing die bij jagers en verzamelaars nooit had bestaan.

De landbouw verlegde ook de horizon waarbinnen de mens problemen moest oplossen. Jagersstammen leefden met een zeer beperkte tijdshorizon. Ze ondernamen zelden projecten die langer dan enkele dagen duurden. Het planten en oogsten van een gewas nam echter maanden in beslag. Projecten met een langere doorlooptijd dreven boeren ertoe hun aandacht op de sterren te richten. Gedetailleerde astronomische waarnemingen waren een voorwaarde voor het opstellen van almanakken en kalenders die als leidraad dienden voor de beste zaai- en oogsttijden. Met de komst van de landbouw verruimde de horizon van de jagers zich.

## Eigendom

De overgang naar een sedentaire agrarische samenleving leidde tot het ontstaan van particulier eigendom. Het is evident dat niemand bereid was een heel groeiseizoen op de akkers te zwoegen, om daarna toe te kijken hoe een ander het resultaat van zijn arbeid opeiste. Het idee van eigendom ontstond als een onvermijdelijk gevolg van de landbouw. De helderheid van het concept van particulier eigendom werd echter ondermijnd door de logica van geweld die met de introductie van de landbouw gepaard ging. De opkomst van eigendom werd vertroebeld door het feit dat de megapolitieke macht van individuen niet langer zo gelijkwaardig was als in jager-verzamelaarssamenlevingen, waar elke gezonde volwassen man een jager was en even zwaar bewapend was als ieder ander. De landbouw leidde tot een specialisatie in geweld. Juist omdat er iets te stelen viel, werden investeringen in betere wapens lonend. Het gevolg was diefstal, vaak op een sterk georganiseerde schaal.

De machtigen konden nu een nieuwe vorm van roof organiseren: een geweldsmonopolie, oftewel een 'overheid'. Dit zorgde voor een scherpe tweedeling in samenlevingen, waardoor zeer verschillende omstandigheden ontstonden voor degenen die profiteerden van de plunderingen en de massa armen die de velden bewerkten. De enkelingen die de militaire macht in handen hadden, konden nu rijk worden, samen met anderen die hun gunst genoten. De god-koningen en hun bondgenoten, de diverse lagere, lokale machthebbers die over de eerste staten in het Nabije Oosten heersten, genoten van eigendomsvormen die veel meer op de moderne leken dan die van de grote massa die onder hen zwoegde.

Natuurlijk is het historisch niet correct om in de vroege agrarische samenlevingen te spreken van een onderscheid tussen particulier en publiek bezit. De heersende god-koning beschikte over alle middelen van de staat op een manier die nauwelijks te onderscheiden was van het bezit van een uitgestrekt landgoed. Net als in de feodale periode van de Europese geschiedenis was al het bezit onderworpen aan de heerschappij van hogere machthebbers. Wie lager op de hiërarchische ladder stond, merkte dat zijn eigendom te allen tijde onderhevig was aan de grillen van de heerser.

Het feit dat de heerser niet door de wet werd beperkt, betekende echter niet dat hij het zich kon veroorloven om zomaar alles in beslag te nemen wat hij wilde. De vrijheid van de farao werd ingeperkt door de heersende kosten en baten, net zoals die van de premier van Canada vandaag de dag. Sterker nog, de farao werd veel meer belemmerd dan hedendaagse leiders, vanwege de beperkte transport- en communicatiemogelijkheden. Alleen al het verplaatsen van een buit, vooral als het voornamelijk landbouwproducten waren, zorgde voor grote verliezen door bederf en diefstal. Door meer ambtenaren aan te stellen die elkaar in de gaten hielden, werd diefstal beperkt, maar stegen de kosten voor de farao aanzienlijk. Decentrale autoriteit verbeterde soms de productie, maar vormde ook krachtige lokale leiders die soms de dynastieke controle uitdaagden. Zelfs despoten in het Oosten waren niet helemaal vrij om te doen wat ze wilden; ze moesten de bestaande machtsverhoudingen respecteren.

Hoewel iedereen, inclusief de rijken, onderhevig was aan willekeurige onteigening, konden sommigen toch eigen bezit vergaren. Net als nu besteedde de staat een groot deel van haar inkomsten aan openbare werken. Projecten als irrigatiesystemen, religieuze monumenten en koninklijke crypten boden architecten en ambachtslieden de kans om een inkomen te verdienen. Sommige individuen in een bevoorrechte positie slaagden erin om een flinke hoeveelheid privébezit op te bouwen. Veel van de overgebleven spijkerschrifttabletten uit Sumer, een oude Mesopotamische beschaving, bevatten handelsdocumenten, vooral over het overdragen van eigendomsrechten.

In de vroege landbouwsamenlevingen bestond privé-eigendom wel, maar zelden aan de onderkant van de sociale piramide. De overgrote meerderheid van de bevolking bestond uit boeren die te arm waren om veel rijkdom te vergaren. Sterker nog, op enkele uitzonderingen na, waren de meeste boeren tot in de moderne tijd zo arm dat ze bij elke droogte, overstroming of plaag, voortdurend het risico liepen om van de honger om te komen. Daarom moesten boeren hun zaken zo organiseren dat de risico's in slechte jaren tot een minimum beperkt bleven. In de brede, verarmde lagen van de samenleving bestond een primitievere vorm van eigendom. Die vergrootte de overlevingskans, maar ging ten koste van de mogelijkheid om kapitaal te vergaren en hogerop te komen in het economische systeem.

### Boerenverzekering

De oplossing lag in wat antropologen en sociale historici omschrijven als het 'gesloten dorp'. Bijna elke boerensamenleving in de premoderne tijden kende het 'gesloten dorp' als belangrijkste vorm van economische organisatie. Anders dan in modernere economische stelsels, waar individuen doorgaans met vele kopers en verkopers op een open markt handelen, functioneerden de huishoudens in het gesloten dorp samen als een soort collectief of een grote familie. Dit was geen open marktplaats, maar een gesloten systeem waarin alle economische transacties van het dorp doorgaans werden afgesloten met één monopolist: de lokale landheer, of zijn vertegenwoordigers. Het dorp maakte gezamenlijk afspraken met de heer, waarbij men doorgaans een hoog percentage van de oogst leverde in plaats van een vaste huurprijs. Deze proportionele pacht betekende dat de landheer een deel van het risico van een slechte oogst voor zijn rekening nam. Uiteraard streek de landheer ook het grootste deel van de potentiële winst op. Meestal zorgden de landheren ook voor het zaaigoed.

Deze regeling beperkte ook het gevaar van hongersnood. Het vereiste dat de landheer, in plaats van de boer, een onevenredig deel van zijn oogstaandeel bewaarde. Omdat de landbouwopbrengsten in het verleden in veel gebieden schrikbarend laag waren, moesten er soms wel twee zaden worden geplant voor elke drie die men oogstte. Onder zulke omstandigheden zou een slechte oogst massale hongersnood betekenen. De boeren hadden natuurlijk de rationele voorkeur voor een regeling waarbij de landheer in hun voortbestaan investeerde. Hoewel ze moesten kopen tegen gemonopoliseerde prijzen, goedkoop moesten verkopen en de landheer van arbeid in natura moesten voorzien, vergrootten de boeren hun overlevingskansen. Om soortgelijke redenen gaf de gewone boer in een gesloten dorp de zekerheid van privébezit op. Door zich afhankelijk te maken van de dorpsleider, maakte het gezin meer kans om te profiteren van de regelmatige herverdeling van akkers. Het kwam geregeld voor dat de dorpsleider de beste stukken grond voor zichzelf en zijn kring hield. Dat was echter een risico dat de boeren moesten tolereren om te kunnen genieten van de overlevingsverzekering die het diffuse dorpsbezit van de akkers bood. In tijden waarin de oogstopbrengsten erbarmelijk laag waren, kon een verschil in de groeiomstandigheden tussen akkers die een steenworp van elkaar verwijderd lagen, het verschil maken tussen hongersnood en overleven. Boeren kozen vaak voor de regeling die het risico op verlies verkleinde, zelfs als dat betekende dat ze elke hoop op grotere welvaart moesten opgeven.

Over het algemeen kwam risicomijdend gedrag veel voor bij alle groepen die op de rand van het bestaan balanceerden. De enorme uitdaging om te overleven in premoderne samenlevingen heeft altijd het gedrag van de armen beperkt. Een interessant kenmerk van deze risicoaversie, zoals besproken in *The Great Reckoning*, is dat het de bandbreedte van vreedzaam economisch gedrag dat individuen maatschappelijk gezien mochten vertonen, verkleinde. Taboes en sociale beperkingen remden experimenten en innovatief gedrag af, zelfs ten koste van potentieel voordelige verbeteringen in bestaande werkwijzen.[^63] Dit was niet onlogisch, aangezien experimenteren tot grotere verschillen in uitkomsten leidt. Een grotere variatie in de resultaten kan niet alleen hogere opbrengsten betekenen, maar er is ook het risico op rampzalige verliezen voor mensen die nauwelijks kunnen overleven. Een groot deel van de culturele energie van arme landbouwsamenlevingen is altijd gericht geweest op het onderdrukken van experimenten. Deze onderdrukking was in feite hun alternatief voor een verzekering. Zouden ze een verzekering hebben gehad, of voldoende spaargeld om hun experimenten zelf te dekken, dan zouden zulke sterke sociale taboes niet nodig zijn geweest om hun overleven te waarborgen.

Culturen zijn functionele aanpassingsmechanismen, geen voorkeuren. Wat in de ene omgeving werkt, kan elders nutteloos of zelfs schadelijk zijn. Mensen leven in een grote verscheidenheid aan leefomgevingen. Het brede scala aan potentiële niches waarin wij leven, vereist gedragsvarianten die te complex zijn om door instinct alleen te worden gestuurd. Daarom wordt gedrag cultureel geprogrammeerd. Voor de overgrote meerderheid in veel agrarische samenlevingen was de cultuur voornamelijk gericht op overleven, en nauwelijks meer dan dat, terwijl de luxe om deel te nemen aan open markten voor een selecte groep was weggelegd.

Persoonlijke bekwaamheid en individuele keuze, of zoals de moderne Amerikanen zeggen "the pursuit of happiness", werden onderdrukt door taboes en maatschappelijke beperkingen die juist onder de armen het sterkst waren. Zulke beperkingen werden in maatschappijen met een beperkte productiviteit slechts met grote moeite overwonnen. Waar en wanneer de landbouwproductiviteit hoger lag, zoals in het oude Griekenland, vonden kleine megapolitieke revoluties plaats. Eigendom nam modernere vormen aan. 'Allodium', of vrij eigendom, deed zijn intrede. Grond werd doorgaans verpacht tegen een vaste vergoeding, en de pachter nam het economische risico voor zijn rekening, maar genoot ook van een groter deel van de winst als de oogst goed was. Met meer spaarmiddelen wordt het mogelijk om het risico van riskant gedrag zelf te dragen. Onder dergelijke omstandigheden konden zelfstandige boeren zich boven de boerenstand verheffen en soms zelfs een eigen vermogen opbouwen.

Het is kenmerkend voor sociale organisatiestructuren dat eigendomsrechten en verhoudingen meer marktgericht worden, vooral aan de economische top of soms zelfs in de volledige economie, wanneer een samenleving zich uit de armoede werkt. Het is hierbij belangrijk om op te merken dat de meest voorkomende organisatievorm van de agrarische samenleving historisch gezien in wezen feodaal was, met marktwerking aan de top en een gesloten dorpssysteem aan de basis. De grote massa boeren was in bijna alle premoderne agrarische samenlevingen aan het land gebonden. Zolang de landbouwproductiviteit laag bleef, of hogere productiviteit afhankelijk was van centrale irrigatiesystemen, bleven de vrijheid en eigendomsrechten van individuele boeren onderaan minimaal. In zulke omstandigheden overheersten feodale eigendomsvormen. Grondbezit was gebaseerd op pacht, niet op een volledige eigendomstitel, en het recht op verkoop, schenking en vererving was doorgaans beperkt.

Het feodalisme in zijn diverse vormen was niet enkel een reactie op de voortdurende dreiging van geweld. Het was tevens een antwoord op de ontzettend lage productiviteit. In agrarische samenlevingen gingen die twee vaak hand in hand, en ze versterkten elkaar met regelmaat. Wanneer het openbare gezag instortte, namen eigendomsrechten en welvaart over het algemeen evenredig af. Een ineenstortende productiviteit ondermijnde op haar beurt eveneens het gezag. Hoewel niet elke droogte of ongunstige klimaatverandering leidde tot het verval van het openbare gezag, was dit in veel gevallen wel zo.

## De feodale revolutie van het jaar 1000

Dit was het geval bij de transformatie van het jaar 1000, die de feodale revolutie in gang zette.[^64] De politieke en economische realiteit rond die periode week op cruciale punten af van het beeld dat we nu van de Middeleeuwen hebben. In de eerste eeuwen na de val van Rome kwijnde de economie van West-Europa weg. De Germaanse koninkrijken die in de gebieden van het voormalige Romeinse Rijk opkwamen, hadden tal van functies van de Romeinse staat overgenomen, zij het op een veel minder ambitieus niveau. De infrastructuur werd min of meer aan haar lot overgelaten. Naarmate de eeuwen verstreken, raakten bruggen en aquaducten in verval en werden ze onbruikbaar. Hoewel Romeinse munten nog in gebruik waren, raakten ze nagenoeg uit circulatie. De bloeiende grondhandel uit de Romeinse tijd viel stil. Steden, ooit administratieve centra, verdwenen vrijwel geheel samen met het vermogen van de staat om belasting te heffen. En daarmee verdwenen ook bijna alle andere kenmerken van beschaving.

De 'Donkere Middeleeuwen' heten niet voor niets zo. Geletterdheid werd zo zeldzaam dat wie kon lezen en schrijven vrijstelling van rechtsvervolging kon verwachten voor vrijwel elke misdaad, moord inbegrepen. Artistieke, wetenschappelijke en technische vaardigheden die in de Romeinse tijd sterk ontwikkeld waren, raakten in de vergetelheid. Van de aanleg van wegen tot het enten van wijnstokken en fruitbomen, West-Europa paste veel technieken die ooit algemeen bekend waren en op hoog niveau werden toegepast, niet langer toe. Zelfs een oeroud werktuig als de pottenbakkersschijf verdween op veel plaatsen. De mijnbouwactiviteit nam af, de metaalbewerking liep terug, en irrigatiewerken in het Middellandse Zeegebied raakten door verwaarlozing in verval.'[^65] Zoals historicus Georges Duby opmerkte: 'Aan het einde van de zesde eeuw was Europa een uiterst onbeschaafde plek.'[^66] Hoewel er rond het jaar 800 onder het bewind van Karel de Grote een korte heropleving van centraal gezag was, viel al snel na zijn dood alles weer uiteen.

Een verrassend gevolg van dit sombere tafereel was dat de ineenstorting van de Romeinse staat de levensstandaard van kleine boeren waarschijnlijk voor enkele eeuwen juist verhoogde. De Germaanse koninkrijken die West-Europa tijdens de Donkere Middeleeuwen domineerden, namen enkele van de wat vrijere sociale gewoonten over die hun voorouderlijke stammen kenden, zoals de juridische gelijkheid van vrije boeren. Als gevolg daarvan waren kleine boeren in de Donkere Middeleeuwen veel vrijer dan ze in de feodale eeuwen zouden geweest zijn. Hieruit kunnen we tevens afleiden dat ze welvarender waren. Zoals we eerder zagen bij de analyse van eigendomsvormen onder verschillende productiviteitsniveau's, is vrij eigendom historisch vaak gepaard gegaan met de relatieve welvaart van kleine boeren. De gesloten dorpen en feodale eigendomsvormen ontstonden vooral in gebieden waar de mogelijkheid van kleine boeren om in hun levensonderhoud te voorzien meer onder druk stond.

Toegegeven, door de vrijwel volledige ineenstorting van de economie tijdens de Donkere Middeleeuwen liepen kleine boeren de voordelen van handel en grotere afzetmarkten mis. Door het wegvallen van de steden stortte de geldeconomie in, maar tegelijkertijd hoefde het platteland niet meer op te draaien voor de kosten van een verstikkend overheidsapparaat. Guy Bois schreef hierover dat de Romeinse stad een parasitaire gemeenschap was en geen productiecentrum: 'In de Romeinse tijd was de voornaamste functie van een stad politiek van aard. Ze leefde voornamelijk van de inkomsten die via de grondbelasting uit de omliggende gebieden werden aangevoerd... De stad produceerde in feite weinig tot niets voor het omliggende platteland'.[^67] De ineenstorting van het Romeinse gezag bevrijdde de boeren op het platteland grotendeels van belastingen, die 'tussen een kwart en een derde van de bruto-opbrengst van het land' opslokte, 'zonder de diverse afpersingspraktijken mee te rekenen waar kleine en middelgrote grondbezitters onder te lijden hadden'.[^68] Door de extreme belastingdruk, die soms met de dood werd afgedwongen, vertrokken veel mensen en lieten hun grond achter. De barbaren schaften deze belastingen gelukkig af.

### Agri deserti

De onderdrukking door de overheid nam dusdanig af door de barbaarse veroveringen dat er voor de armen een mogelijkheid ontstond om eigen bezit te verwerven en te behouden. Een deel van de *agri deserti*, de boerderijen die door hun eigenaren, vanwege de roofbelastingen in de nadagen van het Romeinse Rijk waren verlaten, werd opnieuw in productie genomen. Ondanks de barre omstandigheden van die tijd en het feit dat de oogsten naar moderne maatstaven belachelijk laag waren, waren de Donkere Middeleeuwen een periode van relatieve welvaart voor de kleine boeren in Europa. Ze genoten toen van een sterke machtspositie die ze pas in de moderne tijd opnieuw zouden bereiken. Enerzijds waren er minder arbeidskrachten beschikbaar om het vruchtbare land, waarvan grote stukken braak waren komen te liggen, te bewerken. Epidemieën, oorlogen en landverlating door eigenaren die het instortende Romeinse Rijk ontvluchtten, hadden eerder gecultiveerde gebieden aanzienlijk ontvolkt. Een ander voordeel voor kleine boeren in de Donkere Middeleeuwen kwam voort uit de invoering van nieuwe landbouwtechnologie in de zesde eeuw: de zware ploeg, vaak op wielen gemonteerd. In combinatie met een verbeterd harnas waarmee meerdere ossen konden worden ingezet, maakte deze technologie het veel eenvoudiger om beboste gronden in Noord-Europa te ontginnen.[^69]

Onder dergelijke omstandigheden verdween de markt voor grond vrijwel volledig. Nieuwe landbouwgrond kon simpelweg worden verkregen door de bossen te verwijderen en een deel van elk nieuw perceel af te staan aan de lokale autoriteiten. Door dit proces, in het Engels bekend als *assarting*, kon de bevolkingsgroei na de val van Rome eeuwenlang worden opgevangen. *Assarting* werd met name aantrekkelijk in dunbevolkte noordelijke regio's, nadat hogere temperaturen in de achtste eeuw de landbouw productiever maakten.

De leiders van de Germaanse stammen die voormalige Romeinse gebieden veroverden, vestigden zich als grootgrondbezitters. Het grootste deel van de rest van de bevolking bewerkte kleine percelen, maar onder hele andere omstandigheden dan die van het latere feodalisme. De rijkere landeigenaren, oftewel de meesters, vormden zo'n 7 tot 10 procent van de bevolking. Het lijkt erop dat vóór het jaar 1000 tweederde van de dorpelingen in een doorsnee Franse streek vrij landeigenaar was.[^70] Ze bezaten ongeveer de helft van alle gecultiveerde grond.[^71] Er waren weinig lijfeigenen. *Coloni*, ofwel pachtboeren, maakten niet meer dan 5 procent van de bevolking uit. Slavernij bleef bestaan, maar op een veel kleinere schaal dan in de Romeinse tijd.

De germaanse koninkrijken die Rome opvolgden, werden militair verdedigd door alle vrije mannen die op oproep van de graaf, de plaatselijke vertegenwoordiger van de koning, de wapens opnamen. Zelfs "kleine en middelgrote grondbezitters" moesten zich groeperen en mensen uit hun midden afvaardigen om in de infanterie te dienen.[^72] In het edict van Pîtres beval Karel de Kale alle mannen die daartoe in staat waren om te paard ten strijde te trekken. Paus Gregorius II had een eeuw voordien getracht deze militaire verplichting kracht bij te zetten door in 732 de consumptie van paardenvlees door de mens te verbieden.[^73] Toch was er nog weinig juridisch of statusonderscheid tussen de infanterie van vrije grondbezitters en de cavalerie. Alle vrije mannen namen deel aan plaatselijke rechtbanken en konden bij de graaf een verzoek indienen om geschillen te beslechten, een ambt dat al sinds de late romeinse tijd bestond. Van adel was er nog geen sprake.

> 'Een sociaal fenomeen dat nieuw was als massaal verschijnsel dook in de jaren 980 plots op: sociale achteruitgang. De eerste slachtoffers waren de kleine allodiumbezitters.'[^74] - Guy Bois

In de loop van de Donkere Middeleeuwen raakten de structuren die de zelfstandigheid van kleine boeren en vrije grondeigenaars in de Germaanse koninkrijken hadden gewaarborgd, steeds meer uit balans door een reeks ontwikkelingen:

1. De bevolkingsaantallen herstelden zich geleidelijk, waardoor de druk op het gebruik van de grond toenam. In de loop van enkele eeuwen werd een groot deel van de meest vruchtbare, nog onontgonnen grond gecultiveerd, een groei die zich met name in Noord-Europa voordeed. De toename van het aantal boeren in verhouding tot de beschikbare hoeveelheid grond deed de waarde van de arbeid van elke boer dalen. De meeste vrije stukken land raakten door erfopvolging versnipperd in steeds kleinere percelen, omdat het in de vroege Middeleeuwen gebruikelijk was om de nalatenschap van ouders gelijk te verdelen over de kinderen. De versnippering van het grondbezit in een tijd van bevolkingsgroei dreef de waarde van grond opnieuw op en leidde tegen het midden van de tiende eeuw tot een heropleving van de actieve handel in grond.
2. In de laatste decennia van de tiende eeuw daalden de temperaturen plotseling, wat een verwoestend effect had op de landbouwopbrengst. Drie opeenvolgende misoogsten leidden tussen 982 en 984 tot een ernstige hongersnood. Na nog een mislukte oogst in 994 sloeg de hongersnood opnieuw toe.[^75] In 997 werd het probleem van de dalende opbrengsten vervolgens verergerd door een plaag, die kleine familiebedrijven bijzonder hard trof omdat de kleine boeren niet over de middelen beschikten om de arbeidskracht van weggevallen familieleden te vervangen. Door deze opeenstapeling van misoogsten en rampen raakten de zelfstandige boeren aanvankelijk diep in de schulden. Toen een herstel van de opbrengsten uitbleef, konden ze hun schulden niet meer aflossen.
3. De machtsverhoudingen raakten steeds verder uit balans door het toenemende belang van de zware cavalerie. Frances Gies, een historicus gespecialiseerd in de Middeleeuwen, beschrijft hoe de gepantserde cavalerist zich ontwikkelde tot de middeleeuwse ridder:

> Hoewel een ridder oorspronkelijk een figuur van bescheiden komaf was, die zich door zijn dure paard en harnas boven de boerenstand verhief, wist hij zijn maatschappelijke positie geleidelijk te verbeteren tot hij tot de adelstand behoorde. Ridders bleven weliswaar de laagste rang binnen de aristocratie, maar het ridderschap kreeg een unieke status, waardoor de ridderslag een eer werd die zelfs door de hoge adel en koningshuizen werd begeerd. Die status was voornamelijk het resultaat van het streven van de Kerk om het ridderschap een christelijk karakter te geven. Dit deed ze door de ridderceremonie te heiligen en een gedragscode, de ridderlijkheid, te stimuleren. Het was een code die misschien vaker werd geschonden dan nageleefd, maar die een onmiskenbare invloed had op het denken en handelen van latere generaties.[^76]

Zoals we in *The Great Reckoning* vertelden, kreeg de bewapende ridder te paard door de uitvinding van de stijgbeugel een enorm aanvalsvermogen. Hij kon nu in volle vaart aanvallen zonder uit het zadel te worden geworpen wanneer hij een doelwit raakte met zijn lans. De militaire waarde van de zware cavalerie nam verder toe door een Aziatische uitvinding die in de tiende eeuw in West-Europa haar intrede deed: het vastgenagelde ijzeren hoefijzer. Dit verbeterde het uithoudingsvermogen van het paard aanzienlijk.[^77] Ook het gevormde zadel, de spoor en het stangbit droegen bij aan de toegenomen slagkracht van de ridder. Ze boden meer controle over het paard en maakten het eenvoudiger om met één hand zware wapens te gebruiken.[^78] Deze op het eerste gezicht kleine technologische verbeteringen maakten kleine boeren op militair vlak vrijwel irrelevant, omdat ze de middelen niet hadden om een strijdros te onderhouden of zichzelf goed te bewapenen. De grote paarden die speciaal voor de strijd werden gefokt, maar goedkoper waren en bekend stonden als 'destriers', waren evenveel waard als vier ossen of veertig schapen. De duurdere oorlogspaarden kostten tien ossen of honderd schapen. Ook een harnas kostte een bedrag dat geen enkele kleine landeigenaar zich kon permitteren, namelijk het equivalent van zestig schapen.[^79]

4. Ook het koudere weer, de mislukte oogsten, de hongersnoden en de plagen in de aanloop naar het jaar 1000 beïnvloedden het gedrag van de mensen. Velen waren ervan overtuigd dat het einde van de wereld of de wederkomst van Christus voor de deur stond. Vrome of angstige landeigenaren, groot en klein, schonken hun grond aan de Kerk in voorbereiding op de apocalyps.

### 'Alleen een arme man verkoopt grond'

De onrustige omstandigheden aan het einde van de tiende eeuw legden de basis voor de feodale revolutie. Door opeenvolgende misoogsten en rampen raakten de zelfstandige boeren diep in de schulden. Toen de oogsten zich niet herstelden, kwamen de vrije boeren in een uitzichtloze situatie terecht. Markten leggen altijd de grootste druk op de zwakste partijen. Dat is zelfs een van hun deugden; ze bevorderen efficiëntie door eigendom van zwakkere eigenaren af te nemen. Maar in het Europa van de late tiende eeuw was zelfvoorzieningslandbouw vrijwel het enige beroep. Families die hun grond verloren, raakten hun enige middel om te overleven kwijt. Geconfronteerd met dit onaantrekkelijke vooruitzicht, besloten veel, zo niet de meeste, vrije boeren tijdens de feodale revolutie hun akkers weg te geven. In de woorden van Guy Bois: 'De enige zekere manier voor een boer om het land dat hij bewerkte te behouden, was om het eigendom ervan af te staan aan de Kerk, zodat hij het vruchtgebruik kon behouden.'[^80] Anderen stonden al hun grond, of een deel ervan, af aan rijkere boeren in wie ze vertrouwen hadden, zoals vriendelijke buren of familieleden.

Deze eigendomsoverdrachten vonden plaats onder de voorwaarde dat de boer, zijn familie en zijn afstammelingen op de akkers mochten blijven werken. De arme boeren konden tevens rekenen op de wederzijdse steun van de meer vermogende landeigenaren, nu de 'edelen', die zich een paard en een harnas konden veroorloven en zo de uitgebreide landgoederen bescherming boden. Vanuit het oogpunt van de nieuwe lijfeigene kan een dergelijke overeenkomst worden gezien als een tussenstation tussen het behoud van economisch eigendom en een gedwongen verkoop. Vaker wel dan niet was het een aanbod dat hij niet kon weigeren.

De dalende productiviteit bracht de arme boeren niet alleen in een wanhopig economisch dilemma, maar ontketende ook een golf van roofzuchtig geweld die de eigendomszekerheid ondermijnde. Wie niet over de middelen beschikte om een deel van de beschikbare, maar ontoereikende voorraad paarden en voer te bemachtigen, merkte plotseling dat hij en zijn bezit niet langer veilig waren. Om hun dilemma in hedendaagse termen te vatten: het was alsof je vandaag de dag gedwongen werd jezelf te bewapenen met een nieuw type wapen, maar de kosten daarvan $100.000 bedroegen. Als je die prijs niet kon betalen, kon je enkel hopen op genade van degenen die dat wel konden.

Binnen een paar jaar stortte het vermogen van de koning en de rechtbanken om de orde te handhaven volledig in.[^81] Iedereen met een harnas en een paard kon nu zijn eigen wet stellen. Wat volgde leek op een middeleeuwse *Blade Runner*, een roerige tijd vol geweld en rooftochten, terwijl de officiële machthebbers machteloos toekeken. Plunderingen en aanvallen door gewapende ridders ontwrichtten het platteland. Het is echter helemaal niet vanzelfsprekend dat alle slachtoffers van deze plunderingen arm waren. Integendeel, de oudere, fysiek zwakkere of slecht voorbereide grootgrondbezitters vormden juist aantrekkelijke doelwitten. Bij hen viel meer te stelen.

Het was geen toeval dat dit gebeurde op het moment dat kouder weer, hongersnood en de pest de middelen schaars maakten. De megapolitieke omstandigheden die de ineenstorting van het gezag in de hand werkten, bestonden al een tijdje. Pas toen er een crisis ontstond, kwam hun vermogen om de machtsverhoudingen te veranderen tot uiting. Misoogsten en hongersnoden lijken precies die rol te hebben vervuld. Hoewel de exacte opeenvolging van gebeurtenissen moeilijk te reconstrueren is, lijkt het erop dat de plunderingen, althans gedeeltelijk, werden veroorzaakt door de wanhopige omstandigheden. Zodra het geweld was losgebarsten, bleek dat niemand de macht kon mobiliseren om het te stoppen. De overgrote meerderheid van slecht bewapende boeren kon zeker weinig uitrichten. Een enkele geharnaste ridder te paard was al genoeg om tientallen boeren te overmeesteren. Vrije boeren konden, net als de gevestigde autoriteiten, de koningen en hun graven, niets beginnen tegen de landroof door gewapende strijders.

### 'De godsvrede'

In deze wanhopige omstandigheden droeg de Kerk bij aan het ontstaan van het feodalisme door een wapenstilstand te proberen te bewerkstelligen op het gewelddadige platteland. Historicus Guy Bois beschreef de situatie als volgt: "De onmacht van de politieke autoriteiten was zodanig dat de Kerk hun rol overnam in een poging om de orde te herstellen, in de beweging die bekendstaat als 'de godsvrede'". 'Vredesconcilies' vaardigden een reeks verboden uit, op straffe van banvloeken, en in grote 'vredesvergaderingen' legden krijgers hun eden af. De beweging ontstond in Zuid-Frankrijk (Concilie van Charroux in 989, Concilie van Narbonne in 990) en verspreidde zich geleidelijk..."[^82]

De overeenkomst die de Kerk sloot, hield de erkenning in van de heerschappij van gewapende ridders in lokale gemeenschappen, in ruil voor het staken of matigen van het geweld en de plunderingen. Na de toename van het geweld aan het einde van de tiende eeuw verschenen titels als 'nobilis' en 'miles' in eigendomsakten, als teken van gezag. Daarmee werd de adel als aparte sociale klasse geboren. In oudere akten, opgesteld voor exact dezelfde personen, ontbraken zulke titels nog volledig.[^83]

Door de dalende productiviteit en de economische onzekerheid van kleine grondbezitters leidde de megapolitieke macht van gewapende ridders onvermijdelijk tot grondbezit op basis van feodale leenverhoudingen. Tegen het einde van het eerste kwart van de elfde eeuw waren de vrije boeren grotendeels verdwenen. Hun allodiale bezittingen waren geslonken tot een fractie van hun vroegere omvang en werden nog maar een deel van de tijd bewerkt. De kleine boeren of hun afstammelingen werden horigen die de meeste tijd al werkend doorbrachten op de landgoederen van feodale heren, zowel wereldlijke als kerkelijke.

De teloorgang van de openbare orde die met de feodale revolutie gepaard ging, leidde tot gedragsveranderingen die het feodalisme versterkten. Daartoe behoorde een explosieve toename van de kastelenbouw. Kastelen doken voor het eerst op in Noordwest-Europa als primitieve houten bouwwerken in de nasleep van de invallen van de Vikingen in de negende eeuw. Oorspronkelijk waren het commandoposten voor Karolingische ambtenaren, maar na de feodale revolutie werden ze erfelijk bezit. Deze vroege bolwerken waren veel primitiever dan hun latere versies, maar desondanks moeilijk aan te vallen. Eenmaal gebouwd, konden kastelen slechts met de grootste moeite met de grond gelijkgemaakt worden. Naarmate kastelen het platteland begonnen te domineren, verloor het centrale gezag zijn greep: de koning en zijn graven waren nauwelijks nog in staat de macht van lokale heren te doorbreken.

### De bijdrage van de Kerk aan de productiviteit

Feodalisme ontstond als antwoord op het wegvallen van orde tijdens een tijd van beperkte productiviteit in de landbouwsamenleving. In het begin van dit systeem speelde de Kerk een belangrijke en economisch productieve rol. Enkele bijdragen van de Kerk:

1. In een omgeving waar militaire macht gedecentraliseerd was, bevond de Kerk zich in een unieke positie om de vrede te bewaren en orderegels te ontwikkelen die versnipperde, lokale soevereiniteiten overstegen. Dit was een taak waar geen enkele seculiere macht tegen opgewassen was. De observaties van de grote religieuze autoriteit A. R. Radcliffe-Brown zijn hier rechtstreeks van toepassing. Hij wees erop dat "de sociale functie van een religie onafhankelijk is van haar waarheid of onwaarheid". Zelfs religies die "absurd en weerzinwekkend zijn, zoals die van sommige primitieve stammen, kunnen belangrijke en effectieve onderdelen van het maatschappelijke raderwerk zijn".[^84] Dit was zeker het geval voor de Kerk in de vroege stadia van het feodalisme. Ze hielp, zoals alleen een religie dat kon, bij het opstellen van regels die mensen in staat stelden om perverse prikkels en gedragsdilemma's te overwinnen. Sommige hiervan waren morele dilemma's die eigen zijn aan het menselijk bestaan. Maar andere waren lokale dilemma's, die uniek waren voor de heersende megapolitieke omstandigheden. In de laatste jaren van de tiende eeuw speelde de middeleeuwse Kerk een bijzondere rol bij het herstellen van de orde op het platteland. Door religieuze en ceremoniële steun te verlenen aan lokale autoriteiten, verlaagde de Kerk de kosten om op zijn minst zwakke, lokale geweldsmonopolies te vestigen. Door op deze manier bij te dragen aan de orde, schiep de Kerk de voorwaarden die uiteindelijk leidden tot stabielere machtsverhoudingen.

De Kerk bleef nog lange tijd een rol spelen in het beteugelen van privéoorlogen en buitensporig geweld dat de wereldlijke autoriteiten anders niet konden indammen. Het relatief grote belang van de Kerk ten opzichte van de wereldlijke autoriteiten blijkt uit het feit dat tegen de elfde eeuw de parochie de voornaamste bestuurlijke eenheid werd in grote delen van West-Europa, en niet langer de civiele indelingen zoals de *ager* en *pagus* (de omgeving rond een stadje), die sinds de Romeinse tijd tot in de Donkere Middeleeuwen hadden standgehouden.[^85]

2. Het was vooral de Kerk die zorg droeg voor het behoud en de verspreiding van technische kennis en informatie. De Kerk financierde universiteiten en zorgde voor het weinige onderwijs dat de middeleeuwse maatschappij genoot. De Kerk bood ook een mechanisme voor het vermenigvuldigen van boeken en manuscripten, waaronder vrijwel alle toenmalige informatie over landbouw en veeteelt. De scriptoria van de benedictijnenkloosters kunnen worden gezien als een alternatieve technologie voor de drukpers, die toen nog niet bestond. Hoe kostbaar en inefficiënt de scriptoria ook waren, ze vormden in de feodale periode praktisch het enige mechanisme om geschreven kennis te vermenigvuldigen en te bewaren.
3. Mede doordat haar boerderijbeheerders geletterd waren, droeg de Kerk sterk bij aan het verhogen van de landbouwproductiviteit in Europa, vooral in de vroege fase van het feodalisme. Vóór de dertiende eeuw waren de beheerders van wereldlijke heren vrijwel allemaal analfabeten, die hun administratie bijhielden met een ingenieus stelsel van merktekens. Al waren deze boeren nog zo slim, ze hadden niet de mogelijkheid om te profiteren van verbeteringen in productiemethoden die ze niet zelf bedachten of met eigen ogen zagen. De Kerk was daarom onmisbaar voor het verbeteren van de kwaliteit van graan, fruit en fokvee. Omdat haar bezittingen over heel Europa verspreid lagen, kon de Kerk hoogwaardig zaaigoed en fokmateriaal inzetten waar de productie achterbleef. De vraag naar wijn voor de misdiensten in Noord-Europa spoorde monniken aan om te experimenteren met druivensoorten die beter bestand waren tegen koudere klimaten. De Kerk hielp ook op andere manieren de productiviteit van de middeleeuwse landbouw te verhogen. Kleine, slecht bruikbare lapjes grond die de Kerk in de feodale periode verwierf, werden vaak opnieuw ingedeeld zodat ze makkelijker te bewerken werden. De Kerk voorzag ook in de aanvullende diensten die kleine boerengemeenschappen nodig hadden. In veel gebieden maalden kerkelijke molens graan tot meel.
4. De Kerk nam veel taken op zich die tegenwoordig onder de overheid vallen, waaronder het voorzien in openbare infrastructuur. Dit is een voorbeeld van hoe de Kerk, in een tijdperk van versnipperd gezag, hielp bij het oplossen van wat economen 'dilemma's van publieke goederen' noemen. Specifieke kloosterordes uit de vroege Middeleeuwen legden zich toe op civieltechnische taken, zoals het aanleggen van wegen, het herbouwen van ingestorte bruggen en het herstellen van vervallen Romeinse aquaducten. Ze ontgonnen ook land, bouwden dammen en legden moerassen droog. Een nieuwe kloosterorde, de kartuizers, groef de eerste 'artesische' put in Artois, Frankrijk. Met behulp van klopboren groeven ze een klein gat dat diep genoeg was om een put te creëren waarvoor geen pomp nodig was.[^86] De cisterciënzerorde nam de bouw en het onderhoud van kwetsbare zeeweringen en dijken in de Lage Landen op zich. Boeren droegen land over aan cisterciënzerkloosters en pachtten het daarna terug, terwijl de monniken de volledige verantwoordelijkheid voor het onderhoud en de herstelwerkzaamheden op zich namen. Cisterciënzers namen ook het voortouw in de ontwikkeling van wateraangedreven machines, die voor uiteenlopende doeleinden werden gebruikt, zoals 'stampen, heffen, malen en persen'.[^87] Het klooster van Clairvaux groef een kanaal van twee mijl lang vanaf de rivier de Aube.[^88] De Kerk faciliteerde ook het aanleggen van nieuwe wegen en bruggen op plaatsen waar bevolkingscentra zich buiten het bereik van de oude Romeinse garnizoenswegen hadden verplaatst. Bisschoppen verleenden aflaten aan lokale heren die rivierovergangen bouwden of herstelden en herbergen voor reizigers onderhielden. Een monnikenorde, opgericht door de heilige Bénézet, de Frères Pontifes of 'Broeders van de Brug', bouwde een aantal van de langste bruggen die destijds bestonden, waaronder de Pont d'Avignon, een gigantische constructie met twintig bogen over de Rhône, met aan één uiteinde een kapel die ook als tolhuis diende. Zelfs de London Bridge, die tot de negentiende eeuw standhield, werd gebouwd door een kapelaan en werd deels gefinancierd met een bijdrage van duizend mark van de pauselijke legaat.[^89]
5. De kerk hielp ook een complexere markt tot ontwikkeling te brengen. De bouw van kathedralen, bijvoorbeeld, is van een andere orde dan openbare infrastructuur zoals bruggen en aquaducten. In principe werden kerkgebouwen alleen voor religieuze diensten gebruikt en niet als verkeersaders voor de handel. Toch mag niet worden vergeten dat de bouw van kerken en kathedralen hielp om markten voor tal van ambachtelijke en technische vaardigheden te creëren en te versterken. Net zoals de militaire uitgaven van de natiestaat tijdens de Koude Oorlog onbedoeld de voedingsbodem voor het internet vormden, zo leidde de bouw van middeleeuwse kathedralen tot andere neveneffecten, zoals de bevordering van de handel. De kerk was de voornaamste klant voor de bouwsector en ambachtslieden. Kerkelijke aankopen van zilver voor de communiediensten, kandelaars en decoratieve kunstwerken, creëerden een markt voor luxegoederen die anders niet zou hebben bestaan.

Op vele manieren hielp de Kerk de hevigheid van het geweld te temperen dat tijdens en na de 'feodale revolutie' door gewapende ridders werd ontketend. Vooral in de eerste eeuwen van het feodalisme leverde de Kerk een aanzienlijke bijdrage aan het verbeteren van de productiviteit van de landbouweconomie. Het was een onmisbare instelling, die goed aansloot bij de behoeften van de agrarische samenleving aan het einde van de Donkere Middeleeuwen.

### Kwetsbaarheid voor geweld

Gedurende "dertig à veertig jaar van gewelddadige onrust" voltrok zich rond het jaar 1000 de feodale revolutie.[^90] Dit was net als de val van Rome vijf eeuwen eerder een uniek gebeuren, voortgekomen uit een complex samenspel van invloeden. Toch weerspiegelt de triomf van mali homines (slechte lieden) en de onderdrukking die ze teweegbrachten in één opzicht perfect de fundamentele kwetsbaarheid voor geweld van de landbouwsamenleving. Waar de jager-verzamelaarsfase van het menselijke bestaan relatief vreedzaam was, betekende de overgang naar landbouw een radicale sprong in gestructureerd geweld en overheersing.

Vanaf het allereerste begin weerspiegelde zich dit in de militant ingestelde culturen van de landbouwvolkeren. De goden van de vroege landbouwsamenlevingen waren goden van regen en overstroming; hun functies weerspiegelden de grote zorg van die samenlevingen voor de factoren die de oogstopbrengsten bepaalden. De brenger van regen of water was vaak ook de oorlogsgod, en werd aangeroepen door de eerste koningen, die vooral als krijgsheren optraden.[^91]

De nauwe band tussen landbouw en oorlogsvoering vond zijn weerslag in de religieuze verbeelding van de mensen wier levens werden getransformeerd door de innovaties van de landbouwrevolutie. De verdrijving uit het hof van Eden kan worden gezien als een beeldend verslag van de overgang van een jager-verzamelaarssamenleving naar een landbouwsamenleving; een overgang van een vrij leven, waarin voedsel met weinig moeite uit de overvloed van de natuur werd geplukt, naar een leven van hard labeur.

## Het verloren paradijs

Landbouw stuurde de mensheid een volkomen nieuwe richting uit. De eerste boeren zaaiden letterlijk de kiem van de beschaving. Uit hun gezwoeg kwamen steden voort, legers, rekenkunde, astronomie, kerkers, wijn en whisky, het geschreven woord, koningen, slavernij en oorlog. Maar ondanks al het drama dat de landbouw het leven zou brengen, lijkt de stap weg van de oereconomie vanaf het begin enorm impopulair te zijn geweest. Daarvan getuigt het verhaal uit het boek Genesis, dat vertelt over de verdrijving uit het paradijs. De bijbelse parabel van het hof van Eden is een nostalgische herinnering aan het onbezorgde leven van de jager-verzamelaar in de wildernis. Geleerden menen dat het woord 'Eden' afkomstig is van een Soemerisch woord voor 'wildernis'.[^92]

De overgang van een vrij en dunbevolkt leven in de wildernis naar een sedentair bestaan in een boerendorp werd diep betreurd, een spijt die niet alleen in de Bijbel tot uiting komt, maar ook in de aanhoudende weerzin van de mens om 's ochtends op te staan en aan het werk te gaan. Zoals Stephen Boyden schreef in *Western Civilization in Biological Perspective*, was de nieuwe levenswijze die met de landbouw gepaard ging 'evodeviant'.[^93] Vóór de komst van de landbouw leefden duizenden generaties mensen zoals Adam in het hof van Eden, op uitnodiging van zijn Schepper: 'Van alle bomen in het hof moogt gij vrij eten'. Jagers en verzamelaars hadden geen gewassen te verbouwen, geen kudde om te hoeden en geen belastingen te betalen. Net als zwervers trokken jager-verzamelaars waar ze maar heen wilden, werkten ze weinig en legden ze aan niemand verantwoording af.

Met de komst van de landbouw begon een nieuwe levenswijze, en wel op veel dwingendere voorwaarden. 'Ook zal ze u doornen en distels voortbrengen, en gij zult het gewas des velds eten. In het zweet uws aanschijns zult gij brood eten'. Landbouw was hard werken. De herinnering aan het leven vóór de landbouw was die van een verloren paradijs.

Meer dan ze zich ooit hadden kunnen voorstellen, creëerden de boeren nieuwe omstandigheden die de logica van geweld radicaal veranderden. Het is geen toeval dat het boek Genesis van Kaïn, de eerste moordenaar, 'een landbouwer' maakt. Het maakt inderdaad deel uit van de wonderbaarlijke profetische kracht van de Bijbel dat het verhaal werd toevertrouwd aan herders, die maar al te goed begrepen hoe de landbouw geweld in de hand werkte. In enkele verzen omvat het bijbelse verslag een logica die duizenden jaren nodig had om zich te ontvouwen. De landbouw was een broedplaats voor geschillen. De landbouw creëerde op grote schaal plaatsgebonden kapitaal, wat de opbrengst van geweld verhoogde en de bescherming van bezittingen erg bemoeilijkte. Voor het eerst maakte de landbouw zowel misdaad als bestuur rendabel.

[^51]: Boyden, op. cit., p.4.
[^52]: Gregg, op. ciL, xv.
[^53]: Boyden, op. cit., p. 62.
[^54]: Ibid., p. 67.
[^55]: Ibid.
[^56]: Geciteerd in E. J. P Veale, *Advance to Barbarism: The Development of Total Warfore* (New York: Devin-Adair, 1968), p. 37.
[^57]: R. Paul Shaw en Yuwa Wong, *Genetic Seeds of Warfare: Evolution, Nationalism and Patriotism* (Boston: Unwin Hyman, 1989), p. 4.
[^58]: Zie Carleton S. Coon, *The Hunting Peoples* (New York: Nick Lyons Books, 1971), p. 275.
[^59]: Gregg, op. cit., p. 23.
[^60]: Boyden, op. cit., p. 69.
[^61]: Shaw and Wong, op. cit., p. 69
[^62]: Voor meer details over de Kafirs, zie Schuyler Jones, *Men of Influence in Nuristan* (Londen: Seminar Press, 1974).
[^63]: Zie Samuel L. Popkin, *The Rational Peasant* (Berkeley: University of California Press 1979), p. 13.
[^64]: Zie Bois, op. cit.
[^65]: Zie Frances en Joseph Gies, *Cathedral, Forge, and Waterwheel: Technology and Invention in the Middle Ages* (New York: HarperCollins, 1994), p.40.
[^66]: Geciteerd in ibid., p. 42.
[^67]: Bois, op. cit., p. 78.
[^68]: Ibid., p. 118.
[^69]: Gies, op. cit., p. 45.
[^70]: Bois, op. cit., p. 116.
[^71]: Ibid., p. 26.
[^72]: Ibid., p. 64.
[^73]: Gies, op. cit., p. 47.
[^74]: Bois, op. cit., p. 52.
[^75]: Ibid., p. 150
[^76]: Gies, op. cit., p.2.
[^77]: Ibid., p.46.
[^78]: Ibidem, p. 56-57.
[^79]: Ibidem, p. 58.
[^80]: Bois, op. cit., p. 87.
[^81]: Ibidem. Hoewel de precieze opeenvolging van gebeurtenissen tijdens de feodale revolutie door een gebrek aan bronnen moeilijk te reconstrueren is, lijkt de these van Guy Bois ons in grote lijnen juist. Ze is niet alleen op zichzelf plausibel, maar biedt ook een verklaring voor anderszins afwijkende feiten én sluit bovendien aan bij onze theorieën.
[^82]: Ibidem, p. 136.
[^83]: Ibid., p. 57 en passim.
[^84]: A. R. Radcliffe-Brown, 'Religion and Society', in *Structure and Function in Primitive Society* (Londen: Cohen & West, 1952), p. 153-177.
[^85]: Bois, op. cit., p. 36.
[^86]: Gies, op. cit., p. 112.
[^87]: Ibid., p. 114.
[^88]: Ibid., p.117.
[^89]: De details over bruggen en infrastructuur zijn voornamelijk afkomstig uit ibid., pp. 148-54.
[^90]: Bois, op. cit., p. 136.
[^91]: Zie Norman Cohn, *Cosmos, Chaos, and the World to Come: The Ancient Roots of the Apocalyptic Faith* (New Haven: Yale University Press, 1993), hfst. I-3, met name p. 60.
[^92]: Bruce Ni. Metzger en Michael D. Coogan, red., *The Oxford Companion to the Bible* (Oxford: Oxford University Press, 1993), p.178.
[^93]: Boyden, op. cit., p. 118.

:::{.content-visible when-format=latex}
\setsubtitle{Parallellen tussen het seniele verval van de heilige moederkerk en de bemoeizuchtige staat}
:::
