# Het leven en de gezondheid van de natiestaat

::: {.content-hidden when-format="latex"}
_Democratie en nationalisme als strategische middelen in het Tijdperk van Geweld_
:::

> "Het allerbelangrijkste voor oorlogsvoering is om voldoende financiële middelen te hebben om alles te leveren wat nodig is."[^163] -- Robert de Balsac, 1502

## Het puin van de geschiedenis

Op 9 en 10 november 1989 zond de televisie wereldwijd beelden uit van uitgelaten Oost-Berlijners die de Berlijnse Muur met voorhamers afbraken. Beginnende ondernemers in de menigte raapten stukken van de muur op, die later aan kapitalisten overal ter wereld werden verkocht als souvenir. Jarenlang werd er een levendige handel in deze relikwieën gedreven. Zelfs op het moment dat we dit schrijven, kom je nog af en toe advertenties tegen in kleine tijdschriften waarin stukken oud Oost-Duits beton worden aangeboden voor prijzen die normaal gesproken alleen voor hoogwaardig zilvererts worden betaald. Degenen die de Berlijnse Muur-souvenirs hebben gekocht, hoeven geen haast te hebben om ze te verkopen. Zij bezitten aandenken aan iets groters dan de val van het communisme. Wij geloven dat de Berlijnse Muur de belangrijkste berg historisch puin is geworden sinds de muren van San Giovanni met de grond gelijk werden gemaakt bijna vijf eeuwen eerder, in februari 1495.[^164]

Het afbreken van San Giovanni door de Franse koning Karel VIII was het eerste salvo van de Buskruitrevolutie. Het markeerde het einde van de feodale fase van de geschiedenis en het begin van het industrialisme, zoals we eerder hebben uiteengezet. De vernietiging van de Berlijnse Muur markeert een andere historische scheidslijn: de overgang van het Industriële Tijdperk naar het nieuwe Informatietijdperk. Nooit eerder was er zo'n grote symbolische triomf van efficiëntie over macht. Toen de muren van San Giovanni vielen, was dat een onmiskenbare demonstratie dat de economische opbrengsten van geweld sterk waren gestegen. De val van de Berlijnse Muur zegt echter iets anders, namelijk dat de opbrengsten van geweld nu dalen. Dit is iets wat nog maar weinigen zijn gaan beseffen, maar het zal dramatische gevolgen hebben.

Om redenen die we in dit hoofdstuk behandelen, kan de Berlijnse Muur veel symbolischer zijn voor het hele tijdperk van de industriële natiestaat dan de menigte die nacht in Berlijn, of de miljoenen die van een afstand keken, beseften. De Berlijnse Muur werd gebouwd met een heel ander doel dan de muren van San Giovanni: om te voorkomen dat mensen aan de binnenkant konden ontsnappen, in plaats van te voorkomen dat roofdieren van buitenaf binnenkwamen. Dat feit alleen al is een veelzeggend teken van de toename van de macht van de staat van de vijftiende tot de twintigste eeuw. En dat op meer dan één manier.

Eeuwenlang maakte de natiestaat alle muren die naar buiten gericht waren overbodig en onnodig. De gebieden waarin de staat als eerste een monopolie op dwang realiseerde, werden zowel intern vreedzamer als militair krachtiger dan welke soevereine macht de wereld ook had gekend. De staat gebruikte de middelen die zij van een grotendeels ontwapende bevolking afnam om kleinschalige roofdieren de kop in te drukken. De natiestaat werd het succesvolste instrument in de geschiedenis om middelen af te pakken. Dat succes was gebaseerd op het superieure vermogen om de rijkdom van zijn burgers voor haar eigen doeleinden in te zetten.

> "MTV is meer dan alleen een leverancier van muziekvideo's en een promotietool van de platenindustrie. Het is het eerste echte mondiale netwerk, dat vrijwel in elk land ter wereld een uniforme programmering biedt. Daardoor creëert MTV een gedeeld gevoel van wereldwijde realiteit voor zijn kijkers, kinderen en jongvolwassenen. Recent onderzoek toont aan dat jongeren wereldwijd steeds vaker niet alleen gemeenschappelijke popiconen en smaken delen, maar ook gelijke verwachtingen over hun carrière, vergelijkbare waarden over wat zinvol is in het leven en wat angst veroorzaakt, en een gemeenschappelijk besef dat politiek minder belangrijk is bij het vormgeven van hun toekomst dan hun eigen vaardigheden."[^165] -- Jim Taylor and Watts Wacker, The 500-Year Delta: What Happens After What Comes Next

### "Houd ervan of vertrek" (tenzij je rijk bent)

Voordat de overgang van de natiestaat naar de nieuwe soevereiniteiten van het Informatietijdperk voltooid is, zullen veel inwoners van de grootste en machtigste westerse natiestaten, net als hun tegenhangers in Oost-Berlijn in 1989, plannen maken om hun eigen weg te vinden. Voor de generaties die volwassen werden vóór de Tweede Wereldoorlog, of vroeg in de Koude Oorlog, is het oversteken van grenzen traumatisch. Maar voor nieuwe generaties, die hun oriëntatie baseren op een meer globale blik, is het verlaten van het land van geboorte niet zo ondenkbaar als voor de ouderen, die dieper geworteld zijn in de ideologie van de natiestaat. Jim Taylor en Watts Wacker rapporteren de intrigerende resultaten van een grootschalige enquête onder 20.000 middenklassers op vijf continenten. In een steekproef tijdens het schooljaar 1995-96, uitgevoerd door Brainwaves Group, een consumentenonderzoeksbureau uit New York, was negen van de tien leerlingen het eens met de uitspraak: "het is aan mij om uit het leven te halen wat ik wil." Opvallender nog: "bijna de helft van de tieners zei dat ze verwachten het land van hun geboorte te verlaten om hun doelen na te streven."[^166] Misschien omdat hij, als eerste presidentskandidaat die campagne voerde op MTV, de mentaliteit van de MTV-generatie goed aanvoelde, heeft Bill Clinton geprobeerd het voor Amerikanen moeilijker te maken om "het land van hun geboorte te verlaten om hun doelen na te streven." In 1995, ongeveer op hetzelfde moment dat de middelbare scholieren hun intenties uitspraken, stelde de president van de Verenigde Staten de invoering van een exitbelasting voor, een "Berlijnse Muur voor kapitaal," die rijke Amerikanen zou verplichten een aanzienlijk bedrag aan losgeld te betalen om zelfs een deel van hun geld mee te nemen.

Clintons losgeld doet niet alleen denken aan het late Oost-Duitse beleid om haar burgers als activa te behandelen, maar het herinnert ook aan de steeds strengere maatregelen die genomen werden om de financiële positie van het vervallende Romeinse Rijk te versterken. Dit fragment uit _The Cambridge Ancient History_ vertelt het verhaal.

> "Zo begon de felle poging van de staat om de bevolking tot de laatste druppel uit te knijpen. Omdat de economische middelen tekortschoten, vochten de sterken om het grootste deel voor zichzelf veilig te stellen, met een geweld en gewetenloosheid die goed pasten bij hun oorsprong en bij een soldaat die gewend was aan plundering. De wet werd onverbiddelijk hard toegepast op de bevolking. Soldaten traden op als deurwaarders of zwierven als geheime politie door het land. Degenen die het meest leden, waren natuurlijk de bezittende klasse. Het was relatief gemakkelijk hun eigendommen in beslag te nemen, en in een noodsituatie waren zij de klasse waar het meest en het snelst iets van af te persen viel."[^167]

Wanneer falende systemen daartoe in staat zijn, leggen ze vaak zware sancties op aan degenen die proberen te ontsnappen. We citeren opnieuw _The Cambridge Ancient History_: "Als de vermogende klasse haar geld verstopte, of twee derde van haar bezit opofferde om een magistratuur te ontvluchten, of zelfs haar gehele eigendom opgaf om verlost te worden van de erfpacht, en de niet-vermogende klasse vluchtte, reageerde de staat door de druk te verhogen."

Houd dit in het achterhoofd wanneer je plannen maakt voor de toekomst. De ondergang van staatsystemen verliep in het verleden zelden op beleefde of ordelijke wijze. We noemden in hoofdstuk 2 de nare gewoonten van Romeinse belastinginners. Het grote aantal verlaten boerderijen, agri deserti, in West-Europa na de val van het Romeinse Rijk weerspiegelde slechts een klein deel van een breder probleem. In feite waren de afpersingen relatief mild in Gallië en in de grensgebieden die het huidige Luxemburg en Duitsland omvatten. In Rome's meest vruchtbare regio, Egypte, waar de landbouw productiever was door irrigatie, was het vertrek van eigenaren een nog groter probleem. De vraag of men moest proberen te ontsnappen, het ultimum refugium zoals het in het Latijn werd genoemd, werd de overheersende twijfel van bijna iedereen met bezit. Archieven tonen aan dat "onder de gewone vragen die men in Egypte aan een orakel stelde, drie standaardtypen waren: 'Word ik bedelaar?', 'Zal ik vluchten?' en 'Zal mijn vlucht worden tegengehouden?'"[^168]

Clintons voorstel bevestigt die vragen. Het betreft immers een vroege vorm van een ontsnappingsdrempel die naar verwachting zwaarder wordt naarmate de fiscale middelen van de natiestaat krimpen. In tegenstelling tot Honeckers betonnen afscheidingen en prikkeldraad is de Amerikaanse vertrekbarrière uiteraard zachter en is het vooral gericht op miljardairs met belastbare bezittingen boven $600.000. Desalniettemin zijn de argumenten ervoor erg vergelijkbaar met die van Honecker, die ooit het beroemdste openbare werk van de inmiddels verdwenen Duitse Democratische Republiek verdedigde. Honecker betoogde dat de Oost-Duitse staat fors had geïnvesteerd in haar potentiële vluchtelingen, en dat het economisch nadeel voor de staat zou veroorzaken als ze zouden vertrekken. De staat rekende immers op hun inzet in Oost-Duitsland.

Als je uitgaat van het idee dat mensen eigendom zijn of zouden moeten zijn van de staat, dan is Honeckers muur logisch. Berlijn zonder muur was voor de communisten een maas in de wet, net zoals ontsnapping aan de Amerikaanse belastingjurisdictie een maas in de wet was in de ogen van Clintons belastingdienst. Naast het feit dat Clintons opmerkingen over miljardairs die het land verlaten de typische politieke slordigheid met cijfers toonden, waren ze vergelijkbaar met Honeckers, maar minder steekhoudend, aangezien de VS nauwelijks economisch geïnvesteerd heeft in rijke burgers die willen vluchten. Het gaat hier niet om mensen die op staatskosten zijn opgeleid en weg willen glippen om elders als advocaat te gaan werken. De overgrote meerderheid van degenen die onder de exitbelasting zouden vallen, hebben hun vermogen door eigen inspanning vergaard, ondanks, en niet dankzij, de Amerikaanse overheid.

Nu de hoogste 1 procent van de belastingbetalers 28,7 procent van de totale inkomstenbelasting in de VS betaalt, is er geen sprake van dat de rijken nalaten een reële investering van de staat in hun opleiding of economische voorspoed terug te betalen. Integendeel. Degenen die het grootste deel van de rekening betalen, betalen veel meer dan de waarde van de voordelen die zij ontvangen. Met een gemiddelde jaarlijkse belastingafdracht van meer dan $125.000 kost de belasting de hoogste 1 procent van de Amerikaanse belastingbetalers veel meer dan zij beseffen. Als we ervan uitgaan dat men over een periode van veertig jaar jaarlijks 10 procent rendement zou kunnen behalen op elke $5.000 aan te veel betaalde belasting, dan betekent dat aan het einde van die periode een vermindering van het potentiële vermogen met $2,2 miljoen. Bij een rendement van 20 procent vermindert elke $5.000 aan overbelasting het nettovermogen met maar liefst $44 miljoen.

Naarmate het millennium nadert, zullen de nieuwe megapolitieke omstandigheden van het Informatietijdperk het steeds duidelijker maken dat de natiestaat, geërfd uit het Industriële Tijdperk, een roofzuchtige instelling is. Met ieder jaar dat voorbijgaat, zal zij minder als een zegen voor de welvaart blijken en meer als een obstakel, iets waaraan het individu wil ontsnappen. Het is die ontsnapping die wanhopige regeringen niet graag zullen toestaan. De stabiliteit en zelfs het voortbestaan van de westerse verzorgingsstaten hangt af van hun vermogen om een enorm deel van de totale wereldproductie te blijven onttrekken voor herverdeling aan een deel van de kiezers in de OESO-landen. Dit vereist dat de belastingen die worden opgelegd aan de meest productieve burgers van de huidige rijke landen worden vastgesteld op supermonopolietarieven, honderden of zelfs duizenden keren hoger dan de werkelijke kosten van de diensten die overheden daarvoor leveren.

## Het leven en sterven van de natiestaat

De val van de Berlijnse Muur was meer dan slechts een zichtbaar symbool van het einde van het communisme. Het betekende een nederlaag voor het mondiale systeem van natiestaten en een overwinning voor efficiëntie en marktwerking. De machtsbasis die eens de geschiedenis bepaalde, is ingrijpend verschoven. Wij zijn ervan overtuigd dat de val van de Berlijnse Muur in 1989 het hoogtepunt betekende van het tijdperk van de natiestaat -- een merkwaardige tweehonderdjarige periode die begon met de Franse Revolutie. Staten bestaan al meer dan zesduizend jaar, maar vóór de negentiende eeuw vertegenwoordigden zij slechts een klein deel van de wereldwijde soevereine entiteiten. Hun opkomst begon en eindigde met revoluties. De grote gebeurtenissen van 1789 dreven Europa tot het vormen van werkelijk nationale regeringen. De grote gebeurtenissen van 1989 markeerden de dood van het communisme en de overwinning van marktwerking op geconcentreerde macht. Die twee revoluties, precies tweehonderd jaar uit elkaar, markeren het tijdperk waarin de natiestaat overheerste in het systeem van de grote mogendheden. De grote mogendheden beheersten op hun beurt de wereld en verspreidden of legden staatsstelsels op, zelfs aan de meest afgelegen tribale enclaves.

Dat de staat uitgroeide tot het voornaamste middel om geweld te organiseren, kwam niet door ideologie maar door de harde logica van geweld. Het was, zoals wij het noemen, een megapolitieke gebeurtenis, niet zozeer gedreven door de wensen van theoretici en staatslieden, of zelfs door het gemanoeuvreer van generaals, maar door de verborgen hefboom van geweld, die de loop van de geschiedenis beïnvloedde zoals Archimedes de wereld had willen verplaatsen.

Staten zijn gedurende de afgelopen tweehonderd jaar van de moderne periode de norm geweest, maar in het langere verloop van de geschiedenis waren ze zeldzaam. Ze waren voor hun levensvatbaarheid altijd afhankelijk van uitzonderlijke megapolitieke omstandigheden. Vóór de moderne periode waren de meeste staten "oosterse despotieën", agrarische samenlevingen in woestijnen die afhankelijk waren van de controle over irrigatiesystemen. Zelfs het Romeinse Rijk was, via haar controle over Egypte en Noord-Afrika, indirect een hydraulische samenleving, maar niet genoeg om te overleven. Rome ontbeerde, net als de meeste premoderne staten, uiteindelijk de capaciteit om het geweldsmonopolie te handhaven, dat berust op de macht om mensen te kunnen uithongeren. De Romeinse staat kon het water voor landbouwgewassen buiten Afrika niet afsluiten door ongehoorzame mensen de toegang tot het irrigatiesysteem te ontzeggen. Geen enkele megapolitieke factor in de economie van de oudheid versterkte de macht van geweld zo sterk als de aanwezigheid van zulke hydraulische systemen. Wie in deze samenlevingen controle had over het water, kon middelen buitmaken op een bijna vergelijkbaar niveau als het percentage van de totale productie dat moderne natiestaten onttrekken.[^169]

### Grootte boven efficiëntie

Buskruit maakte het voor staten eenvoudiger om zich uit te breiden voorbij de grenzen van rijstvelden en droge rivierdalen. De aard van buskruitwapens en de opbouw van de industriële economie brachten flinke schaalvoordelen in de oorlogsvoering met zich mee. Dit leidde tot hoge én steeds verder toenemende opbrengsten van geweld. Zoals historicus Charles Tilly het verwoordde: '[S]taten met de meeste dwangmiddelen wonnen de oorlogen; efficiëntie (de verhouding tussen output en input) kwam op de tweede plaats na effectiviteit (totale output).'[^170] Aangezien regeringen zich vrijwel altijd op grote schaal organiseerden, hadden zelfs de weinige kleine soevereiniteiten, zoals Monaco of Andorra, de erkenning van de grotere staten nodig om hun onafhankelijkheid te waarborgen. Alleen grote overheden met een steeds grotere controle over middelen konden op het slagveld concurreren.

### De grote onbeantwoorde vraag

Dit brengt ons bij een van de grote onopgeloste raadsels van de moderne geschiedenis: waarom de Koude Oorlog, die volgde op het systeem van grote mogendheden, uiteindelijk communistische dictaturen tegenover democratische verzorgingsstaten plaatste. Dit vraagstuk is zo weinig onderzocht dat het voor velen zelfs aannemelijk leek toen een analist van het Amerikaanse ministerie van Buitenlandse Zaken, Francis Fukuyama, na de val van de Berlijnse Muur "het einde van de geschiedenis" uitriep. Het enthousiaste publiek dat zijn werk toejuichte, nam te veel als vanzelfsprekend aan. Blijkbaar hadden noch de auteur, noch vele anderen de fundamentele vraag gesteld: welke gemeenschappelijke kenmerken van staatssocialisme en democratische verzorgingsstaten maakten dat zij de laatste kandidaten voor wereldheerschappij werden?

Dit is een belangrijk vraagstuk. In de afgelopen vijf eeuwen zijn immers tientallen concurrerende soevereiniteitsstelsels gekomen en gegaan, waaronder absolute monarchieën, tribale enclaves, prins-bisdommen, direct pauselijk gezag, sultansrijken, stadstaten en wederdoperkolonies. Het is nu nauwelijks voor te stellen dat een ziekenhuisorganisatie, uitgerust met eigen strijdkrachten, eeuwenlang de macht over een land kon uitoefenen. Toch is er iets dergelijks gebeurd. Vanaf 1228 regeerde de Duitse Orde van het Sint-Mariaziekenhuis te Jeruzalem, later verenigd met de Zwaardbroeders van Lijfland, driehonderd jaar lang over Oost-Pruisen en diverse gebieden in Oost-Europa, waaronder delen van Litouwen en Polen. Toen kwam de Buskruitrevolutie. Binnen enkele decennia werd de Duitse Orde uit al hun gebieden verdreven en hun grootmeester had militair niet meer belang dan een schaakkampioen. Waarom? Waarom raakten zoveel andere soevereiniteitsvormen in verval, terwijl aan het einde van het Industriële Tijdperk de grote machtsstrijd om de wereldheerschappij werd uitgevochten tussen massademocratieën en staatssocialistische systemen?

### Onbelemmerde controle

Als onze theorie van de megapolitiek klopt, is het antwoord eenvoudig. Het is vergelijkbaar met de vraag waarom sumoworstelaars meestal dik zijn. Het antwoord is dat een magere sumoworstelaar, hoe indrukwekkend zijn verhouding tussen kracht en gewicht ook is, niet kan concurreren met een andere worstelaar die gigantisch is. Zoals Tilly stelt, ging het om "effectiviteit (totale output)", niet om "efficiëntie (de verhouding tussen output en input)". In een wereld die steeds gewelddadiger werd, domineerden de systemen die de beste toegang gaven tot middelen om op grote schaal oorlog te voeren.

Hoe werkte dat?

In het geval van het communisme is het antwoord duidelijk. Onder het communisme hadden degenen die de staat beheersten controle over vrijwel alles. Tijdens de Koude Oorlog kon de KGB de tandenborstel van burgers van de Sovjet-Unie afpakken als ze dat nuttig achtten. Ze hadden zelfs je tanden kunnen afpakken. Volgens geloofwaardige schattingen, die nog aannemelijker zijn geworden sinds de opening van voormalige Sovjetarchieven in 1992, namen de geheime politie en andere agenten van de late Sovjetstaat in vierenzeventig jaar tijd het leven van 50 miljoen mensen. Het staatssocialistische systeem kon vrijwel alles binnen haar grenzen mobiliseren voor haar leger, met weinig kans dat iemand daar bezwaar tegen zou maken.

In het geval van westerse democratieën ligt het minder voor de hand, deels omdat we geneigd zijn democratie scherp te contrasteren met het communisme. In termen van het Industriële Tijdperk waren de twee systemen inderdaad grote tegenpolen. Maar vanuit het perspectief van het Informatietijdperk hadden ze meer gemeen dan je zou denken. Beide maakten ongehinderde overheidscontrole mogelijk. Het verschil was dat de democratische verzorgingsstaat zelfs meer middelen in handen van de staat bracht dan de staatssocialistische systemen.

Dit is een duidelijk voorbeeld van het zeldzame verschijnsel waarbij minder juist meer is. Het staatssocialistische systeem ging uit van het idee dat de staat alles bezat. De democratische verzorgingsstaat daarentegen maakte meer bescheiden aanspraken. Dit creëerde betere prikkels waardoor een grotere productie kon gerealiseerd worden. In plaats van vanaf het begin alles op te eisen, lieten westerse regeringen individuen eigendom bezitten en rijkdom vergaren. Vervolgens, nadat die rijkdom was opgebouwd, begonnen de westerse natiestaten er een groot deel van te belasten. Onroerendgoedbelasting, inkomstenbelasting en hoge successierechten leverden de democratische verzorgingsstaat enorme hoeveelheden middelen op, vergeleken met wat de staatssocialistische systemen konden genereren.

### Inefficiëntie, waar het ertoe deed

Vergeleken met het communisme werkte de verzorgingsstaat inderdaad veel efficiënter. Echter, als je deze vergelijkt met andere systemen voor het vergaren van rijkdom, zoals een echte laissez‑faire‑enclave als _Hongkong_, bleek de verzorgingsstaat op dat gebied minder efficiënt te opereren. Opnieuw werd duidelijk: minder kan meer betekenen. Juist deze ogenschijnlijke inefficiëntie stelde de verzorgingsstaat tijdens de megapolitieke periode van het Industriële Tijdperk in staat zich te onderscheiden.

Wie doorgrondt waarom, ziet veel duidelijker wat de val van de Berlijnse Muur en het verdwijnen van het communisme echt inhouden. Het suggereerde niet dat de democratische verzorgingsstaat de toekomst had, maar eerder dat haar evenbeeld vredig aan ouderdom was gestorven. Dezelfde megapolitieke revolutie die het communisme heeft gedood, zal waarschijnlijk ook de democratische verzorgingsstaten, zoals we die in de twintigste eeuw hebben gekend, ondermijnen en vernietigen.

## Wie bestuurt de overheid?

Herkennen waar de controle over de democratische regering ligt, is de sleutel tot deze onconventionele conclusie. Dit is een vraagstuk dat minder eenvoudig is dan het lijkt. In de moderne tijd werd de vraag wie controle heeft over de overheid bijna altijd gesteld als een politieke vraag. Daarop zijn veel antwoorden gegeven, maar vrijwel altijd ging het om het identificeren van de politieke partij, groep of factie die op een bepaald moment de controle had over een bepaalde staat. Je hebt vast wel gehoord van overheden die werden bestuurd door kapitalisten, door arbeiders, door katholieken of door islamitische fundamentalisten, door tribale en raciale groepen, door Hutu's en door blanken. Je zult ook gehoord hebben van overheden bestuurd door beroepsgroepen, zoals advocaten of bankiers, of door buitenstedelijke belangen, door stedelijke machtsblokken en door mensen die in de buitenwijken wonen. En zeker zul je hebben gehoord van overheden bestuurd door politieke partijen, zoals de democraten, conservatieven, christendemocraten, liberalen, radicalen, republikeinen en socialisten.

Je hebt echter waarschijnlijk niet veel gehoord over een overheid die werd bestuurd door haar klanten. De economische historicus Frederic Lane legde in enkele van zijn heldere essays over de economische gevolgen van geweld die eerder aan bod kwamen de basis voor een nieuwe manier om te doorgronden waar de controle over een overheid ligt. Lane kwam op het idee om de overheid als een economische eenheid te beschouwen die bescherming verkoopt. Door de overheid in economische termen te analyseren in plaats van politieke, bedacht hij dat er drie fundamentele alternatieven zijn voor wie controle heeft over de overheid, elk met verschillende prikkels: eigenaren, werknemers en klanten.

### Eigenaren

In zeldzame gevallen, zelfs in de huidige tijd, leidt één eigenaar een overheid, meestal een heerser met erfopvolging, die feitelijk het land bezit. Zo beschouwt de sultan van Brunei de overheid van Brunei deels als privébezit. In de middeleeuwen kwam dit vaker voor, toen heren hun leengoed als privé-eigendom inzetten om hun inkomsten te maximaliseren.

Lane verwoordde de prikkels voor "de eigenaren van de productieonderneming" als volgt:

> "Om zijn winst te vergroten, zou hij proberen de kosten te drukken zonder de prijzen te verlagen. Hij zou, net als Hendrik VII van Engeland of Lodewijk XI van Frankrijk, goedkope trucs, of liever nog, zo goedkoop mogelijke middelen inzetten om zijn legitimiteit te bevestigen, de binnenlandse orde te handhaven en de aandacht van naburige vorsten af te leiden, zodat zijn eigen militaire uitgaven laag blijven. Hij behaalde winst door kostenverlagingen, door hogere heffingen die dankzij de kracht van zijn monopolie mogelijk waren, of door een combinatie van beide."[^171]

Overheden die door eigenaren worden bestuurd, hebben sterke prikkels om de kosten voor het bieden van bescherming of het monopoliseren van geweld in een bepaald gebied te drukken. Maar zolang hun heerschappij onbetwist blijft, vinden zij weinig reden om de prijs (belasting) die zij aan hun klanten vragen te verlagen tot onder het niveau dat de opbrengsten maximaliseert. Hoe hoger de prijs die een monopolist kan vragen en hoe lager zijn daadwerkelijke kosten, hoe groter de winst zal zijn. Het ideale fiscale beleid voor een door eigenaren beheerde regering leidt dan ook tot een forse winst. Wanneer overheden erin slagen hun inkomsten hoog te houden en tegelijkertijd hun uitgaven te beperken, heeft dat een grote invloed op het gebruik van middelen. Arbeid en andere waardevolle productiefactoren, die anders verspild zouden worden aan het leveren van onnodig dure bescherming, komen dan beschikbaar voor investeringen en andere doeleinden. Hoe meer winst de vorst boekt door kosten te drukken, hoe meer middelen er vrijkomen. Worden die middelen voor investeringen ingezet, stimuleren ze de economische groei. Zelfs wanneer ze enkel voor luxe-uitgaven worden ingezet, stimuleren ze toch de vorming van nieuwe markten die niet zouden ontstaan als de middelen waren verkwist aan inefficiënte "bescherming."

### Werknemers

Het is eenvoudig om de prikkels te typeren die overheersen bij overheden die door hun werknemers worden bestuurd. Het zijn vergelijkbare prikkels als in andere door werknemers geleide organisaties. Allereerst hebben door werknemers bestuurde organisaties de neiging elk beleid te steunen dat de werkgelegenheid vergroot en maatregelen af te wijzen die banen verminderen. Zoals Lane het formuleerde: "Wanneer werknemers de macht hadden, lag hun prioriteit niet bij het drukken van beschermingskosten en al helemaal niet het bij beperken van hun eigen loonlast. Het maximaliseren van de omvang van de organisatie had meer hun voorkeur."[^172] Een door werknemers bestuurde overheid zou zelden prikkels hebben om de kosten van de overheid of de prijs die aan hun klanten wordt berekend te verlagen. Wanneer men op sterke weerstand tegen de hoge prijzen stuit, zijn dit soort overheden echter geneigd om hun inkomsten te laten dalen tot onder het niveau van hun uitgaven in plaats van simpelweg minder uit te geven. Met andere woorden, deze prikkels zorgen voor een neiging tot chronische tekorten, in tegenstelling tot overheden die onder controle van eigenaren staan.

### Klanten

Zijn er voorbeelden van regeringen die door hun klanten werden gecontroleerd? Ja. Lane vond zijn inspiratie in steden als Venetië, waar kooplieden de macht hadden, en gebruikte dat om staatscontrole in economische termen te duiden. Daar had een groep groothandelaars, die bescherming nodig hadden, gedurende eeuwen effectief de controle over de overheid. Zij waren werkelijk klanten van de beschermingsdienst die de overheid leverde, geen eigenaars. Ze betaalden voor de dienst en probeerden niet te profiteren van hun controle over het geweldsmonopolie van de staat. Als sommigen dat toch deden, weerhielden andere klanten hen voor lange tijd ervan om dat nogmaals te doen. Andere voorbeelden van door klanten bestuurde overheden zijn democratieën en republieken met een beperkt kiesrecht, zoals de democratieën van de oudheid of de Amerikaanse republiek in haar beginperiode. In die tijd mochten alleen degenen die voor de overheid betaalden, ongeveer 10 procent van de bevolking, stemmen.

Overheden die door hun klanten worden bestuurd, hebben net als die van eigenaars de prikkel om hun operationele kosten zoveel mogelijk te beperken. Maar in tegenstelling tot overheden die door eigenaars of werknemers worden gecontroleerd, hebben regeringen die daadwerkelijk door hun klanten worden bestuurd ook de prikkel om de prijzen die zij rekenen laag te houden. Waar klanten de macht hebben, zijn overheden klein en doorgaans onopvallend, met lage bedrijfskosten, een minimaal aantal werknemers en lage belastingen. Een overheid onder controle van haar klanten stelt de belastingdruk niet in om de overheidsinkomsten te maximaliseren, maar om het resultaat van haar klanten te optimaliseren.

Zoals typische ondernemingen in concurrerende markten zou zelfs een monopolie dat door haar klanten wordt bestuurd, gedwongen worden om efficiënt te functioneren. Het zou geen belastingen kunnen heffen die de kosten met meer dan een minimale marge overschreden.

## De rol van democratie: kiezers als werknemers en klanten

Lane bekijkt de democratie op de traditionele manier en gaat ervan uit dat zij ervoor zorgt dat ondernemingen die geweld inzetten en produceren 'steeds meer onder de controle van hun klanten komen.'[^173] Dit is natuurlijk de politiek correcte conclusie, maar is dat wel zo? Wij twijfelen daar sterk aan. Kijk eens goed hoe moderne democratieën nu werkelijk functioneren.

In de eerste plaats missen ze de typische eigenschappen van competitieve markten waarin klanten de voorwaarden dicteren. Democratische regeringen besteden namelijk doorgaans slechts een fractie van hun totale uitgaven aan hun kerntaak: bescherming. In de Verenigde Staten besteden de deelstaten en lokale overheden bijvoorbeeld slechts 3,5 procent van hun totale uitgaven aan politie, rechtbanken en gevangenissen. Tel de militaire uitgaven daarbij op, en nog steeds gaat slechts ongeveer 10 procent van de inkomsten naar bescherming.

Een ander veelzeggend teken dat een massademocratie niet door haar klanten wordt bestuurd, is het feit dat het in de hedendaagse politieke cultuur, geërfd uit het Industriële Tijdperk, ondenkbaar zou zijn als beleid inzake cruciale kwesties werkelijk zou worden bepaald door de belangen van degenen die de rekeningen betalen. Stel je de verontwaardiging voor als een Amerikaanse president of een Britse premier zou voorstellen om de groep burgers die het merendeel van de belastingen betaalt, te laten beslissen welke overheidsprogramma's moeten doorgaan en welke groepen ambtenaren ontslagen zouden moeten worden. Zo'n handelwijze zou indruisen tegen het fundamentele beeld van wat een overheid behoort te doen, meer dan wanneer ambtenaren de macht hadden om te bepalen wie extra belasting moest betalen.

Toch, als je erover nadenkt: wanneer klanten werkelijk aan het roer staan, zou het juist schandalig worden gevonden als zij niet zouden krijgen wat ze willen. Als je een winkel binnen zou lopen om meubels te kopen, en de verkopers zouden je geld aannemen maar vervolgens negeren ze je verzoeken en zouden anderen raadplegen over hoe jouw geld moest worden besteed, zou je terecht verontwaardigd zijn. Je zou het ook niet normaal of gerechtvaardigd vinden als de werknemers van de winkel zouden betogen dat jij de meubels eigenlijk niet verdient, en dat deze in plaats daarvan moeten worden geleverd aan iemand die zij meer geschikt achten. Het feit dat iets zeer vergelijkbaars gebeurt in de omgang met de overheid, laat zien hoe weinig controle haar "klanten" in werkelijkheid hebben.

Hoe je het ook bekijkt, de kosten van democratische regeringen lopen volledig uit de hand, in schril contrast met de omstandigheden in competitieve markten, waar klanten de aanbieders dwingen efficiënt te werken. De meeste democratieën kampen met structurele begrotingstekorten. Dit is kenmerkend voor een fiscaal beleid dat voortkomt uit de controle van de werknemers. Overheden blijken bijzonder terughoudend als het gaat om het snijden in hun operationele kosten. Wereldwijd horen we vrijwel altijd de klacht dat het erg moeilijk is om eenmaal ingevoerde politieke programma's te stoppen. Ambtenaren ontslaan blijkt vrijwel onmogelijk. Sterker nog, een van de belangrijkste voordelen van de privatisering van functies, die voorheen door de staat werden uitgevoerd, is dat particuliere controle het veel eenvoudiger maakt om overbodige banen te schrappen. Van Groot-Brittannië tot Argentinië laten nieuwe particuliere managers vaak 50 tot 95 procent van de voorheen door de staat tewerkgestelde werknemers gaan.

Bedenk ook hoe de fiscale voorwaarden voor de beschermingsdienst van de overheid worden bepaald. Je zult niet snel invloeden van competitie vinden wanneer je de belastingtarieven analyseert. Zelfs de sporadische discussies over belastingverlaging die de afgelopen jaren in het politieke debat aan bod kwamen, tonen aan hoe ver een democratische overheid doorgaans van controle door haar klanten is verwijderd. Voorstanders van lagere belastingen betoogden soms dat de overheidsinkomsten juist zouden stijgen, omdat de tarieven voorheen zo hoog waren dat ze economische activiteit ontmoedigden.

De afweging die zij doorgaans wilden benadrukken, ging niet over concurrentie tussen jurisdicties, maar over iets veel verbazingwekkenders. Ze stelden niet dat de tarieven in de Verenigde Staten of Duitsland niet hoger mochten zijn dan 15 procent, omdat de belastingtarieven in Hongkong ook slechts 15 procent waren. Integendeel, debatten over de belastingdruk gingen er meestal van uit dat de afweging voor de belastingbetaler niet lag tussen zaken doen in de ene jurisdictie of in een andere, maar tussen zaken doen tegen draconische tarieven of een vakantie nemen. Er werd gezegd dat productieve individuen die aan roofzuchtige belastingen onderworpen waren, hun werk zouden neerleggen en gaan golfen als hun belastingdruk niet werd verlicht.

Het feit dat zo'n argument zelfs kon ontstaan, laat zien hoe ver de tarieven voor bescherming, die door democratische verzorgingsstaten worden opgelegd, verwijderd zijn van een competitief uitgangspunt. De voorwaarden van progressieve inkomstenbelasting, die in de loop van de twintigste eeuw in elke democratische verzorgingsstaat ontstonden, wijken dramatisch af van prijsbepalingen die door klanten zouden worden geprefereerd. Het verschil valt op wanneer men belastingen voor een beschermingsmonopolie afzet tegen de tarieven van telefoondiensten, die tot voor kort overal monopolistisch waren. Klanten zouden moord en brand schreeuwen als een telefoonbedrijf probeerde te factureren op dezelfde basis als waarop inkomstenbelastingen worden geheven. Stel dat het telefoonbedrijf een rekening van €50.000 stuurt voor een gesprek naar Londen, alleen omdat je toevallig tijdens dat gesprek een deal van €125.000 had gesloten. Noch jij, noch een andere klant met gezond verstand zou dat betalen. Maar dat is precies de basis waarop inkomstenbelastingen in elke democratische verzorgingsstaat worden geheven.

Wanneer je goed kijkt naar de manier waarop industriële democratieën hebben geopereerd, is het logischer om ze te beschouwen als een vorm van overheid die door haar werknemers wordt bestuurd. Als je massademocratie ziet als een door ambtenaren bestuurde overheid, wordt duidelijk waarom beleidsveranderingen zo lastig zijn. De overheid lijkt in veel opzichten bestuurd ten voordele van de werknemers. Zo lijken openbare ­scholen in de meeste democratische landen chronisch slecht te functioneren, en zonder zicht op verbetering. Als de klanten werkelijk aan het roer stonden, zouden ze het gemakkelijker vinden om nieuwe beleidsrichtingen uit te zetten. Degenen die voor de democratische overheid betalen, bepalen zelden de voorwaarden van de overheidsuitgaven. In feite is de overheid een coöperatief systeem dat geen privé-eigendom heeft en zich gedraagt als een natuurlijk monopolie. Prijzen houden weinig verband met kosten. De kwaliteit van de dienstverlening is over het algemeen laag in vergelijking met die in de private sector. Klachten van klanten zijn moeilijk te verhelpen. Kortom, massademocratie leidt tot controle over de overheid door haar "werknemers."

Maar wacht. Je zou kunnen zeggen dat er in de meeste jurisdicties veel meer kiezers zijn dan mensen op de loonlijst van de overheid. Hoe zou het onder zulke omstandigheden mogelijk zijn dat werknemers domineren? Dit probleem werd opgelost door het ontstaan van de verzorgingsstaat. Om het aantal werknemers aan te vullen tot een werkbare meerderheid, werden steeds meer kiezers praktisch op de loonlijst geplaatst door ze allerlei vormen van staatssteun te geven. In feite werden de ontvangers van uitkeringen en subsidies pseudo-werknemers van de overheid, die zich konden ontdoen van het gedoe om dagelijks op het werk te verschijnen. Het was een resultaat dat werd bepaald door de megapolitieke logica van het Industriële Tijdperk.

Wanneer de omvang van het dwingende instituut belangrijker is dan de efficiënte inzet van middelen, zoals het geval was vóór 1989, is het vrijwel onmogelijk dat de meeste overheden door hun klanten worden bestuurd. Zoals het voorbeeld van de late Sovjet-Unie zo duidelijk aantoonde, was het tot een paar jaar geleden mogelijk voor staten om grote macht in de wereld uit te oefenen, zelfs terwijl ze op enorme schaal middelen verspilden. Wanneer de opbrengsten van geweld hoog en stijgend zijn, telt omvang meer dan efficiëntie. Grotere entiteiten hebben dan de neiging om te winnen van kleinere. De overheden die effectiever zijn in het mobiliseren van militaire middelen, zelfs als dat verspilling betekent, hebben dan de neiging te zegevieren boven degenen die hun middelen efficiënter gebruiken.

Denk eens na over wat dit betekent. Het impliceert onontkoombaar dat wanneer omvang belangrijker is dan efficiëntie, overheden die door hun klanten worden bestuurd, niet kunnen zegevieren en vaak ook niet kunnen overleven. Onder zulke omstandigheden zullen de entiteiten die militair het meest effectief zijn degenen zijn die de meeste middelen voor oorlog kunnen opeisen. Echter, regeringen die echt worden bestuurd door hun betalende klanten, zouden waarschijnlijk niet onbeperkt middelen van iedereen kunnen afromen

Klanten wensen normaal gesproken dat de prijzen die zij voor een product of dienst betalen, inclusief voor bescherming, worden verlaagd en onder controle worden gehouden. Als de westerse democratieën tijdens de Koude Oorlog onder controle van de klant hadden gestaan, zou dat alleen al hun militaire slagkracht hebben verminderd, doordat het vrijwel zeker de toevoer van middelen naar de overheid zou hebben ingeperkt. Vergeet niet dat in situaties waarin klanten heersen, zowel de prijzen als de kosten nauwlettend beheerst dienen te worden. Maar dit is nauwelijks wat er gebeurde. De verzorgingsstaten waren absolute winnaars van de uitgavenwedstrijd tijdens de Koude Oorlog. Analisten van diverse achtergronden stelden dat hun overwinning mede te danken was aan hun capaciteit om zoveel geld uit te geven dat de Sovjet-Unie in financiële problemen kwam.

Precies dit feit benadrukt hoe de inefficiënties van de democratie haar op megapolitiek niveau dominant maakten tijdens een periode geweld steeds meer opleverde. Massale militaire uitgaven vormen, met al hun verspilling, duidelijk een suboptimale inzet van kapitaal voor het opbouwen particuliere welvaart. We suggereerden eerder dat, hoewel verzorgingsstaten economisch efficiënter waren in vergelijking tot socialistische overheidssystemen, ze veel minder efficiënt zijn voor het creëren van rijkdom dan laissez-faire enclaves, zoals Hongkong. Ironisch genoeg was het juist deze inefficiëntie, vergeleken met een minder belemmerd vrijemarktsysteem, die de democratische verzorgingsstaat succesvol maakte onder de megapolitieke omstandigheden van het industrialisme.

Hoe werd democratische inefficiëntie een succesfactor tijdens het Tijdperk van Geweld? De sleutel tot het ontrafelen van deze schijnbare paradox ligt in het erkennen van twee punten:

1. Succes voor een soevereiniteit in de moderne periode lag niet in het creëren van rijkdom, maar in het creëren van een militaire macht die in staat was overweldigend geweld tegen elke andere staat in te zetten. Geld was nodig om dat te doen, maar geld zelf kon een veldslag niet winnen. De uitdaging was niet om een systeem met de efficiëntste economie of de hoogste groeisnelheid te creëren, maar een systeem dat meer middelen kon onttrekken om het vervolgens in het leger te kanaliseren. Militaire uitgaven zijn van nature een kostenpost waarvan de financiële opbrengsten op zichzelf laag of afwezig zijn.
2. De gemakkelijkste manier om toestemming te krijgen voor het investeren van geld in activiteiten met weinig of geen direct financieel rendement, zoals belastingbetalingen, is om toestemming te vragen aan iemand anders dan de persoon die het zal moeten opbrengen. Een van de manieren waarop de Nederlanders Manhattan konden kopen voor drieëntwintig dollar aan kralen, was dat de specifieke indianen aan wie ze het aanbod deden, het eigenlijk niet bezaten. "Getting to yes", zoals de marketingmensen zeggen, is onder die voorwaarden veel gemakkelijker. Stel bijvoorbeeld dat wij als auteurs van dit boek niet zouden willen dat u de kaftprijs, maar 40 procent van uw jaarlijkse inkomen zou betalen voor een exemplaar. We zouden veel eerder toestemming krijgen als we het aan iemand anders zouden vragen, en u niet zelf zouden hoeven te benaderen. Sterker nog, we zouden veel overtuigender kunnen zijn als we zouden kunnen vertrouwen op de instemming van meerdere mensen die u zelfs niet kent. We zouden een ad-hocverkiezing kunnen houden, wat H. L. Mencken, met minder overdrijving dan hij misschien dacht, beschreef als "een geavanceerde veiling van gestolen goederen." En om het voorbeeld realistischer te maken, zouden we ermee kunnen instemmen om een deel van het door u betaalde geld te delen met deze anonieme omstanders in ruil voor hun steun.

Dat is de rol die de moderne democratische verzorgingsstaat is gaan vervullen. Het was een onovertroffen systeem in het Industriële Tijdperk omdat het zowel efficiënt als inefficiënt was waar het ertoe deed. Het combineerde de efficiëntie van particulier bezit en prikkels voor het creëren van rijkdom met een mechanisme dat in wezen onbelemmerde toegang tot die rijkdom faciliteerde. Democratie hield de portemonnees van welvaartsproducenten open. Het kende militair succes in de periode waarin het rendement van geweld wereldwijd op zijn hoogtepunt was, juist omdat het het voor klanten moeilijk maakte om de belastingen die de overheid inde, of andere manieren om middelen voor het leger te financieren, zoals inflatie, te beperken.

### Waarom klanten niet konden domineren

In de moderne periode waren degenen die voor "bescherming" betaalden niet in staat hun middelen te onthouden van de soeverein, zelfs niet in gezamenlijk verzet, omdat dit enkel zou hebben geleid tot overheersing door andere, mogelijk nog vijandigere staten. Dit was een duidelijke overweging tijdens de Koude Oorlog. De klanten, of belastingbetalers, die een onevenredig groot deel van de kosten van de overheid in de leidende westerse industriële staten droegen, hadden geen mogelijkheid om hoge belastingen te weigeren. Het resultaat zou zijn geweest dat zij zichzelf zouden blootstellen aan totale confiscatie door de Sovjet-Unie of een andere agressieve groep met de macht om geweld te organiseren.

### Industrialisme en democratie

Op langere termijn zou de massademocratie wel eens achterhaald idee kunnen blijken te zijn dat het einde van het Industriële Tijdperk niet lang zal overleven. Zeker is dat massademocratie en de natiestaat samen opkwamen met de Franse Revolutie aan het einde van de achttiende eeuw, waarschijnlijk als reactie op een stijging van het reële inkomen. Rond 1750 begonnen de inkomens in West-Europa in snel tempo te stijgen, deels als gevolg van warmer weer. Dit viel samen met een periode van technologische innovatie die de geschoolde arbeid van ambachtslieden verdrong door machines die bediend konden worden door ongeschoolde arbeiders, zelfs vrouwen en kinderen. Deze nieuwe industriële apparatuur verhoogde de lonen van ongeschoolde arbeiders, waardoor de inkomensverdeling gelijker werd.

Het cruciale keerpunt van de revolutie was wellicht niet, zoals vaak wordt gedacht, het merkwaardige idee dat mensen geneigd zijn in opstand te komen wanneer de omstandigheden verbeteren. Belangrijker was mogelijk het feit dat toen de inkomens een bepaald niveau hadden bereikt, het voor de vroegmoderne staat eindelijk praktisch werd om de particuliere tussenpersonen en machtige magnaten, met wie eerder over middelen werd onderhandeld, te omzeilen en over te stappen op een systeem van "directe heerschappij", waarin een nationale overheid rechtstreeks zaken deed met individuele burgers, hen tegen steeds hogere tarieven belastte en slecht gecompenseerde militaire dienst eiste in ruil voor de verstrekking van diverse voordelen.[^174]

Omdat de opkomende middenklasse in relatief korte tijd genoeg geld had verzameld om te belasten, was het voor de heersers niet langer essentieel, zoals voorheen wel het geval was, om te onderhandelen met machtige grondbezitters of kooplieden die, zoals de historicus Charles Tilly schreef, "in staat waren om de vorming van een machtige staat te verhinderen" die "hun bezittingen in beslag zou nemen en hun transacties zou inperken."[^175] Je kunt duidelijk zien waarom regeringen succesvoller middelen konden onttrekken van de maatschappij toen zij te maken kregen met miljoenen individuele burgers, in plaats van met een handjevol heren, hertogen, graven, bisschoppen, huurlingen, vrije steden en andere semi-soevereine entiteiten met wie de heersers van Europese staten zich vóór het midden van de achttiende eeuw genoodzaakt zagen te onderhandelen.

Stijgende reële inkomens stelden regeringen in staat een strategie te hanteren die meer middelen onder hun controle bracht. Kleine bedragen die via belastingen van miljoenen werden geïnd, konden meer inkomsten opleveren dan grotere sommen die door enkele machtigen werden betaald. Bovendien was het veel makkelijker om met de velen om te gaan dan met de enkelen, die over het algemeen onwillig waren hun geld af te staan en veel beter in staat waren zich te verzetten.

De doorsnee boer, kleine koopman of arbeider beschikte immers over verwaarloosbaar weinig middelen in vergelijking met de staat zelf. Het was aan de vooravond van de Franse Revolutie voor een doorsnee particulier in West-Europa volstrekt onmogelijk om succesvol met de staat te onderhandelen over het verlagen van zijn belastingtarief, of om een doeltreffend verzet te organiseren tegen overheidsplannen en -beleid die zijn belangen bedreigden. Maar dit is precies wat machtige particuliere magnaten eeuwenlang hadden gedaan en zouden blijven doen. Zij boden daadwerkelijk weerstand en onderhandelden met heersers, waardoor hun vermogen om middelen op te eisen werd ingeperkt.

> "Oorlogsvoering versnelde de overgang van indirect naar direct bestuur. Vrijwel elke staat die oorlog voert ontdekt dat hij de inspanning niet kan bekostigen uit zijn opgebouwde reserves en lopende inkomsten. Bijna alle oorlogvoerende staten lenen grootschalig, verhogen belastingen en eisen de middelen voor de strijd, inclusief mannen, op van onwillige burgers die hun middelen liever anders aanwenden."[^176] -- Charles Tilly

Het voorbeeld van Polen in het midden van de achttiende eeuw illustreert dit perfect. In 1760 telde het Poolse nationale leger achttienduizend soldaten. Dit was een magere strijdmacht vergeleken met de legers van de naburige machthebbers in Oostenrijk, Pruisen en Rusland, van wie het kleinste staande leger al zo'n 100.000 man telde. In feite was het Poolse nationale leger in 1760 zelfs klein in vergelijking met andere eenheden binnen Polen. De gezamenlijke strijdkrachten van de Poolse adel telden dertigduizend man.[^177]

Als de Poolse koning de mogelijkheid had gehad om direct belasting te heffen bij miljoenen individuele Polen, in plaats van afhankelijk te zijn van de bijdragen van de invloedrijke Poolse magnaten, zou de centrale overheid ongetwijfeld aanzienlijk hogere inkomsten hebben kunnen verwerven en dus een omvangrijker leger hebben kunnen financieren.

Ten opzichte van individuele burgers, die niet de mogelijkheid hadden om collectief met miljoenen tegelijk op te treden, bleken centrale autoriteiten overal onoverwinnelijk machtig. De koning van Polen had in 1760 echter niet de mogelijkheid zijn burgers rechtstreeks te belasten. Hij moest zijn toevlucht nemen tot de heren, rijke kooplieden en andere notabelen, die een kleine, hechte groep vormden. Zij hadden wél de mogelijkheid om gezamenlijk op te treden om de koning ervan te weerhouden hun middelen zonder hun toestemming op te eisen. Aangezien de Poolse adel over veel meer troepen beschikte dan hijzelf, stond de koning niet sterk genoeg om zijn zin door te duwen.

Uiteindelijk bleek dit militaire nadeel, het onvermogen om de rijken en machtigen te omzeilen bij het vergaren van middelen, doorslaggevend in het Tijdperk van Geweld. Binnen enkele jaren hield Polen op te bestaan als onafhankelijke staat. Het werd veroverd door Oostenrijk, Pruisen en Rusland, drie landen met legers die elk vele malen groter waren dan de kleine Poolse strijdmacht. In elk van die landen hadden de heersers manieren gevonden om de mogelijkheden van rijke kooplieden en de adel om hun middelen te beschermen te omzeilen.

### Na de Franse Revolutie

De Franse Revolutie leidde tot een nog grotere toename van de omvang van legers, een feit dat de kracht van de democratische strategie aantoonde in een periode waarin het rendement van geweld toenam. De afspraak die regeringen vanaf de Franse Revolutie maakten, was om een ongekende mate van betrokkenheid in het leven van gewone mensen te bieden, in ruil voor hun deelname aan oorlogen, in plaats van huurlingen, en het belasten van een steeds groter deel van hun stijgende inkomens. Zoals Tilly zei:

> "De reikwijdte van de staat breidde zich ver buiten het militaire kerngebied uit, en haar burgers begonnen aanspraken te maken op een zeer breed scala aan bescherming, rechtspraak, productie en distributie. Naarmate nationale wetgevers hun bereik ver voorbij het goedkeuren van belastingen uitbreidden, werden ze geconfronteerd met eisen van alle goed georganiseerde belangengroepen die door de staat werden geraakt of geraakt konden worden. Direct bestuur en massale nationale politiek groeiden samen en versterkten elkaar."[^178]

Dezelfde logica die in de achttiende eeuw gold, bleef gelden tot 1989, toen de Berlijnse Muur viel. Naarmate het Industriële Tijdperk vorderde, bleven de inkomens voor ongeschoold werk stijgen, waardoor massademocratie een nog effectievere methode werd om de onttrekking van middelen te optimaliseren. Als gevolg hiervan groeide de overheid voortdurend, met jaarlijks gemiddeld ongeveer een half procent extra belasting op het inkomen in een gemiddeld industrieel land gedurende de twintigste eeuw.

Tijdens het Industriële Tijdperk voorafgaand aan 1989 kwam democratie naar voren als de meest effectieve regeringsvorm op militair vlak, juist omdat democratie het moeilijk of onmogelijk maakte om effectieve grenzen te stellen aan de confiscatie van middelen door de staat. De ruime invoering van sociale voorzieningen aan iedereen nodigde een meerderheid van de kiezers uit om feitelijk ambtenaar van de overheid te worden. Dit werd het overheersende politieke kenmerk van alle leidende industriële landen, omdat kiezers een onvoldoende sterke positie hadden om hun rol als klant voor bescherming te vervullen. Niet alleen stonden ze tegenover de agressieve dreiging van communistische systemen, die grote middelen voor militaire doeleinden konden genereren omdat de staat de gehele economie beheerde, maar echte controle over de overheid was als belastingbetaler ook om een andere reden onpraktisch.

Miljoenen gewone burgers kunnen niet effectief samenwerken om hun belangen te beschermen. Omdat de obstakels voor hun samenwerking groot zijn en het verdedigen van de gemeenschappelijke belangen van de groep op individueel niveau weinig oplevert, zullen miljoenen gewone burgers minder succesvol het hoofd kunnen bieden tegen de overheid als dat kleinere groepen met gunstigere prikkels dat kunnen.

Andere dingen gelijk, zou je dus verwachten dat een groter deel van de totale middelen door de overheid wordt opgeëist in een massademocratie dan in een oligarchie of in een systeem van gefragmenteerde soevereiniteit waar magnaten militaire macht hadden en hun eigen legers op de been brachten, zoals dat overal in het vroegmoderne Europa vóór de achttiende eeuw het geval was.

Een cruciale, zij het zelden onderzochte reden voor de groei van democratische overheden in de westerse wereld is dus het relatieve belang van onderhandelingskosten tijdens een periode waarin geweld steeds meer loonde. Het kostte gewoon meer om middelen bij enkelen te halen dan bij velen.

Een relatief kleine elitegroep van rijken vormt een coherenter en effectiever geheel dan een grote massa burgers. De kleine groep heeft sterkere prikkels om samen te werken. Zij zal bijna onvermijdelijk succesvoller zijn in het beschermen van haar belangen dan een grote massa.[^179] En zelfs als de meeste leden van de groep ervoor kiezen niet samen te werken aan een gezamenlijke actie, kunnen een paar rijken genoeg middelen inzetten om het werk gedaan te krijgen.

Met democratische besluitvorming kon de natiestaat veel vollediger macht uitoefenen over miljoenen personen, die niet gemakkelijk konden samenwerken om collectief hun belangen te verdedigen, terwijl een kleinere groep de organisatorische hindernissen gemakkelijker kon overwinnen en zo hun geconcentreerde belangen kon beschermen. Democratie bood het extra voordeel van een gelegitimeerd besluitvormingsmechanisme, waarmee de staat toegang kreeg tot de middelen van de rijken zonder dat hun directe instemming nodig was. Het vulde de natiestaat aan omdat het de concentratie van militaire macht in de handen van de machthebbers vergemakkelijkte, in een tijd waarin de omvang van de ingezette kracht belangrijker was dan de efficiëntie van de mobilisatie.

De Franse Revolutie bewees dit duidelijk. Doordat het de omvang van de militaire macht op het slagveld vergrootte, hadden andere concurrerende natiestaten weinig andere keuze dan een vergelijkbare organisatie na te streven, waarvan de legitimiteit uiteindelijk verbonden werd aan democratische besluitvorming. Samengevat: de democratische natiestaat slaagde in de afgelopen twee eeuwen om deze verborgen redenen:

1. Geweld loonde steeds meer, waardoor de schaal van de macht belangrijker werd als bestuursprincipe dan efficiëntie.
2. Inkomens stegen voldoende boven het bestaansminimum, waardoor de staat de mogelijkheid kreeg om grote hoeveelheden aan middelen te innen zonder te hoeven onderhandelen met machtige magnaten die weerstand konden bieden.
3. Democratie bleek voldoende verenigbaar met de werking van vrije markten om het toenemen van de welvaart vol te kunnen houden.
4. Democratie faciliteerde een dominante overheid, bestuurd door haar "werknemers", waardoor het moeilijk werd de uitgaven, inclusief militaire uitgaven, te beperken.
5. Democratische besluiten bleken een effectief middel tegen het vermogen van de rijken om gezamenlijk op te treden tegen het vermogen van de natiestaat om belastingen te heffen of op andere manieren inbreuk te maken op hun eigendom.

Democratie werd de winnende militaire strategie omdat het het vergemakkelijkte om meer middelen in handen van de staat te brengen. In vergelijking met andere vormen van soevereiniteit die hun legitimiteit ontleenden aan andere principes, zoals de feodale heffing, het goddelijk recht van koningen, religieuze plicht of de vrijwillige bijdragen van de rijken, werd massademocratie militair de krachtigste, omdat het de meest zekere manier was om middelen te verzamelen in een industriële economie.

> "De natie, als een cultureel gedefinieerde gemeenschap, is de hoogste symbolische waarde van de moderniteit; ze is gezegend met een quasi-heilig karakter dat alleen door religie wordt geëvenaard. In feite is dit quasi-heilige karakter afgeleid van religie. In de praktijk is de natie ofwel de moderne, seculiere vervanger van religie geworden, of haar machtigste bondgenoot. In de moderne tijd worden de gemeenschapsgevoelens die door de natie worden opgewekt hoog gewaardeerd en gezocht als basis voor groepsloyaliteit... Dat de moderne staat hier vaak de begunstigde van is, hoeft nauwelijks te verbazen, gezien haar opperste macht."[^180] -- Joseph R. Llobera

### Nationalisme

Veel van hetzelfde kan gezegd worden van nationalisme, dat een uitvloeisel werd van massademocratie. Staten die nationalisme konden inzetten, ontdekten dat ze grotere legers tegen lagere kosten konden mobiliseren. Nationalisme was een uitvinding die het voor een staat mogelijk maakte om haar militaire effectiviteit op te schalen. Net als de politiek zelf is nationalisme grotendeels een moderne uitvinding. Zoals socioloog Joseph Llobera in zijn rijk gedocumenteerde boek over de opkomst van nationalisme heeft aangetoond, is de natie een ingebeelde gemeenschap die in grote mate tot stand kwam als een manier om staatsmacht te mobiliseren tijdens de Franse Revolutie. Zoals hij stelt: "In de moderne betekenis van de term bestaat nationaal bewustzijn pas sinds de Franse Revolutie, sinds het moment waarop in 1789 de Grondwetgevende Vergadering het volk van Frankrijk gelijkstelde met de Franse natie."[^181]

Nationalisme maakte het eenvoudiger om macht te mobiliseren en controle uit te oefenen over grote aantallen mensen. Natiestaten werden gevormd door het benadrukken van kenmerken die mensen gemeen hadden, met name de gesproken taal. Dit vergemakkelijkte heerschappij zonder tussenkomst van tussenpersonen. Het vereenvoudigde de taken van de bureaucratie. Besluiten die slechts in één taal hoefden te worden uitgevaardigd, konden sneller en met minder verwarring worden verspreid dan degenen die vertaald moesten worden in alle talen van de toren van Babel. Nationalisme maakte het dus goedkoper om grotere gebieden te beheersen. Voor het nationalisme had de vroegmoderne staat de hulp nodig van heren, hertogen, graven, bisschoppen, vrije steden en andere corporatieve en etnische tussenpersonen, van belastingpachters tot militaire leveranciers en huurlingen, om inkomsten te innen, troepen te werven en andere overheidstaken uit te voeren.

Nationalisme was ook doorslaggevend voor het verlagen van de kosten voor het mobiliseren van militair personeel door groepsidentificatie met de belangen van de staat aan te moedigen. Er was zo'n aanzienlijk voordeel te behalen door groepsgevoel te koppelen aan de belangen van de staat dat de meeste staten, zelfs de zogenaamd internationalistische Sovjet-Unie, op nationalisme uitkwamen als aanvullende ideologie.

In een langere historische context is nationalisme net zo goed een anomalie als de staat zelf. Zoals historicus William McNeill heeft gedocumenteerd, waren poly-etnische soevereiniteiten vroeger de norm.[^182]

In McNeill's woorden: "Het idee dat een overheid alleen rechtmatig over burgers van een enkele ethnos zou moeten heersen, begon zich tegen het einde van de Middeleeuwen in West-Europa te ontwikkelen."[^183] Een vroege nationalistische entiteit was de Pruisische Liga (Preußischer Bund), die in 1440 werd gevormd als verzet tegen het bewind van de Duitse Orde. Sommige kenmerken van de orde zijn eerder genoemd als een uiterst voorbeeld van een soevereiniteit die niet leek op de natiestaat. De Duitse Orde was een soort gecharterde onderneming waarvan bijna geen enkel lid afkomstig was uit Pruisen. Het hoofdkwartier verschoof in de loop der tijd van Bremen en Lübeck naar Jeruzalem, Akko, Venetië en uiteindelijk Marienberg aan de Wisła. Op een bepaald moment bestuurde zij zelfs het district Burzenland in Transsylvanië. Het is dan ook niet verrassend dat een soevereiniteit die zo weinig leek op een staat het voorwerp werd van een van de eerste pogingen om nationaal gevoel te mobiliseren als factor in de organisatie van macht. Het volgende laat echter zien hoe anders het vroege nationalisme was ten opzichte van latere varianten: de Duitstalige edelen van de Pruisische Liga verzochten de koning van Polen om Pruisen onder Pools gezag te plaatsen, grotendeels omdat de Poolse koning toen een relatief zwakke monarch was waarvan niet verwacht werd dat hij met dezelfde strengheid zou regeren als de Duitse Orde.

Nationalisme, in zijn vroege verschijningsvormen, kwam net voor de Buskruitrevolutie op. Het bleef groeien naarmate de vroegmoderne staat zich verder ontwikkelde, en werd erg belangrijk ten tijde van de Franse Revolutie. Volgens ons heeft het nationalisme als krachtig idee zijn terugtocht al ingezet. Het bereikte waarschijnlijk zijn hoogtepunt met Woodrow Wilsons poging om aan elk etnisch volk in Europa een eigen staat toe te wijzen na afloop van de Eerste Wereldoorlog. Tegenwoordig is het een reactionaire kracht, aangewakkerd in regio's met dalende inkomens en teruglopende vooruitzichten, zoals Servië.

Zoals we later zullen bespreken, verwachten wij dat nationalisme een belangrijk onderwerp zal worden waar mensen met weinig vaardigheden, nostalgisch naar dwang, zich achter zullen scharen wanneer de welvaartsstaat instort in de westerse democratieën. Wat je nu al hebt ervaren, stelt nog niets voor. Voor de meeste mensen in het Westen leek de ondergang van het communisme relatief onschuldig. Je hebt een daling van militaire uitgaven gezien, een instorting van de aluminiumprijzen, en een nieuwe bron van ijshockeyspelers voor de NHL. Dat is het goede nieuws. Nieuws dat de meeste mensen die in de twintigste eeuw volwassen werden, konden toejuichen, zeker als ze fan waren van ijshockey. Het grootste deel van het nieuws dat minder populair zal blijken, moet nog komen.

Nu het Industriële Tijdperk tot zijn einde komt, houden de megapolitieke omstandigheden die democratie mogelijk maakten snel op te bestaan. Daarom is het twijfelachtig dat massademocratie en de verzorgingsstaat lang zullen overleven in de nieuwe megapolitieke omstandigheden van het Informatietijdperk.

> "Het Congres was geen tempel van de democratie, maar een markt om wetten te verhandelen." -- Alberto Fujimori, president van Peru

Toekomstige historici zouden zelfs kunnen melden dat we de eerste postmoderne staatsgreep al hebben gezien, de opmerkelijke verzegeling van het congres in Peru in 1993. Dit was nauwelijks een gebeurtenis die veel aandacht trok in de leidende industriële democratieën. Maar het zou achteraf belangrijker kunnen blijken dan conventionele analisten vermoeden. De weinigen die erover nadachten, zagen het vooral als nog een machtsgreep van het soort dat Latijns-Amerika doorheen de geschiedenis treurig genoeg al vaak heeft gekend. Wij zien het echter mogelijk als de eerste stap richting de delegitimering van een bestuursvorm waarvan de onmiddellijke megapolitieke bestaansreden met de overgang naar het Informatietijdperk is beginnen te verdwijnen. Fujimori's sluiting van het congres is een symptoom van de uiteindelijke waardevermindering van politieke beloften. Een soortgelijk lot kan andere parlementen te wachten staan zodra hun krediet is uitgeput.

De technologische verschuiving die het industrialisme ondermijnt, heeft veel landen opgescheept met regeringen die niet langer functioneren, of slecht functioneren. Vooral parlementen lijken steeds disfunctioneler te worden. Ze produceren wetten die vijftig jaar geleden misschien slechts dom waren, maar die vandaag de dag gevaarlijk zijn. Dit was spectaculair duidelijk in Peru, waar de interne soevereiniteit van de staat tegen 1993 vrijwel ingestort was.

> "Aanvallen, ontvoeringen, verkrachtingen en moorden gingen hand in hand met steeds agressiever rijgedrag en onveilige straten. De politie heeft geleidelijk de controle over de situatie verloren en sommige van haar leden zijn betrokken geraakt bij schandalen en doorgewinterde criminelen geworden... Mensen zijn geleidelijk gewend geraakt om buiten de wet te leven. Diefstal, illegale inbeslagnames en fabrieksbezettingen zijn alledaagse verschijnselen geworden."[^184] -- Hernando De Soto

### Peru in ruïnes

In zekere zin was Peru in 1993 geen moderne natiestaat meer. Het had nog een vlag en een leger, maar de meeste instituties lagen in puin. Zelfs de gevangenissen waren overgenomen door de gedetineerden. Deze desintegratie kent meerdere oorzaken, maar de meeste verklaringen van deskundigen missen de kern. Peru viel namelijk al vroeg ten prooi aan de technologische veranderingen die gesloten economieën disfunctioneel maken en de centrale autoriteit ondermijnen. Bovendien verergeren deze megapolitieke spanningen wanneer besluitvormingsorganen, zoals het Peruaanse congres, door perverse prikkels worden gedwongen de problemen eigenlijk te verergeren in plaats van op te lossen.

De representatieve democratie in Peru was te vergelijken met een paar valse dobbelstenen. Democratie was ongeëvenaard als middel om staatsmacht uit te breiden, maar toen veranderende omstandigheden een verandering van de macht eisten, werden de eigenschappen die haar in de oude megapolitieke context zo succesvol hadden gemaakt, een bron van toenemend disfunctioneren. De wetten die het congres aannam, verzwakten razendsnel elk fundament voor waarde en respect voor de wet. Zoals de Soto in _The Other Path_ verwoordt: 'Kleine belangengroepen ruziën met elkaar, veroorzaken faillissementen en beïnvloeden ambtenaren, overheden kennen privileges toe, en de wet wordt ingezet om veel meer te geven en af te nemen dan de moraal toelaat.'[^185] Een congres dat, zoals in Peru, volledig beheerst wordt door belangengroepen, heeft dezelfde morele status als een bende die gestolen goederen veilt. Dit maakte de vrije markt ontoegankelijk, waardoor de wet haar geloofwaardigheid verloor. Zoals de Soto schrijft over de periode vóór Fujimori:

> "Een complete omkering van doelen en middelen heeft het maatschappelijke leven in Peru zo verstoord dat bepaalde daden, hoewel wettelijk strafbaar, niet langer door het collectieve bewustzijn worden veroordeeld. Smokkelen is daar een treffend voorbeeld van. Iedereen, van aristocratische dames tot de meest nederige mannen, verwerft gesmokkelde goederen. Niemand heeft er gewetensbezwaren tegen; integendeel, men beschouwt het als een test van persoonlijke vindingrijkheid of als een vorm van wraak op de staat. Deze infiltratie van geweld en criminaliteit in het dagelijks leven gaat gepaard met toenemende armoede en ontbering. In het algemeen is het reële gemiddelde inkomen van de Peruanen de afgelopen tien jaar gestaag gedaald en bevindt het zich nu op het niveau van twintig jaar geleden. Overal hopen bergen afval zich op. Dag en nacht omsingelen legioenen bedelaars, autowassers en aaseters de voorbijgangers op zoek naar geld. Geestelijk zieken zwermen naakt door de straten en stinken naar urine. Kinderen, alleenstaande moeders en gehandicapten bedelen op elke straathoek om aalmoezen. Het traditionele centralisme van onze samenleving heeft duidelijk niet voldaan aan de vele behoeften van een land in transitie."[^186]

De Soto omschreef het loslaten van de groteske juridische economie ten gunste van de zwarte markt, een ontwikkeling die al in gang was gezet voordat Fujimori het congres opsloot, als 'een onzichtbare revolutie'.

Wij staan positief tegenover de voordelen van de vrije markt, maar zijn minder enthousiast over een samenleving waarin de wet net zo weinig waard is als het geld. De wereld die de Soto in Peru schetste vóór 1993, was een 'Clockwork Orange'-wereld waarin overmatig gecentraliseerde en dysfunctionele overheidsinstellingen de maatschappij letterlijk vernietigden.

Dit was immers wat Fujimori wilde veranderen. Hij verlaagde de inflatie drastisch door de geldpersen stil te leggen. Ook slaagde hij erin vijftigduizend ambtenaren te ontslaan en diverse subsidies in te perken. Hij begon met het in evenwicht brengen van de begroting. Zijn hervormingsprogramma omvatte uitgebreide plannen om vrije markten tot stand te brengen en de industrie te privatiseren. Maar, net als in de voormalige Sovjet-Unie, had hij in 1993 de meest cruciale elementen van zijn hervorming, waaronder de eerste ronde grootschalige privatiseringen van staatsbanken, mijnbouwbedrijven en nutsbedrijven, nog niet gerealiseerd. In plaats van deze broodnodige maatregelen te realiseren, probeerde het Peruaanse congres, net als het Russische congres dat Jeltsins hervormingen in Moskou blokkeerde, een stap achteruit te zetten. Hun plan luidde: subsidies herstellen vanuit een lege schatkist, de lonen spekken en alle gevestigde belangen beschermen, met name de bureaucratie; precies wat je zou verwachten van een overheid die door haar werknemers wordt beheerst.

Fujimori beweerde dat het congres van Peru aarzelend en corrupt was, een uitspraak waar vrijwel iedereen het mee eens was. Hij voegde eraan toe dat de aarzelende en corrupte werkwijze in het congres iedere poging om de ineenstortende economie van Peru te hervormen of de gewelddadige aanvallen van narco-terroristen en nihilistische guerrilla's van _het Sendero Luminoso (Shining Path)_ tegen te gaan, onmogelijk maakte.

### De 70-procentoplossing

Dus sloot Fujimori het Congres, een daad die erop kon wijzen dat hij even autoritair was als veel voorgaande Latijns-Amerikaanse leiders. Maar wij dachten, en zeiden dat destijds ook, dat Fujimori terecht een fundamentele belemmering voor hervorming had geïdentificeerd. De buitensporige officiële lofzangen op het Peruaanse congres door Amerikaanse redactieschrijvers en functionarissen van het State Department werden niet gedeeld door het volk van Peru. Terwijl Noord-Amerikanen deden alsof het Peruaanse congres de belichaming van vrijheid en beschaving was, juichte het Peruaanse volk. De populariteit van president Fujimori steeg boven de 70 procent toen hij het congres naar huis stuurde. En later werd hij met een verpletterende meerderheid herkozen voor een tweede termijn. De meeste burgers zagen hun wetgevende macht blijkbaar meer als een hindernis voor hun welzijn dan als een belichaming van hun rechten. In 1994 bereikte de reële economische groei in Peru 12,9 procent, de hoogste ter wereld.

### Deflatie van politieke beloften

Wij zagen de onrust in Peru niet als een terugkeer naar de dictaturen van het verleden maar eerder als een vroeg voorbeeld van een bredere overgangscrisis. Het is te verwachten dat in tal van landen crises van wanbestuur ontstaan wanneer politieke beloften niet worden nagekomen en overheden hun krediet uitgeput hebben. Uiteindelijk zullen nieuwe institutionele vormen moeten ontstaan die in staat zijn de vrijheid te bewaren onder de nieuwe technologische omstandigheden, terwijl zij tegelijkertijd uitdrukking en inhoud geven aan de gemeenschappelijke belangen die alle burgers delen.

Bijna niemand denkt nog na over de onverenigbaarheid tussen sommige instituties van de industriële overheid en de megapolitiek van de postindustriële samenleving. Of deze tegenstrijdigheden nu expliciet worden erkend of niet, hun gevolgen zullen steeds duidelijker worden naarmate voorbeelden van politiek falen zich wereldwijd opstapelen. Overheidsinstellingen die in de moderne tijd zijn ontstaan, weerspiegelen de megapolitieke omstandigheden van een of meerdere eeuwen geleden. Het Informatietijdperk zal nieuwe vertegenwoordigingsmechanismen vereisen om chronische disfunctionaliteit en zelfs sociale ineenstorting te vermijden.

Toen de Berlijnse Muur in 1989 viel, betekende dat niet alleen het einde van de Koude Oorlog; het was ook het signaal aan de buitenwereld dat er een stille aardbeving in de fundamenten van de macht in de wereld gaande was. Het betekende het einde van de lange periode van stijgende rendementen op geweld. De val van het communisme, die wij in 1987 voorspelden in _Blood in the Streets_ en nog eerder in onze maandelijkse nieuwsbrief _Strategic Investment_, was niet louter een verwerping van een ideologie. Het diende als zichtbaar symbool voor de meest betekenisvolle verandering in de geschiedenis van geweld van de laatste vijfhonderd jaar. Indien onze analyse juist is, zal de maatschappelijke structuur zich aanpassen aan de groeiende inefficiënties die gepaard gaan met het grootschalig inzetten van geweld. De grenzen waarbinnen de toekomst zich moet afspelen, zijn hertekend.

[^163]: Quoted in Tilly, op. cit., p.84.

[^164]: See John Keegan, *A History of Warfare* (London: Hutchinson, 1993), p.321.

[^165]: Jim Taylor and Watts Wacker, The 500-Year Delta: What Happens After What Comes Next. New York: HarperCollins, 1997, pp. 38-39.

[^166]: Ibid., p. 39.

[^167]: The Cambridge Ancient History, op. cit., pp.263-64.

[^168]: Cook et al., op. cit., p.268.

[^169]: For more on the logic of hydraulic societies, see Karl A. Wittfogel, *Oriental Despotism: A Comparative Study of Total Power* (New Haven: Yale University Press, 1957).

[^170]: Tilly, op. cit., p.28.

[^171]: Lane, "Consequences of Organized Violence," op. cit., p.406.

[^172]: Ibid.

[^173]: Ibid., p.412.

[^174]: Tilly, op. cit., pp.96-126.

[^175]: Ibid., p.130.

[^176]: Ibid., p.110.

[^177]: This example in ibid., p.139.

[^178]: Ibid., p.115.

[^179]: See Mancur Olson, *The Logic of Collective Action* (Cambridge: Harvard University Press, 1965).

[^180]: Josep R. Llobera, *The God of Modernity: The Development of Nationalism in Western Europe* (Oxford: Berg Publishers, 1994), pp. ix-x.

[^181]: Ibid., p. xiii.

[^182]: See William McNeill, *Polyethnicity and National Unity in World History* (Toronto: University of Toronto Press, 1986).

[^183]: Ibid., p.7.

[^184]: Hernando de Soto, *The Other Path* (New York: Harper & Row, 1989).

[^185]: Ibid.

[^186]: Ibid., p.6.
