# De megapolitiek van het Informatietijdperk

::: {.content-hidden when-format="latex"}
De triomf van efficiëntie boven macht
:::

> ...het is gecomputeriseerde informatie, niet mankracht of massaproductie, die de Amerikaanse economie steeds meer aandrijft en die oorlogen zal winnen in een wereld die is bekabeld voor 500 TV-kanalen. De gecomputeriseerde informatie bestaat in de cyberspace, de nieuwe dimensie die is ontstaan door de eindeloze productie van computernetwerken, satellieten, modems, databanken en het publieke internet. -- NEIL MUNRO

Op 30 december 1936 bezetten medewerkers die hogere salarissen eisten met geweld twee hoofdvestigingen van General Motors in Flint, Michigan. Ze legden machines stil, zetten de lopende banden uit en deden alsof ze thuis waren. Werknemers die waren aangenomen om de fabrieken te bedienen, gingen letterlijk zitten in een industriële confrontatie die vele weken zou duren. Het was een drama, onderbroken door gewelddadige rellen en de wisselende loyaliteit van de politie, de militie van Michigan en politieke figuren op alle bestuursniveaus. Toen hun eisen weinig vooruitgang boekten, sloeg de vakbond op 1 februari 1937 opnieuw toe.

Vakbondsactivisten namen met geweld GM's Chevrolet-fabriek in Flint over. Door de belangrijkste installaties van General Motors te bezetten en te sluiten, slaagden de arbeiders erin om de productieve capaciteit van het bedrijf bijna volledig te verlammen. In de tien dagen na de inname van de derde fabriek produceerde GM in de Verenigde Staten slechts 153 auto's.

We halen dit nieuwsbericht van zestig jaar geleden aan om de revolutie in megapolitieke omstandigheden die nu gaande is, scherper te belichten. De sit-downstaking bij GM gebeurde nog binnen het leven van sommige lezers van dit boek. Toch geloven wij dat sit-downstakingen in het Informatietijdperk net zo achterhaald zullen blijken te zijn als slaven die door de woestijn sjouwen met enorme stenen om grafpiramides voor de farao's te bouwen. Vakbonden en hun intimidatietactieken werden in het Industriële Tijdperk zo vertrouwd dat ze een onbetwist deel van het sociale landschap vormden. Ze berustten echter op speciale megapolitieke omstandigheden die nu snel verdwijnen. Er zullen geen Chevrolets en geen UAW (de vakbond in kwestie) zijn om te staken op de Informatie-Supersnelweg.

Overheden zullen net als hun tegenhangers, de vakbonden, in verval raken. Geïnstitutionaliseerde dwang van het soort dat een cruciale rol speelde in de twintigste-eeuwse samenleving zal niet langer mogelijk zijn. Technologie veroorzaakt een diepgaande verandering in de logica van afpersing en bescherming.

> ...er zal geen eigendom zijn, geen heerschappij, geen onderscheid tussen het mijne en het uwe; maar alleen datgene wat ieder kan verkrijgen, en zolang hij het kan behouden. -- THOMAS HOBBES

### Afpersing en bescherming

Door de geschiedenis heen is geweld een dolk geweest die op het hart van de economie was gericht. Zoals Thomas Schelling scherp opmerkte: "De macht om pijn te doen, om dingen te vernietigen die iemand dierbaar zijn, om pijn en verdriet toe te brengen, is een vorm van onderhandelingsmacht, die niet makkelijk is te gebruiken, maar vaak wordt toegepast. In de onderwereld vormt het de basis voor chantage, afpersing en ontvoering; in de commerciële wereld voor boycots, stakingen en uitsluitingen... Het is vaak de basis voor discipline, civiel en militair; en goden gebruiken het om discipline af te dwingen." Het vermogen van de staat om belastingen te heffen, hangt af van dezelfde kwetsbaarheden die ook ten grondslag liggen aan particuliere afpersing en chantage. Hoewel we het doorgaans niet in deze termen zien, geeft het aandeel van de middelen dat dwingend wordt beheerd en besteed, via misdaad en overheid, een ruwe maatstaf van het megapolitieke evenwicht tussen afpersing en bescherming.

Als technologie de bescherming van bezittingen moeilijk maakt, zal misdaad waarschijnlijk wijdverspreid zijn, net als vakbondsactiviteit. Onder zulke omstandigheden zal de overheid dus een hoge premie kunnen afdwingen voor het leveren van bescherming. Belastingen zullen hoog zijn. Wanneer belastingen laag zijn en lonen vooral door marktwerking worden bepaald in plaats van door politieke inmenging of dwang, zorgt technologie ervoor dat de verhoudingen verschuiven in het voordeel van bescherming, en niet van afpersing.

De technologische disbalans tussen afpersing en bescherming bereikte een extreem aan het einde van het derde kwart van de twintigste eeuw. In sommige geavanceerde westerse samenlevingen werd meer dan de helft van de middelen door regeringen opgeëist. De inkomens van een groot deel van de bevolking werden ofwel bij decreet vastgesteld, of beïnvloed door dwang, bijvoorbeeld door stakingen en dreiging met andere vormen van geweld. De verzorgingsstaat en de vakbond waren beide producten van technologie, die samen profiteerden van de overwinning van macht boven efficiëntie in de twintigste eeuw. Ze hadden niet kunnen bestaan zonder de militaire en civiele technologieën die het rendement op geweld in het Industriële Tijdperk verhoogden.

Het vermogen om bezittingen te creëren heeft altijd enige kwetsbaarheid voor afpersing met zich meegebracht. Hoe waardevoller de bezittingen die werden gecreëerd of beheerd, des te hoger de prijs die op de een of andere manier betaald moest worden. Of je betaalde iedereen die machtig genoeg was om je met geweld af te persen, of je betaalde voor militaire macht die in staat was om elke poging tot afpersing met brute kracht te verslaan.

> Er zal geen geweld meer worden gehoord in uw land, geen verderf of vernieling binnen uw grenzen... -- JESAJA 60:18

### De wiskunde van bescherming

Nu kan de dolk van geweld binnenkort mogelijk worden getemd. Informatie­technologie belooft het evenwicht tussen bescherming en afpersing ingrijpend te veranderen, waardoor de bescherming van bezittingen in veel gevallen veel eenvoudiger wordt en afpersing moeilijker. De technologie van het Informatietijdperk maakt het mogelijk bezittingen te creëren die buiten het bereik van veel vormen van dwang liggen.

Deze nieuwe asymmetrie tussen bescherming en afpersing berust op een fundamentele wiskundige waarheid: het is gemakkelijker om te vermenigvuldigen dan om te delen. Hoewel deze waarheid eenvoudig lijkt, bleven de diepgaande gevolgen ervan onzichtbaar tot de komst van microprocessors. Computers hebben in het afgelopen decennium miljarden keren meer berekeningen uitgevoerd dan in de hele voorgaande geschiedenis van de wereld.

Deze sprong in rekenkracht heeft ons voor het eerst in staat gesteld enkele universele kenmerken van complexiteit te doorgronden. Wat de computers laten zien, is dat complexe systemen alleen van onderaf kunnen worden opgebouwd en begrepen. Het vermenigvuldigen van priemgetallen is eenvoudig. Maar het uit elkaar halen van complexiteit door het product van grote priemgetallen te ontbinden is vrijwel onmogelijk. Kevin Kelly, redacteur van _Wired_, verwoordt het zo:\
"Het vermenigvuldigen van meerdere priemgetallen tot een groter product is eenvoudig; elk kind op de basisschool kan dat, maar alle supercomputers in de wereld stikken terwijl ze een product terug proberen te ontleden in zijn eenvoudige priemgetallen."

### De logica van complexe systemen

De cybereconomie zal onvermijdelijk worden gevormd door deze fundamantele wiskundige waarheid. Het manifesteert zich al in sterke encryptiemethoden. Zoals we later in dit hoofdstuk zullen bespreken, zullen deze algoritmen het mogelijk maken om een nieuw, beschermd domein van cyberhandel te creëren waarin het geweldsmonopolie sterk wordt teruggedrongen. Het evenwicht tussen afpersing en bescherming zal drastisch doorslaan in de richting van bescherming. Dit zal de opkomst bevorderen van een economie die meer steunt op spontane, adaptieve mechanismen en minder op bewuste besluitvorming en toewijzing van middelen via bureaucratie. Het nieuwe systeem, waarin bescherming centraal zal staan, zal sterk verschillen van datgene wat voortkwam uit de overheersing van dwang in het Industriële Tijdperk.

### Command-and-control systemen zijn primitief

We schreven in _The Great Reckoning_ dat de computer ons in staat stelt om de complexiteit in een hele reeks systemen te "zien" die voorheen onzichtbaar was. Geavanceerde rekenkracht maakt het niet alleen mogelijk de dynamiek van complexe systemen beter te begrijpen, maar ook om deze complexiteiten op productieve manieren te benutten. In zekere zin is dit niet eens een keuze, maar het is onvermijdelijk als de economie verder wil komen dan het starre, centraal gestuurde ontwikkelingsstadium. Een dergelijk systeem, dat afhankelijk is van lineaire relaties, is in wezen primitief. De inbeslagname van middelen door de overheid trekt onvermijdelijk middelen weg van complexe toepassingen met hoge waarde naar primitieve toepassingen met lage waarde. Het is een proces dat wordt beperkt door dezelfde wiskundige asymmetrie die voorkomt dat het product van grote priemgetallen kan worden ontbonden. Het verdelen van de buit kan nooit meer zijn dan primitief.

### Alles wordt complexer

Overal in het universum zien we systemen die naarmate ze evolueren grotere complexiteit bereiken. Dit geldt in de astrofysica. Het geldt in een plas water. Laat regenwater in een lage plek liggen en het zal complexer worden. Geavanceerde systemen van elke soort zijn complexe adaptieve systemen zonder een centrale autoriteit. Elk complex systeem in de natuur, waarvan de markteconomie de meest evidente sociale manifestatie is, berust op een verscheidenheid aan competenties. Systemen die in de meest uiteenlopende omstandigheden het best functioneren, danken hun robuustheid aan een spontane orde die ruimte laat voor het onverwachte. Het leven zelf is zo'n complex systeem. Miljarden potentiële genetische combinaties produceren één enkel menselijk individu. Het ordenen daarvan zou elke bureaucratie doen vastlopen.

Vijfentwintig jaar geleden kon dat slechts een intuïtie zijn. Vandaag is het aantoonbaar. Naarmate computers ons meer inzicht geven in de wiskunde achter kunstmatig leven, groeit ons begrip van de wiskunde van het werkelijke leven, dat berust op biologische complexiteit. Dankzij informatietechnologie kunnen deze geheimen van complexiteit worden toegepast om economieën om te vormen tot steeds complexere systemen. Het Internet en het World Wide Web hebben al kenmerken aangenomen van een organisch systeem, zoals Kevin Kelly suggereert in _Out of Control: The New Biology of Machines, Social Systems, and the Economic World_. In zijn woorden is de natuur "een ideeënfabriek. Vitale, postindustriële paradigma's liggen verborgen in elke mierenhoop in de jungle... De grootschalige overdracht van het biologische naar machines zou ons diep moeten verwonderen. Wanneer de vereniging van het geboren en het gemaakte voltooid is, zullen onze creaties leren, zich aanpassen, zichzelf genezen en evolueren. Dit is een kracht waar we nauwelijks van hebben durven dromen."

De gevolgen van deze "grootschalige overdracht van het biologische naar machines" zullen inderdaad verstrekkend zijn. Sociale systemen hebben altijd een sterke neiging gehad om de kenmerken van de heersende technologie te imiteren. Marx had hierover gelijk. Gigantische fabrieken vielen samen met het tijdperk van de grote overheid. Microprocessing is nu bezig met het miniaturiseren van instituties. Als onze analyse klopt, zal de technologie van het Informatietijdperk uiteindelijk een economie scheppen die beter geschikt is om de voordelen van complexiteit te benutten.

Toch zijn de megapolitieke dimensies van zo'n verandering zo weinig begrepen dat zelfs de meesten die het wiskundige belang ervan hebben erkend, dit op een achterhaalde manier hebben gedaan. Het is eenvoudigweg moeilijk om volledig te bevatten en te internaliseren dat technologische verandering in de komende jaren de meeste politieke vormen en concepten van de moderne wereld zal verouderen. Zo schreef de overleden natuurkundige Heinz Pagels in zijn vooruitziende boek _The Dreams of Reason_: "Ik ben ervan overtuigd dat de naties en volkeren die de nieuwe wetenschap van complexiteit beheersen, de economische, culturele en politieke supermachten van de volgende eeuw zullen worden." Het is een indrukwekkende voorspelling. Wij geloven echter dat het onjuist zal blijken, niet omdat het een verkeerde observatie is, maar juist omdat het méér bewaarheid zal worden dan Pagels durfde uit te spreken. Samenlevingen die zich herconfigureren tot complexere adaptieve systemen zullen inderdaad opbloeien. Maar wanneer dat gebeurt, zullen het waarschijnlijk geen naties zijn, laat staan "politieke supermachten". Het is waarschijnlijker dat de directe begunstigden van de toegenomen complexiteit van de sociale systemen de Soevereine Individuen van het nieuwe millennium zullen zijn.

Pagels' voorspelling komt neer op wat een sjamaan van een jagersgroep vijfhonderd generaties terug bij het kampvuur zou hebben gezegd: "Ik ben ervan overtuigd dat de eerste jagersgroep die de nieuwe wetenschap van geïrrigeerde landbouw beheerst, meer vrije tijd voor het vertellen van verhalen zal hebben dan zelfs die kerels die de grote vissen vangen daar bij het meer." Hoezeer hij ook gelijk had over het belang van complexiteit, Pagels miste het meest fundamentele feit van allemaal: wanneer de logica van geweld verandert, verandert de samenleving.

## De logica van geweld

Om te begrijpen hoe en waarom, moeten we ons richten op diverse aspecten van de megapolitiek die je zelden tegenkomt. Deze vraagstukken onderzocht historicus Frederic C. Lane, wiens werk over geweld en de economische betekenis van oorlog elders in dit boek aan bod komt. Toen Lane in het midden van deze eeuw zijn werk schreef, was een informatiesamenleving nog ondenkbaar. Onder die omstandigheden kon hij er rotsvast van overtuigd zijn dat de strijd om geweld wereldwijd in zijn definitieve fase beland was met de opkomst van de natiestaat. In zijn werken geeft hij niet aan dat hij microprocessing had voorzien of dat hij geloofde dat het technologisch haalbaar was om activa in de cyberspace, een rijk zonder fysiek bestaan, te creëren. Lane ging niet in op de implicaties van de mogelijkheid dat grote handelsvolumes vrijwel immuun zouden kunnen worden gemaakt voor de invloed van geweld.

Hoewel Lane de huidige technologische revoluties niet had voorzien, blijken zijn inzichten in de verschillende stadia van de monopolisatie van geweld uit het verleden zo scherp dat ze duidelijk toepasbaar zijn op de opkomende informatierevolutie. In zijn studie van de gewelddadige middeleeuwse wereld richtte hij de aandacht op vraagstukken die conventionele economen en historici vaak over het hoofd zien. Hij realiseerde zich dat de manier waarop geweld wordt georganiseerd en gecontroleerd een cruciale rol speelt bij de allocatie van schaarse middelen. Lane erkende bovendien dat, hoewel de productie van geweld doorgaans niet als onderdeel van de economische output wordt gezien, de beheersing ervan essentieel is voor de economie. De voornaamste taak van de overheid bestaat immers uit het bieden van bescherming tegen geweld. Zoals hij het verwoordde:

> Elke economische onderneming heeft bescherming nodig en betaalt daarvoor; bescherming tegen de vernietiging of de gewapende inbeslagname van haar kapitaal en tegen de gewelddadige verstoring van haar arbeid. In sterk georganiseerde samenlevingen behoort het leveren van deze bescherming tot de taken van een speciale vereniging of onderneming die men 'overheid' noemt. Inderdaad, een van de meest onderscheidende kenmerken van overheden is hun poging om wet en orde te handhaven door zelf macht in te zetten en op diverse wijzen het gebruik van geweld door anderen te beheersen.

Dit punt is zo fundamenteel dat het niet in leerboeken of burgerlijke discussies, die zogenaamd de politieke koers bepalen, wordt besproken. Maar men kan het niet zomaar negeren als je de informatierevolutie, die zich nu ontvouwt, wil doorgronden. De bescherming van leven en eigendom is immers een essentiële behoefte waar elke samenleving in de geschiedenis mee te maken heeft gehad. Het afweren van gewelddadige agressie vormt het centrale dilemma in de geschiedenis en kent geen eenvoudige oplossing, al bestaan er meerdere manieren om bescherming te bieden.

### Het einde van een tijdperk

Terwijl we dit schrijven, beginnen de megapolitieke gevolgen van het Informatietijdperk net voelbaar te worden. De economische verschuivingen van de afgelopen decennia waren van industrie naar informatie en rekenkracht, van machinale kracht naar microprocessing, van fabrieken naar bureau's, van massaproductie naar kleine teams, of zelfs naar zelfstandigen. Naarmate ondernemingen kleiner worden, neemt de kans op sabotage en chantage op de werkvloer af. Vakbonden vinden het veel lastiger om kleinere bedrijven te organiseren.

Dankzij microtechnologie kunnen ondernemingen kleiner en mobieler opereren. Velen leveren diensten of producten die nauwelijks natuurlijke hulpbronnen vereisen. In principe kunnen deze ondernemingen vrijwel overal op aarde werken, omdat ze niet gebonden zijn aan een specifieke locatie, zoals een mijn of een haven. Daardoor lopen ze op den duur veel minder kans om door vakbonden of politici onder druk te worden gezet. Een oud Chinees gezegde luidt: 'Van alle zesendertig manieren om uit de problemen te komen, is vertrekken de beste.'

In het Informatietijdperk zal die oosterse wijsheid haar vruchten afwerpen. Wanneer het bedrijfsleven onaangenaam wordt door buitensporige eisen op één locatie, wordt verhuizen een stuk eenvoudiger. Inderdaad, zoals we straks bespreken, kunnen ondernemers in het Informatietijdperk virtuele ondernemingen opzetten, waarbij hun vestigingsplaats volledig afhankelijk is van de spotmarkt. Een plotselinge toename van de pogingen tot afpersing, of het nu door overheden of anderen komt, kan ertoe leiden dat de activiteiten en activa van een virtuele onderneming met de snelheid van het licht uit de betreffende jurisdictie verdwijnen.

De toenemende integratie van microtechnologie in industriële processen betekent dat zelfs bedrijven die nog steeds producten met grote schaalvoordelen produceren, niet langer even kwetsbaar zijn voor de dreiging van geweld als vroeger. Een voorbeeld hiervan is het falen van de langdurige staking van de United Auto Workers tegen Caterpillar, die eind 1995, na bijna twee jaar, werd beëindigd. In tegenstelling tot de assemblagelijnen van de jaren dertig maakt de huidige Caterpillar-fabriek veel meer gebruik van vakbekwame werknemers. Onder druk van buitenlandse concurrentie besteedde Caterpillar veel laaggeschoold werk uit, sloot inefficiënte fabrieken en investeerde bijna 2 miljard dollar in de computerisering van bestaande machines en de installatie van assemblagerobots. De staking stimuleerde zelfs het doorvoeren van deze arbeidsbesparende efficiëntieslag. Het bedrijf stelt nu tweeduizend werknemers minder nodig te hebben dan toen het werk werd neergelegd.

De megapolitieke omstandigheden van het productieproces zijn ingrijpender veranderd dan de meeste mensen beseffen. Deze verandering is nog niet duidelijk zichtbaar, deels omdat er altijd een vertraging zit tussen een revolutie in megapolitieke omstandigheden en de institutionele veranderingen die zij onvermijdelijk teweegbrengt. Bovendien betekent de snelle evolutie van microprocessingtechnologie dat er nu producten verschijnen waarvan de megapolitieke gevolgen al voorzien kunnen worden, nog voordat ze bestaan. Zij zullen zorgen voor een fundamenteel andere wereld.

## Uitbuiting van de kapitalisten door de arbeiders

De aard van de technologie in het merendeel van de twintigste eeuw zorgde ervoor dat eigenaars en managers weinig middelen hadden om een gedwongen bezetting van een fabriek of een sit-downstaking tegen te gaan. Zoals historicus Robert S. McElvaine opmerkte, maakte een sit-downstaking het "moeilijk voor werkgevers om de staking af te breken zonder hetzelfde met hun eigen uitrusting te doen." In feite hielden de arbeiders het kapitaal van de eigenaars fysiek gegijzeld. Om redenen die hieronder worden toegelicht, bleken grotere industriële ondernemingen makkelijkere doelwitten voor vakbonden dan kleinere bedrijven. In 1937 was General Motors misschien wel hét toonaangevende industriële concern ter wereld. Haar fabrieken behoorden tot de grootste en duurste verzameling machines ooit gebouwd en boden werk aan tienduizenden arbeiders. Elk uur van elke dag dat de GM-fabrieken stil lagen, kostte het bedrijf een klein fortuin. Een staking die wekenlang onopgelost bleef, zoals die in de winter van 1936-37, betekende snel oplopende verliezen.

### In verzet tegen vraag en aanbod

General Motors capituleerde snel nadat de derde fabriek bezet werd en de productie van auto's volledig stilviel. Dat was geen economische beslissing gebaseerd op de vraag en het aanbod van arbeid. Integendeel, toen General Motors toegaf aan de eisen van de vakbond waren er negen miljoen werklozen in de VS, wel 14% van de beroepsbevolking. Velen waren bereid en bekwaam genoeg om de assemblagebanen bij GM in te vullen, al zul je dat waarschijnlijk niet van de rapportage destijds hebben gehoord. Een verfijnde etiquette verhulde een eerlijke analyse van de arbeidsverhoudingen tijdens de industriële periode. Het idee dat fabriekswerk, en dan met name in het midden van de twintigste eeuw, vakmanschap vereiste, was grotendeels fictie. De meeste fabrieksbanen konden door bijna iedereen uitgevoerd worden die op tijd kon opdagen. Ze vereisten amper training en zelfs geen geletterdheid. Nog zo recent als in de jaren '80 waren veel arbeiders van GM analfabeet of konden niet rekenen, of beide, en tot in de jaren '90 kreeg een nieuwe werknemer gemiddeld slechts één dag oriëntatie. Een baan die je in een dag kunt leren, kun je geen vakmanschap noemen.

Terwijl zowel geschoolde als ongeschoolde arbeiders in de rij stonden om smeekbedes te doen voor werk, slaagden de fabrieksarbeiders van GM er in 1937 toch in om hun werkgevers tot een loonsverhoging te dwingen. Hun succes had veel meer te maken met de dynamiek van geweld dan met de vraag en het aanbod van arbeid. In maart 1937, de maand na de schikking, waren er 17 extra sit-downstakingen in de Verenigde Staten. De meeste waren succesvol. Vergelijkbare gebeurtenissen vonden plaats in elk geïndustrialiseerd land. De arbeiders namen simpelweg de fabrieken in beslag en verkochten ze terug aan de eigenaars. Het was een uiterst eenvoudige tactiek, en een die in de meeste gevallen winstgevend en leuk was voor de deelnemers. Eén sit-downstaker schreef: "Ik heb de tijd van mijn leven, iets nieuws, iets anders, volop eten en muziek."

De GM-sit-downstaking van 1936-37 en de andere gewelddadige fabrieksovernames uit die tijd waren voorbeelden van een fenomeen dat wij in _Blood in the Streets_ beschreven als "de uitbuiting van de kapitalisten door de arbeiders." Dit was niet de visie die Pete Seeger in zijn droevige liederen verwerkte. Maar tenzij je een carrière als volkszanger in een arbeidersbuurt overweegt, is het belangrijk niet te focussen op de populaire interpretatie, maar op de onderliggende werkelijkheid. Waar je ook in de geschiedenis kijkt, er is bijna altijd een laag van rationalisatie en schijn die de ware megapolitieke fundamenten van systematische afpersing verhult. Als je die rationalisaties voor lief neemt, is de kans klein dat je werkelijk begrijpt wat er gaande is.

## Het ontcijferen van de logica van afpersing

Om de megapolitieke implicaties van de huidige overgang naar het Informatietijdperk te begrijpen, moet je de retoriek wegstrepen en je concentreren op de werkelijke logica van geweld in de samenleving. Dit is vergelijkbaar met het pellen van een te rijpe ui. Het kan tranen in je ogen brengen, maar kijk niet weg. We beginnen met de logica van afpersing op de werkplek en breiden de analyse vervolgens uit naar bredere kwesties, zoals de creatie en bescherming van bezittingen en de aard van de moderne overheid. In grotere mate dan de meeste mensen zich realiseren, was de welvaart van de overheid, net als die van vakbonden, direct gecorreleerd aan de mate waarin afpersing effectief ingezet kan worden. In de negentiende eeuw was de effectiviteit ervan lager dan in de twintigste. In het volgende millennium zal zij bijna tot nul afnemen.

De hele logica van overheid en de aard van macht zijn getransformeerd door microprocessing. Dit lijkt op het eerste gezicht misschien overdreven, maar kijk aandachtig mee. De welvaart van regeringen is in de twintigste eeuw hand in hand gegaan met de welvaart van vakbonden. Vóór de twintigste eeuw onttrokken de meeste overheden aanzienlijk minder middelen dan de militante verzorgingsstaten die we nu kennen. Evenzo waren vakbonden vóór deze eeuw kleine of onbelangrijke factoren in het economische leven. Het vermogen van arbeiders om hun werkgevers te dwingen tot het betalen van hogere lonen dan de marktprijs, vond haar oorsprong in dezelfde megapolitieke omstandigheden die het voor overheden mogelijk maakten om 40 procent van de economische productie te belasten, of meer.

### Afpersing op de werkvloer vóór de twintigste eeuw

De opkomst en ondergang van de afpersing van kapitalisten door vakbonden is makkelijk te verklaren door te kijken naar de veranderende megapolitieke omstandigheden binnen het productieproces. In 1776, toen Adam Smith _The Wealth of Nations_ publiceerde, waren de condities voor afpersing op de werkvloer zo ongunstig dat het vormen van "combinaties" van arbeiders om "de prijs van hun arbeid te verhogen" zelden uitvoerbaar bleek. De meeste productiebedrijven waren klein en door families gerund, en grootschalige industriële activiteiten stonden nog in de kinderschoenen. Hoewel geweld niet uitgesloten werd, was het niet heel effectief. In de tijd van Smith en tot ver in de negentiende eeuw beschouwde men vakbonden als illegale combinaties in Groot-Brittannië, de Verenigde Staten en andere landen met common-law. Adam Smith omschreef de stakingen als volgt: 'Hun gebruikelijke voorwendselen zijn soms de hoge prijzen van levensmiddelen, soms de enorme winst die hun meester behaalt met hun werk... Zij grijpen altijd terug op luid tumult, en soms zelfs op schokkend geweld en de meest gruwelijke beledigingen.' Toch behalen arbeiders 'zeer zelden enig voordeel uit die tumultueuze combinaties,' behalve 'de bestraffing of ondergang van de aanvoerders.'

In de negentiende eeuw genoot de industrie van steeds meer schaalvoordelen en de omvang van ondernemingen nam toe. Toch bleven de meeste individuen voor zichzelf werken als boeren of kleine ondernemers, en pogingen tot vakbondsvorming, zoals beschreven door Adam Smith, "eindigden over het algemeen in niets." De juridische en politieke positie van vakbonden veranderde pas toen de schaal van ondernemingen toenam. De eerste vakbonden die zich succesvol organiseerden, waren ambachtsvakbonden van hooggeschoolde arbeiders, die zich over het algemeen zonder veel geweld organiseerden. Ze stelden zich tevreden met loonsverhogingen die overeenkwamen met de potentiële kosten van hun vervanging. Vakbonden voor ongeschoolde arbeiders waren een ander verhaal. Zij maakten gebruik van de verschuiving naar grotere ondernemingen door zich te richten op precies die industrieën die bijzonder kwetsbaar waren voor dwang, hetzij omdat ze op grotere schaal opereerden, hetzij omdat het karakter van de werkzaamheden hun eigenaars blootstelde aan fysieke sabotage. Dit patroon werd bevestigd van Newcastle tot Argentinië.

Een vroeg voorbeeld van gewelddadige arbeidersbewegingen in de Verenigde Staten was een aanval op het Chesapeake and Ohio Canal in 1834. In tegenstelling tot de meeste bedrijven van het begin van de negentiende eeuw, was het C\&O Canal geen afgesloten en gemakkelijk te beschermen onderneming. Oorspronkelijk zou het 550 kilometer lang worden, met een hoogteverschil van ruim 900 meter van de lagere Potomac tot de bovenloop van de Ohio. Het graven van zo'n kanaal was een enorme klus die nooit helemaal zou worden voltooid. Toch waren er talrijke arbeiders mee bezig, waarbij enkelen snel inzagen dat het kanaal eenvoudig onklaar te maken was. Zonder regelmatig onderhoud kon het door muskusratten die onder het jaagpad groeven, worden gesaboteerd. Daarnaast konden de sluizen en kanalen tijdens het gebruik makkelijk beschadigd raken door onzorgvuldig gebruik, overstromingen door zware regenval of door botsingen met onbeheerde boten. Het was dan ook niet moeilijk voor stakers om de waterweg te blokkeren met gezonken boten of ander puin. Begin 1834 leidde een rel tussen rivaliserende groepen Ierse arbeiders op het C\&O tot een poging om dit potentieel te benutten en het kanaal over te nemen. De poging mislukte echter nadat president Andrew Jackson federale troepen van Fort McHenry had gestuurd om de arbeiders te verdrijven. Hierbij kwamen vijf mensen om het leven.

Mijnen en spoorwegen waren ook vroege doelwitten voor vakbondsactivisme in Amerika. Net als het C\&O Canal waren zij zeer kwetsbaar voor sabotage: mijnen konden bijvoorbeeld worden overstroomd of bij de ingang worden geblokkeerd; het doden van de muildieren die de ertswagentjes uit ondergrondse mijnen trokken, creëerde een lastige en onaangename situatie voor de eigenaars; spoorwegbeddingen strekten zich over vele kilometers uit en konden slechts moeilijk worden bewaakt. Het was relatief eenvoudig voor vakbondscriminelen om mijnen en spoorwegen aan te vallen en aanzienlijke economische schade aan te richten. Dergelijke aanvallen kwamen veelvuldig voor tijdens pogingen om effectieve vakbonden te organiseren. Deze inspanningen waren over het algemeen het intensiefst tijdens perioden waarin de reële lonen stegen door deflatie. Wanneer eigenaars probeerden om de nominale lonen aan te passen, leidde dit vaak tot protesten die tot geweld escaleerden. Zulke incidenten waren wijdverspreid tijdens de depressie die volgde op de paniek van 1873.

In december 1874 brak er oorlog uit in de anthracietmijnen van het oosten van Pennsylvania. De vakbonden organiseerden een gewelddadige staking onder de dekmantel van een geheime maatschappij genaamd de Ancient Order of Hibernians, ook bekend als de "Molly Maguires," naar een Ierse revolutionair. Deze groep stond bekend om het terroriseren van de kolenmijnen en het verhinderen dat mijnwerkers die wilden werken, hun werk konden doen. Tegen haar leden werden sabotage en vernietiging van eigendom, en zelfs moord en liquidaties ten laste gelegd.

Er was ook terugkerend geweld onder spoorwegmedewerkers. Bijvoorbeeld in juli 1877 waren er ernstige uitbarstingen gericht op het vernietigen van eigendommen van zowel de Pennsylvania Railroad als de Baltimore & Ohio Railroad. Arbeiders namen wissels over, haalden sporen weg, sloten rangeerterreinen af, schakelden locomotieven uit, saboteerden en plunderden treinen, en erger. In Pittsburgh werden de ronde werkplaatsen van de Pennsylvania Railroad in brand gestoken met honderden mensen erin. Tientallen werden gedood, tweeduizend wagons werden verbrand en geplunderd, en de machinewerkplaats werd vernietigd, samen met een graanlift en 125 locomotieven. Federale troepen grepen in om de orde te herstellen.

Hoewel deze vroege stakingen sympathiek werden geïnterpreteerd door socialistische en vakbondsactivisten, inspireerden ze weinig publieke steun. Ondanks de inherente kwetsbaarheid van industrieën zoals mijnen en spoorwegen, waren de algemene megapolitieke omstandigheden nog niet gunstig voor de uitbuiting van kapitalisten door arbeiders. De schaal van ondernemingen was te klein om systematische afpersing mogelijk te maken. Hoewel er kwetsbare industrieën waren, boden zij werk aan een te klein deel van de bevolking om de voordelen van dwang tegen werkgevers breed te laten delen. Zonder dergelijke steun waren ze niet houdbaar, omdat eigenaars op de overheid konden rekenen voor bescherming. Hoewel vakbonden soms probeerden lokale ambtenaren via dreigementen ervan te weerhouden rechterlijke bevelen uit te voeren, waren deze pogingen zelden succesvol. Zelfs de meest gewelddadige stakingen werden meestal binnen enkele dagen of weken door militaire middelen onderdrukt.

### Chantage eenvoudig gemaakt

Het feit dat pogingen van vakbonden om lonen van kleine bedrijven boven het marktconforme niveau te krijgen zelden succesvol waren, leert ons een les voor het Informatietijdperk. Zelfs die bedrijfstakken die duidelijk kwetsbaar waren voor sabotage, zoals kanalen, spoorwegen, trams en mijnen, waren niet gemakkelijk onder controle te brengen. Dit kwam niet omdat de vakbonden geweld schuwden. Integendeel, geweld werd royaal ingezet, soms ook tegen prominente individuen. Bijvoorbeeld, in een zaak die binnen de Amerikaanse arbeidersbeweging werd gevierd als "wraak van de mijnwerkers", werd gouverneur Frank Steunenberg van Idaho, die een poging van mijnwerkers om eigendommen in Coeur d'Alene te blokkeren had tegengewerkt, vermoord door een bom die door een huurmoordenaar van de vakbond was gegooid. Zelfs moord en dreigementen waren vóór de opkomst van grootschalige fabrieken en massaproductiebedrijven in de twintigste eeuw echter meestal onvoldoende om vakbondserkenning te verkrijgen.

Om te begrijpen waarom de omstandigheden van vakbonden in de twintigste eeuw zo veranderden, moet je kijken naar de kenmerken van productietechnologie. Er veranderde iets met de snelle opkomst van fabrieksarbeid in de vroege decennia van de twintigste eeuw. Deze verandering maakte de economische koplopers bijzonder kwetsbaar voor afpersing. In feite leken de fysieke eigenschappen van industriële technologie arbeiders bijna uit te nodigen om de kapitalisten af te persen. Overweeg het volgende:

1. _De meeste industriële producten bevatten een grote hoeveelheid natuurlijke hulpbronnen._ Dit leidde ertoe dat de productie gebonden bleef aan een beperkt aantal locaties, net zoals dat mijnen moeten geplaatst worden waar de ertsen zich bevinden. Fabrieken die nabij transportknooppunten lagen met gemakkelijke toegang tot leveranciers van onderdelen en grondstoffen, hadden significante operationele voordelen. Dit maakte het voor dwingende organisaties, zoals overheden en vakbonden, gemakkelijker om een deel van die voordelen voor zichzelf te claimen.
2. _Toenemende schaalvoordelen leidden tot zeer grote ondernemingen._ Fabrieken aan het begin van de negentiende eeuw waren relatief klein. Met de opkomst van de assemblagelijn in de twintigste eeuw namen de schaalvoordelen toe, waardoor de grootte en de kosten van de modernste fabrieken sterk opliepen. Dit maakte ze op verschillende manieren een makkelijk doelwit. Bijvoorbeeld, grote schaalvoordelen gaan vaak gepaard met lange productcycli. Lange productcycli zorgen voor stabielere markten. Dit maakt ondernemingen vatbaar voor roofzuchtige acties, omdat het betekent dat er voordelen op de lange termijn te behalen zijn.
3. _Het aantal concurrenten in toonaangevende industrieën daalde scherp. Het was tijdens de industriële periode niet ongebruikelijk om slechts een handvol bedrijven te vinden dat concurreerde om miljardenmarkten._ Ook dit maakte hen makkelijkere doelwitten voor afpersing door vakbonden. Het is veel eenvoudiger om vijf bedrijven aan te vallen dan vijfduizend. De concentratie van de industrie zelf was een factor die afpersing vergemakkelijkte. Dit voordeel werkte zelfversterkend, omdat bedrijven die gedwongen werden om hogere lonen te betalen, zelden te maken kregen met concurrenten die daarvan waren vrijgesteld. Vakbonden konden daardoor een behoorlijk deel van de winst van dergelijke bedrijven afromen zonder dat ze direct failliet gingen. Uiteraard, als werkgevers routinematig failliet zouden gaan telkens wanneer ze lonen moesten betalen die hoger waren dan de marktprijs, dan zouden arbeiders weinig winnen door hen daartoe te dwingen.
4. _Door de grotere schaal van de ondernemingen, namen de kapitaalvereisten toe._ Dit vergrootte niet alleen de kwetsbaarheid van kapitaal en verhoogde de kosten van fabrieksluitingen; het maakte het ook steeds onwaarschijnlijker dat een moderne fabriek in handen van één individu of familie kon zijn, behalve via erfopvolging van iemand die het bedrijf op kleinere schaal was begonnen. Om de enorme kosten van uitrusting en exploitatie van een grote fabriek te financieren, moest het vermogen van honderden of duizenden mensen worden samengebracht op de kapitaalmarkten. Dit maakte het moeilijker voor de gefragmenteerde en bijna anonieme eigenaren om hun eigendom te verdedigen. Ze werden vrijwel gedwongen om professionele bestuurders in te schakelen, die doorgaans slechts een fractie van de aandelen van het bedrijf in bezit hadden. Het vertrouwen op ondergeschikte managers verzwakte de weerstand van bedrijven tegen afpersing. De managers hadden weinig prikkels om hun leven of lichamelijke integriteit te riskeren ter bescherming van het eigendom van het bedrijf. Hun verzet bereikte zelden de felheid waarmee kleine ondernemers, zoals slijterijhouders, hun eigendom verdedigen.
5. _De grotere omvang van bedrijven betekende ook dat een groter deel van de totale beroepsbevolking in minder bedrijven werkzaam was dan ooit tevoren._ In sommige gevallen vonden tienduizenden arbeiders werk bij één enkel bedrijf. In militaire termen waren de eigenaars en managers ruimschoots in de minderheid ten opzichte van de personen in ondergeschikte functies. Verhoudingen van dertig tegen één of erger waren gebruikelijk. Dit nadeel nam toe met de bedrijfsgrootte, omdat enorme aantallen werknemers die samenkwamen, gemakkelijker geweld op anonieme wijze konden toepassen. Onder dergelijke omstandigheden hadden de werknemers waarschijnlijk geen betekenisvol contact of relaties met de eigenaren van de fabriek. Het anonieme karakter van deze relaties maakte het ongetwijfeld gemakkelijker voor werknemers om het belang van de eigendomsrechten van de eigenaren te negeren.
6. _Massale tewerkstelling in een klein aantal bedrijven was een breed maatschappelijk fenomeen._ Dit zorgde voor een verdere versterking van de megapolitieke voordelen van vakbonden vergeleken met het Amerika van de negentiende eeuw, toen de meeste mensen zelfstandig waren of in kleine bedrijven werkten. In 1940 had 6 procent van de Amerikaanse beroepsbevolking een baan als arbeider. Als gevolg hiervan vond het afdwingen van hogere lonen onder een groot aantal mensen, die dachten er zelf voordeel uit te halen, steeds meer steun. Dit werd geïllustreerd door een studie uit 1938-39 van de opvattingen van 1.700 mensen in Akron, Ohio, over het eigendom van corporaties. De enquête wees uit dat 68 procent van de CIO Rubber Workers weinig of geen sympathie had voor het idee dat corporaties eigendomsrecht mogen hebben, terwijl slechts één procent sterke steun voor het corporatieve eigendomsrecht toonde. Aan de andere kant viel geen enkele ondernemer, zelfs geen kleine eigenaar, in de categorie "sterke tegenstand tegen corporatief eigendom"; 94 procent kreeg beoordelingen in de categorie extreem hoge steun voor eigendomsrechten.
7. _Assemblagelijntechnologie was inherent sequentieel._ Het feit dat het hele productieproces afhankelijk was van het verplaatsen en assembleren van onderdelen in een vaste volgorde, creëerde extra kwetsbaarheden voor verstoring. In feite was de assemblagelijn als een spoorweg binnen de fabrieksmuren. Als het spoor geblokkeerd kon worden of de beschikbaarheid van één enkel onderdeel kon worden afgekapt, werd het hele productieproces stilgelegd.
8. _Assemblagelijntechnologie standaardiseerde arbeid._ Dit verminderde de afwijkingen in de output van personen met verschillende vaardigheden die met dezelfde gereedschappen werkten. In feite was een cruciaal doel van fabrieksontwerp het creëren van een systeem waarin een genie en een idioot op opeenvolgende ploegen van de assemblagelijn hetzelfde product zouden produceren. Wat men "domme" machines zou kunnen noemen, waren ontworpen om slechts één soort output te leveren. Dit maakte het zelfs voor de koper van een Cadillac overbodig om zich te informeren welke lijnarbeiders zijn voertuig produceerden. Alle producten waren bedoeld om gelijk te zijn, ongeacht de verschillen in vaardigheden en intelligentie tussen de werknemers die ze produceerden.

Het feit dat ongeschoolde arbeiders op de assemblagelijn hetzelfde product konden maken als meer bekwame individuen, droeg bij aan de egalitaire agenda doordat het de indruk wekte dat ieders economische bijdragen gelijk waren. Ondernemersvaardigheden en mentale inspanning leken minder belangrijk. De magie van moderne productie leek in de machines zelf te liggen. Zelfs als ze niet daadwerkelijk door iedereen ontworpen konden zijn, leken ze toch intellectueel toegankelijk voor bijna iedereen. Dit gaf meer geloofwaardigheid aan de fictie dat ongeschoolde arbeid "uitgebuit" werd door de fabriekseigenaar, die uit het proces zou kunnen worden gehaald zonder dat iemand er nadeel van zou ondervinden behalve de fabriekseigenaar zelf. "We hebben geleerd dat we de fabriek kunnen overnemen", zei een GM-staker. "We wisten al hoe we de fabriek moesten runnen. Als General Motors niet oppast, trekken we vanzelf de logische conclusies."

Deze kenmerken van industriële technologie leidden overal tot de oprichting van vakbonden om de kwetsbaarheid voor afpersing te benutten, en tot grotere overheden die profiteerden van de hoge belastingen die opgelegd konden worden aan grootschalige industriële faciliteiten. Dit gebeurde niet één of twee keer, het gebeurde overal waar grootschalige industrieën opkwamen. Steeds weer ontstonden vakbonden die geweld gebruikten om lonen ver boven de marktprijs te realiseren. Ze konden dit doen omdat industriële fabrieken duur, zichtbaar, immobiel en kostbaar waren. Ze konden nauwelijks worden verborgen of verplaatst. Elk moment dat ze buiten gebruik waren, betekende dat hun enorme kosten niet werden afgeschreven.

Hierdoor waren het makkelijke doelwitten voor dwangmatige afpersing, een feit dat veel duidelijker is in de geschiedenis van vakbonden dan de heersende ideologie van de twintigste eeuw doet geloven. De bekende econoom Henry Simons formuleerde het in 1944 als volgt:

> "Arbeidsorganisatie zonder grote macht tot dwang en intimidatie is een onrealistische abstractie. Vakbonden hebben nu zulke machten; ze hebben die altijd gehad en zullen die altijd hebben, zolang ze in de huidige vorm blijven bestaan. Waar de macht klein of onzeker is, moet deze openlijk en uitgebreid worden uitgeoefend; macht die groot en onaangevochten is, functioneert als overheid: zelfverzekerd, gerespecteerd en zelden opvallend tentoongesteld."

Hoewel Simons' analyse precies is, zat hij verkeerd op een cruciaal punt. Hij ging ervan uit dat vakbonden "altijd zullen hebben" wat hij beschreef als een "grote macht tot dwang en intimidatie." In werkelijkheid verdwijnen vakbonden, niet alleen in de Verenigde Staten en Groot-Brittannië, maar ook in andere volwassen industriële samenlevingen. De reden dat ze verdwijnen, wat Simons miste en wat zelfs veel vakbondsorganisatoren niet begrijpen, is dat de verschuiving naar een Informatiesamenleving de megapolitieke omstandigheden op cruciale manieren heeft veranderd, waardoor de veiligheid van eigendom sterk toeneemt. Microtechnologie heeft al bewezen de afpersing die de verzorgingsstaat ondersteunt te ondermijnen, omdat ze zelfs in de commerciële sfeer geheel andere prikkels creëert dan in de industriële periode.

1. _Informatie­technologie bevat nauwelijks natuurlijke hulpbronnen._ Ze biedt weinig of geen inherente locatievoordelen. De meeste informatietechnologie is zeer verplaatsbaar. Omdat het onafhankelijk van plaats kan functioneren, vergroot informatie­technologie de mobiliteit van ideeën, mensen en kapitaal. General Motors kon zijn drie assemblagelijnen in Flint, Michigan, niet inpakken en op het vliegtuig zetten. Een softwarebedrijf kan dat wel. De eigenaren kunnen hun algoritmen op draagbare computers downloaden en het eerstvolgende vliegtuig nemen. Dergelijke bedrijven hebben bovendien een extra prikkel om te ontsnappen aan hoge belastingen of vakbondseisen voor onredelijk hoge lonen. Kleinere bedrijven hebben meestal meer concurrenten. Als je tientallen of zelfs honderden concurrenten hebt die je klanten proberen te verleiden, kun je het je niet veroorloven om politici of werknemers veel meer te betalen dan ze daadwerkelijk waard zijn. Als jij dat alleen zou proberen, zouden je kosten hoger zijn dan die van je concurrenten en zou je failliet gaan. Het ontbreken van significante operationele voordelen op een bepaalde locatie betekent dat dwingende organisaties, zoals overheden en vakbonden, onvermijdelijk minder de mogelijkheid krijgen om deze voordelen voor zichzelf te benutten.
2. _Informatie­technologie verkleint de omvang van ondernemingen._ Dit leidt tot kleinere bedrijven, wat een groter aantal concurrenten betekent. Hoe meer concurrentie, hoe moeilijker afpersing wordt, omdat er meer doelwitten zijn die onder controle gehouden moeten worden om lonen of belastingen boven het competitieve niveau te brengen. De scherpe daling van de gemiddelde bedrijfsgrootte, gefaciliteerd door informatietechnologie, heeft het aantal personen in ondergeschikte posities al verminderd. In de Verenigde Staten, bijvoorbeeld, suggereren breed gerapporteerde schattingen dat in 1996 ongeveer 30 miljoen mensen zelfstandig in hun eigen bedrijf werkten. Uiteraard is het onwaarschijnlijk dat deze 30 miljoen tegen zichzelf in staking zullen gaan. Het is slechts iets minder aannemelijk dat de miljoenen mensen die werken in kleine bedrijven met een handvol werknemers hun werkgevers zouden proberen te dwingen tot lonen die hoger dan de marktprijs zijn. Werknemers die in het Informatietijdperk hun loon via dwang willen verhogen, missen het militaire voordeel van hun grote aantallen dat hen vroeger in de fabriek sterk maakte. Hoe minder mensen in een bedrijf werken, hoe minder mogelijkheden er zijn voor anoniem geweld. Door deze reden alleen al zouden tienduizend werknemers verdeeld over vijfhonderd bedrijven een kleinere bedreiging vormen voor het eigendom van die bedrijven dan tienduizend werknemers in één bedrijf, zelfs als de verhouding werknemers/eigenaren/managers exact hetzelfde was.
3. _Een kleinere omvang van ondernemingen betekent ook dat pogingen om lonen boven de marktprijs af te dwingen minder vaak brede maatschappelijke steun genieten, dan in de industriële periode._ Vakbonden die werkgevers proberen af te persen, zullen zich veel vaker in een vergelijkbare situatie bevinden als de kanaal-, spoorweg- en mijnwerkers van de negentiende eeuw. Zelfs waar enkele grootschalige bedrijven als overblijfselen uit het Industriële Tijdperk blijven bestaan, zullen ze dit doen in een context van wijdverspreide werkgelegenheid in kleine bedrijven. Het overwicht van kleine bedrijven en zelfstandigen duidt op bredere sociale steun voor eigendomsrechten, zelfs als de wens om inkomen te herverdelen onveranderd blijft.
4. _Informatie­technologie verlaagt de kapitaalkosten, wat ook de concurrentie bevordert door ondernemerschap te vergemakkelijken en meer mensen in staat te stellen zelfstandig te werken._ Lagere kapitaaleisen verminderen niet alleen de toetredingsdrempels, maar ook de "uitgangsdrempels." Met andere woorden: bedrijven zullen waarschijnlijk minder activa hebben ten opzichte van hun inkomsten en daardoor een kleiner vermogen om verliezen te dragen. Bedrijven in het Informatietijdperk zullen niet alleen minder vaak bij banken hoeven lenen, maar zullen waarschijnlijk ook minder fysieke activa hebben om te benutten.
5. _Informatie­technologie verkort de productcyclus._ Dit leidt tot snellere productveroudering. Ook hierdoor blijven winsten die voortkomen uit het afpersen van hogere lonen boven het markt­niveau niet lang bestaan. In sterk concurrerende markten kunnen te hoge lonen direct leiden tot het verlies van banen en zelfs het faillissement van het bedrijf. Pogingen om tijdelijk hogere lonen te verkrijgen ten koste van het behoud van je baan zijn als het verbranden van je meubels om het huis een paar graden warmer te maken.
6.  _Informatie­technologie is niet sequentieel maar gelijktijdig en verspreid._ In tegenstelling tot de assemblagelijn kan informatietechnologie meerdere processen tegelijkertijd accommoderen. Het verdeelt activiteiten over netwerken, waardoor redundantie en substitutie mogelijk zijn tussen de duizenden of zelfs miljoenen werkstations overal ter wereld. In een toenemend aantal activiteiten kunnen mensen samenwerken zonder ooit fysiek contact met elkaar te hebben. Naarmate virtual reality en videoconferencing zich verder ontwikkelen, zal de trend naar het decentraliseren van functies en telewerken versnellen. Dit is het Informatietijdperk-equivalent van "huisnijverheid", dat de macht van de middeleeuwse gilden brak. Het feit dat steeds minder mensen samen in rokerige fabrieken werken, neemt niet alleen een belangrijk voordeel weg dat werknemers vroeger hadden bij het afdwingen van geld van kapitalisten; het maakt het ook steeds moeilijker om het soort afpersing dat acceptabel was op de werkvloer nog te onderscheiden van georganiseerde misdaad. Tot nu toe mochten alleen personen die samenwerkten en door een bedrijf in een gemeenschappelijke setting werden tewerkgesteld, geweld gebruiken om hun inkomen te verhogen. Als de "werkplek" echter niet bestaat als centrale locatie, en de meeste functies zijn verspreid over onderaannemers en telewerkers, lijken hun pogingen om geld te eisen van hun klanten of "werkgevers" toch sterk op een afpersingspraktijk. Bijvoorbeeld, is een telewerker die onder dreiging van een virus extra geld eist een stakende werknemer? Of een internetcrimineel?

    Of hij het ene of het andere is, zal uiteindelijk weinig verschil maken. De reactie van de getroffen bedrijven zal in elk geval grotendeels hetzelfde zijn. Technische oplossingen tegen informaticasabotage die hackers buiten houden, zoals sterke encryptie en beveiligde netwerken, zullen eveneens verhinderen dat ontevreden werknemers of onderaannemers schade aanrichten aan hun klanten of partners. Natuurlijk kan worden gesteld dat de werknemer of telewerker altijd naar kantoor kan komen om een meer traditionele staking uit te voeren, maar zelfs dit is misschien niet zo eenvoudig als het lijkt in het Informatietijdperk. Het vermogen van informatietechnologie om lokale beperkingen te overstijgen en economische functies te verspreiden betekent dat werknemers en werkgevers voor het eerst niet eens in dezelfde rechtsgebieden hoeven te wonen. Hier gaat het niet om het verschil tussen wijken als Mayfair en Peckham, maar om werkgevers in Bermuda en telewerkers in New Delhi.

    Mocht de fascinatie van de Indiërs voor de grote GM-stakingen van 1936-37 hen naar Bermuda leiden om te demonstreren, dan zouden ze bij aankomst wellicht totaal geen fysiek kantoor aantreffen. Chiat/Day, een groot reclamebedrijf, heeft haar hoofdkantoor al grotendeels ontmanteld. Werknemers of onderaannemers blijven in contact via call-forwarding en het Internet. Wanneer het nodig is om teams samen te stellen voor projecten, huren ze vergaderruimtes in hotels. Na afloop van het project checken ze uit. Het feit dat microprocessing helpt met het bevrijden van het productieproces en het verspreiden van de vaste volgorde van de assemblagelijn, vermindert de macht die dwingende organisaties zoals vakbonden en overheden vroeger hadden aanzienlijk. Als de assemblagelijn een spoorweg binnen fabrieksmuren voorstelde die gemakkelijk door een zitstaking kon worden veroverd, is cyberspace een grenzeloos domein zonder fysieke aanwezigheid. Het kan niet met geweld worden bezet of worden gegijzeld. De positie van werknemers die geweld willen gebruiken als pressiemiddel om een hoger inkomen af te dwingen, zal in het Informatietijdperk veel zwakker zijn dan ten tijde van de zitstakingen bij General Motors in 1936-37.
7.  _Microprocessing individualiseert werk. Industriële technologie standaardiseerde werk._ iedereen die dezelfde gereedschappen gebruikte, produceerde hetzelfde resultaat. Microtechnologie vervangt "domme" machines door intelligentere machines die een sterk variabele output kunnen leveren. Deze toegenomen variabiliteit van output heeft ingrijpende gevolgen. Belangrijk is dat waar de output varieert, ook de inkomens variëren. In markten waar talent en vaardigheden uiteenlopen, zal een klein aantal mensen meestal het leeuwendeel van de waarde produceren, wat typisch is voor de meest concurrerende sectoren. Dit is vrij duidelijk te zien in bijvoorbeeld sport. Miljoenen jongeren spelen wereldwijd voetbal, maar 99% van het geld dat wordt uitgegeven aan het kijken van voetbal gaat naar een zeer klein aantal spelers. Ook bereiken slechts enkele acteurs een sterrenstatus en ontvangen een klein aantal auteurs van de tienduizenden boeken die jaarlijks uitgegeven worden het grootste deel van de royalty's. Jammer genoeg maken wij geen deel uit van die groep.

    De enorme variabiliteit in output tussen personen die hetzelfde materiaal gebruiken, vormt opnieuw een obstakel voor afpersing. Het veroorzaakt een groot onderhandelingsprobleem over hoe de opbrengst verdeeld dient te worden. Wanneer een relatief klein deel van de deelnemers aan een bepaalde activiteit het grootste deel van de waarde creëert, is het vrijwel wiskundig onmogelijk dat zij erop vooruitgaan als de inkomens onder dwang worden gemiddeld. De ene softwareprogrammeur kan een algoritme voor het aansturen van een robot ontwikkelen dat miljoenen waard blijkt te zijn. Een ander, die met exact dezelfde spullen werkt, kan een programma schrijven dat niets waard is. De productievere programmeur zal net zo min willen dat zijn inkomen gekoppeld wordt aan dat van zijn collega als dat Tom Clancy zou instemmen met het middelen van zijn boekroyalties met de onze.\
    \
    Al in de beginfase van de Informatiesamenleving werd duidelijker dan in 1975 dat economische output sterk afhankelijk is van vaardigheden en intellectuele bekwaamheid. Dit heeft de ooit trotse rechtvaardiging voor afpersing van kapitalisten door arbeiders uit de industriële periode al tenietgedaan. De gedachte dat ongeschoolde arbeid werkelijk de waarde creëerde die kennelijk in onevenredig grote mate door kapitalisten en ondernemers werd opgeëist, is al achterhaald. Het is niet eens een plausibele fictie in het geval van informatietechnologie. Bij een programmeur is er een te direct verband tussen zijn vaardigheid en zijn product om veel twijfel te laten over wie verantwoordelijk is. Het is onbetwistbaar duidelijk dat een analfabeet of semi-geletterde geen computer kan programmeren. Het is daarom even duidelijk dat waarde in programma's die door anderen zijn samengesteld, niet van hem gestolen kan zijn. Daarom is het geroep over "uitbuiting" van arbeiders nu vooral aanwezig onder schoonmakers.\
    \
    Informatietechnologie maakt duidelijk dat het probleem van mensen met lage vaardigheden niet is dat hun productieve capaciteiten oneerlijk worden uitgebuit, maar eerder de angst dat zij mogelijk niet in staat zijn een echte economische bijdrage te leveren. Zoals Kevin Kelly suggereert in _Out Of Control_, kan het "Upstart"-autobedrijf van het Informatietijdperk het geesteskind zijn van "een dozijn mensen", die het merendeel van hun onderdelen uitbesteden en toch auto's produceren die zorgvuldiger zijn aangepast aan de wensen van hun kopers dan alles wat tot nu toe uit Detroit of Tokio is gekomen: "Auto's, elk op maat gemaakt voor de klant, worden besteld via een netwerk van klanten en verzonden zodra ze klaar zijn. Mallen voor de carrosserie worden snel gevormd door computergestuurde lasers en gevoed met ontwerpen die zijn gegenereerd op basis van communicatie met de klant en doelgerichte marketing. Een flexibele productielijn van robots assembleert de auto's. De reparatie en verbetering van de robots wordt uitbesteed aan een robotbedrijf."

### "Gereedschap met een stem"

In toenemende mate kan ongeschoold werk worden gedaan door geautomatiseerde machines, robots en computersystemen zoals digitale assistenten. Toen Aristoteles slaven beschreef als "werktuigen met een stem", doelde hij op mensen. In de nabije toekomst zal "Gereedschap met een stem", zoals de geesten uit sprookjes, kunnen spreken, instructies opvolgen en zelfs complexe opdrachten uitvoeren. De snel toenemende rekenkracht heeft al geleid tot een aantal primitieve toepassingen van spraakherkenning, zoals handsfree-telefoons en computers die wiskundige berekeningen uitvoeren op basis van mondelinge instructies. Computers die spraak omzetten naar tekst werden eind 1996, toen wij dit schreven, al op de markt gebracht. Naarmate patroonherkenning beter wordt, zullen computers gekoppeld aan stem­synthesizers via netwerken talloze functies uitvoeren die vroeger werden gedaan door mensen die werkten als telefonisten, secretaresses, reisagenten, administratieve assistenten, schaakkampioenen, schade-experts, componisten, obligatiehandelaren, cyberoorlogsspecialisten, wapenanalisten, of zelfs gewiekste flirtmachines die de telefoon aannemen bij 0900-lijnen.

Michael Mauldin van Carnegie-Mellon University heeft een kunstmatige persoonlijkheid geprogrammeerd, genaamd Julia, die bijna iedereen kan misleiden met wie zij online een gesprek voert. Volgens persberichten is Julia een gevatte dame die haar leven leidt in een rollenspel op internet. Ze is slim, grappig en houdt van flirten. Ze is ook een beetje een hockeyfanaat en kan op elk moment de perfecte sarcastische opmerking maken. Julia is echter geen dame. Ze is een bot, een kunstmatige intelligentie die alleen bestaat in de ether van het Internet. De opmerkelijke vooruitgang die al is geboekt in het programmeren van kunstmatige intelligentie en digitale dienaren laat weinig twijfel bestaan dat er nog vele praktische toepassingen zullen volgen. Dit heeft ingrijpende megapolitieke gevolgen.

### Het individu als ensemble

De ontwikkeling van "gereedschap met een stem" voor meerdere toepassingen schept de mogelijkheid om het individu te verdelen over meerdere gelijktijdige activiteiten. Het individu zal wellicht niet langer enkelvoudig zijn, maar een ensemble van tientallen of zelfs duizenden activiteiten die worden uitgevoerd via intelligente assistenten. Dit zal niet alleen de productieve capaciteit van de meest begaafde individuen enorm vergroten, maar heeft ook de potentie om het Soevereine Individu veel krachtiger te maken in militair opzicht dan ooit tevoren.

Eén individu zal zijn activiteiten zichtbaar kunnen vermenigvuldigen door een vrijwel onbeperkt aantal intelligente assistenten in te zetten. Hij of zij zal zelfs na de dood kunnen handelen. Voor het eerst zal een individu in staat zijn uitgebreide taken uit te voeren, zelfs als hij biologisch dood is. Het doden van een individu zal voor een crimineel of een vijand in oorlogstijd niet langer de mogelijkheid tot wraak volledig wegnemen. Dit is een van de meest revolutionaire innovaties in de logica van geweld in de hele geschiedenis.

### Inzichten voor het Informatietijdperk

De grootste veranderingen in het leven doen zich voor bij variabelen die niemand in de gaten houdt. Of anders gezegd: we nemen variabelen als vanzelfsprekend aan die eeuwenlang of zelfs honderden generaties nauwelijks zijn veranderd. Gedurende het grootste deel van de geschiedenis, zo niet van het menselijk bestaan, bewoog het evenwicht tussen bescherming en afpersing zich binnen een smalle marge, waarbij afpersing altijd de overhand had. Dat staat nu op het punt te veranderen. Informatietechnologie legt de basis voor een fundamentele verschuiving in de factoren die de kosten en baten van het toepassen van geweld bepalen. Het feit dat intelligente assistenten beschikbaar zullen zijn om onderzoek te doen en mogelijk op de een of andere manier wraak te nemen op degenen die geweld initiëren, is slechts een voorproefje van dit nieuwe perspectief op bescherming. Vijfentwintig jaar geleden zou de volgende uitspraak niet meer zijn geweest dan het geraas van een zonderling: "Als je mij doodt, zal ik het geld van je bankrekeningen wegsluizen en het schenken aan liefdadigheid in Nepal." Na de eeuwwisseling hoeft dat niet langer ondenkbaar te zijn. Of het een praktische dreiging vormt, zal afhangen van tijd en plaats. Maar zelfs als de rekeningen van de misdadiger ontoegankelijk blijken, zal er ongetwijfeld ander kostbaar onheil zijn dat een leger van intelligente assistenten kan aanrichten als vergelding voor een misdrijf. Denk daar maar eens over na.

### Nieuwe alternatieven voor bescherming

Dit is slechts één van de vele manieren waarop de technologie van het Informatietijdperk nieuwe mogelijkheden opent voor bescherming. De meeste daarvan ondermijnen de bijna-monopoliepositie van overheden op bescherming en afpersing die zij de afgelopen twee eeuwen hebben genoten. Zelfs zonder de nieuwe technologische toeters en bellen hebben er altijd alternatieven bestaan voor bescherming die niet door de overheid werden gemonopoliseerd.

Iemand die zich bedreigd voelt, kan simpelweg wegrennen. Toen de wereld nog jong was en de horizon openlag, werd deze optie vaak benut. Wie zich zorgen maakt over diefstal of vandalisme kan besluiten een verzekeringspolis af te sluiten om dergelijke risico's af te dekken. Vervloekingen en bezweringen, hoewel zwakke vormen van bescherming, hebben ook levens gered en diefstal voorkomen in samenlevingen met bijgelovige criminelen. Waardevolle spullen kunnen daarnaast, waar mogelijk, met relatief succes beschermd worden door ze te verbergen. Bezittingen kunnen worden begraven, beveiligd met sloten, achter hoge muren geplaatst, of voorzien van sirenes en elektronische bewaking. Het verbergen van personen en eigendommen is echter niet altijd praktisch gebleken.

Ondanks de verscheidenheid aan beschermingsmiddelen die in de geschiedenis zijn gebruikt, heeft één methode alle andere gedomineerd: het vermogen om geweld met geweld te beantwoorden, door een grotere macht in te zetten om elke potentiële aanvaller of dief te overmeesteren. De vraag is tot wie je je kunt wenden voor zo'n dienst, en hoe je iemand kunt motiveren zijn hele hebben en houden te riskeren om je te helpen tegen boeven die geweld tegen je willen gebruiken. Soms hebben naaste familieleden gehoor gegeven aan die roep. Soms hebben tribale ­groepen of clans als onofficiële politie gefungeerd, door geweld tegen een van hun leden te beantwoorden met bloedwraak. Soms werden huurlingen of privéwachten ingehuurd om aanvallen af te slaan, maar niet altijd met het gewenste resultaat. De nieuwe intelligente assistenten van het Informatietijdperk voegen een nieuw alternatief toe, hoewel hun activiteiten grotendeels beperkt zullen blijven tot de cyberspace. Bij hen is er, in tegenstelling tot die van huurlingen, privéwachten of zelfs verre verwanten, geen twijfel over hun loyaliteit.

### De paradoxen van de macht

Het gebruik van geweld ter bescherming tegen geweld zit vol paradoxen. Onder de omstandigheden die tot nu toe hebben bestaan, gold dat elke groep of instantie die je kon inzetten om je leven en bezit met succes te beschermen tegen een aanval, noodzakelijkerwijs ook de capaciteit had om die af te nemen. Dat is een nadeel waarvoor geen eenvoudige oplossing bestaat. Normaal gesproken kun je rekenen op concurrentie om aanbieders van een economische dienst ervan te weerhouden de wensen van hun klanten te negeren. Maar waar het geweld betreft, heeft directe concurrentie vaak averechtse gevolgen. In het verleden leidde dit meestal tot meer geweld. Wanneer twee potentiële beschermingsinstanties hun troepen uitzonden om elkaar te arresteren, resulteerde dat meer in burgeroorlog dan in bescherming. Wanneer je bescherming zoekt tegen geweld, wil je normaal gesproken niet dat de hoeveelheid geweld toeneemt, maar dat deze wordt onderdrukt. En wel op voorwaarden die niet toestaan dat de klanten die voor de beschermingsdienst betalen, zelf geplunderd worden.

> ...wanneer mensen leven zonder een gemeenschappelijke macht die hen allen ontzag inboezemt, bevinden zij zich in de toestand die oorlog wordt genoemd: en wel een oorlog van ieder mens tegen ieder mens, waarin mensen geen andere zekerheid hebben dan wat hun eigen kracht en vindingrijkheid hen kan verschaffen. -- THOMAS HOBBES

### Monopolie en anarchie

Dit is de reden waarom anarchie, of "de oorlog van allen tegen allen", zoals Hobbes het beschreef, zelden een bevredigende toestand is geweest. Lokale concurrentie in het gebruik van geweld betekende meestal hogere kosten voor minder feitelijke bescherming. Af en toe hebben enthousiaste vrijemarktdenkers gesuggereerd dat marktmechanismen alleen voldoende zouden zijn om eigendomsrechten en levens te beschermen, zonder dat er enige soevereiniteit nodig zou zijn. Sommige van de analyses waren elegant, maar feit blijft dat de voorziening van politiediensten en justitie door de vrije markt onder de megapolitieke voorwaarden van het industrialisme niet levensvatbaar is gebleken. Alleen primitieve samenlevingen met kleine en homogene populaties waarin gedrag sterk gestandaardiseerd was, konden overleven zonder overheden die via geweld de gemonopoliseerde lokale beschermingsdienst leverden.

Voorbeelden van anarchistische samenlevingen boven het niveau van de jager-verzamelaarsstam zijn schaars en oud. Het waren allemaal erg eenvoudige economieën zoals regenwaterboeren in afgelegen gebieden, de Kafirs in pre-islamitisch Afghanistan, sommige Ierse stammen in de donkere middeleeuwen, enkele indianenstammen in Brazilië, Venezuela en Paraguay, en andere inheemse groepen verspreid over de wereld. Hun methoden om bescherming zonder overheid te organiseren, zijn alleen bekend bij kenners van extreme gevallen. Wie daar meer over wil weten, kan in onze voetnoten meerdere boeken vinden met verdere details. Primitieve groepen konden functioneren zonder een aparte organisatie die gespecialiseerd was in geweld, enkel omdat zij kleine, gesloten en geïsoleerde samenlevingen waren. Ze konden om zich te verdedigen tegen de meeste gewelddreigingen op kleine schaal, de enige soort waarmee zij waarschijnlijk te maken kregen, terugvallen op hechte familiebanden. Wanneer zij grotere bedreigingen tegenkwamen, georganiseerd door staten, werden zij overmeesterd en onderworpen aan een door externe groepen gemonopoliseerde heerschappij. Dit gebeurde steeds opnieuw. Overal waar samenlevingen ontstonden boven het niveau van clans en stammen, vooral waar handelsroutes verschillende volkeren met elkaar in contact brachten, kwamen er altijd specialisten in geweld op om de surplusproductie van vreedzamere mensen te plunderen. Wanneer technologische omstandigheden het rendement van geweld verhoogden, waren samenlevingen die niet georganiseerd waren om grote middelen in oorlogvoering te steken gedoemd te verdwijnen.

> Welke vorsten leverden de dienst van politie? Welke waren afpersers of zelfs plunderaars? Een plunderaar kon in feite de politiechef worden zodra hij zijn 'opbrengst' met regelmaat inde, deze afstemde op het betalingsvermogen, zijn gebied verdedigde tegen andere plunderaars en zijn territoriale monopolie lang genoeg handhaafde totdat gewoonte het legitiem maakte. -- FREDERIC C. LANE

### Overheid als verkoper van bescherming

Zoals we al meerdere keren hebben gesteld, is de voornaamste economische functie van de overheid, vanuit het perspectief van degenen die belastingen betalen, het bieden van bescherming van leven en eigendom. Toch functioneert de overheid vaak als georganiseerde misdaad, door middelen af te romen van mensen binnen haar invloedssfeer in de vorm van een heffing of gewoon ordinaire diefstal. De overheid is niet alleen een beschermingsdienst; het is een beschermingsmaffia. Terwijl de overheid bescherming biedt tegen geweld van buitenaf, vraagt zij, net als de maffia, ook geld voor bescherming tegen schade die zij anders zelf zou toebrengen. De eerste handeling is een economische dienst. De tweede is afpersing. In de praktijk kan het lastig zijn om deze twee vormen van "bescherming" te onderscheiden. Overheden, merkte Charles Tilly op, kunnen misschien het best worden begrepen als "onze grootste voorbeelden van georganiseerde misdaad."

Zelfs de beste overheid leverde meestal een mengvorm van bescherming gecombineerd met afpersing. Historisch gezien konden beiden het meest effectief worden uitgevoerd wanneer de overheid nagenoeg een monopolie op dwang kon opleggen binnen de gebieden waar zij actief was. In gevallen waar één gewapende groep de overhand kon krijgen in het gebruik van geweld, was de kwaliteit van de bescherming die zij kon bieden doorgaans veel beter dan die van meerdere concurrerende leveranciers van beschermingsdiensten die om hetzelfde territorium vochten.

### Een natuurlijk monopolie op land

Het bereiken van een lokaal monopolie op dwang stelde een overheid niet alleen in staat haar potentiële klanten effectiever te beschermen tegen geweld van buitenaf; het verlaagde ook sterk de operationele kosten. Zoals Lane het formuleerde: "De industrie die geweld toepast en geweld beheerst was een natuurlijk monopolie, althans op land. Binnen territoriale grenzen kon de dienst die zij leverde veel goedkoper worden geproduceerd door een monopolie." Zo stelde "een monopolie op het gebruik van geweld binnen een aaneengesloten gebied een bescherming producerende onderneming in staat haar product te verbeteren en de kosten te verlagen." Een dergelijke organisatie kon meer bescherming bieden tegen lagere kosten, zolang zij niet voortdurend militaire acties hoefde te voeren om concurrerende groepen af te weren die eveneens geld wilden innen bij haar klanten.

Het vooruitzicht dat informatietechnologie zal bijdragen aan het "versoepelen" van de aanname dat soevereiniteit gebaseerd moet zijn op een territoriaal monopolie, heeft al de aandacht getrokken van politieke theoretici. Het is het centrale thema van _Beyond Sovereignty: Territory and Political Economy in the Twenty-First Century_, van David J. Elkins. Elkins sluit zich aan bij onze these dat monopolistische overheden dezelfde desintermediatie tegemoet gaan als religieuze monopolies na 1500. Hij schrijft: "We namen vroeger aan dat religies hun eigen territorium of 'domein' moesten hebben. Toen naties universele religies vervingen als soevereine scheidsrechters over leven en dood, maakten de 'compactheid' en de 'afgebakendheid' van religie plaats voor het ons inmiddels vertrouwde vermengen van verscheidene gelovigen in hetzelfde gebied. Daarentegen weigeren we het vermengen van naties, of zelfs provincies, te accepteren, hoewel ik geloof dat deze aanname bezig is te verdwijnen." Hij betoogt verder, geheel in lijn met onze visie, dat territoriale monopolies op soevereiniteit kunnen worden afgebroken zonder dat dit tot anarchie hoeft te leiden. Bewijzen daarvoor zijn de verdeling van soevereiniteit tussen nationale en provinciale regeringen in een federaal systeem zoals dat van Canada, en het condominium-bestuur met gezamenlijke Franse en Britse soevereiniteit dat een aantal eilanden in de Stille Oceaan gedurende een groot deel van deze eeuw kenmerkte. Territoriale monopolies op soevereiniteit zijn dus zelden met geweld ontmanteld, maar kunnen wel door middel van overeenstemming worden ontbundeld. Volgens Elkins, en wij zijn het daarmee eens, "is de territoriale natiestaat een bundel of mand waarin andere aspecten van ons leven passen. Het is vergelijkbaar met het economische concept van een 'mand' goederen; je kunt de goederen niet afzonderlijk verkrijgen, maar neemt het geheel. In een restaurant kan men à la carte bestellen, maar wat betreft onze identiteiten moeten we nemen wat naties samenbundelen, wat neerkomt op 'table d'hôte'... Een overheid _à la carte_ zal voor burgers in de eenentwintigste eeuw vanzelfsprekend lijken." Geen ontwikkeling zal meer bijdragen aan de ontbundeling van soevereiniteit en de opkomst van de overheid _à la carte_ dan de opkomst van een cyber­economie die fysieke grenzen volledig overstijgt.

> Wanneer frequenties stijgen en golflengtes dalen, verbetert digitale prestatie exponentieel. Bandbreedte stijgt, energieverbruik daalt, antenneformaten krimpen, interferentie stort in, foutenmarges kelderen. -- GEORGE GILDER

## De wet van de telekosmos heft de wetten van naties op

Wij zijn niet de enigen die inzien dat bandbreedte (of het draagvermogen van communicatiemedia) het territoriale staatsmodel zal overschaduwen. Jim Taylor en Watts Wacker, auteurs van _The 500-Year Delta: What Happens After What Comes Next_, formuleren hun betoog anders dan wij, maar erkennen dat "toegang globalisme creëert, en globalisme politieke systemen ontwricht, waardoor het concept van grenzen achterhaald raakt. Naarmate grenzen verdwijnen, wordt het concept van belastingheffing, dat overheden ondersteunt, steeds fragieler... Naarmate grenzen verdwijnen, valt ook het concept van aanspraak uiteen, het geloof dat je, omdat je op een bepaalde plek bent geboren, recht hebt op de economische voordelen van die plek, en daarmee verdwijnen de privileges van het staatsburgerschap. En terwijl dat gebeurt, worden de idealen die nationaliteit onderbouwen, namelijk patriottisme, democratie, de staat, de smeltkroes, eenheid, verantwoord burgerschap, of welke idealen in welk land dan ook, verwezen naar de geschiedkundige vuilnisbelt." Zonder het expliciet te zeggen, voelen ook zij blijkbaar dat de geschiedenis richting de bevrijding van het Soevereine Individu beweegt. Zoals ze stellen: "Aan de horizon wacht een veel zuiverdere vorm van individualisme dan democratie, zoals wij die nu begrijpen, toelaat." Hoe zal dit gebeuren? Taylor en Wacker zien een krachtige dynamiek aan het werk:

Het simpele feit is dat het bredere gevoel van patriottisme, de liefde voor de natie en een gevoel van kinderlijke plicht eraan, niet langer een bijzonder nuttige instelling is. Burgers die gedijen in de mondiale samenleving zullen hun keuzes niet baseren op nationale identiteit, maar op politieke, sociale en economische identiteiten die direct verbonden zijn met hun eigen belangen. Zij zullen zich daarnaar organiseren. Ze zullen hun vrijheid om te weten, te reizen, te handelen en te zijn, maximaliseren. Naties en bedrijven die dat niet doen, die achterhoedegevechten blijven voeren uit nostalgie, zullen wegkwijnen.

De ontwaarding van fysieke grenzen, die wordt geïmpliceerd door de jaarlijkse verdrievoudiging van de bandbreedte en de exponentiële groei van het internet en het World Wide Web, zal het proces van desintermediatie van overheden versnellen. Een voortzetting van de jaarlijkse verdrievoudiging van de bandbreedte tot 2012 zou een miljardvoudige groei betekenen sinds 1993, toen George Gilder voor het eerst suggereerde dat bandbreedte nog sneller zou verdubbelen dan de capaciteit van microprocessors. Indien dit werkelijkheid wordt, en daar rekenen wij op gezien recente doorbraken in geïntegreerde optica, zal de overvloed aan communicatiemogelijkheden leiden tot een enorme toename van cybercommerce. Met wave division multiplexing kan een enkele glasvezel, zo dun als een mensenhaar, één biljoen bits per seconde vervoeren. Met andere woorden: een enkele glasvezelkabel zou vijfentwintig keer meer bits kunnen verwerken dan de totale capaciteit van alle communicatienetwerken ter wereld samen. De uitbreidingsmogelijkheden zijn verbijsterend. Met zoveel communicatiemogelijkheden, en de extreem lage kosten ervan, zal er enorm veel meer geld naar communicatie vloeien. Traditionele media zoals vaste telefonie en televisie zullen anachronismen worden. Het World Wide Web zal een rijkere mix van signalen naar elke computer brengen dan consumenten vandaag met televisienetwerken ervaren. Naarmate de bandbreedterevolutie zich ontvouwt, zullen mensen steeds verder worden meegezogen in de grenzeloze virtuele wereld van online gemeenschappen en cybercommerce, een wereld met voldoende grafische dichtheid om de "metaverse" te worden, de alternatieve cyberspace-realiteit zoals beschreven door sciencefictionauteur Neal Stephenson. Stephensons "metaverse" is een virtuele gemeenschap met eigen wetten, machthebbers en schurken.

Naarmate steeds meer economische activiteit wordt verplaatst naar de cyberspace, zal de waarde van het monopolie van staten binnen fysieke grenzen afnemen, waardoor ze steeds meer geprikkeld zullen worden om hun soevereiniteit uit te besteden en te fragmenteren. Zoals natiestaten nu prikkels hebben om vrijhavens, vrijhandelszones en _zona francas_ te hosten, zo zullen zij prikkels hebben om hun soevereiniteit te verhuren. Wij hebben al gesproken over de vergevorderde onderhandelingen tussen de negenhonderd jaar oude Soevereine Militaire Hospitaalorde van Sint-Jan van Jeruzalem, van Rhodos en van Malta, beter bekend als de Orde van Malta, en de Republiek Malta om de soevereiniteit over Fort Sint-Angelo terug te geven aan de Orde. Wij verwachten dat deze onderhandelingen succesvol zullen worden afgerond. Anderen zullen volgen. Sommige staten zullen soevereiniteit afstaan over kleine enclaves en afgelegen gebieden aan geheel nieuwe groeperingen en virtuele gemeenschappen. Het is zelfs niet onwaarschijnlijk dat commerciële partijen, zoals beveiligingsbedrijven en hotelketens, zullen bieden op soevereiniteit over kleine stukken grond. Wackenhut, Pinkerton en Argenbright zouden in de toekomst hybride omheinde gemeenschappen voor gepensioneerden en belastingvrije zones kunnen aanbieden in aantrekkelijke klimaten wereldwijd. Religieuze ordes, zoals de Orde van Malta, maar dan van elke denkbare denominatie, zullen op hun manier proberen een hemel op aarde te creëren in afgelegen uithoeken. Zelfs rijke individuen en families zullen hun eigen domeinen bezitten waar zij beperkte soevereiniteit uitoefenen, eigen postzegels en paspoorten uitgeven en een website onderhouden.

## Monopolie en plundering

Het is belangrijk op te merken dat de motieven voor het delen of verhuren van soevereiniteit tegen betaling anders zijn dan de prikkels waarmee heersers in het verleden te maken hadden, toen hun monopolie op geweld door rivalen werd uitgedaagd. Verhuurde soevereiniteit is net zo weinig destabiliserend als het vestigen van een vrijhandelszone. Daarentegen beïnvloedt militaire machtsstrijd, zoals die van strijdende krijgsheren en guerrillabendes, rechtstreeks of een aspirant-overheid meer prikkels heeft om de bevolking te beschermen of juist te plunderen. Waar rivaliserende groepen in een wankel evenwicht manoeuvreren, nemen de prikkels tot roofzuchtig geweld toe. Plundering wordt aantrekkelijker, omdat de macht minder stabiel is en het lokale geweldsmonopolie minder zeker. Het verkort de tijdshorizonten van wie geweld kan inzetten. De "koning van de berg" staat op zo'n glibberige helling dat hij er niet op kan rekenen lang genoeg te overleven om een aandeel te realiseren in de grote winsten die uiteindelijk voortvloeien uit het indammen van geweld. In dat geval is er weinig dat de gezaghebbenden ervan weerhoudt om hun macht te gebruiken om de samenleving te terroriseren en te plunderen.

De logica van dwang leert dus dat hoe meer gewapende groepen er in een gebied actief zijn, des te groter de kans is dat zij roofzuchtig geweld zullen inzetten. Zonder een overweldigende macht die freelance-geweld onderdrukt, heeft het de neiging zich te verspreiden, en gaan veel van de baten van economische en sociale samenwerking in rook op.

De schade die kan ontstaan wanneer geweld vrij spel krijgt in een toestand van anarchie, wordt geïllustreerd door het lot van China onder de krijgsheren in de jaren twintig. Dit verhaal vertelden wij in _The Great Reckoning_. De rivaliserende krijgsheren richtten grote schade aan in gebieden waar geen enkele overweldigende macht hen in toom kon houden. Soortgelijke verhalen, die hetzelfde punt duidelijk maken, zijn wereldwijd in levendige kleuren uitgezonden door CNN-reportages vanuit de straten van Mogadishu, Somalië. De strijdkrachten van de Somalische krijgsheren, bijgenaamd de "technicals", brachten anarchie naar dat gehavende land voordat de Verenigde Staten een massale militaire interventie leidden om hen in te dammen. Toen de Amerikaanse troepenmacht zich terugtrok, kwamen de technicals opnieuw met hun wapens tevoorschijn, en hervatte de anarchie zich. Een verslag in de _Washington Post_ merkte op:

> \[P]ick-uptrucks met luchtafweerkanonnen rijden opnieuw door de stoffige, met puin bezaaide straten. Ook zijn de zelfverzekerde jonge mannen terug, in T-shirts met Kalasjnikovs nonchalant over hun schouders, die geld afpersen van passerende auto's en bussen bij geïmproviseerde wegversperringen. Eén wijk hier wordt bestuurd door zo'n zwaar gewapende militie dat de lokale bevolking ernaar verwijst als 'Bosnië-Herzegovina.' Rondrijden door de gevaarlijke straten van deze stad doet vandaag sterk denken aan 1992, toen chaotische gevechten tussen rivaliserende milities Somalië in anarchie en een hongersnood stortten die een door de VS geleide interventie uitlokte. Opnieuw moeten reizigers om Mogadishu te doorkruisen een wagen vol gewapende knokploegen inhuren, in de hoop dat zij bescherming bieden voor honderd dollar per dag, plus lunchpauze.

De voorbeelden van Somalië, Rwanda en anderen die u binnenkort op televisie zult zien, leveren in kleur het bewijs dat een gewelddadige strijd om territoriale controle niet dezelfde directe economische voordelen oplevert als andere vormen van competitie. Integendeel. De rondtrekkende bendes en plunderaars die onder anarchie opereren, missen zelfs de zwakke prikkels om productieve activiteit te beschermen die dictators soms nog wel hebben zodra hun heerschappij veiliggesteld is.

> De samenleving die wij de moderne tijd noemen, wordt in het Westen bovenal gekenmerkt door een bepaald niveau van monopolisering. Vrij gebruik van militaire wapens is de individuele burger ontzegd en voorbehouden aan een centrale autoriteit van welke aard dan ook, en evenzo is de belastingheffing op eigendom of inkomen van individuen geconcentreerd in de handen van een centrale maatschappelijke autoriteit. De financiële middelen die zo naar deze centrale autoriteit vloeien, onderhouden haar monopolie op militaire macht, terwijl dit op zijn beurt het belastingmonopolie in stand houdt. Geen van beide heeft in enige zin voorrang op de ander; het zijn twee kanten van hetzelfde monopolie. Als het ene verdwijnt, volgt het andere automatisch; het monopolie kan af en toe harder wankelen aan de ene zijde dan aan de andere. -- NORBERT ELIAS

## De evolutie van bescherming

Lane ontwikkelde een argument dat wij ons voor onze analyse van hoe het Informatie­tijdperk zich mogelijk zal ontvouwen eigen hebben gemaakt. Hij stelde dat de geschiedenis van de westerse economieën sinds de Donkere Middeleeuwen kan worden geïnterpreteerd op basis van vier stadia van competitie en monopolie in de organisatie van geweld. Hoewel Lane grotendeels zwijgt over de megapolitieke factoren die wij aanwijzen als bepalend voor de schaal waarop regeringen opereren, sluit zijn verkenning van de economie van geweld nauw aan bij het betoog dat wij uiteen hebben gezet in _Blood in the Streets_, _The Great Reckoning_ en elders in dit boek.

We hebben reeds enkele van de megapolitieke factoren geanalyseerd die een rol speelden in de evolutie van de westerse samenleving na de val van Rome. Lane onderzocht eveneens deze periode, met de nadruk op de economische gevolgen van de strijd om het monopolie op geweld. Hij onderscheidde vier belangrijke stadia in het functioneren van economieën in de afgelopen duizend jaar, elk gekenmerkt door een andere fase in de organisatie van geweld.

### Uit de Donkere Middeleeuwen

De eerste fase kenmerkt zich door 'anarchie en plundering', zoals tijdens de feodale revolutie van duizend jaar geleden. Lane geeft geen specifieke data voor de door hem onderscheiden perioden, maar eenvoudige berekeningen maken duidelijk waar zijn eerste periode begint. Zijn beschrijving van de fase van 'anarchie en plundering' lijkt te passen bij de omstandigheden tijdens de transitie uit de Donkere Middeleeuwen, toen het gebruik van geweld 'zeer competitief was, zelfs op land'. Hij licht niet toe waarom, maar wanneer geweld 'zeer competitief' is. Het wijst doorgaans op aanzienlijke belemmeringen voor het uitoefenen van macht over afstand. In militaire begrippen: de verdediging overheerst de aanval.

Zoals we in hoofdstuk 3 hebben toegelicht, viel deze fase van 'anarchie en plundering' samen met een daling van de landbouwproductiviteit als gevolg van ongunstige klimaatveranderingen. Omdat de technologie destijds nauwelijks effectieve schaalvoordelen opleverde waarmee een monopolie op geweld kon worden gevestigd, woedde de concurrentie tussen potentiële machthebbers hevig. Hierdoor kwam de economische activiteit ernstig in het gedrang.

De zwakte van de economie verergerde het probleem om een stabiele orde tot stand te brengen. Het vestigen van een lokaal geweldsmonopolie ging gepaard met hoge militaire kosten in verhouding tot de beperkte economische opbrengsten. De bewapende ridders te paard slaagden er niet in om een effectief monopolie te handhaven over een economisch levensvatbaar gebied, en terroriseerden en plunderden erop los terwijl ze nauwelijks echte 'bescherming' boden aan hun klanten.

### Feodalisme

"De tweede fase begint wanneer kleine regionale of provinciale monopolies worden gevestigd. De landbouwproductie stijgt dan, en het grootste deel van het overschot wordt geïnd door de pas opgekomen monopolisten van geweld." Toch blijft het overschot relatief gering in deze tweede fase, die wij identificeren met de vroege Middeleeuwen. Economische groei blijft beperkt door het ontbreken van schaalvoordelen in de organisatie van geweld, waardoor de militaire kosten voor het afdwingen van lokale monopolies hoog blijven. Maar hoewel de kosten hoog zijn, stijgt de prijs die minisoevereinen voor bescherming kunnen vragen, aangezien economische activiteit toeneemt zodra de anarchie wordt ingeperkt.

In een latere fase van de tweede periode proberen veel heffinginners klanten te lokken met speciale aanbiedingen voor landbouw en handel. Zij bieden bescherming tegen lage prijzen aan wie nieuwe gronden cultiveert, en leveren extra politiediensten ter bevordering van de handel, zoals de graven van Champagne deden voor kooplieden die hun jaarmarkten bezochten. Met andere woorden: zodra zij voldoende territoriale controle hadden om geloofwaardig te kunnen onderhandelen, deden lokale krijgsheren hetzelfde als kooplieden die hun marktaandeel willen vergroten, ze boden korting om klanten te trekken. Later gebruikten ze de extra middelen uit de toegenomen economische activiteit om hun greep op grotere gebieden te consolideren. Zodra die controle stevig gevestigd was, begonnen ze meer van de voordelen van een monopolie te genieten. De militaire kosten voor hun politietaken daalden, en ze konden ook hun prijzen verhogen zonder zich zorgen te maken dat hun dienst daardoor minder aantrekkelijk zou worden.

In deze complexe fase van de westerse geschiedenis nemen zij die geweld gebruiken, de middeleeuwse heren en vorsten, het grootste deel van de inkomsten boven het bestaansminimum. Er zijn weinig kooplieden, en de meest succesvolle zijn degenen die het beste in staat zijn belastingen, heffingen en andere kosten die worden opgelegd als betaling voor "beschermingsdiensten" te ontwijken of te minimaliseren.

### De Vroegmoderne Periode

Een derde fase wordt bereikt wanneer de kooplieden en grondbezitters die geen specialisten in geweld zijn "meer van het economische surplus overhouden dan leenheren en vorsten... In deze derde fase ontvangen de ondernemingen die gespecialiseerd zijn in het gebruik van geweld minder van het surplus dan de ondernemingen die bescherming van de regeringen kopen." Omdat succesvolle kooplieden hun winsten eerder herinvesteren dan consumeren, leidden de hogere winsten van kooplieden in die fase van de geschiedenis tot zelfversterkende groei.

### Het tijdperk van de fabrieken

Lane identificeert de overgang van de derde naar de vierde fase met het ontstaan van technologische en industriële innovaties als belangrijkere factoren voor winst dan het verlagen van de kosten voor bescherming. Daarmee lijkt Lane te doelen op de periode sinds 1750. Vanaf dat moment begon de aard van technologie duidelijk een dominante rol te spelen in de regionale welvaart. Zelfs in gebieden zonder overheid, zoals bepaalde streken in Nieuw-Zeeland vóór 1840, leidde het feit dat er geen belastingen waren niet automatisch tot grote welvaart. Op dat punt in de geschiedenis waren innovaties in industriële technologie belangrijker voor het behalen van winst dan kostenbesparingen op bescherming, zelfs als de kosten tot nul zouden zakken. Naarmate de schaal van overheden toenam, kwamen de krediet- en financieringsmechanismen die oorspronkelijk door regeringen waren ontwikkeld om middelen voor militaire operaties te verkrijgen, beschikbaar voor de financiering van grootschalige ondernemingen.

Hoewel Lane dit niet expliciet zegt, zorgde de concentratie van technologische voordelen in een bepaald gebied voor minder concurrentie tussen jurisdicties en stelde dit "gespecialiseerde ondernemingen in het gebruik van geweld", oftewel overheden, in staat hogere prijzen te vragen. Wanneer er grote technologische verschillen bestonden tussen de concurrenten in de ene jurisdictie en die in een andere, zoals tijdens het Industriële Tijdperk, verdienden ondernemers in de jurisdicties met de beste technologie doorgaans meer geld, ook al moesten zij hogere belastingen en andere kosten aan hun overheden betalen.

### Roof met een glimlach

Overheden in het Industriële Tijdperk genoten van een monopolie dat ze naar hartelust konden uitbuiten. De werkelijke kosten voor het beschermen van lijf en goed waren verwaarloosbaar klein in verhouding tot de prijzen (belastingen) die zij hieven. Toch bevonden zij zich in een situatie waarin de concurrentie zo pervers was dat zij zich veel meer konden bezighouden met plundering dan met bescherming, zonder dat dit feit vrijwel werd opgemerkt. Het was een zeldzaam moment in de geschiedenis.

De nadelen van anarchie onder de megapolitieke omstandigheden van het industrialisme maakten concurrentie in beschermingsdiensten binnen hetzelfde grondgebied technologisch onuitvoerbaar. De enige manier om effectieve bescherming onder die omstandigheden te bereiken, was door te beschikken over een groter vermogen tot geweld. Daarom viel er weinig te winnen met een poging om beter te onderscheiden welk deel van de belastingen, in Lane's woorden, "als betaling voor de geleverde dienst" gold en welk deel "roof genoemd kan worden." Het onderscheid was er wel degelijk. Aangezien men echter hoe dan ook vastzat aan het betalen van belastingen, had het onderzoeken hiervan weinig toegevoegde waarde, behalve om morbide nieuwsgierigheid te bevredigen. Zoals Lane zei: ongeacht hoe groot het deel van de belastingen roof was, was het een prijs die men moest betalen "om ernstigere verliezen te vermijden."

### De stijging van inkomens onder het industrialisme

Het feit dat de inkomens fors stegen, vooral in de landen waar de meeste industriële ontwikkeling plaatsvond, verklaart deels waarom dit dilemma in de afgelopen twee eeuwen van natiestaat-heerschappij aanvaardbaar bleef. De overheden van de OESO-landen belastten bijna elk jaar een hoger percentage van de inkomens, maar de toename van de plundering ging desalniettemin gepaard met een veel grotere welvaart, en een grotere ongelijkheid van rijkdom ten opzichte van de rest van de wereld. Onder zulke omstandigheden waren bezwaren tegen de stijgende belastingdruk onvermijdelijk marginaal en onvoldoende om een ander verloop van gebeurtenissen te realiseren dan de meest logische koers. Sterker nog, om redenen die in eerdere hoofdstukken uiteen zijn gezet, hing het militaire voortbestaan van een industriële natiestaat grotendeels af van haar onbegrensde aanspraken op de middelen van haar burgers.

In elke industriële staat bewogen de beleidslijnen zich min of meer in dezelfde richting. Op het hoogtepunt van het industrialisme na de Tweede Wereldoorlog bereikte het marginale inkomstenbelastingtarief 90 procent of hoger. Dit was een veel agressievere aanspraak van de staat om middelen af te romen dan zelfs de oosterse despoten van de vroege hydraulische beschavingen gewoonlijk maakten. Toch volgde de industriële variant van plundering zijn eigen logica. Veel ervan werd bepaald door het karakter van de industriële technologie in de eerste helft van de twintigste eeuw, zoals eerder beschreven.

Deze technologie maakte het vrijwel onvermijdelijk dat de staat een groot deel van het inkomen zou opeisen en herverdelen, waarbij een groot deel van de lasten van de roof op een kleine groep kapitalisten viel. De meeste industriële processen waren sterk afhankelijk van natuurlijke hulpbronnen, en dus gebonden aan de locaties waar die zich bevonden. Een staalfabriek, een mijn of een haven kon slechts tegen astronomische kosten worden verplaatst, of helemaal niet. Zulke faciliteiten waren daarom stationaire doelwitten die eenvoudig belast konden worden. Onroerendgoed-, vennootschaps- en winstbelastingen stegen sterk in deze eeuw. Dat gold ook voor de inkomstenbelasting, aanvankelijk voor de kapitalisten, maar uiteindelijk ook voor de arbeiders zelf. De opkomst van grootschalige industriële werkgelegenheid maakte een brede inkomstenbelasting praktisch uitvoerbaar. Lonen konden aan de bron worden ingehouden, waarbij de belastingdiensten de inning coördineerden met de boekhoudafdelingen van industriële ondernemingen. Dat beschouwen we vandaag als vanzelfsprekend, maar het innen van een inkomstenbelasting bij de fabriekspoort was een veel eenvoudigere taak dan het afpersen van een deel van de winsten van miljoenen zelfstandige ambachtslieden en boeren over het uitgestrekte platteland.

Kortom, industriële technologie maakte belastingen meer geroutineerd, voorspelbaarder en minder persoonlijk riskant dan in veel eerdere perioden. Desalniettemin slaagde het erin om een hoger percentage van de middelen van de maatschappij af te romen dan welke andere vorm van soevereiniteit tot dan toe had gedaan.

### Wat wordt beschermd?

Het feit dat samenlevingen rijker konden worden terwijl het totale percentage van het inkomen dat in belastingen werd afgeroomd aanzienlijk steeg, roept de vraag op naar het karakter van de bescherming die regeringen aan industriële economieën boden. Wat beschermden zij? Ons antwoord: voornamelijk industriële installaties met hoge kapitaalkosten en een grote kwetsbaarheid voor aanvallen. Het bestaan van grootschalige industriële ondernemingen zou onmogelijk zijn geweest in een chaotische omgeving met meer competitief geweld, zelfs als het resultaat van die concurrentie een lager belastingpercentage zou zijn geweest.

Dit is waarom kapitaalintensieve activiteiten oneconomisch zijn in de Amerikaanse sloppenwijken, evenals in derdewereldsamenlevingen waar ad-hocgeweld endemisch is. De industriële samenleving als geheel kon zich ontwikkelen omdat er een bepaald soort orde werd gevestigd en gehandhaafd. Ondernemingen werden blootgesteld aan regelmatige, voorspelbare afpersingen in plaats van grillig geweld.

Zelfs op het hoogtepunt van het industrialisme was het altijd overdreven om te spreken van een overheid die een "monopolie op dwang" uitoefende. Alle overheden proberen een dergelijk monopolie te handhaven, maar zoals we hebben gezien, ontdekten werknemers van industriële bedrijven meestal dat zij in staat waren om geweld tegen hun werkgevers te gebruiken. Zolang het grote publiek toegang heeft tot enig wapen, of een wanordelijke menigte fysiek in staat is een bus omver te werpen of stenen naar de politie te gooien, monopoliseren degenen die controle hebben over de overheid het geweld niet volledig. Zij beheersen slechts het overheersende geweld, dominant in die mate dat het voor de meeste mensen economisch onaantrekkelijk wordt om met hen te concurreren onder de bestaande omstandigheden.

> Voordelen hoeven niet alleen persoonlijke goederen of diensten te zijn, maar kunnen ook de bredere voordelen van een regulerend regime omvatten: een schoon, transparant marktplein met gedefinieerde regels en consequenties, of een toezichthoudende gemeenschap waar kinderen de mensen die zij tegenkomen kunnen vertrouwen en waar de privacy van individuen wordt beschermd. -- Esther Dyson

### Het Informatietijdperk

Het Informatietijdperk markeert de komst van een vijfde fase in de ontwikkeling van de manier waarop in het Westen om het gebruik van geweld wordt geconcurreerd. Deze fase werd niet door Lane voorzien. Het gaat hier om competitie in de cyberspace, een arena die niet kan worden gemonopoliseerd door wat voor "geweldsgebruikende onderneming" dan ook. Dat is onmogelijk omdat de cyberspace geen territorium is.

Lane's analyse vertrok nog vanuit de conventionele naoorlogse aanname van het onvermijdelijke bestaan van de natiestaat. Toch wees hij op een punt dat vandaag veel crucialer blijkt te zijn dan het vijftig jaar geleden leek: overheden hebben nooit stabiele monopolies van dwang gevestigd op de open zee. Geen enkele staat kon haar wetten daar exclusief handhaven. Dit gegeven is van groot belang om te kunnen begrijpen hoe de organisatie van geweld en bescherming zich zal ontwikkelen nu de economie naar de cyberspace migreert, een domein zonder fysieke grenzen of tastbare ruimte. Om dezelfde redenen die Lane opmerkte voor het feit dat geen enkele overheid er ooit in slaagde het geweld op zee te monopoliseren, zo is het nog minder aannemelijk dat een overheid een oneindig domein zonder fysieke grenzen succesvol zou kunnen monopoliseren.

## Concurrentie zonder anarchie

In het verleden, wanneer de omstandigheden het voor een enkel gewelddadig machtsapparaat moeilijk maakten om een monopolie te vestigen, volgde anarchie en plundering. Het Informatie­tijdperk daarentegen heeft de technologische voorwaarden voor de organisatie van geweld op een diepgaande manier veranderd. Anders dan vroeger, toen het onvermogen om bescherming in een regio te monopoliseren hogere militaire kosten en lagere economische opbrengsten betekende, impliceert het feit dat overheden de cyberspace niet kunnen monopoliseren juist lagere militaire kosten en hogere economische opbrengsten. Dit komt doordat informatietechnologie een nieuwe dimensie van bescherming creëert. Voor het eerst in de geschiedenis maakt informatietechnologie het mogelijk om activa te scheppen en te beschermen die volledig buiten het domein van het territoriale geweldsmonopolie van welke individuele overheid dan ook liggen.

> Landen met een gefragmenteerde politieke macht en bestuur waarbij een centrale, stabiele en onbetwiste toezichthoudende bron van jurisdictie en macht ontbreekt, moeten hun eigen werkbare oplossingen bedenken om om te gaan met de problemen die door zulke grenzen worden opgeworpen. -- REES DAVIES

### De analogie met de grens

De cyberspace is in zekere zin het equivalent van een technologisch beschermde _march_-regio zoals die bestond in grensgebieden tijdens de Middeleeuwen. In het verleden, toen de macht van heren en koningen zwak was en de aanspraken van één of meer elkaar overlapten aan een grens, bestond er iets dat leek op concurrentie tussen de overheden. Een blik op hoe de _march_-regio's functioneerden kan inzicht geven in hoe wetten van de _march_ of iets dergelijks mogelijk ook in de cyberspace zullen ontstaan.

Andorra overleeft als een soort versteende _march_-regio tussen Frankrijk en Spanje, een overblijfsel van megapolitieke omstandigheden die het voor beide koninkrijken moeilijk maakten om de overhand te krijgen in dat koude en bijna ontoegankelijke gebied in de Pyreneeën van zo'n 490 vierkante kilometer. In 1278 werd een overeenkomst gesloten waarbij de suzereiniteit over Andorra werd verdeeld tussen lokale Franse en Spaanse feodale heren, de Franse graaf van Foix en de Spaanse bisschop van Urgel. Beiden benoemden een van de twee "viquiers" die de minimale overheidsmacht in Andorra spaarzaam uitoefenden, voornamelijk door het bevel te voeren over de kleine Andorrese militie, nu een politie-eenheid. De rol van de graaf is in de loop van de geschiedenis allang achterhaald. De Franse regering vertegenwoordigt hem nu vanuit Parijs. Eén van haar taken is het innen van de helft van het jaarlijkse tribuut dat Andorra betaalt, een bedrag dat lager is dan de maandhuur van een bouwvallig appartement. De bisschop van Urgel blijft zijn deel van het tribuut ontvangen, net als zijn voorgangers in de Middeleeuwen.

Zoals het gedeelde tribuut impliceert, waren er in Andorra twee bronnen van "toezichthoudende jurisdictie en macht" in plaats van één. Beroepen tegen civiele vonnissen in Andorra werden traditioneel ingediend bij het bisschoppelijk college van Urgel of bij het Hof van Cassatie in Parijs.

Een gevolg van Andorra's dubbelzinnige positie was dat er vrijwel geen wetten werden uitgevaardigd. Andorra heeft al meer dan zevenhonderd jaar een verwaarloosbaar kleine overheid en geen belastingen. Vandaag de dag heeft het land daardoor een groeiende aantrekkingskracht als belastingparadijs. Tot een generatie geleden stond Andorra echter bekend als arm. Wat eens een dicht bos was, werd over de eeuwen heen ontbost door de bewoners die warm wilden blijven in de strenge winters; elk jaar ligt het van november tot april volledig onder de sneeuw. Zelfs in de zomer is Andorra zo koud dat gewassen alleen op de zuidelijke hellingen groeien. Deze beschrijving doet het misschien als onprettig overkomen, maar dat is net het geheim van haar succes. Andorra overleefde als feodale enclave in het tijdperk van de natiestaat omdat het afgelegen en straatarm was.

Er waren ooit talrijke middeleeuwse grens- of _march_-regio's waar soevereiniteiten met elkaar vermengd raakten. Deze gewelddadige, vaak arme grenzen bleven tientallen of soms honderden jaren bestaan in de grensgebieden van Europa. Zoals eerder vermeld, waren er _marches_ tussen gebieden onder Keltische en Engelse controle in Ierland, tussen Wales en Engeland, Schotland en Engeland, Italië en Frankrijk, Frankrijk en Spanje, Duitsland en de Slavische grenzen van Midden-Europa, en tussen de christelijke koninkrijken van Spanje en het islamitische koninkrijk Granada. Net als Andorra ontwikkelden deze _march_-regio's eigen, specifieke institutionele en juridische vormen van een soort die we waarschijnlijk opnieuw zullen zien in het volgende millennium.

Door de zwakke positie van de twee concurrerende autoriteiten, riepen heersers soms zelfs vrijwilligers uit hun onderdanen op om zich in _march_-regio's te vestigen om zo hun invloed te vergroten. Bijna vanzelfsprekend werden de onderdanen gelokt met vrijstelling van belastingen. Aangezien ze opereerden op flinterdunne marges, zou het invoeren van belastingen door een van de autoriteiten in een grensregio, de eigen volgelingen financieel onder druk zetten en ze een reden geven om zich met de tegenpartij te verbinden. Daarom hadden inwoners van een _march_ meestal de keuze wiens wetten zij zouden gehoorzamen. Deze keuze was gebaseerd op de zwakke positie van de concurrerende autoriteiten; het was geen ideologisch gebaar.

Toch ontstonden er praktische moeilijkheden die moesten worden opgelost. Onder het feodalisme werden landeigenaren met bezittingen aan beide zijden van een nominale grens geconfronteerd met een ernstig conflict wat betreft hun plichten. Bijvoorbeeld: een heer aan de grens van Schotland en Engeland die eigendommen in beide koninkrijken bezat, kon theoretisch militaire dienst aan beide kanten verschuldigd zijn in geval van oorlog. Om deze tegenstrijdige verplichting op te lossen kon vrijwel iedereen in de feodale hiërarchie kiezen wiens wetten hij gehoorzaamde via een juridisch proces dat _avowal_ werd genoemd.

Door informatietechnologie zullen er ook mogelijkheden ontstaan om economische activiteit te vestigen op concurrerende locaties, maar met belangrijke verschillen. Een daarvan is dat de cyberspace naar verwachting, anders dan de middeleeuwse grensregio's, uiteindelijk het rijkste economische terrein zal vormen. Het zal dus een groeiend domein zijn, in plaats van een die langzaam wegkwijnt. Zonder sterke, vaak religieuze prikkels zouden maar weinig mensen uit de kerngebieden van de middeleeuwse samenleving de wens hebben gehad om naar de grenzen te verhuizen, omdat deze regio's doorgaans gewelddadig en arm waren. Ze trokken dus geen middelen weg uit de macht van de autoriteiten. De cyberspace zal dat wel doen.

Ten tweede zal het nieuwe grensgebied geen duopolie zijn, dat samenwerking tussen twee autoriteiten uitlokt om tot een compromis te komen over hun aanspraken erop. Zulke compromissen waren in de middeleeuwen meestal niet effectief, deels vanwege de grote culturele verschillen tussen de rivalen, en vooral omdat zij de fysieke macht misten om een regeling af te dwingen. In het tijdperk van de natiestaat verdwenen de meeste _marches_ en vage grenzen zodra nationale autoriteiten wél over voldoende militaire macht beschikten om oplossingen af te dwingen. Grensafbakening werd de norm, wat een stabiele oplossing is wanneer een duopolie het gezag over het geweld in twee aaneengesloten gebieden moet verdelen. Maar de concurrentie om transacties te vestigen in de cybereconomie zal niet plaatsvinden tussen twee autoriteiten, maar tussen honderden autoriteiten wereldwijd. Voor territoriale staten zal het vrijwel onmogelijk zijn om de belastingtarieven hoog te houden door het vormen van een kartel, net als dat kartelvorming om monopoliewinsten te behouden niet werkt in markten met honderden concurrenten.

De Seychellen, een klein land in de Indische Oceaan, bewijst dit punt. Ze voerden een investeringswet in die door Amerikaanse functionarissen werd beschreven als de wet "Welkom Criminelen". Volgens die wet krijgt iedereen die $10 miljoen investeert niet alleen bescherming tegen uitlevering, maar ook een diplomatiek paspoort. In tegenstelling tot de beweringen van de Amerikaanse regering waren de beoogde begunstigden echter geen drugsdealers, die doorgaans toch al onder de bescherming van belangrijkere overheden vallen, maar onafhankelijke ondernemers die politiek incorrect waren geworden. De eerste potentiële begunstigde van de Seychellen-wet was een blanke Zuid-Afrikaan die rijk werd door de economische sancties tegen het voormalige apartheidsregime te omzeilen. Nu loopt hij het risico op economische represailles van de nieuwe Zuid-Afrikaanse regering en is hij bereid de Seychellen te betalen voor bescherming.

Wat de merites van individuele gevallen ook zijn, het voorbeeld laat zien waarom pogingen van overheden om een kartel voor bescherming te vormen, gedoemd zijn te mislukken. Anders dan in de middeleeuwse grensgebieden, waar de concurrentie slechts tussen twee autoriteiten plaatsvond, zullen de grenzen in de cyberhandel tussen honderden jurisdicties liggen, en waarschijnlijk zal het zelfs tot in de duizenden oplopen.

In het tijdperk van de virtuele onderneming zullen individuen ervoor kiezen hun inkomensgenererende activiteiten te vestigen in de jurisdictie die de beste diensten levert tegen de laagste kosten. Met andere woorden, soevereiniteit zal worden gecommercialiseerd. Anders dan de meeste middeleeuwse _march_-samenlevingen, die arm en gewelddadig waren, zal de cyberspace dat niet zijn. De concurrentie waarin informatietechnologie overheden dwingt zich te begeven, is geen militaire concurrentie, maar concurrentie in de kwaliteit en prijs van een economische dienst: echte bescherming. Kortom, overheden zullen hun klanten moeten geven wat ze willen.

### De verminderde effectiviteit van geweld

Dit wil natuurlijk niet zeggen dat overheden zullen ophouden geweld te gebruiken. Integendeel, wij stellen dat geweld een groot deel van zijn effectiviteit verliest. Een mogelijke reactie van overheden zou kunnen zijn om hun gebruik van geweld in lokale contexten te intensiveren, als poging om het verlies aan hun mondiale betekenis te compenseren. Wat overheden ook doen, zij zullen de cyberspace echter niet kunnen verzadigen met geweld zoals ze de gebieden die ze in de moderne wereld monopoliseerden met geweld konden verzadigen. Hoeveel overheden ook proberen de cyberspace te betreden, zij zullen daar niet capabeler of machtiger zijn dan anderen.

Ironisch genoeg zouden pogingen van natiestaten om "informatie-oorlogen" te voeren om de toegang tot de cyberspace te domineren of te blokkeren, waarschijnlijk alleen hun eigen ondergang versnellen. De neiging tot de devolutie van grote systemen is al sterk aanwezig door het wegvallen van schaalvoordelen en de stijgende kosten om uiteenvallende sociale groepen bijeen te houden. De ironie van informatie-oorlogen is dat ze mogelijk de broze systemen die uit het Industriële Tijdperk zijn overgebleven meer schaden dan de opkomende Informatiemaatschappij zelf.

Zolang essentiële informatietechnologie blijft functioneren, kan cyberhandel parallel doorgaan met de strijd van een informatie-oorlog, op een manier die in een territoriale oorlog onmogelijk zou zijn. Het is ondenkbaar dat miljoenen commerciële transacties plaatsvinden aan het front in een oorlog uit de twintigste eeuw. Virtuele oorlogen hoeven echter de capaciteit van de cyberspace om meerdere activiteiten te huisvesten niet uit te putten, en omdat de virtuele realiteit niet fysiek bestaat, levert nabijheid tot het front nauwelijks gevaar op, en is er al helemaal geen risico op exploderende virtuele granaatscherven.

### Kwetsbaarheid van grootschalige systemen

In een informatie-oorlog lopen voornamelijk de grootschalige industriële systemen die draaien op centraal bevel en controle gevaar. Militaire autoriteiten in de Verenigde Staten en andere toonaangevende landen maken zich zorgen over en bereiden zich voor op informatiesabotage, waarbij grote systemen kunnen worden uitgeschakeld. Cyberaanvallen kunnen bijvoorbeeld een telefoonwisselstation stilleggen, de luchtverkeersleiding ontregelen of een pompsysteem dat de watertoevoer naar een stad regelt saboteren. Een computervirus kan zelfs conventionele of nucleaire energiebronnen doen uitvallen, waardoor delen van het elektriciteitsnet tot stilstand komen. Zogenaamde _logic bombs_ zijn in staat om enorme hoeveelheden informatie te vernietigen, waaronder de uiterst gevoelige gegevens in de centrale controlesystemen die de kwetsbare, grote industriële installaties aansturen. Tenzij men daadwerkelijk alle informatietechnologie massaal vernietigt, wat de wereldeconomie letterlijk tot stilstand zou brengen, zullen overheden er niet in slagen om de internethandel en de virtuele realiteit te onderdrukken of monopoliseren.

Zelfs een belangrijk nadeel van informatietechnologie, namelijk de vermeende kwetsbaarheid voor het verval en de vernietiging van data-opslagsystemen, wordt grotendeels door de recente archiveringstechnologie opgelost. Een nieuw systeem, High-Density Read-Only Memory (HD-ROM), maakt gebruik van een ionenfrees, vergelijkbaar met die in computergestuurde productie, om archieven in vacuüm te vervaardigen. De opslagcapaciteit bereikt maar liefst 10.000 megabytes per vierkante centimeter. Waar oudere systemen snel achteruitgingen door bederf en schokken, verzekert HD-ROM dat de opgeslagen data de volledige levensduur beschikbaar blijft. Eén van de ontwikkelaars van HD-ROM, Bruce Lamartine, verklaart: 'Het is vrijwel ondoordringbaar voor de verwoestende invloeden van tijd, thermische en mechanische schokken, en elektromagnetische velden die andere opslagmedia beschadigen.' Zelfs een nucleaire explosie leidt niet per se tot de verstoring of vernietiging van vitale informatie, zoals de codes voor digitaal geld, waarop het soepele functioneren van een cybereconomie steunt.

> Moderne legers zijn zo afhankelijk van informatie dat je ze kunt verblinden en doof maken, om zo een overwinning te behalen zonder op de conventionele wijze te vechten. -- COL. ALAN CAMPEN, U.S.A.F (Gep.)

## Supermachten in de virtuele oorlogsvoering

De veronderstellingen van de oorlogvoerende natiestaat zullen steeds minder logisch zijn op megapolitiek vlak naarmate informatie belangrijker wordt in de oorlogsvoering. Omdat de cyberspace geen fysieke vorm heeft, zijn parameters zoals wij die in de fysieke wereld kennen niet bepalend. Het maakt niet uit hoeveel programmeurs betrokken waren bij het opstellen van een reeks commando's. Het enige dat telt is of het programma functioneert. Het Soevereine Individu kan in de cyberspace werkelijk net zoveel betekenen als een natiestaat met een zetel in de VN, een eigen vlag en een leger op de grond. In puur economische termen beschikken sommige Soevereine Individuen al over investeerbare inkomens van honderden miljoenen per jaar, bedragen die het discretionaire bestedingsvermogen van sommige failliete natiestaten overtreffen. Maar dat is niet alles. Op het gebied van virtuele oorlogsvoering via informatie kunnen sommige individuen net zo machtig of machtiger zijn dan veel staten. Één bizar genie, die met digitale helpers werkt, zou in theorie dezelfde impact in een cyberoorlog kunnen hebben als een natiestaat. Bill Gates zou dat zeker kunnen.

In die zin is het tijdperk van het Soevereine Individu niet slechts een slogan. Een hacker, of een klein groepje wiskundigen, laat staan een bedrijf als Microsoft, of vrijwel elk softwarebedrijf, kan in principe alles doen wat het Pentagon's Cyber War Task Force kan. Honderden bedrijven in Silicon Valley en elders hebben al een grotere capaciteit om een cyberoorlog te voeren dan 90 procent van de bestaande natiestaten. De aanname dat overheden het leven op de grond zullen blijven monopoliseren terwijl alternatieve beschermingsmiddelen overal opkomen, is achterhaald. het is waarschijnlijker dat natiestaten opnieuw ingericht moeten worden om hun kwetsbaarheid te verminderen voor computervirussen, logische bommen, geïnfecteerde kabels en trapdoor-programma's onder controle van de Amerikaanse National Security Agency, of van een tienerhacker.

De megapolitieke logica van de cyberspace suggereert dat centrale command-and-control-systemen die momenteel de wereldwijde infrastructuur domineren, vervangen moeten worden door multicentrische beveiligingsmodellen met gedistribueerde capaciteiten zodat ze niet eenvoudig door een virus kunnen worden overgenomen of geblokkeerd. Nieuwe soorten software, bekend als agoric open systems, zullen command-and-control-software uit het Industriële Tijdperk vervangen. Die oudere software verdeelde rekenkracht volgens rigide prioriteiten, vergelijkbaar met hoe centrale planners bij Gosplan in de voormalige Sovjet-Unie goederen aan wagons toewezen volgens vaste regels. De nieuwe systemen worden bestuurd door algoritmen die marktmechanismen nabootsen zodat middelen efficiënter toegewezen worden via een intern biedproces dat de competitieve processen in de hersenen imiteert. In plaats van gigantische computermonopolies die belangrijke command-and-control-functies uitvoeren, zullen ze in het nieuwe millennium gedecentraliseerd zijn.

Er is geen beter voorbeeld van de veerkracht van gedistribueerde netwerken vergeleken met command-and-control-systemen dan dat van Digital Equipment in het onderzoekscentrum in Palo Alto. Een ingenieur opende een kast met het bedrijfseigen computernetwerk. Zoals Kevin Kelly vertelt, "trok de ingenieur dramatisch een kabel uit het netwerk, waarop het rond de schade routeerde en geen moment haperde."

Het Informatietijdperk zal niet alleen concurrentie zonder anarchie in de cyberspace mogelijk maken, het zal onvermijdelijk leiden tot het herontwerp van belangrijke systemen uit het industrialisme. Een dergelijke herconfiguratie is essentieel om ze minder kwetsbaar te maken voor schade van wie of waar dan ook. Net zoals het Industriële Tijdperk onvermijdelijk leidde tot de herconfiguratie van overgebleven middeleeuwse instituties zoals scholen en universiteiten, zullen de overgebleven instituties van het Industriële Tijdperk waarschijnlijk in miniatuurvorm evolueren, volgens de logica van de microtechnologie.

De noodzaak tot bescherming tegen bandieten op de Informatiesnelweg zal de wijdverspreide toepassing van public key-private key-encryptie vereisen. Deze maken het nu mogelijk voor elke gebruiker van een personal computer om een bericht veiliger te versleutelen dan het Pentagon haar lanceercodes een generatie geleden had kunnen beveiligen. Deze krachtige, onbreekbare vormen van encryptie zullen nodig zijn om financiële transacties tegen hackers en dieven te beschermen.

Ze zijn ook om een andere reden noodzakelijk. Particuliere financiële instellingen en centrale banken zullen onbreekbare encryptie-algoritmen toepassen zodra ze beseffen dat de Amerikaanse overheid, en mogelijk niet alleen zij, in staat is om de huidige banksoftware en computersystemen te penetreren en een land letterlijk failliet te laten gaan of de bankrekening van bijna iedereen leeg te halen. Er is geen technologische reden waarom een individu of land zijn financiële tegoeden of transacties, legaal of illegaal, overgeleverd zou moeten laten aan de Amerikaanse National Security Agency of opvolgers van de KGB, of een soortgelijke organisatie.

Encryptie-algoritmen die door overheden niet te doorbreken zijn, zijn geen droombeelden. Ze zijn al als _shareware_ via het Internet beschikbaar. Wanneer satellietsystemen in een lage baan rond de aarde volledig operationeel zijn, zullen individuen met geavanceerde personal computers en antennes niet groter dan die van mobiele telefoons overal ter wereld kunnen communiceren zonder het telefoonnetwerk te gebruiken. Het zal even onmogelijk zijn voor een overheid om de cyberspace, een niet-fysieke werkelijkheid, te monopoliseren als het voor middeleeuwse ridders zou zijn geweest om de transacties in het Industriële Tijdperk te paard te controleren.

### Bescherming door onopvallendheid

Informatiemaatschappijen zullen een enorme hoeveelheid middelen buiten het bereik van rovers plaatsen. Wanneer de cyberspace steeds meer financiële transacties en andere vormen van handel gaat huisvesten, zullen de daar gebruikte middelen min of meer immuun zijn voor gewone afpersing en diefstal. Rovers zullen daardoor niet in staat zijn om een zo groot deel van de middelen te veroveren als ze vandaag de dag doen en hebben gedaan gedurende het grootste deel van de twintigste eeuw.

Daarom zal overheidsbescherming van een groot deel van de wereldrijkdom onnodig worden. De overheid zal niet beter in staat zijn om een banktegoed in de cyberspace te beschermen dan uzelf. Omdat de overheid minder noodzakelijk zal zijn, zal haar relatieve prijs waarschijnlijk alleen al om die reden dalen, maar er zijn nog andere.

Nu een groot en groeiend aandeel van de financiële transacties in dit nieuwe millennium in de cyberspace plaatsvindt, zullen individuen een keuze hebben in welke jurisdictie zij hun transacties onderbrengen. Het zal intense concurrentie creëren om de prijs van overheidsdiensten (de heffingen die zij oplegt) op een niet-monopolistische wijze te bepalen. Dit is revolutionair. Zoals George Melloan betoogde in _The Wall Street Journal_, 'de instelling die veruit het meest succesvol de krachten van wereldwijde concurrentie heeft weerstaan, is de verzorgingsstaat.' Een studie door onderzoekers van de Wharton School en de Australian National University besprak de krachten die van invloed zijn op inkomensherverdeling. Garrett en Mitchell stelden vast dat er 'vrijwel geen aanwijzingen bestaan dat meer marktintegratie de belangrijkste sociale vangnetten heeft verzwakt.' Integendeel, schrijven zij, 'overheden hebben altijd gereageerd op toenemende integratie in internationale markten door inkomensherverdeling te vergroten.' De opkomst van de cybereconomie zal eindelijk de verzorgingsstaat blootstellen aan echte concurrentie. Het zal de aard van soevereiniteit veranderen en economieën transformeren, omdat de balans tussen bescherming en afpersing meer dan ooit in het voordeel van bescherming zal verschuiven.

[^187]: Neil Munro, 'The Pentagon's new nightmare: an electronic Pearl Harbor', *Washington Post*, 16 juli 1995, p. C3.

[^188]: Thomas Hobbes, Leviathan, hoofdstuk 13, 'De natuurlijke toestand van de mens betreffende hun gelukzaligheid en ellende'.

[^189]: Thomas Schelling, Arms and Influence (New Haven: Yale University Press, 1966).

[^190]: Kevin Kelly, Out of Control: The New Biology of Machines, Social Systems, and the Economic World (Reading, Mass.: Addison-Wesley, 1995), pp. 45–46.

[^191]: Ibid., pp. 2–4.

[^192]: Ibid., p. 4.

[^193]: Heinz Pagels, *the dreams of reason* (New York: Bantam Books, 1989), geciteerd in Roger Lewin, *complexity: life at the edge of chaos* (New York: Macmillan, 1992), p. 10.

[^194]: Lane, 'economic consequences of organized violence' (op. cit., p. 402).

[^195]: Frederic C. Lane, 'the economic meaning of war and protection' in *Venice and history: the collected papers of Frederic C. Lane* (Baltimore: The Johns Hopkins Press, 1966), pp. 383–384.

[^196]: Shi Mai'an and Lao Guanzhong, *outlaws of the marsh*, vertaald door Sidney Shapiro (Bloomington: Indiana University Press, 1981), p. 12.

[^197]: George E Will, 'Vaarwel aan de welvaartsstaten,' *Washington Post*, 17 december 1995, p. C7.

[^198]: Robert S. MeElvaine, De grote depressie: Amerika, 1929–1941 (New York: *Times Books*, 1984), p. 292.

[^199]: Ibid., p. 293.

[^200]: Smith, op. cit., p. 75.

[^201]: Ibid., p. 76.

[^202]: Ibid.

[^203]: Een van de eerste vakbonden in Argentinië die zich daadwerkelijk organiseerden, was de spoorwegvakbond, opgericht in 1887. Zie Carmelo Mesa-Lago, *Social Security in Latin America: Pressure Groups, Stratification, and Inequality* (Pittsburgh: University of Pittsburgh Press, 1978), p. 161.

[^204]: Voor meer details over de planning en bouw van het C&O-kanaal raadpleeg je Robert J. Brugger, *Maryland: A Middle Temperament 1634-1980* (Baltimore: The Johns Hopkins Press, 1990), pp. 202–3f.

[^205]: Irving J. Sloan, *Our Violent Past: An American Chronicle* (New York: Random House, 1970), p. 177

[^206]: Voor meer informatie over het geweld tijdens de spoorwegstakingen van 1877 zie ibid. en Brugger, op. cit., pp. 341–344.

[^207]: Sloan, op. cit., p. 202. Zie ook S. S. Boynton, 'Miners’ vengeance', *'Overland Monthly'*, vol. 22 (1893), pp. 303–307

[^208]: Benjamin Schwartz, 'American inequality: its history and scary future', *'New York Times'*, 19 december 1995, p. A25

[^209]: MeElvaine, op. cit., p. 293

[^210]: Ibid.

[^211]: Ibid.

[^212]: Henry C. Simons, 'Enkele overpeinzingen over syndicalisme', *Journal of Political Economy*, maart 1944, p. 22.

[^213]: Kelly, op. cit., pp. 191–192.

[^214]: Gayle N. Hanson, 'Een meeslepend verslag van “het leven” in de postmodernistische cyberspace', *Washington Times*, 24 december 1995, p. B7.

[^215]: Een beknopte inleiding op het academische onderzoek naar anarchie vindt u in Gordon Tullock (red.), *Explorations in the Theory of Anarchy* (Blacksburg, Va.: Virginia Polytechnic Institute and State University, 1972). Zie ook Murray N. Rothbard, *Power and Market: Government and the Economy* (Menlo Park, Calif., 1970) en Robert Nozick, *Anarchy, State and Utopia* (New York: Basic Books, 1974).

[^216]: Zie Pierre Clastres, *Society Against the State: The Leader as Servant and the Humane Uses of Power Among the Indians of the Americas* (New York: Urizen Books, 1977) en Jones, op. cit.

[^217]: Lane, *economische gevolgen van georganiseerd geweld*, op. cit., p. 403.

[^218]: Charles Tilly, *oorlogsvoering en staatsvorming als georganiseerde misdaad*, in Peter B. Evans, Dietrich Rueschemeyer en Theda Skoepol, *de staat weer betrekken* (Cambridge: *Cambridge University Press*, 1985), p. 169.

[^219]: Ibid.

[^220]: Lane, *economische gevolgen van georganiseerd geweld*, op. cit., p. 402.

[^221]: David J. Elkins, *voorbij soevereiniteit: territorium en politieke economie in de eenentwintigste eeuw*. Toronto: *University of Toronto Press*, 1995, pp. 13–14.

[^222]: Ibid., p. 29

[^223]: Jim Taylor en Watts Wacker, *The 500-year delta: what happens after what comes next.* New York: *HarperCollins*, 1997, p. 40.

[^224]: Ibid., p. 67

[^225]: Ibid., pp. 41–42

[^226]: George Gilder, *Fiber keeps its promise: get ready. Bandwidth will triple each year for the next 25, creating trillions in new wealth.* *Forbes ASAP*, 7 april 1997

[^227]: Zie Neal Stephenson, Snow Crash. New York: *Bantam Books*, 1993

[^228]: Keith B. Richburg, 'Twee jaar na de landing van de VS in Somalië is het weer chaotisch', *Washington Post*, 4 december 1994, p. A1.

[^229]: Geciteerd in Tilly, Coercion, Capital and European States, op. cit., p. 85.

[^230]: Lane, 'Economische gevolgen van georganiseerd geweld', op. cit., p. 411.

[^231]: Ibid.

[^232]: Ibid.

[^233]: Ibid., p. 412.

[^234]: Ibid., p. 403.

[^235]: Ibid., p. 404.

[^236]: Esther Dyson, *Release 2.1: een ontwerp voor het leven in het digitale tijdperk*. New York: *Broadway Books*, 1998, p. 131

[^237]: Rees Davies, *Frontier arrangements in fragmented societies: Ireland and Wales*, in Robert Bartlett en Angus MacKay (red.), *Medieval frontier societies* (Oxford: *Oxford University Press*, 1992), p. 80.

[^238]: Zie Thomas W. Lippman, *Seychelles offers investors safe haven for $10 million*, *Washington Post*, 31 december 1995, p. A27.

[^239]: Zie *ROM of ages*, *Wired*, januari 1996, p. 52.

[^240]: Geciteerd in James Adams, *Dawn of the cyber soldiers*, *The Sunday Times* (London), 15 oktober 1995, pp. 3–5.

[^241]: Kelly, op. cit., p. 19.

[^242]: George Melloan, 'Hervorming van de welvaartsstaat is grotendeels mythologisch', *The Wall Street Journal*. 14 oktober 1996, p. A19.

[^243]: Zie hoofdstuk 8 van *The Great Reckoning*, 'Lineaire verwachtingen in een niet-lineaire wereld: hoe de telescoop ons leerde rekenen; hoe de computer ons kan helpen te zien.'

[^244]: Merk op dat Lane's vier fasen van concurrentie en monopolie in het gebruik van geweld afwijken van de vier fasen in de organisatie van het economisch leven die wij onderscheiden, namelijk: jagen en verzamelen, landbouw, industrialisme en het informatietijdperk.