# Nawoord: decentralisatie en de wet van de afnemende meeropbrengst

> "Wat buiten zijn proporties wordt opgeblazen, stort onvermijdelijk in... Wat geconcentreerd, samenhangend en geworteld is in zijn verleden, is machtig. Wat verspillend, verdeeld en opgeblazen is, vergaat en valt uiteen. Hoe meer iets opzwelt, hoe harder het valt." -- Robert Greene en Joost Elffers, 'The 48 Laws of Power'

De geschiedenis van de menselijke samenleving kenmerkt zich tot nu toe door een ontwikkeling naar meer "complexiteit" of sociaal-politieke controle. Kleine groepen jagers en verzamelaars evolueerden tot agrarische staten, die uiteindelijk plaatsmaakten voor grotere industriële natiestaten. Zoals de archeoloog en historicus Joseph A. Tainter in zijn werk _The Collapse of Complex Societies_ schrijft: "De geschiedenis van de mensheid wordt over het algemeen gekenmerkt door een schijnbaar onstuitbare neiging naar een hogere mate van complexiteit, specialisatie en sociaal-politieke controle. ..." Nu belooft de opkomst van de volgende economische ontwikkelingsfase, de Informatiemaatschappij, echter een ommekeer in de schijnbaar "onstuitbare trend" naar een steeds hogere mate van centralisatie.

Tainters werk roept veel interessante vragen op die relevant zijn voor de thema's in dit boek. Als Tainter gelijk heeft dat minder centrale controle en herverdeling onvermijdelijk tot een ineenstorting leiden, dan lijkt het onhoudbaar dat de industriële natiestaat in haar huidige vorm blijvend kan bestaan naast microstaten waarin mensen als Soevereine Individuen leven. Natiestaten zijn mogelijk niet in staat om met gelijkblijvende, laat staan minder, middelen te functioneren. Zoals Tainter uitvoerig beschrijft, doet bij overontwikkelde systemen die hun potentieel hebben uitgeput, zoals volgens vandaag de dag bij de natiestaten het geval is, vaak 'de wet van de afnemende meeropbrengst' haar intrede. Op "veel cruciale gebieden" dalen de opbrengsten van extra investeringen in gecentraliseerde sociaal-politieke controle of worden deze zelfs negatief. Dit verklaart het fenomeen van de 'wetten van Parkinson', waarbij het aantal werknemers en de operationele kosten van de Britse Admiraliteit in de twintigste eeuw de pan uit rezen, terwijl het aantal schepen in de Britse marine flink afnam.

Vergelijkbare verschijnselen van de 'wet van de afnemende meeropbrengst' zijn zeker waarneembaar nu de twintigste eeuw op haar einde loopt, zowel in de Verenigde Staten als in andere toonaangevende economieën. Roger Lane, professor sociale wetenschappen aan het Haverford College, schreef in zijn essay _On the Social Meaning of Homicide Trends in America:_ "De oude instituties van sociale controle -- wetten, scholen, politie, gevangenissen -- hebben aan doeltreffendheid ingeboet, ondanks de constante toevoer van mankracht en geld." Er is duidelijk bewijs voor stijgende kosten die samenhangen met de totale bestuurlijke lasten. Zo zijn de totale belastinginkomsten in de VS gestegen van 27,8 procent van het mediane inkomen in 1957 naar 37,6 procent in 1997. Dit is een sterke aanwijzing, zo niet onomstotelijk bewijs, voor afnemende meeropbrengsten op alle gebieden van overheidsactiviteit in de Verenigde Staten.

In het verleden waren sterk afnemende meeropbrengsten vaak voorboden van een ineenstorting. De stelling van dit boek is dat het toegenomen vermogen van mensen om hun transacties en vermogen te beschermen tegen roofzuchtige belastingen, zal leiden tot een afname van de herverdeling van middelen, minder centrale sociale controle, minder regulering en uniformiteit en uiteindelijk tot een decentralisatie van de jurisdictie. Al deze ontwikkelingen hebben zich in de geschiedenis geuit als een 'ineenstorting'. In Tainters woorden duidt 'ineenstorting' op de toestand "wanneer een gecentraliseerd controlesysteem niet meer waard is wat het kost."

> "Wanneer een drempel wordt bereikt, of het nu een fysieke, biologische of sociale is, wordt de configuratie van het systeem instabiel. De kleinste, zelfs oneindig kleine verandering in de configuratie van het systeem kan daardoor een verandering in het gedrag van een enkel individu teweegbrengen, hoe klein dan ook, die in een instabiel sociaal configuratieproces leidt tot een beperkte en soms radicale verandering." -- Nicholas Rashevsky, 'Looking at History Through Mathematics'

Hoewel de meeste individuele aanpassingen aan verandering weliswaar marginaal en evolutionair van aard zijn, kunnen er wel degelijk revolutionaire 'paradigmaverschuivingen' plaatsvinden. Soms storten zelfs grote rijken hierdoor in. De meeropbrengsten van verdere investeringen in centrale controle kunnen zo overweldigend negatief worden dat het voor de meeste mensen niet langer economisch rationeel is om het oude systeem te blijven ondersteunen. Tainter verklaart de val van het Romeinse Rijk met deze woorden: "Als we de verslagen mogen geloven, zag een deel van de uitgeputte plattelandsbevolking de komst van de barbaren als een kans om aan de druk van het Romeinse bewind te ontsnappen. Een aanzienlijk groter deel stond blijkbaar apathisch tegenover de naderende ineenstorting... De kosten van het keizerrijk waren enorm gestegen, terwijl de bescherming die de staat aan veel van haar burgers kon bieden, in het licht van de successen van de barbaren, steeds ineffectiever werd. Voor veel mensen bood het keizerrijk simpelweg geen voordelen meer, aangezien zowel barbaren als belastingambtenaren hun land doorkruisten en verwoestten. Zoals Gunderson opmerkt: '...de nettowaarde van lokale autonomie overtrof die van het lidmaatschap van het keizerrijk.' Complexiteit bracht geen voordelen meer die opwogen tegen het verval, maar kostte in plaats daarvan aanzienlijk meer."

Tainter citeert andere autoriteiten om zijn stelling dat een ineenstorting "een overeenkomstige toename van de meeropbrengst van sociale investeringen met zich mee kan brengen," te onderbouwen.

> "Zosimus, een schrijver uit de tweede helft van de vijfde eeuw na Christus, schreef over Thessalië en Macedonië dat '...als gevolg van deze belastingheffingen in stad en land geklaag en gejammer klonk, en iedereen de barbaren om hun hulp vroeg.' ... 'In de vijfde eeuw,' concludeert R.M. Adams, 'waren de mensen bereid de beschaving zelf op te geven om aan de afschuwelijke belastingdruk te ontsnappen."

Rashevsky's analyse van de "rol van determinisme versus indeterminisme" in de geschiedenis onderstreept hoe kwetsbaar systemen zijn voor radicale veranderingen. Zo'n verandering kan zelfs door één individu in gang worden gezet wanneer het systeem instabiel wordt en een bepaald 'kantelpunt' bereikt. Op het moment dat de omstandigheden rijp zijn voor verandering (bijvoorbeeld wanneer de marginale opbrengsten van het in stand houden van een centraal systeem geen "evident voordeel boven verval" meer bieden), is de kans op een radicale omwenteling zo groot dat vrijwel iedereen die teweeg kan brengen. Rashevsky schrijft: 'De persoon die een eindige verandering teweegbrengt, hoeft geen _uitzonderlijk_ individu te zijn. Het kan _ieder_ individu zijn. De situatie is vergelijkbaar met een fysiek systeem waarin op een punt van instabiliteit een willekeurige verschuiving van een van de biljoenen identieke moleculen een eindige overgang naar een stabiele toestand veroorzaakt.'

We kunnen niet exact bepalen wie de ineenstorting van het overbelaste natiestaatsysteem zal veroorzaken of wanneer dat zal gebeuren. Maar uit de analyses van Tainter en Rashevsky over de dynamiek van maatschappelijke verandering kunnen we wel een naderende instorting voorspellen. De meest ontwikkelde en tot dusver succesvolle natiestaten worden stuk voor stuk gekenmerkt door een krimpende bevolking en gigantische, ongedekte pensioenverplichtingen. Zonder een ongekende immigratiegolf uit minder ontwikkelde landen of een onverwachte toestroom van engelen die bereid zijn om over te werken en roofzuchtige belastingtarieven te betalen, zullen de toonaangevende staten in Europa, Noord-Amerika en Australazië qua inkomsten ver achterblijven bij wat nodig is om de huidige sociale voorzieningen te handhaven. Actuarissen voorspellen stijgende belastingen en dalende uitkeringen, oftewel afnemende marginale opbrengsten, vooral voor ondernemers die een onevenredig groot deel van de belastingdruk dragen.

Uit cijfers van de Amerikaanse belastingdienst blijkt dat in 1997 een tiende procent van de Amerikanen het leeuwendeel van de inkomstenbelasting in de Verenigde Staten droegen. Het zijn juist deze mensen voor wie efficiënte minisoevereiniteiten nieuwe kansen bieden om zich te vestigen tegen verwaarloosbare belastingtarieven. Het verschil tussen de beschermingskosten van een gecommercialiseerde soevereiniteit en de uitbuitende belastingen van de oude natiestaten kan gedurende een heel leven oplopen tot vele miljoenen of zelfs miljarden dollars aan inkomen.

De conventionele micro-economie gaat uit van de veronderstelling dat mensen die een briefje van honderd dollar op straat zien liggen, het zullen oprapen. De mogelijkheid om miljoenen of miljarden te besparen, zou tienduizenden of zelfs miljoenen keren overtuigender zijn. Mensen zullen op de beschreven manier handelen wanneer ze voor de keuze staan: ofwel hun dure loyaliteit aan instellingen met afnemende marginale opbrengsten handhaven, ofwel zich aansluiten bij nieuwe structuren die minder vragen en meer beloven.

> "Van alle 36 manieren om uit de penarie te komen, is de beste: er gewoon vandoor gaan." -- Chinees spreekwoord

In dit boek wordt overtuigend uiteengezet waarom het tijd is om je kapitaal te herverdelen, als je daarover beschikt. Het staatsburgerschap is achterhaald. Om je inkomen gedurende jouw leven te optimaliseren en een Soeverein Individu te worden, kun je beter een klant worden van de overheid of van beschermingsdiensten, in plaats van jezelf als burger te zien. In plaats van de belastingdruk te dragen die hebzuchtige politici aan je opleggen, heb je een betere uitgangspositie om te slagen in het Informatietijdperk door de vrijheid te nemen om een privébelastingcontract te onderhandelen, waarin je je ertoe verbindt niet meer te betalen voor overheidsdiensten dan wat ze je werkelijk waard zijn.

De geschiedenis van andere dominante systemen die op het punt stonden in te storten, leert ons dat wie er op tijd uit stapt en kiest voor het _ultieme toevluchtsoord_, hiervan zal profiteren. Dit blijkt al uit de stortvloed van wetten die in de jaren 1990 werden aangenomen om Amerikanen te bestraffen die hun staatsburgerschap opgeven. Het is cruciaal om de gevaren van een nationalistische reactie op de crisis van de natiestaat, en de daarmee gepaard gaande ruimte voor tirannie en onheil, niet te onderschatten. Hoewel het recht op emigratie is vastgelegd in de Amerikaanse onafhankelijkheidsverklaring, zullen de Verenigde Staten waarschijnlijk een van de meer tirannieke rechtsgebieden worden die de opkomst van een gecommercialiseerde soevereiniteit zullen tegenwerken. Zorg er altijd voor dat je je geld niet achterlaat in een rechtsgebied dat het recht claimt om jou, je kinderen of je kleinkinderen op te eisen.

Waar je ook woont of welke nationaliteit je ook hebt, om je vermogen te optimaliseren kun je het beste hoofdzakelijk in een ander land wonen dan dat van je oorspronkelijke staatsburgerschap, terwijl je het merendeel van je geld in een derde rechtsgebied onderbrengt, idealiter in een belastingparadijs.

Om je beter vertrouwd te maken met de alternatieven, raden we je aan om veel te reizen en aantrekkelijke plekken te bezoeken waar je in geval van nood een verblijfsrecht zou willen veiligstellen.

Als je echt ambitieus bent, wil je misschien zelfs een eigen minisoevereiniteit oprichten. In de bijlagen vind je contactpersonen die ondersteuning kunnen bieden bij onderhandelingen over een belastingvrije zone, _zona franca_, met een overheid die bereid is beperkte soevereiniteit over te dragen.

Stel dat je nog aan het begin staat...

Maar stel nu dat je instemt met de basisaannames van dit boek en enthousiast bent over het vooruitzicht van het Informatietijdperk, maar niet over het kapitaal beschikt om de kansen te benutten en te profiteren van de gecommercialiseerde soevereiniteit. Wat doe je dan?

Elke simpele formule voor succes eindigt vroeg of laat in teleurstelling. Door de Informatierevolutie zijn er talloze wegen naar succes ontstaan, maar welke voor jou werkt, valt niet zomaar te zeggen. Als je vastbesloten bent om vermogen op te bouwen om je volledige potentieel als Soeverein Individu te realiseren, geef dan prioriteit aan het bestuderen en evalueren van de werken van diverse goeroes met nuttige tips voor succes.

Elke goede speciaalzaak of een van de online boekhandels, zoals Amazon, heeft een ruime keuze aan zelfhulpboeken over succes. Lees er zoveel mogelijk, niet met het idee dat een bepaalde set regels je automatisch financiële onafhankelijkheid zal bezorgen, maar vanuit het besef dat succes een keuze is. Als je succesvol wil zijn, moet je je het perspectief en de gewoonten eigen maken die succesvolle mensen kenmerken.

Als je je nog in de beroepskeuze-fase bevindt, trek dan niet de eenvoudige conclusie dat de beste weg naar succes in het Informatietijdperk erin bestaat computerprogrammeur te worden. Ja, het klopt dat er tijdens de Informatierevolutie, die in het laatste kwart van de twintigste eeuw plaatsvond, veel vraag was naar programmeurs. Maar naarmate de rekenkracht toegenomen is, heeft ook de kunstmatige intelligentie zich snel ontwikkeld. Een bedrijf met de naam Authorgenics heeft al aangetoond dat het in staat is om objectgeoriënteerde software te ontwikkelen zonder programmeurs. Je zult niet rijkelijk worden beloond voor een vaardigheid die de lamp van Aladin ook beheerst. Het probleem met een specialisatie in software, of een ander snel evoluerend vakgebied in het hart van de Informatierevolutie, is dat je expertise snel verouderd kan zijn.

Dit onderstreept de wijsheid van de traditionele algemene vorming, die erop gericht was studenten aan te moedigen hun kritisch denkvermogen en intellectuele vaardigheden te ontwikkelen. Zowel in het zakenleven als daarbuiten hangt succes af van het vermogen om problemen op te lossen. Leer problemen op te lossen en een succesvolle carrière ligt binnen handbereik. Waar je ook woont, er zijn talloze problemen die schreeuwen om een oplossing. In de meeste gevallen zijn degenen die baat hebben bij een oplossing, of wiens problemen jij aanpakt, bereid je rijkelijk te betalen om die oplossing te vinden.
